CARLA: xml_parser Struct Reference
xml_parser Struct Reference
Public Member Functions
char_t * parse_doctype_group (char_t *s, char_t endch)
char_t * parse_doctype_ignore (char_t *s)
char_t * parse_doctype_primitive (char_t *s)
char_t * parse_exclamation (char_t *s, xml_node_struct *cursor, unsigned int optmsk, char_t endch)
char_t * parse_question (char_t *s, xml_node_struct *&ref_cursor, unsigned int optmsk, char_t endch)
char_t * parse_tree (char_t *s, xml_node_struct *root, unsigned int optmsk, char_t endch)
xml_parser (xml_allocator *alloc_)
Static Public Member Functions
static bool has_element_node_siblings (xml_node_struct *node)
static xml_parse_result parse (char_t *buffer, size_t length, xml_document_struct *xmldoc, xml_node_struct *root, unsigned int optmsk)
static char_t * parse_skip_bom (char_t *s)
Public Attributes
xml_allocator * alloc
char_t * error_offset
xml_parse_status error_status
Detailed Description
Definition at line 2918 of file pugixml.cpp.
Constructor & Destructor Documentation
xml_parser()
xml_parser::xml_parser (xml_allocator * alloc_) inline
Definition at line 2924 of file pugixml.cpp.
Member Function Documentation
has_element_node_siblings()
static bool xml_parser::has_element_node_siblings (xml_node_struct * node) inline static
Definition at line 3499 of file pugixml.cpp.
References PUGI__NODETYPE.
Referenced by parse().
parse()
static xml_parse_result xml_parser::parse (char_t * buffer, size_t length, xml_document_struct * xmldoc, xml_node_struct * root, unsigned int optmsk) inline static
Definition at line 3511 of file pugixml.cpp.
References error_offset, error_status, has_element_node_siblings(), make_parse_result(), parse_skip_bom(), parse_tree(), and PUGI__OPTSET.
parse_doctype_group()
char_t * xml_parser::parse_doctype_group (char_t * s, char_t endch) inline
Definition at line 2999 of file pugixml.cpp.
References parse_doctype_ignore(), parse_doctype_primitive(), and PUGI__THROW_ERROR.
Referenced by parse_exclamation().
parse_doctype_ignore()
char_t * xml_parser::parse_doctype_ignore (char_t * s) inline
Definition at line 2968 of file pugixml.cpp.
References PUGI__THROW_ERROR.
Referenced by parse_doctype_group().
parse_doctype_primitive()
char_t * xml_parser::parse_doctype_primitive (char_t * s) inline
Definition at line 2935 of file pugixml.cpp.
References PUGI__SCANFOR, and PUGI__THROW_ERROR.
Referenced by parse_doctype_group().
parse_exclamation()
char_t * xml_parser::parse_exclamation (char_t * s, xml_node_struct * cursor, unsigned int optmsk, char_t endch) inline
Definition at line 3045 of file pugixml.cpp.
References ct_space, parse_doctype_group(), PUGI__CHECK_ERROR, PUGI__ENDSWITH, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__THROW_ERROR, strconv_cdata(), and strconv_comment().
Referenced by parse_tree().
parse_question()
char_t * xml_parser::parse_question (char_t * s, xml_node_struct *& ref_cursor, unsigned int optmsk, char_t endch) inline
Definition at line 3154 of file pugixml.cpp.
References ct_space, ct_start_symbol, ct_symbol, PUGI__CHECK_ERROR, PUGI__ENDSEG, PUGI__ENDSWITH, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__SCANWHILE, PUGI__SKIPWS, and PUGI__THROW_ERROR.
Referenced by parse_tree().
parse_skip_bom()
static char_t * xml_parser::parse_skip_bom (char_t * s) inline static
Definition at line 3493 of file pugixml.cpp.
Referenced by parse().
parse_tree()
char_t * xml_parser::parse_tree (char_t * s, xml_node_struct * root, unsigned int optmsk, char_t endch) inline
Definition at line 3248 of file pugixml.cpp.
References alloc, append_new_attribute(), ct_space, ct_start_symbol, ct_symbol, get_strconv_attribute(), get_strconv_pcdata(), parse_exclamation(), parse_question(), PUGI__ENDSEG, PUGI__ENDSWITH, PUGI__IS_CHARTYPE, PUGI__NODETYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__SCANWHILE_UNROLL, PUGI__SKIPWS, and PUGI__THROW_ERROR.
Referenced by parse().
Member Data Documentation
alloc
xml_allocator* xml_parser::alloc
Definition at line 2920 of file pugixml.cpp.
Referenced by parse_tree().
error_offset
char_t* xml_parser::error_offset
Definition at line 2921 of file pugixml.cpp.
Referenced by parse().
error_status
xml_parse_status xml_parser::error_status
Definition at line 2922 of file pugixml.cpp.
Referenced by parse().
The documentation for this struct was generated from the following file:
pugixml.cpp