CARLA: FCarlaServer::FPimpl Class Reference
FCarlaServer::FPimpl Class Reference
Public Member Functions
FPimpl (uint16_t RPCPort, uint16_t StreamingPort, uint16_t SecondaryPort)
std::shared_ptr< carla::multigpu::Router > GetSecondaryServer ()
Public Attributes
carla::streaming::Stream BroadcastStream
UCarlaEpisode * Episode = nullptr
std::shared_ptr< carla::multigpu::Router > SecondaryServer
carla::rpc::Server Server
carla::streaming::Server StreamingServer
std::atomic_size_t TickCuesReceived { 0u }
std::map< uint16_t, std::string > TrafficManagerInfo
Map of pairs < port , ip > with all the Traffic Managers active in the simulation.
Private Member Functions
void BindActions ()
Detailed Description
Definition at line 100 of file CarlaServer.cpp.
Constructor & Destructor Documentation
FPimpl()
FCarlaServer::FPimpl::FPimpl (uint16_t RPCPort, uint16_t StreamingPort, uint16_t SecondaryPort) inline
Definition at line 104 of file CarlaServer.cpp.
References BindActions(), and SecondaryServer.
Member Function Documentation
BindActions()
void FCarlaServer::FPimpl::BindActions () private
Looks for a Traffic Manager running on port
Gets a pair filled with the <IP, port> of the Trafic Manager running on port. If there is no Traffic Manager running the pair will be ("", 0)
Add a new Traffic Manager running on <IP, port>
Definition at line 219 of file CarlaServer.cpp.
References ActorNotFound, ActorTypeMismatch, FCarlaActor::AddActorAngularImpulse(), FCarlaActor::AddActorForce(), FCarlaActor::AddActorForceAtLocation(), FCarlaActor::AddActorImpulse(), FCarlaActor::AddActorImpulseAtLocation(), FCarlaActor::AddActorTorque(), FCarlaActor::AddChildren(), FCarlaActor::ApplyAckermannControllerSettings(), FCarlaActor::ApplyAckermannControlToVehicle(), FCarlaActor::ApplyControlToVehicle(), FCarlaActor::ApplyControlToWalker(), FCarlaActor::ApplyPhysicsControl(), UCarlaEpisode::ApplySettings(), ACarlaGameModeBase::ApplyTextureToActor(), UCarlaEpisode::AttachActors(), FActorRegistry::begin(), BIND_ASYNC, BIND_SYNC, FCarlaActor::BlendPose(), carla::rpc::BoneTransformDataOut::bone_name, FWalkerBoneControlOut::BoneTransforms, BroadcastStream, ASceneCaptureSensor::CameraGBuffers, URayTracer::CastRay(), FCarlaActor::CloseVehicleDoor(), carla::rpc::BoneTransformDataOut::component, FWalkerBoneControlOutData::Component, ComponentNotFound, ALargeMapManager::ConsiderSpectatorAsEgo(), ACarlaGameModeBase::CreateUETexture(), ASceneCaptureSensor::CustomDepth, ASceneCaptureSensor::CustomStencil, FActorInfo::Description, UCarlaEpisode::DestroyActor(), FCarlaActor::DisableActorConstantVelocity(), carla::streaming::Server::DisableForROS(), FDebugShapeDrawer::Draw(), FCarlaActor::EnableActorConstantVelocity(), FCarlaActor::EnableCarSim(), FCarlaActor::EnableChronoPhysics(), ACarlaGameModeBase::EnableEnvironmentObjects(), carla::streaming::Server::EnableForROS(), Episode, ACarlaGameModeBase::FindActorByName(), UCarlaEpisode::FindCarlaActor(), FCarlaActor::FreezeTrafficLight(), FunctionNotAvailiableWhenDormant, ASceneCaptureSensor::GBufferA, ASceneCaptureSensor::GBufferB, ASceneCaptureSensor::GBufferC, ASceneCaptureSensor::GBufferD, ASceneCaptureSensor::GBufferE, ASceneCaptureSensor::GBufferF, FCarlaActor::GetAckermannControllerSettings(), FCarlaActor::GetActor(), UCarlaEpisode::GetActorDefinitions(), UCarlaEpisode::GetActorDescriptionFromStream(), FCarlaActor::GetActorId(), FCarlaActor::GetActorInfo(), UCarlaEpisode::GetActorRegistry(), FCarlaActor::GetActorType(), ACarlaGameModeBase::GetAllBBsOfLevel(), UCarlaStatics::GetAllMapNames(), FCarlaActor::GetBonesTransform(), ACarlaGameModeBase::GetEnvironmentObjects(), carla::geom::Transform::GetForwardVector(), FCarlaEngine::GetFrameCounter(), ACarlaGameModeBase::GetFullMapPath(), UCarlaStatics::GetGameInstance(), UCarlaStatics::GetGameMode(), UCarlaEpisode::GetId(), carla::ros2::ROS2::GetInstance(), UCarlaStatics::GetLargeMapManager(), UCarlaLightSubsystem::GetLights(), ACarlaGameModeBase::GetLMManager(), UCarlaEpisode::GetMapName(), ACarlaGameModeBase::GetNamesOfAllActors(), FCarlaActor::GetParent(), FCarlaActor::GetPhysicsControl(), FCarlaActor::GetPoseFromAnimation(), UCarlaEpisode::GetRecommendedSpawnPoints(), UCarlaEpisode::GetRecorder(), UCarlaEpisode::GetSettings(), UCarlaEpisode::GetSpectatorPawn(), FCameraGBufferUint8::GetToken(), carla::streaming::Server::GetToken(), UBoundingBoxCalculator::GetTrafficLightBoundingBox(), FCarlaActor::GetVehicleLightState(), UCarlaEpisode::GetWeather(), FCarlaActor::GetWheelSteerAngle(), UOpenDrive::GetXODR(), ALargeMapManager::GlobalToLocalLocation(), ACarlaGameModeBase::IMUISensorGravity, FCarlaActor::IsDormant(), carla::streaming::Server::IsEnabledForROS(), FNavigationMesh::Load(), ACarlaGameModeBase::LoadMapLayer(), UCarlaEpisode::LoadNewEpisode(), UCarlaEpisode::LoadNewOpendriveEpisode(), ALargeMapManager::LocalToGlobalLocation(), ALargeMapManager::LocalToGlobalTransform(), MAKE_RESULT, carla::Functional::MakeOverload(), carla::Functional::MakeRecursiveOverload(), NotATrafficLight, ALargeMapManager::OnActorSpawned(), FCarlaActor::OpenVehicleDoor(), PhysicsControl, URayTracer::ProjectPoint(), UCarlaEpisode::PutActorToSleep(), carla::rpc::BoneTransformDataOut::relative, FWalkerBoneControlOutData::Relative, ACarlaRecorder::ReplayFile(), REQUIRE_CARLA_EPISODE, FCarlaActor::ResetTrafficLightGroup(), RESPOND_ERROR, RESPOND_ERROR_FSTRING, RespondError(), FCarlaActor::RestorePhysXPhysics(), ASceneCaptureSensor::SceneColor, ASceneCaptureSensor::SceneDepth, ASceneCaptureSensor::SceneStencil, SecondaryServer, ACustomV2XSensor::Send(), UCarlaEpisode::SerializeActor(), FCarlaActor::SetActorAutopilot(), FCarlaActor::SetActorCollisions(), FCarlaActor::SetActorDead(), FCarlaActor::SetActorEnableGravity(), FCarlaActor::SetActorGlobalLocation(), FCarlaActor::SetActorGlobalTransform(), FCarlaActor::SetActorSimulatePhysics(), FCarlaActor::SetActorState(), FCarlaActor::SetActorTargetAngularVelocity(), FCarlaActor::SetActorTargetVelocity(), FCarlaActor::SetAttachmentType(), FCarlaActor::SetBonesTransform(), UCarlaLightSubsystem::SetDayNightCycle(), FCarlaActor::SetLightGreenTime(), FCarlaActor::SetLightRedTime(), UCarlaLightSubsystem::SetLights(), FCarlaActor::SetLightYellowTime(), UCarlaGameInstance::SetMapLayer(), FCarlaActor::SetParent(), ACarlaRecorder::SetReplayerIgnoreHero(), ACarlaRecorder::SetReplayerIgnoreSpectator(), ACarlaRecorder::SetReplayerTimeFactor(), carla::streaming::Server::SetSynchronousMode(), FCarlaActor::SetTrafficLightState(), FCarlaActor::SetVehicleLightState(), FCarlaActor::SetWalkerState(), FCarlaActor::SetWheelSteerDirection(), ACarlaRecorder::ShowFileActorsBlocked(), ACarlaRecorder::ShowFileCollisions(), ACarlaRecorder::ShowFileInfo(), FCarlaActor::ShowVehicleDebugTelemetry(), UCarlaEpisode::SpawnActorWithInfo(), ASceneCaptureSensor::SSAO, UCarlaEpisode::StartRecorder(), FActorSpawnResult::StatusToString(), ACarlaRecorder::Stop(), ACarlaRecorder::StopReplayer(), StreamingServer, Success, FCarlaServer::TickCueReceived(), TickCuesReceived, carla::streaming::detail::Stream< StreamStateT >::token(), carla::rpc::TrafficLight, TrafficLight, TrafficManagerInfo, ACarlaGameModeBase::UnLoadMapLayer(), FCarlaActor::UseCarSimRoad(), FActorDescription::Variations, FCarlaActor::Vehicle, Vehicle, ASceneCaptureSensor::Velocity, carla::rpc::BoneTransformDataOut::world, and FWalkerBoneControlOutData::World.
Referenced by FPimpl().
GetSecondaryServer()
std::shared_ptr< carla::multigpu::Router > FCarlaServer::FPimpl::GetSecondaryServer () inline
Definition at line 115 of file CarlaServer.cpp.
References SecondaryServer.
Member Data Documentation
BroadcastStream
carla::streaming::Stream FCarlaServer::FPimpl::BroadcastStream
Definition at line 126 of file CarlaServer.cpp.
Referenced by BindActions().
Episode
UCarlaEpisode* FCarlaServer::FPimpl::Episode = nullptr
Definition at line 130 of file CarlaServer.cpp.
Referenced by BindActions().
SecondaryServer
std::shared_ptr<carla::multigpu::Router> FCarlaServer::FPimpl::SecondaryServer
Definition at line 128 of file CarlaServer.cpp.
Referenced by BindActions(), FPimpl(), and GetSecondaryServer().
Server
carla::rpc::Server FCarlaServer::FPimpl::Server
Definition at line 122 of file CarlaServer.cpp.
StreamingServer
carla::streaming::Server FCarlaServer::FPimpl::StreamingServer
Definition at line 124 of file CarlaServer.cpp.
Referenced by BindActions().
TickCuesReceived
std::atomic_size_t FCarlaServer::FPimpl::TickCuesReceived { 0u }
Definition at line 132 of file CarlaServer.cpp.
Referenced by BindActions().
TrafficManagerInfo
std::map<uint16_t, std::string> FCarlaServer::FPimpl::TrafficManagerInfo
Map of pairs < port , ip > with all the Traffic Managers active in the simulation.
Definition at line 120 of file CarlaServer.cpp.
Referenced by BindActions().
The documentation for this class was generated from the following file:
CarlaServer.cpp