CARLA: MeshReconstruction::Cube Class Reference
MeshReconstruction::Cube Class Reference
#include <Cube.h>
Public Member Functions
Cube (Rect3 const &space, Fun3s const &sdf)
IntersectInfo Intersect (double isoLevel=0) const
Private Member Functions
Vec3 LerpVertex (double isoLevel, int i1, int i2) const
int SignConfig (double isoLevel) const
Private Attributes
Vec3 pos [8]
double sdf [8]
Detailed Description
Definition at line 16 of file Cube.h.
Constructor & Destructor Documentation
Cube()
MeshReconstruction::Cube::Cube (Rect3 const & space, Fun3s const & sdf)
Definition at line 113 of file Cube.h.
References MeshReconstruction::Rect3::min, pos, sd, sdf, MeshReconstruction::Rect3::size, MeshReconstruction::Vec3::x, MeshReconstruction::Vec3::y, and MeshReconstruction::Vec3::z.
Member Function Documentation
Intersect()
IntersectInfo MeshReconstruction::Cube::Intersect (double isoLevel = 0) const
Definition at line 156 of file Cube.h.
References MeshReconstruction::IntersectInfo::edgeVertIndices, LerpVertex(), MeshReconstruction::IntersectInfo::signConfig, and SignConfig().
Referenced by MeshReconstruction::MarchCube().
LerpVertex()
Vec3 MeshReconstruction::Cube::LerpVertex (double isoLevel, int i1, int i2) const private
Definition at line 94 of file Cube.h.
References pos, and sdf.
Referenced by Intersect().
SignConfig()
int MeshReconstruction::Cube::SignConfig (double isoLevel) const private
Definition at line 141 of file Cube.h.
References sdf.
Referenced by Intersect().
Member Data Documentation
pos
Vec3 MeshReconstruction::Cube::pos[8] private
Definition at line 18 of file Cube.h.
Referenced by Cube(), and LerpVertex().
sdf
double MeshReconstruction::Cube::sdf[8] private
Definition at line 19 of file Cube.h.
Referenced by Cube(), LerpVertex(), and SignConfig().
The documentation for this class was generated from the following file:
Cube.h