CARLA: carla::opendrive::parser::GeoReferenceParser Class Reference
carla::opendrive::parser::GeoReferenceParser Class Reference
#include <GeoReferenceParser.h>
Static Public Member Functions
static void Parse (const pugi::xml_document &xml, carla::road::MapBuilder &map_builder)
Detailed Description
Definition at line 22 of file GeoReferenceParser.h.
Member Function Documentation
Parse()
void carla::opendrive::parser::GeoReferenceParser::Parse (const pugi::xml_document & xml, carla::road::MapBuilder & map_builder) static
Definition at line 62 of file GeoReferenceParser.cpp.
References pugi::xml_node::child(), pugi::xml_node::child_value(), carla::opendrive::parser::ParseGeoReference(), and carla::road::MapBuilder::SetGeoReference().
Referenced by carla::opendrive::OpenDriveParser::Load().
The documentation for this class was generated from the following files:
GeoReferenceParser.h
GeoReferenceParser.cpp