CARLA: ACarlaWheeledVehicle Class Reference
ACarlaWheeledVehicle Class Reference
Base class for CARLA wheeled vehicles.
#include <CarlaWheeledVehicle.h>
Public Member Functions
Constructor and destructor
ACarlaWheeledVehicle (const FObjectInitializer &ObjectInitializer)
~ACarlaWheeledVehicle ()
Get functions
const FVehicleControl & GetVehicleControl () const
Vehicle control currently applied to this vehicle.
const FVehicleAckermannControl & GetVehicleAckermannControl () const
Vehicle Ackermann control currently applied to this vehicle.
FTransform GetVehicleTransform () const
Transform of the vehicle.
float GetVehicleForwardSpeed () const
Forward speed in cm/s. Might be negative if goes backwards.
FVector GetVehicleOrientation () const
Orientation vector of the vehicle, pointing forward.
int32 GetVehicleCurrentGear () const
Active gear of the vehicle.
FTransform GetVehicleBoundingBoxTransform () const
Transform of the vehicle's bounding box relative to the vehicle.
FVector GetVehicleBoundingBoxExtent () const
Extent of the vehicle's bounding box.
UBoxComponent * GetVehicleBoundingBox () const
Get vehicle's bounding box component.
float GetMaximumSteerAngle () const
Get the maximum angle at which the front wheel can steer.
AI debug state
void SetAIVehicleState (ECarlaWheeledVehicleState InState)
ECarlaWheeledVehicleState GetAIVehicleState () const
FVehiclePhysicsControl GetVehiclePhysicsControl () const
FAckermannControllerSettings GetAckermannControllerSettings () const
void RestoreVehiclePhysicsControl ()
FVehicleLightState GetVehicleLightState () const
void ApplyVehiclePhysicsControl (const FVehiclePhysicsControl &PhysicsControl)
void ApplyAckermannControllerSettings (const FAckermannControllerSettings &AckermannControllerSettings)
void SetSimulatePhysics (bool enabled)
void SetWheelCollision (UWheeledVehicleMovementComponent4W *Vehicle4W, const FVehiclePhysicsControl &PhysicsControl)
void SetWheelCollisionNW (UWheeledVehicleMovementComponentNW *VehicleNW, const FVehiclePhysicsControl &PhysicsControl)
void SetVehicleLightState (const FVehicleLightState &LightState)
void SetFailureState (const carla::rpc::VehicleFailureState &FailureState)
bool IsTwoWheeledVehicle ()
virtual bool IsTwoWheeledVehicle_Implementation ()
Vehicle input control
void ApplyVehicleControl (const FVehicleControl &Control, EVehicleInputPriority Priority)
void ApplyVehicleAckermannControl (const FVehicleAckermannControl &AckermannControl, EVehicleInputPriority Priority)
bool IsAckermannControlActive () const
void ActivateVelocityControl (const FVector &Velocity)
void DeactivateVelocityControl ()
void ShowDebugTelemetry (bool Enabled)
void FlushVehicleControl ()
DEPRECATED Set functions
void SetThrottleInput (float Value)
void SetSteeringInput (float Value)
void SetBrakeInput (float Value)
void SetReverse (bool Value)
void ToggleReverse ()
void SetHandbrakeInput (bool Value)
void HoldHandbrake ()
void ReleaseHandbrake ()
TArray< float > GetWheelsFrictionScale ()
void SetWheelsFrictionScale (TArray< float > &WheelsFrictionScale)
void SetCarlaMovementComponent (UBaseCarlaMovementComponent *MoementComponent)
template<typename T = UBaseCarlaMovementComponent>
T * GetCarlaMovementComponent () const
Overriden from AActor
TArray< FName > ConstraintComponentNames
float DoorOpenStrength = 100.0f
ECarlaWheeledVehicleState State = ECarlaWheeledVehicleState::UNKNOWN
Current state of the vehicle controller (for debugging purposes).
UVehicleVelocityControl * VelocityControl
struct {
FVehicleControl Control
FVehicleLightState LightState
EVehicleInputPriority Priority = EVehicleInputPriority::INVALID
} InputControl
FVehicleControl LastAppliedControl
FVehicleAckermannControl LastAppliedAckermannControl
FVehiclePhysicsControl LastPhysicsControl
bool bAckermannControlActive = false
FAckermannController AckermannController
float RolloverBehaviorForce = 0.35
int RolloverBehaviorTracker = 0
float RolloverFlagTime = 5.0f
carla::rpc::VehicleFailureState FailureState = carla::rpc::VehicleFailureState::None
bool bPhysicsEnabled = true
UBaseCarlaMovementComponent * BaseMovementComponent = nullptr
TArray< UPhysicsConstraintComponent * > ConstraintsComponents
TMap< UPhysicsConstraintComponent *, UPrimitiveComponent * > ConstraintDoor
TMap< UPrimitiveComponent *, FTransform > DoorComponentsTransform
TMap< UPrimitiveComponent *, UPhysicsConstraintComponent * > CollisionDisableConstraints
FTimerHandle TimerHandler
float DetectionSize { 750.0f }
FBox FoliageBoundingBox
UBoxComponent * VehicleBounds
float CarSimOriginOffset = 150.f
bool bIsNWVehicle = false
float SpeedAnim { 0.0f }
float RotationAnim { 0.0f }
FBox GetDetectionBox () const
float GetDetectionSize () const
void UpdateDetectionBox ()
const TArray< int32 > GetFoliageInstancesCloseToVehicle (const UInstancedStaticMeshComponent *Component) const
void DrawFoliageBoundingBox () const
FBoxSphereBounds GetBoxSphereBounds () const
bool IsInVehicleRange (const FVector &Location) const
void SetWheelSteerDirection (EVehicleWheelLocation WheelLocation, float AngleInDeg)
Set the rotation of the car wheels indicated by the user 0 = FL_VehicleWheel, 1 = FR_VehicleWheel, 2 = BL_VehicleWheel, 3 = BR_VehicleWheel NOTE : This is purely aesthetic.
float GetWheelSteerAngle (EVehicleWheelLocation WheelLocation)
void OpenDoor (const EVehicleDoor DoorIdx)
void CloseDoor (const EVehicleDoor DoorIdx)
void OpenDoorPhys (const EVehicleDoor DoorIdx)
void CloseDoorPhys (const EVehicleDoor DoorIdx)
void RecordDoorChange (const EVehicleDoor DoorIdx, const bool bIsOpen)
virtual FVector GetVelocity () const override
void SetRolloverFlag ()
carla::rpc::VehicleFailureState GetFailureState () const
float GetSpeedAnim () const
void SetSpeedAnim (float Speed)
float GetRotationAnim () const
void SetRotationAnim (float Rotation)
virtual void BeginPlay () override
virtual void EndPlay (const EEndPlayReason::Type EndPlayReason)
void RefreshLightState (const FVehicleLightState &VehicleLightState)
void AdjustVehicleBounds ()
void ResetConstraints ()
static FRotator GetPhysicsConstraintAngle (UPhysicsConstraintComponent *Component)
static void SetPhysicsConstraintAngle (UPhysicsConstraintComponent *Component, const FRotator &NewAngle)
void ApplyRolloverBehavior ()
Rollovers tend to have too much angular velocity, resulting in the vehicle doing a full 360 flip.
void CheckRollover (const float roll, const std::pair< float, float > threshold_roll)
void AddReferenceToManager ()
void RemoveReferenceToManager ()
Detailed Description
Base class for CARLA wheeled vehicles.
Definition at line 72 of file CarlaWheeledVehicle.h.
Constructor & Destructor Documentation
ACarlaWheeledVehicle()
ACarlaWheeledVehicle::ACarlaWheeledVehicle (const FObjectInitializer & ObjectInitializer)
Definition at line 35 of file CarlaWheeledVehicle.cpp.
References BaseMovementComponent, VehicleBounds, and VelocityControl.
~ACarlaWheeledVehicle()
ACarlaWheeledVehicle::~ACarlaWheeledVehicle ()
Definition at line 50 of file CarlaWheeledVehicle.cpp.
Member Function Documentation
ActivateVelocityControl()
void ACarlaWheeledVehicle::ActivateVelocityControl (const FVector & Velocity)
Definition at line 807 of file CarlaWheeledVehicle.cpp.
References VelocityControl.
AddReferenceToManager()
void ACarlaWheeledVehicle::AddReferenceToManager () private
Definition at line 1110 of file CarlaWheeledVehicle.cpp.
References AVegetationManager::AddVehicle(), and IsValid().
Referenced by BeginPlay().
AdjustVehicleBounds()
void ACarlaWheeledVehicle::AdjustVehicleBounds () protected
Definition at line 257 of file CarlaWheeledVehicle.cpp.
References BoundingBox, UBoundingBoxCalculator::GetVehicleBoundingBox(), and VehicleBounds.
ApplyAckermannControllerSettings()
void ACarlaWheeledVehicle::ApplyAckermannControllerSettings (const FAckermannControllerSettings & AckermannControllerSettings) inline
Definition at line 181 of file CarlaWheeledVehicle.h.
ApplyRolloverBehavior()
void ACarlaWheeledVehicle::ApplyRolloverBehavior () private
Rollovers tend to have too much angular velocity, resulting in the vehicle doing a full 360 flip.
This function progressively reduces the vehicle's angular velocity so that it ends up upside down instead.
Definition at line 1063 of file CarlaWheeledVehicle.cpp.
References CheckRollover(), FailureState, GetVehicleTransform(), carla::rpc::None, RolloverBehaviorTracker, RolloverFlagTime, SetRolloverFlag(), and TimerHandler.
ApplyVehicleAckermannControl()
void ACarlaWheeledVehicle::ApplyVehicleAckermannControl (const FVehicleAckermannControl & AckermannControl, EVehicleInputPriority Priority) inline
Definition at line 225 of file CarlaWheeledVehicle.h.
ApplyVehicleControl()
void ACarlaWheeledVehicle::ApplyVehicleControl (const FVehicleControl & Control, EVehicleInputPriority Priority) inline
Definition at line 210 of file CarlaWheeledVehicle.h.
Referenced by SetBrakeInput(), SetHandbrakeInput(), SetReverse(), SetSteeringInput(), SetThrottleInput(), and AWheeledVehicleAIController::Tick().
ApplyVehiclePhysicsControl()
void ACarlaWheeledVehicle::ApplyVehiclePhysicsControl (const FVehiclePhysicsControl & PhysicsControl)
Definition at line 588 of file CarlaWheeledVehicle.cpp.
References AckermannController, bIsNWVehicle, FVehicleNWGearData::DownRatio, UCarlaStatics::GetRecorder(), LastPhysicsControl, PhysicsControl, FVehicleNWGearData::Ratio, ResetConstraints(), SetWheelCollision(), SetWheelCollisionNW(), FAckermannController::UpdateVehiclePhysics(), and FVehicleNWGearData::UpRatio.
Referenced by RestoreVehiclePhysicsControl().
BeginPlay()
void ACarlaWheeledVehicle::BeginPlay () override protected virtual
Definition at line 98 of file CarlaWheeledVehicle.cpp.
References AckermannController, AddReferenceToManager(), CollisionDisableConstraints, ConstraintComponentNames, ConstraintDoor, ConstraintsComponents, UDefaultMovementComponent::CreateDefaultMovementComponent(), DoorComponentsTransform, AFrictionTrigger::Friction, GetVehiclePhysicsControl(), LastPhysicsControl, ResetConstraints(), SetWheelsFrictionScale(), and FAckermannController::UpdateVehiclePhysics().
CheckRollover()
void ACarlaWheeledVehicle::CheckRollover (const float roll, const std::pair< float, float > threshold_roll) private
Definition at line 1090 of file CarlaWheeledVehicle.cpp.
References RolloverBehaviorForce, and RolloverBehaviorTracker.
Referenced by ApplyRolloverBehavior().
CloseDoor()
void ACarlaWheeledVehicle::CloseDoor (const EVehicleDoor DoorIdx)
Definition at line 990 of file CarlaWheeledVehicle.cpp.
References All, CloseDoorPhys(), and ConstraintsComponents.
CloseDoorPhys()
void ACarlaWheeledVehicle::CloseDoorPhys (const EVehicleDoor DoorIdx)
Definition at line 1040 of file CarlaWheeledVehicle.cpp.
References ConstraintDoor, ConstraintsComponents, DoorComponentsTransform, and RecordDoorChange().
Referenced by CloseDoor(), and ResetConstraints().
DeactivateVelocityControl()
void ACarlaWheeledVehicle::DeactivateVelocityControl ()
Definition at line 812 of file CarlaWheeledVehicle.cpp.
References VelocityControl.
DrawFoliageBoundingBox()
void ACarlaWheeledVehicle::DrawFoliageBoundingBox () const
Definition at line 238 of file CarlaWheeledVehicle.cpp.
References FoliageBoundingBox.
EndPlay()
void ACarlaWheeledVehicle::EndPlay (const EEndPlayReason::Type EndPlayReason) protected virtual
Definition at line 966 of file CarlaWheeledVehicle.cpp.
References RemoveReferenceToManager(), and ShowDebugTelemetry().
FlushVehicleControl()
void ACarlaWheeledVehicle::FlushVehicleControl ()
Todo
This function should be private to AWheeledVehicleAIController.
Definition at line 320 of file CarlaWheeledVehicle.cpp.
References AckermannController, bAckermannControlActive, BaseMovementComponent, InputControl, INVALID, LastAppliedControl, UBaseCarlaMovementComponent::ProcessControl(), FAckermannController::RunLoop(), and FAckermannController::UpdateVehicleState().
Referenced by AWheeledVehicleAIController::Tick().
GetAckermannControllerSettings()
FAckermannControllerSettings ACarlaWheeledVehicle::GetAckermannControllerSettings () const inline
Definition at line 169 of file CarlaWheeledVehicle.h.
GetAIVehicleState()
ECarlaWheeledVehicleState ACarlaWheeledVehicle::GetAIVehicleState () const inline
Definition at line 160 of file CarlaWheeledVehicle.h.
References State.
GetBoxSphereBounds()
FBoxSphereBounds ACarlaWheeledVehicle::GetBoxSphereBounds () const
Definition at line 246 of file CarlaWheeledVehicle.cpp.
References UCarlaStatics::GetLargeMapManager(), ALargeMapManager::LocalToGlobalTransform(), and VehicleBounds.
GetCarlaMovementComponent()
template<typename T = UBaseCarlaMovementComponent> T * ACarlaWheeledVehicle::GetCarlaMovementComponent () const inline
Definition at line 296 of file CarlaWheeledVehicle.h.
GetDetectionBox()
FBox ACarlaWheeledVehicle::GetDetectionBox () const
Definition at line 227 of file CarlaWheeledVehicle.cpp.
References FoliageBoundingBox, and GetDetectionBox().
Referenced by GetDetectionBox().
GetDetectionSize()
float ACarlaWheeledVehicle::GetDetectionSize () const
Definition at line 233 of file CarlaWheeledVehicle.cpp.
References DetectionSize.
Referenced by AVegetationManager::DestroySkeletalFoliages(), and AVegetationManager::SpawnSkeletalFoliages().
GetFailureState()
carla::rpc::VehicleFailureState ACarlaWheeledVehicle::GetFailureState () const
Definition at line 1106 of file CarlaWheeledVehicle.cpp.
References FailureState.
GetFoliageInstancesCloseToVehicle()
const TArray< int32 > ACarlaWheeledVehicle::GetFoliageInstancesCloseToVehicle (const UInstancedStaticMeshComponent * Component) const
Definition at line 221 of file CarlaWheeledVehicle.cpp.
References FoliageBoundingBox, and GetFoliageInstancesCloseToVehicle().
Referenced by AVegetationManager::GetElementsToSpawn(), and GetFoliageInstancesCloseToVehicle().
GetMaximumSteerAngle()
float ACarlaWheeledVehicle::GetMaximumSteerAngle () const
Get the maximum angle at which the front wheel can steer.
Definition at line 307 of file CarlaWheeledVehicle.cpp.
Referenced by AWheeledVehicleAIController::OnPossess().
GetPhysicsConstraintAngle()
FRotator ACarlaWheeledVehicle::GetPhysicsConstraintAngle (UPhysicsConstraintComponent * Component) static
Definition at line 1140 of file CarlaWheeledVehicle.cpp.
GetRotationAnim()
float ACarlaWheeledVehicle::GetRotationAnim () const inline
Definition at line 477 of file CarlaWheeledVehicle.h.
GetSpeedAnim()
float ACarlaWheeledVehicle::GetSpeedAnim () const inline
Definition at line 471 of file CarlaWheeledVehicle.h.
GetVehicleAckermannControl()
const FVehicleAckermannControl & ACarlaWheeledVehicle::GetVehicleAckermannControl () const inline
Vehicle Ackermann control currently applied to this vehicle.
Definition at line 102 of file CarlaWheeledVehicle.h.
GetVehicleBoundingBox()
UBoxComponent * ACarlaWheeledVehicle::GetVehicleBoundingBox () const inline
Get vehicle's bounding box component.
Definition at line 137 of file CarlaWheeledVehicle.h.
GetVehicleBoundingBoxExtent()
FVector ACarlaWheeledVehicle::GetVehicleBoundingBoxExtent () const
Extent of the vehicle's bounding box.
Definition at line 302 of file CarlaWheeledVehicle.cpp.
References VehicleBounds.
GetVehicleBoundingBoxTransform()
FTransform ACarlaWheeledVehicle::GetVehicleBoundingBoxTransform () const
Transform of the vehicle's bounding box relative to the vehicle.
Definition at line 297 of file CarlaWheeledVehicle.cpp.
References VehicleBounds.
GetVehicleControl()
const FVehicleControl & ACarlaWheeledVehicle::GetVehicleControl () const inline
Vehicle control currently applied to this vehicle.
Definition at line 95 of file CarlaWheeledVehicle.h.
Referenced by UDefaultMovementComponent::ProcessControl().
GetVehicleCurrentGear()
int32 ACarlaWheeledVehicle::GetVehicleCurrentGear () const
Active gear of the vehicle.
Definition at line 292 of file CarlaWheeledVehicle.cpp.
References BaseMovementComponent, and UBaseCarlaMovementComponent::GetVehicleCurrentGear().
GetVehicleForwardSpeed()
float ACarlaWheeledVehicle::GetVehicleForwardSpeed () const
Forward speed in cm/s. Might be negative if goes backwards.
Definition at line 282 of file CarlaWheeledVehicle.cpp.
References BaseMovementComponent, and UBaseCarlaMovementComponent::GetVehicleForwardSpeed().
Referenced by CaService::AddBasicVehicleContainerHighFrequency(), CaService::CheckSpeedDelta(), and CaService::ComputeSpeed().
GetVehicleLightState()
FVehicleLightState ACarlaWheeledVehicle::GetVehicleLightState () const
Definition at line 578 of file CarlaWheeledVehicle.cpp.
References InputControl.
Referenced by CaService::AddLowFrequencyContainer().
GetVehicleOrientation()
FVector ACarlaWheeledVehicle::GetVehicleOrientation () const
Orientation vector of the vehicle, pointing forward.
Definition at line 287 of file CarlaWheeledVehicle.cpp.
References GetVehicleTransform().
Referenced by CaService::CheckHeadingDelta().
GetVehiclePhysicsControl()
FVehiclePhysicsControl ACarlaWheeledVehicle::GetVehiclePhysicsControl () const
Definition at line 401 of file CarlaWheeledVehicle.cpp.
References bIsNWVehicle, bPhysicsEnabled, FWheelPhysicsControl::DampingRate, FGearPhysicsControl::DownRatio, LastPhysicsControl, FWheelPhysicsControl::LatStiffMaxLoad, FWheelPhysicsControl::LatStiffValue, FWheelPhysicsControl::LongStiffValue, FWheelPhysicsControl::MaxBrakeTorque, FWheelPhysicsControl::MaxHandBrakeTorque, FWheelPhysicsControl::MaxSteerAngle, PhysicsControl, FWheelPhysicsControl::Position, FWheelPhysicsControl::Radius, FGearPhysicsControl::Ratio, FWheelPhysicsControl::TireFriction, FGearPhysicsControl::UpRatio, and FVehiclePhysicsControl::Wheels.
Referenced by BeginPlay().
GetVehicleTransform()
FTransform ACarlaWheeledVehicle::GetVehicleTransform () const inline
Transform of the vehicle.
Location is shifted so it matches center of the vehicle bounds rather than the actor's location.
Definition at line 110 of file CarlaWheeledVehicle.h.
Referenced by ApplyRolloverBehavior(), and GetVehicleOrientation().
GetVelocity()
FVector ACarlaWheeledVehicle::GetVelocity () const override virtual
Definition at line 961 of file CarlaWheeledVehicle.cpp.
References BaseMovementComponent, and UBaseCarlaMovementComponent::GetVelocity().
GetWheelsFrictionScale()
TArray< float > ACarlaWheeledVehicle::GetWheelsFrictionScale ()
Definition at line 368 of file CarlaWheeledVehicle.cpp.
GetWheelSteerAngle()
float ACarlaWheeledVehicle::GetWheelSteerAngle (EVehicleWheelLocation WheelLocation)
Definition at line 890 of file CarlaWheeledVehicle.cpp.
References bPhysicsEnabled.
Referenced by FFrameData::AddVehicleWheelsAnimation(), and ACarlaRecorder::AddVehicleWheelsAnimation().
HoldHandbrake()
void ACarlaWheeledVehicle::HoldHandbrake () inline
Definition at line 278 of file CarlaWheeledVehicle.h.
IsAckermannControlActive()
bool ACarlaWheeledVehicle::IsAckermannControlActive () const inline
Definition at line 232 of file CarlaWheeledVehicle.h.
IsInVehicleRange()
bool ACarlaWheeledVehicle::IsInVehicleRange (const FVector & Location) const
Definition at line 205 of file CarlaWheeledVehicle.cpp.
References FoliageBoundingBox, and IsInVehicleRange().
Referenced by IsInVehicleRange().
IsTwoWheeledVehicle()
bool ACarlaWheeledVehicle::IsTwoWheeledVehicle ()
Referenced by FFrameData::AddVehicleWheelsAnimation(), ACarlaRecorder::AddVehicleWheelsAnimation(), and SetWheelCollision().
IsTwoWheeledVehicle_Implementation()
virtual bool ACarlaWheeledVehicle::IsTwoWheeledVehicle_Implementation () inline virtual
Definition at line 198 of file CarlaWheeledVehicle.h.
OpenDoor()
void ACarlaWheeledVehicle::OpenDoor (const EVehicleDoor DoorIdx)
Definition at line 973 of file CarlaWheeledVehicle.cpp.
References All, ConstraintsComponents, and OpenDoorPhys().
OpenDoorPhys()
void ACarlaWheeledVehicle::OpenDoorPhys (const EVehicleDoor DoorIdx)
Definition at line 1007 of file CarlaWheeledVehicle.cpp.
References CollisionDisableConstraints, ConstraintDoor, ConstraintsComponents, DoorComponentsTransform, DoorOpenStrength, and RecordDoorChange().
Referenced by OpenDoor(), and ResetConstraints().
RecordDoorChange()
void ACarlaWheeledVehicle::RecordDoorChange (const EVehicleDoor DoorIdx, const bool bIsOpen)
Definition at line 1054 of file CarlaWheeledVehicle.cpp.
References UCarlaStatics::GetRecorder().
Referenced by CloseDoorPhys(), and OpenDoorPhys().
RefreshLightState()
void ACarlaWheeledVehicle::RefreshLightState (const FVehicleLightState & VehicleLightState) protected
Referenced by SetVehicleLightState().
ReleaseHandbrake()
void ACarlaWheeledVehicle::ReleaseHandbrake () inline
Definition at line 284 of file CarlaWheeledVehicle.h.
RemoveReferenceToManager()
void ACarlaWheeledVehicle::RemoveReferenceToManager () private
Definition at line 1125 of file CarlaWheeledVehicle.cpp.
References IsValid(), and AVegetationManager::RemoveVehicle().
Referenced by EndPlay().
ResetConstraints()
void ACarlaWheeledVehicle::ResetConstraints () protected
Definition at line 949 of file CarlaWheeledVehicle.cpp.
References CloseDoorPhys(), ConstraintsComponents, and OpenDoorPhys().
Referenced by ApplyVehiclePhysicsControl(), BeginPlay(), and SetSimulatePhysics().
RestoreVehiclePhysicsControl()
void ACarlaWheeledVehicle::RestoreVehiclePhysicsControl ()
Definition at line 583 of file CarlaWheeledVehicle.cpp.
References ApplyVehiclePhysicsControl(), and LastPhysicsControl.
Referenced by UCarSimManagerComponent::DisableCarSimPhysics(), and UBaseCarlaMovementComponent::EnableUE4VehiclePhysics().
SetAIVehicleState()
void ACarlaWheeledVehicle::SetAIVehicleState (ECarlaWheeledVehicleState InState) inline
Todo
This function should be private to AWheeledVehicleAIController.
Definition at line 154 of file CarlaWheeledVehicle.h.
References State.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot().
SetBrakeInput()
void ACarlaWheeledVehicle::SetBrakeInput (float Value)
Definition at line 347 of file CarlaWheeledVehicle.cpp.
References ApplyVehicleControl(), FVehicleControl::Brake, Control, and InputControl.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot().
SetCarlaMovementComponent()
void ACarlaWheeledVehicle::SetCarlaMovementComponent (UBaseCarlaMovementComponent * MoementComponent)
Definition at line 866 of file CarlaWheeledVehicle.cpp.
References BaseMovementComponent.
SetFailureState()
void ACarlaWheeledVehicle::SetFailureState (const carla::rpc::VehicleFailureState & FailureState)
Definition at line 861 of file CarlaWheeledVehicle.cpp.
References FailureState.
SetHandbrakeInput()
void ACarlaWheeledVehicle::SetHandbrakeInput (bool Value)
Definition at line 361 of file CarlaWheeledVehicle.cpp.
References ApplyVehicleControl(), FVehicleControl::bHandBrake, Control, and InputControl.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot().
SetPhysicsConstraintAngle()
void ACarlaWheeledVehicle::SetPhysicsConstraintAngle (UPhysicsConstraintComponent * Component, const FRotator & NewAngle) static
Definition at line 1146 of file CarlaWheeledVehicle.cpp.
SetReverse()
void ACarlaWheeledVehicle::SetReverse (bool Value)
Definition at line 354 of file CarlaWheeledVehicle.cpp.
References ApplyVehicleControl(), FVehicleControl::bReverse, Control, and InputControl.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot().
SetRolloverFlag()
void ACarlaWheeledVehicle::SetRolloverFlag ()
Definition at line 1099 of file CarlaWheeledVehicle.cpp.
References FailureState, carla::rpc::Rollover, and RolloverBehaviorTracker.
Referenced by ApplyRolloverBehavior().
SetRotationAnim()
void ACarlaWheeledVehicle::SetRotationAnim (float Rotation) inline
Definition at line 480 of file CarlaWheeledVehicle.h.
Referenced by FFrameData::ProcessReplayerAnimBiker(), and CarlaReplayerHelper::ProcessReplayerAnimBiker().
SetSimulatePhysics()
void ACarlaWheeledVehicle::SetSimulatePhysics (bool enabled)
Definition at line 907 of file CarlaWheeledVehicle.cpp.
References bPhysicsEnabled, and ResetConstraints().
SetSpeedAnim()
void ACarlaWheeledVehicle::SetSpeedAnim (float Speed) inline
Definition at line 474 of file CarlaWheeledVehicle.h.
Referenced by FFrameData::ProcessReplayerAnimBiker(), and CarlaReplayerHelper::ProcessReplayerAnimBiker().
SetSteeringInput()
void ACarlaWheeledVehicle::SetSteeringInput (float Value)
Definition at line 340 of file CarlaWheeledVehicle.cpp.
References ApplyVehicleControl(), Control, InputControl, and FVehicleControl::Steer.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot().
SetThrottleInput()
void ACarlaWheeledVehicle::SetThrottleInput (float Value)
Definition at line 333 of file CarlaWheeledVehicle.cpp.
References ApplyVehicleControl(), Control, InputControl, and FVehicleControl::Throttle.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot(), and UDefaultMovementComponent::ProcessControl().
SetVehicleLightState()
void ACarlaWheeledVehicle::SetVehicleLightState (const FVehicleLightState & LightState)
Definition at line 842 of file CarlaWheeledVehicle.cpp.
References FVehicleLightState::Brake, FVehicleLightState::Fog, FVehicleLightState::HighBeam, InputControl, FVehicleLightState::Interior, FVehicleLightState::LeftBlinker, LightState, FVehicleLightState::LowBeam, FVehicleLightState::Position, RefreshLightState(), FVehicleLightState::Reverse, FVehicleLightState::RightBlinker, FVehicleLightState::Special1, and FVehicleLightState::Special2.
SetWheelCollision()
void ACarlaWheeledVehicle::SetWheelCollision (UWheeledVehicleMovementComponent4W * Vehicle4W, const FVehiclePhysicsControl & PhysicsControl)
Definition at line 52 of file CarlaWheeledVehicle.cpp.
References IsTwoWheeledVehicle(), and PhysicsControl.
Referenced by ApplyVehiclePhysicsControl().
SetWheelCollisionNW()
void ACarlaWheeledVehicle::SetWheelCollisionNW (UWheeledVehicleMovementComponentNW * VehicleNW, const FVehiclePhysicsControl & PhysicsControl)
Definition at line 78 of file CarlaWheeledVehicle.cpp.
References PhysicsControl.
Referenced by ApplyVehiclePhysicsControl().
SetWheelsFrictionScale()
void ACarlaWheeledVehicle::SetWheelsFrictionScale (TArray< float > & WheelsFrictionScale)
Definition at line 385 of file CarlaWheeledVehicle.cpp.
Referenced by BeginPlay().
SetWheelSteerDirection()
void ACarlaWheeledVehicle::SetWheelSteerDirection (EVehicleWheelLocation WheelLocation, float AngleInDeg)
Set the rotation of the car wheels indicated by the user 0 = FL_VehicleWheel, 1 = FR_VehicleWheel, 2 = BL_VehicleWheel, 3 = BR_VehicleWheel NOTE : This is purely aesthetic.
It will not modify the physics of the car in any way
Definition at line 875 of file CarlaWheeledVehicle.cpp.
References bPhysicsEnabled.
ShowDebugTelemetry()
void ACarlaWheeledVehicle::ShowDebugTelemetry (bool Enabled)
Definition at line 817 of file CarlaWheeledVehicle.cpp.
References ACarlaHUD::AddDebugVehicleForTelemetry(), and ACarlaHUD::DebugVehicle.
Referenced by EndPlay().
ToggleReverse()
void ACarlaWheeledVehicle::ToggleReverse () inline
Definition at line 269 of file CarlaWheeledVehicle.h.
UpdateDetectionBox()
void ACarlaWheeledVehicle::UpdateDetectionBox ()
Definition at line 212 of file CarlaWheeledVehicle.cpp.
References DetectionSize, and FoliageBoundingBox.
Referenced by AVegetationManager::Tick().
Member Data Documentation
AckermannController
FAckermannController ACarlaWheeledVehicle::AckermannController private
Definition at line 349 of file CarlaWheeledVehicle.h.
Referenced by ApplyVehiclePhysicsControl(), BeginPlay(), and FlushVehicleControl().
bAckermannControlActive
bool ACarlaWheeledVehicle::bAckermannControlActive = false private
Definition at line 348 of file CarlaWheeledVehicle.h.
Referenced by FlushVehicleControl().
BaseMovementComponent
UBaseCarlaMovementComponent* ACarlaWheeledVehicle::BaseMovementComponent = nullptr private
Definition at line 439 of file CarlaWheeledVehicle.h.
Referenced by ACarlaWheeledVehicle(), FlushVehicleControl(), GetVehicleCurrentGear(), GetVehicleForwardSpeed(), GetVelocity(), and SetCarlaMovementComponent().
bIsNWVehicle
bool ACarlaWheeledVehicle::bIsNWVehicle = false
Definition at line 420 of file CarlaWheeledVehicle.h.
Referenced by ACarlaWheeledVehicleNW::ACarlaWheeledVehicleNW(), ApplyVehiclePhysicsControl(), and GetVehiclePhysicsControl().
bPhysicsEnabled
bool ACarlaWheeledVehicle::bPhysicsEnabled = true private
Definition at line 435 of file CarlaWheeledVehicle.h.
Referenced by GetVehiclePhysicsControl(), GetWheelSteerAngle(), SetSimulatePhysics(), and SetWheelSteerDirection().
CarSimOriginOffset
float ACarlaWheeledVehicle::CarSimOriginOffset = 150.f
Definition at line 416 of file CarlaWheeledVehicle.h.
Referenced by UCarSimManagerComponent::BeginPlay().
CollisionDisableConstraints
TMap<UPrimitiveComponent*, UPhysicsConstraintComponent*> ACarlaWheeledVehicle::CollisionDisableConstraints private
Definition at line 452 of file CarlaWheeledVehicle.h.
Referenced by BeginPlay(), and OpenDoorPhys().
ConstraintComponentNames
TArray<FName> ACarlaWheeledVehicle::ConstraintComponentNames protected
Definition at line 319 of file CarlaWheeledVehicle.h.
Referenced by BeginPlay().
ConstraintDoor
TMap<UPhysicsConstraintComponent*, UPrimitiveComponent*> ACarlaWheeledVehicle::ConstraintDoor private
Definition at line 445 of file CarlaWheeledVehicle.h.
Referenced by BeginPlay(), CloseDoorPhys(), and OpenDoorPhys().
ConstraintsComponents
TArray<UPhysicsConstraintComponent*> ACarlaWheeledVehicle::ConstraintsComponents private
Definition at line 442 of file CarlaWheeledVehicle.h.
Referenced by BeginPlay(), CloseDoor(), CloseDoorPhys(), OpenDoor(), OpenDoorPhys(), and ResetConstraints().
Control
FVehicleControl ACarlaWheeledVehicle::Control
Definition at line 339 of file CarlaWheeledVehicle.h.
Referenced by SetBrakeInput(), SetHandbrakeInput(), SetReverse(), SetSteeringInput(), and SetThrottleInput().
DetectionSize
float ACarlaWheeledVehicle::DetectionSize { 750.0f }
Definition at line 359 of file CarlaWheeledVehicle.h.
Referenced by GetDetectionSize(), and UpdateDetectionBox().
DoorComponentsTransform
TMap<UPrimitiveComponent*, FTransform> ACarlaWheeledVehicle::DoorComponentsTransform private
Definition at line 449 of file CarlaWheeledVehicle.h.
Referenced by BeginPlay(), CloseDoorPhys(), and OpenDoorPhys().
DoorOpenStrength
float ACarlaWheeledVehicle::DoorOpenStrength = 100.0f protected
Definition at line 322 of file CarlaWheeledVehicle.h.
Referenced by OpenDoorPhys().
FailureState
carla::rpc::VehicleFailureState ACarlaWheeledVehicle::FailureState = carla::rpc::VehicleFailureState::None private
Definition at line 355 of file CarlaWheeledVehicle.h.
Referenced by ApplyRolloverBehavior(), GetFailureState(), SetFailureState(), and SetRolloverFlag().
FoliageBoundingBox
FBox ACarlaWheeledVehicle::FoliageBoundingBox
Definition at line 362 of file CarlaWheeledVehicle.h.
Referenced by DrawFoliageBoundingBox(), GetDetectionBox(), GetFoliageInstancesCloseToVehicle(), IsInVehicleRange(), and UpdateDetectionBox().
[struct]
struct { ... } ACarlaWheeledVehicle::InputControl
Referenced by FlushVehicleControl(), GetVehicleLightState(), SetBrakeInput(), SetHandbrakeInput(), SetReverse(), SetSteeringInput(), SetThrottleInput(), and SetVehicleLightState().
LastAppliedAckermannControl
FVehicleAckermannControl ACarlaWheeledVehicle::LastAppliedAckermannControl private
Definition at line 345 of file CarlaWheeledVehicle.h.
LastAppliedControl
FVehicleControl ACarlaWheeledVehicle::LastAppliedControl private
Definition at line 344 of file CarlaWheeledVehicle.h.
Referenced by FlushVehicleControl().
LastPhysicsControl
FVehiclePhysicsControl ACarlaWheeledVehicle::LastPhysicsControl private
Definition at line 346 of file CarlaWheeledVehicle.h.
Referenced by ApplyVehiclePhysicsControl(), BeginPlay(), GetVehiclePhysicsControl(), and RestoreVehiclePhysicsControl().
LightState
FVehicleLightState ACarlaWheeledVehicle::LightState
Definition at line 340 of file CarlaWheeledVehicle.h.
Referenced by SetVehicleLightState().
Priority
EVehicleInputPriority ACarlaWheeledVehicle::Priority = EVehicleInputPriority::INVALID
Definition at line 338 of file CarlaWheeledVehicle.h.
RolloverBehaviorForce
float ACarlaWheeledVehicle::RolloverBehaviorForce = 0.35 private
Definition at line 351 of file CarlaWheeledVehicle.h.
Referenced by CheckRollover().
RolloverBehaviorTracker
int ACarlaWheeledVehicle::RolloverBehaviorTracker = 0 private
Definition at line 352 of file CarlaWheeledVehicle.h.
Referenced by ApplyRolloverBehavior(), CheckRollover(), and SetRolloverFlag().
RolloverFlagTime
float ACarlaWheeledVehicle::RolloverFlagTime = 5.0f private
Definition at line 353 of file CarlaWheeledVehicle.h.
Referenced by ApplyRolloverBehavior().
RotationAnim
float ACarlaWheeledVehicle::RotationAnim { 0.0f }
Definition at line 468 of file CarlaWheeledVehicle.h.
SpeedAnim
float ACarlaWheeledVehicle::SpeedAnim { 0.0f }
Definition at line 467 of file CarlaWheeledVehicle.h.
State
ECarlaWheeledVehicleState ACarlaWheeledVehicle::State = ECarlaWheeledVehicleState::UNKNOWN private
Current state of the vehicle controller (for debugging purposes).
Definition at line 331 of file CarlaWheeledVehicle.h.
TimerHandler
FTimerHandle ACarlaWheeledVehicle::TimerHandler private
Definition at line 465 of file CarlaWheeledVehicle.h.
Referenced by ApplyRolloverBehavior().
VehicleBounds
UBoxComponent* ACarlaWheeledVehicle::VehicleBounds
Definition at line 365 of file CarlaWheeledVehicle.h.
Referenced by ACarlaWheeledVehicle(), AdjustVehicleBounds(), GetBoxSphereBounds(), GetVehicleBoundingBoxExtent(), and GetVehicleBoundingBoxTransform().
VelocityControl
UVehicleVelocityControl* ACarlaWheeledVehicle::VelocityControl private
Definition at line 334 of file CarlaWheeledVehicle.h.
Referenced by ACarlaWheeledVehicle(), ActivateVelocityControl(), and DeactivateVelocityControl().
The documentation for this class was generated from the following files:
CarlaWheeledVehicle.h
CarlaWheeledVehicle.cpp