CARLA: carla::sensor::SensorData Class Reference
carla::sensor::SensorData Class Reference
Base class for all the objects containing data generated by a sensor.
#include <SensorData.h>
Public Member Functions
size_t GetFrame () const
Frame count when the data was generated.
const rpc::Transform & GetSensorTransform () const
Sensor's transform when the data was generated.
double GetTimestamp () const
Simulation-time when the data was generated.
virtual ~SensorData ()=default
Protected Member Functions
const auto & GetEpisode () const
SensorData (const RawData &data)
SensorData (size_t frame, double timestamp, const rpc::Transform &sensor_transform)
Private Attributes
client::detail::WeakEpisodeProxy _episode
const size_t _frame
const rpc::Transform _sensor_transform
const double _timestamp
Friends
class client::detail::Simulator
Additional Inherited Members
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Detailed Description
Base class for all the objects containing data generated by a sensor.
Definition at line 20 of file SensorData.h.
Constructor & Destructor Documentation
SensorData() [1/2]
carla::sensor::SensorData::SensorData (size_t frame, double timestamp, const rpc::Transform & sensor_transform) inline protected
Definition at line 25 of file SensorData.h.
SensorData() [2/2]
carla::sensor::SensorData::SensorData (const RawData & data) inline explicit protected
Definition at line 30 of file SensorData.h.
~SensorData()
virtual carla::sensor::SensorData::~SensorData () virtual default
Member Function Documentation
GetEpisode()
const auto & carla::sensor::SensorData::GetEpisode () const inline protected
Definition at line 54 of file SensorData.h.
References _episode.
Referenced by carla::sensor::data::CollisionEvent::GetActor(), carla::sensor::data::LaneInvasionEvent::GetActor(), carla::sensor::data::ObstacleDetectionEvent::GetActor(), carla::sensor::data::CollisionEvent::GetOtherActor(), and carla::sensor::data::ObstacleDetectionEvent::GetOtherActor().
GetFrame()
size_t carla::sensor::SensorData::GetFrame () const inline
Frame count when the data was generated.
Definition at line 38 of file SensorData.h.
References _frame.
GetSensorTransform()
const rpc::Transform & carla::sensor::SensorData::GetSensorTransform () const inline
Sensor's transform when the data was generated.
Definition at line 48 of file SensorData.h.
References _sensor_transform.
GetTimestamp()
double carla::sensor::SensorData::GetTimestamp () const inline
Simulation-time when the data was generated.
Definition at line 43 of file SensorData.h.
References _timestamp.
Referenced by carla::sensor::data::RawEpisodeState::GetGameTimeStamp().
Friends And Related Symbol Documentation
client::detail::Simulator
friend class client::detail::Simulator friend
Todo
This shouldn't be exposed in this namespace.
Definition at line 61 of file SensorData.h.
Member Data Documentation
_episode
client::detail::WeakEpisodeProxy carla::sensor::SensorData::_episode private
Definition at line 62 of file SensorData.h.
Referenced by GetEpisode().
_frame
const size_t carla::sensor::SensorData::_frame private
Definition at line 64 of file SensorData.h.
Referenced by GetFrame().
_sensor_transform
const rpc::Transform carla::sensor::SensorData::_sensor_transform private
Definition at line 68 of file SensorData.h.
Referenced by GetSensorTransform().
_timestamp
const double carla::sensor::SensorData::_timestamp private
Definition at line 66 of file SensorData.h.
Referenced by GetTimestamp().
The documentation for this class was generated from the following file:
SensorData.h