CARLA: sensor_msgs::msg::ImuPubSubType Class Reference
sensor_msgs::msg::ImuPubSubType Class Reference
This class represents the TopicDataType of the type Imu defined by the user in the IDL file.
#include <ImuPubSubTypes.h>
Public Types
typedef Imu type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport ImuPubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~ImuPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type Imu defined by the user in the IDL file.
Definition at line 49 of file ImuPubSubTypes.h.
Member Typedef Documentation
type
typedef Imu sensor_msgs::msg::ImuPubSubType::type
Definition at line 53 of file ImuPubSubTypes.h.
Constructor & Destructor Documentation
ImuPubSubType()
sensor_msgs::msg::ImuPubSubType::ImuPubSubType ()
Definition at line 33 of file ImuPubSubTypes.cpp.
References sensor_msgs::msg::Imu::getKeyMaxCdrSerializedSize(), sensor_msgs::msg::Imu::getMaxCdrSerializedSize(), sensor_msgs::msg::Imu::isKeyDefined(), and m_keyBuffer.
~ImuPubSubType()
sensor_msgs::msg::ImuPubSubType::~ImuPubSubType () override virtual
Definition at line 46 of file ImuPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * sensor_msgs::msg::ImuPubSubType::createData () override virtual
Definition at line 123 of file ImuPubSubTypes.cpp.
deleteData()
void sensor_msgs::msg::ImuPubSubType::deleteData (void * data) override virtual
Definition at line 128 of file ImuPubSubTypes.cpp.
deserialize()
bool sensor_msgs::msg::ImuPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 83 of file ImuPubSubTypes.cpp.
References sensor_msgs::msg::Imu::deserialize().
getKey()
bool sensor_msgs::msg::ImuPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 134 of file ImuPubSubTypes.cpp.
References sensor_msgs::msg::Imu::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and sensor_msgs::msg::Imu::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> sensor_msgs::msg::ImuPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 113 of file ImuPubSubTypes.cpp.
References sensor_msgs::msg::Imu::getCdrSerializedSize().
serialize()
bool sensor_msgs::msg::ImuPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 54 of file ImuPubSubTypes.cpp.
References sensor_msgs::msg::Imu::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* sensor_msgs::msg::ImuPubSubType::m_keyBuffer
Definition at line 106 of file ImuPubSubTypes.h.
Referenced by getKey(), ImuPubSubType(), and ~ImuPubSubType().
m_md5
MD5 sensor_msgs::msg::ImuPubSubType::m_md5
Definition at line 105 of file ImuPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
ImuPubSubTypes.h
ImuPubSubTypes.cpp