CARLA: CarlaRecorderEventsDel Class Reference
CarlaRecorderEventsDel Class Reference
#include <CarlaRecorderEventDel.h>
Public Member Functions
void Add (const CarlaRecorderEventDel &Event)
void Clear (void)
const std::vector< CarlaRecorderEventDel > & GetEvents ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderEventDel > Events
Detailed Description
Definition at line 20 of file CarlaRecorderEventDel.h.
Member Function Documentation
Add()
void CarlaRecorderEventsDel::Add (const CarlaRecorderEventDel & Event)
Definition at line 29 of file CarlaRecorderEventDel.cpp.
References Events.
Referenced by FFrameData::AddEvent(), ACarlaRecorder::AddEvent(), and Read().
Clear()
void CarlaRecorderEventsDel::Clear (void)
Definition at line 24 of file CarlaRecorderEventDel.cpp.
References Events.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetEvents()
const std::vector< CarlaRecorderEventDel > & CarlaRecorderEventsDel::GetEvents ()
Definition at line 76 of file CarlaRecorderEventDel.cpp.
References Events.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderEventsDel::Read (std::istream & InFile)
Definition at line 62 of file CarlaRecorderEventDel.cpp.
References Add(), and EventDel.
Referenced by FFrameData::Read().
Write()
void CarlaRecorderEventsDel::Write (std::ostream & OutFile)
Definition at line 34 of file CarlaRecorderEventDel.cpp.
References EventDel, and Events.
Referenced by ACarlaRecorder::Write(), and FFrameData::Write().
Member Data Documentation
Events
std::vector<CarlaRecorderEventDel> CarlaRecorderEventsDel::Events private
Definition at line 31 of file CarlaRecorderEventDel.h.
Referenced by Add(), Clear(), GetEvents(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderEventDel.h
CarlaRecorderEventDel.cpp