CARLA: carla::MsgPack Class Reference
carla::MsgPack Class Reference
#include <MsgPack.h>
Static Public Member Functions
template<typename T >
static Buffer Pack (const T &obj)
template<typename T >
static T UnPack (const Buffer &buffer)
template<typename T >
static T UnPack (const unsigned char *data, size_t size)
Detailed Description
Definition at line 15 of file MsgPack.h.
Member Function Documentation
Pack()
template<typename T > static Buffer carla::MsgPack::Pack (const T & obj) inline static
Definition at line 19 of file MsgPack.h.
Referenced by carla::sensor::s11n::GnssSerializer::Serialize(), carla::sensor::s11n::ObstacleDetectionEventSerializer::Serialize(), carla::sensor::s11n::CollisionEventSerializer::Serialize(), and carla::sensor::s11n::IMUSerializer::Serialize().
UnPack() [1/2]
template<typename T > static T carla::MsgPack::UnPack (const Buffer & buffer) inline static
Definition at line 27 of file MsgPack.h.
References carla::Buffer::data(), and carla::Buffer::size().
UnPack() [2/2]
template<typename T > static T carla::MsgPack::UnPack (const unsigned char * data, size_t size) inline static
Definition at line 33 of file MsgPack.h.
The documentation for this class was generated from the following file:
MsgPack.h