CARLA: CarlaRecorderAnimVehicles Class Reference
CarlaRecorderAnimVehicles Class Reference
#include <CarlaRecorderAnimVehicle.h>
Public Member Functions
void Add (const CarlaRecorderAnimVehicle &InObj)
void Clear (void)
const std::vector< CarlaRecorderAnimVehicle > & GetVehicles ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderAnimVehicle > Vehicles
Detailed Description
Definition at line 29 of file CarlaRecorderAnimVehicle.h.
Member Function Documentation
Add()
void CarlaRecorderAnimVehicles::Add (const CarlaRecorderAnimVehicle & InObj)
Definition at line 39 of file CarlaRecorderAnimVehicle.cpp.
References Vehicle, and Vehicles.
Referenced by FFrameData::AddAnimVehicle(), ACarlaRecorder::AddAnimVehicle(), and Read().
Clear()
void CarlaRecorderAnimVehicles::Clear (void)
Definition at line 34 of file CarlaRecorderAnimVehicle.cpp.
References Vehicles.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetVehicles()
const std::vector< CarlaRecorderAnimVehicle > & CarlaRecorderAnimVehicles::GetVehicles ()
Definition at line 84 of file CarlaRecorderAnimVehicle.cpp.
References Vehicles.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderAnimVehicles::Read (std::istream & InFile)
Definition at line 70 of file CarlaRecorderAnimVehicle.cpp.
References Add(), and Vehicle.
Referenced by FFrameData::Read().
Write()
void CarlaRecorderAnimVehicles::Write (std::ostream & OutFile)
Definition at line 44 of file CarlaRecorderAnimVehicle.cpp.
References AnimVehicle, Vehicles, and Write().
Referenced by ACarlaRecorder::Write(), Write(), and FFrameData::Write().
Member Data Documentation
Vehicles
std::vector<CarlaRecorderAnimVehicle> CarlaRecorderAnimVehicles::Vehicles private
Definition at line 44 of file CarlaRecorderAnimVehicle.h.
Referenced by Add(), Clear(), GetVehicles(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderAnimVehicle.h
CarlaRecorderAnimVehicle.cpp