CARLA: CarlaEpisode.h File Reference
CarlaEpisode.h File Reference
#include "Carla/Actor/ActorDispatcher.h"
#include "Carla/Recorder/CarlaRecorder.h"
#include "Carla/Sensor/WorldObserver.h"
#include "Carla/Server/CarlaServer.h"
#include "Carla/Settings/EpisodeSettings.h"
#include "Carla/Util/ActorAttacher.h"
#include "Carla/Weather/Weather.h"
#include "Carla/Game/FrameData.h"
#include "Carla/Sensor/SensorManager.h"
#include "GameFramework/Pawn.h"
#include "Materials/MaterialParameterCollectionInstance.h"
#include <compiler/disable-ue4-macros.h>
#include <carla/geom/BoundingBox.h>
#include <carla/geom/GeoLocation.h>
#include <carla/ros2/ROS2.h>
#include <carla/rpc/Actor.h>
#include <carla/rpc/ActorDescription.h>
#include <carla/rpc/OpendriveGenerationParameters.h>
#include <carla/streaming/Server.h>
#include <compiler/enable-ue4-macros.h>
#include "CarlaEpisode.generated.h"
Classes
class UCarlaEpisode
A simulation episode.
Functions
FString CarlaGetRelevantTagAsString (const TSet< crp::CityObjectLabel > &SemanticTags)
Function Documentation
CarlaGetRelevantTagAsString()
FString CarlaGetRelevantTagAsString (const TSet< crp::CityObjectLabel > & SemanticTags)
Definition at line 59 of file ActorRegistry.cpp.
References ATagger::GetTagAsString().
Referenced by FActorRegistry::MakeCarlaActor(), and UCarlaEpisode::SerializeActor().