CARLA: test_buffer.cpp File Reference
test_buffer.cpp File Reference
#include "test.h"
#include <carla/Buffer.h>
#include <carla/BufferPool.h>
#include <array>
#include <list>
#include <set>
#include <string>
#include <vector>
Functions
TEST (buffer, buffer_pool)
TEST (buffer, compile)
TEST (buffer, copy)
TEST (buffer, copy_buffer_sequence)
TEST (buffer, copy_with_offset)
TEST (buffer, memcpy)
TEST (buffer, message_too_big)
TEST (buffer, to_from_string)
TEST (buffer, to_from_vector)
Function Documentation
TEST() [1/9]
TEST (buffer , buffer_pool)
Definition at line 123 of file test_buffer.cpp.
References util::buffer::as_string().
TEST() [2/9]
TEST (buffer , compile)
Definition at line 20 of file test_buffer.cpp.
References carla::Buffer::copy_from().
TEST() [3/9]
TEST (buffer , copy)
Definition at line 82 of file test_buffer.cpp.
References util::buffer::make_empty(), and util::buffer::make_random().
TEST() [4/9]
TEST (buffer , copy_buffer_sequence)
Definition at line 42 of file test_buffer.cpp.
References util::buffer::as_string().
TEST() [5/9]
TEST (buffer , copy_with_offset)
Definition at line 90 of file test_buffer.cpp.
References util::buffer::as_string(), carla::Buffer::copy_from(), carla::Buffer::data(), and carla::Buffer::size().
TEST() [6/9]
TEST (buffer , memcpy)
Definition at line 106 of file test_buffer.cpp.
References util::buffer::make_empty(), and util::buffer::make_random().
TEST() [7/9]
TEST (buffer , message_too_big)
Definition at line 116 of file test_buffer.cpp.
References carla::Buffer::reset().
TEST() [8/9]
TEST (buffer , to_from_string)
Definition at line 59 of file test_buffer.cpp.
References util::buffer::as_string(), and carla::Buffer::size().
TEST() [9/9]
TEST (buffer , to_from_vector)
Definition at line 67 of file test_buffer.cpp.
References carla::Buffer::data(), and carla::Buffer::size().