CARLA: carla_msgs::msg::LaneInvasionEvent Class Reference
carla_msgs::msg::LaneInvasionEvent Class Reference
This class represents the structure LaneInvasionEvent defined by the user in the IDL file.
#include <CarlaLineInvasion.h>
Public Member Functions
eProsima_user_DllExport std::vector< int32_t > & crossed_lane_markings ()
This function returns a reference to member crossed_lane_markings.
eProsima_user_DllExport const std::vector< int32_t > & crossed_lane_markings () const
This function returns a constant reference to member crossed_lane_markings.
eProsima_user_DllExport void crossed_lane_markings (const std::vector< int32_t > &_crossed_lane_markings)
This function copies the value in member crossed_lane_markings.
eProsima_user_DllExport void crossed_lane_markings (std::vector< int32_t > &&_crossed_lane_markings)
This function moves the value in member crossed_lane_markings.
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport std_msgs::msg::Header & header ()
This function returns a reference to member header.
eProsima_user_DllExport const std_msgs::msg::Header & header () const
This function returns a constant reference to member header.
eProsima_user_DllExport void header (const std_msgs::msg::Header &_header)
This function copies the value in member header.
eProsima_user_DllExport void header (std_msgs::msg::Header &&_header)
This function moves the value in member header.
eProsima_user_DllExport LaneInvasionEvent ()
Default constructor.
eProsima_user_DllExport LaneInvasionEvent (const LaneInvasionEvent &x)
Copy constructor.
eProsima_user_DllExport LaneInvasionEvent (LaneInvasionEvent &&x) noexcept
Move constructor.
eProsima_user_DllExport bool operator!= (const LaneInvasionEvent &x) const
Comparison operator.
eProsima_user_DllExport LaneInvasionEvent & operator= (const LaneInvasionEvent &x)
Copy assignment.
eProsima_user_DllExport LaneInvasionEvent & operator= (LaneInvasionEvent &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const LaneInvasionEvent &x) const
Comparison operator.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport ~LaneInvasionEvent ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const carla_msgs::msg::LaneInvasionEvent &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
std::vector< int32_t > m_crossed_lane_markings
std_msgs::msg::Header m_header
Detailed Description
This class represents the structure LaneInvasionEvent defined by the user in the IDL file.
Definition at line 75 of file CarlaLineInvasion.h.
Constructor & Destructor Documentation
LaneInvasionEvent() [1/3]
carla_msgs::msg::LaneInvasionEvent::LaneInvasionEvent ()
Default constructor.
Definition at line 44 of file CarlaLineInvasion.cpp.
~LaneInvasionEvent()
carla_msgs::msg::LaneInvasionEvent::~LaneInvasionEvent ()
Default destructor.
Definition at line 48 of file CarlaLineInvasion.cpp.
LaneInvasionEvent() [2/3]
carla_msgs::msg::LaneInvasionEvent::LaneInvasionEvent (const LaneInvasionEvent & x)
Copy constructor.
Parameters
x Reference to the object carla_msgs::msg::LaneInvasionEvent that will be copied.
Definition at line 52 of file CarlaLineInvasion.cpp.
References m_crossed_lane_markings, and m_header.
LaneInvasionEvent() [3/3]
carla_msgs::msg::LaneInvasionEvent::LaneInvasionEvent (LaneInvasionEvent && x) noexcept
Move constructor.
Parameters
x Reference to the object carla_msgs::msg::LaneInvasionEvent that will be copied.
Definition at line 59 of file CarlaLineInvasion.cpp.
Member Function Documentation
crossed_lane_markings() [1/4]
std::vector< int32_t > & carla_msgs::msg::LaneInvasionEvent::crossed_lane_markings ()
This function returns a reference to member crossed_lane_markings.
Returns
Reference to member crossed_lane_markings
Definition at line 203 of file CarlaLineInvasion.cpp.
crossed_lane_markings() [2/4]
const std::vector< int32_t > & carla_msgs::msg::LaneInvasionEvent::crossed_lane_markings () const
This function returns a constant reference to member crossed_lane_markings.
Returns
Constant reference to member crossed_lane_markings
Definition at line 194 of file CarlaLineInvasion.cpp.
crossed_lane_markings() [3/4]
void carla_msgs::msg::LaneInvasionEvent::crossed_lane_markings (const std::vector< int32_t > & _crossed_lane_markings)
This function copies the value in member crossed_lane_markings.
Parameters
_crossed_lane_markings New value to be copied in member crossed_lane_markings
Definition at line 174 of file CarlaLineInvasion.cpp.
Referenced by getCdrSerializedSize().
crossed_lane_markings() [4/4]
void carla_msgs::msg::LaneInvasionEvent::crossed_lane_markings (std::vector< int32_t > && _crossed_lane_markings)
This function moves the value in member crossed_lane_markings.
Parameters
_crossed_lane_markings New value to be moved in member crossed_lane_markings
Definition at line 184 of file CarlaLineInvasion.cpp.
deserialize()
void carla_msgs::msg::LaneInvasionEvent::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 126 of file CarlaLineInvasion.cpp.
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::deserialize().
getCdrSerializedSize()
size_t carla_msgs::msg::LaneInvasionEvent::getCdrSerializedSize (const carla_msgs::msg::LaneInvasionEvent & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 103 of file CarlaLineInvasion.cpp.
References crossed_lane_markings(), std_msgs::msg::Header::getCdrSerializedSize(), and header().
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t carla_msgs::msg::LaneInvasionEvent::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 209 of file CarlaLineInvasion.cpp.
References carla_msgs_msg_LaneInvasionEvent_max_key_cdr_typesize.
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::getKey(), and carla_msgs::msg::LaneInvasionEventPubSubType::LaneInvasionEventPubSubType().
getMaxCdrSerializedSize()
size_t carla_msgs::msg::LaneInvasionEvent::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 96 of file CarlaLineInvasion.cpp.
References carla_msgs_msg_LaneInvasionEvent_max_cdr_typesize.
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::LaneInvasionEventPubSubType().
header() [1/4]
std_msgs::msg::Header & carla_msgs::msg::LaneInvasionEvent::header ()
This function returns a reference to member header.
Returns
Reference to member header
Definition at line 166 of file CarlaLineInvasion.cpp.
header() [2/4]
const std_msgs::msg::Header & carla_msgs::msg::LaneInvasionEvent::header () const
This function returns a constant reference to member header.
Returns
Constant reference to member header
Definition at line 157 of file CarlaLineInvasion.cpp.
header() [3/4]
void carla_msgs::msg::LaneInvasionEvent::header (const std_msgs::msg::Header & _header)
This function copies the value in member header.
Parameters
_header New value to be copied in member header
Definition at line 137 of file CarlaLineInvasion.cpp.
Referenced by getCdrSerializedSize().
header() [4/4]
void carla_msgs::msg::LaneInvasionEvent::header (std_msgs::msg::Header && _header)
This function moves the value in member header.
Parameters
_header New value to be moved in member header
Definition at line 147 of file CarlaLineInvasion.cpp.
isKeyDefined()
bool carla_msgs::msg::LaneInvasionEvent::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 216 of file CarlaLineInvasion.cpp.
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::LaneInvasionEventPubSubType().
operator!=()
bool carla_msgs::msg::LaneInvasionEvent::operator!= (const LaneInvasionEvent & x) const
Comparison operator.
Parameters
x carla_msgs::msg::LaneInvasionEvent object to compare.
Definition at line 90 of file CarlaLineInvasion.cpp.
operator=() [1/2]
carla_msgs::msg::LaneInvasionEvent & carla_msgs::msg::LaneInvasionEvent::operator= (const LaneInvasionEvent & x)
Copy assignment.
Parameters
x Reference to the object carla_msgs::msg::LaneInvasionEvent that will be copied.
Definition at line 66 of file CarlaLineInvasion.cpp.
References m_crossed_lane_markings, and m_header.
operator=() [2/2]
carla_msgs::msg::LaneInvasionEvent & carla_msgs::msg::LaneInvasionEvent::operator= (LaneInvasionEvent && x) noexcept
Move assignment.
Parameters
x Reference to the object carla_msgs::msg::LaneInvasionEvent that will be copied.
Definition at line 75 of file CarlaLineInvasion.cpp.
operator==()
bool carla_msgs::msg::LaneInvasionEvent::operator== (const LaneInvasionEvent & x) const
Comparison operator.
Parameters
x carla_msgs::msg::LaneInvasionEvent object to compare.
Definition at line 84 of file CarlaLineInvasion.cpp.
References m_crossed_lane_markings, and m_header.
serialize()
void carla_msgs::msg::LaneInvasionEvent::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 119 of file CarlaLineInvasion.cpp.
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::serialize().
serializeKey()
void carla_msgs::msg::LaneInvasionEvent::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 221 of file CarlaLineInvasion.cpp.
Referenced by carla_msgs::msg::LaneInvasionEventPubSubType::getKey().
Member Data Documentation
m_crossed_lane_markings
std::vector<int32_t> carla_msgs::msg::LaneInvasionEvent::m_crossed_lane_markings private
Definition at line 237 of file CarlaLineInvasion.h.
Referenced by LaneInvasionEvent(), operator=(), and operator==().
m_header
std_msgs::msg::Header carla_msgs::msg::LaneInvasionEvent::m_header private
Definition at line 236 of file CarlaLineInvasion.h.
Referenced by LaneInvasionEvent(), operator=(), and operator==().
The documentation for this class was generated from the following files:
CarlaLineInvasion.h
CarlaLineInvasion.cpp