CARLA: carla::ros2::CarlaSSCameraPublisher Class Reference
carla::ros2::CarlaSSCameraPublisher Class Reference
#include <CarlaSSCameraPublisher.h>
Public Member Functions
CarlaSSCameraPublisher (CarlaSSCameraPublisher &&)
CarlaSSCameraPublisher (const CarlaSSCameraPublisher &)
CarlaSSCameraPublisher (const char *ros_name="", const char *parent="")
bool HasBeenInitialized () const
bool Init ()
void InitInfoData (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify)
CarlaSSCameraPublisher & operator= (CarlaSSCameraPublisher &&)
CarlaSSCameraPublisher & operator= (const CarlaSSCameraPublisher &)
bool Publish ()
void SetCameraInfoData (int32_t seconds, uint32_t nanoseconds)
void SetImageData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, const uint8_t *data)
const char * type () const override
~CarlaSSCameraPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Member Functions
bool InitImage ()
bool InitInfo ()
bool PublishImage ()
bool PublishInfo ()
void SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > &&data)
void SetInfoRegionOfInterest (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify)
Private Attributes
std::shared_ptr< CarlaSSCameraPublisherImpl > _impl
std::shared_ptr< CarlaCameraInfoPublisherImpl > _impl_info
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 19 of file CarlaSSCameraPublisher.h.
Constructor & Destructor Documentation
CarlaSSCameraPublisher() [1/3]
carla::ros2::CarlaSSCameraPublisher::CarlaSSCameraPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 339 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaSSCameraPublisher()
carla::ros2::CarlaSSCameraPublisher::~CarlaSSCameraPublisher ()
Definition at line 346 of file CarlaSSCameraPublisher.cpp.
References _impl, and _impl_info.
CarlaSSCameraPublisher() [2/3]
carla::ros2::CarlaSSCameraPublisher::CarlaSSCameraPublisher (const CarlaSSCameraPublisher & other)
Definition at line 378 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaSSCameraPublisher() [3/3]
carla::ros2::CarlaSSCameraPublisher::CarlaSSCameraPublisher (CarlaSSCameraPublisher && other)
Definition at line 396 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
HasBeenInitialized()
bool carla::ros2::CarlaSSCameraPublisher::HasBeenInitialized () const
Definition at line 54 of file CarlaSSCameraPublisher.cpp.
References _impl_info.
Init()
bool carla::ros2::CarlaSSCameraPublisher::Init ()
Definition at line 64 of file CarlaSSCameraPublisher.cpp.
References InitImage(), and InitInfo().
InitImage()
bool carla::ros2::CarlaSSCameraPublisher::InitImage () private
Definition at line 68 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Referenced by Init().
InitInfo()
bool carla::ros2::CarlaSSCameraPublisher::InitInfo () private
Definition at line 116 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Referenced by Init().
InitInfoData()
void carla::ros2::CarlaSSCameraPublisher::InitInfoData (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify)
Definition at line 58 of file CarlaSSCameraPublisher.cpp.
References _impl_info, and SetInfoRegionOfInterest().
operator=() [1/2]
CarlaSSCameraPublisher & carla::ros2::CarlaSSCameraPublisher::operator= (CarlaSSCameraPublisher && other)
Definition at line 404 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaSSCameraPublisher & carla::ros2::CarlaSSCameraPublisher::operator= (const CarlaSSCameraPublisher & other)
Definition at line 386 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaSSCameraPublisher::Publish ()
Definition at line 164 of file CarlaSSCameraPublisher.cpp.
References PublishImage(), and PublishInfo().
PublishImage()
bool carla::ros2::CarlaSSCameraPublisher::PublishImage () private
Definition at line 168 of file CarlaSSCameraPublisher.cpp.
References _impl.
Referenced by Publish().
PublishInfo()
bool carla::ros2::CarlaSSCameraPublisher::PublishInfo () private
Definition at line 230 of file CarlaSSCameraPublisher.cpp.
References _impl_info.
Referenced by Publish().
SetCameraInfoData()
void carla::ros2::CarlaSSCameraPublisher::SetCameraInfoData (int32_t seconds, uint32_t nanoseconds)
Definition at line 328 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl_info, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
SetData()
void carla::ros2::CarlaSSCameraPublisher::SetData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector< uint8_t > && data) private
Definition at line 310 of file CarlaSSCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
Referenced by SetImageData().
SetImageData()
void carla::ros2::CarlaSSCameraPublisher::SetImageData (int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, const uint8_t * data)
Definition at line 292 of file CarlaSSCameraPublisher.cpp.
References SetData().
SetInfoRegionOfInterest()
void carla::ros2::CarlaSSCameraPublisher::SetInfoRegionOfInterest (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify) private
Definition at line 300 of file CarlaSSCameraPublisher.cpp.
References _impl_info, sensor_msgs::msg::RegionOfInterest::do_rectify(), sensor_msgs::msg::RegionOfInterest::height(), sensor_msgs::msg::RegionOfInterest::width(), sensor_msgs::msg::RegionOfInterest::x_offset(), and sensor_msgs::msg::RegionOfInterest::y_offset().
Referenced by InitInfoData().
type()
const char * carla::ros2::CarlaSSCameraPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 35 of file CarlaSSCameraPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaSSCameraPublisherImpl> carla::ros2::CarlaSSCameraPublisher::_impl private
Definition at line 47 of file CarlaSSCameraPublisher.h.
Referenced by CarlaSSCameraPublisher(), CarlaSSCameraPublisher(), InitImage(), operator=(), operator=(), PublishImage(), SetData(), and ~CarlaSSCameraPublisher().
_impl_info
std::shared_ptr<CarlaCameraInfoPublisherImpl> carla::ros2::CarlaSSCameraPublisher::_impl_info private
Definition at line 48 of file CarlaSSCameraPublisher.h.
Referenced by CarlaSSCameraPublisher(), CarlaSSCameraPublisher(), HasBeenInitialized(), InitInfo(), InitInfoData(), operator=(), operator=(), PublishInfo(), SetCameraInfoData(), SetInfoRegionOfInterest(), and ~CarlaSSCameraPublisher().
The documentation for this class was generated from the following files:
CarlaSSCameraPublisher.h
CarlaSSCameraPublisher.cpp