CARLA: carla::client::ActorAttribute Class Reference
carla::client::ActorAttribute Class Reference
An attribute of an ActorBlueprint.
#include <ActorAttribute.h>
Public Member Functions
ActorAttribute (ActorAttribute &&)=default
ActorAttribute (ActorAttribute const &)=default
ActorAttribute (rpc::ActorAttribute attribute)
virtual const std::string & GetId () const override
const std::vector< std::string > & GetRecommendedValues () const
virtual rpc::ActorAttributeType GetType () const override
virtual const std::string & GetValue () const override
bool IsModifiable () const
operator rpc::ActorAttributeValue () const
Serialize this object as a carla::rpc::ActorAttributeValue.
ActorAttribute & operator= (ActorAttribute &&)=default
ActorAttribute & operator= (ActorAttribute const &)=default
void Set (std::string value)
Set the value of this attribute.
virtual ~ActorAttribute ()=default
Public Member Functions inherited from carla::client::ActorAttributeValueAccess
ActorAttributeValueAccess ()=default
ActorAttributeValueAccess (ActorAttributeValueAccess &&)=default
ActorAttributeValueAccess (ActorAttributeValueAccess const &)=default
template<>
bool As () const
template<>
int As () const
template<>
float As () const
template<typename T >
T As () const
Cast the value to the given type.
template<rpc::ActorAttributeType Type>
auto As () const
Cast the value to the type specified by the enum carla::rpc::ActorAttributeType.
template<>
bool As () const
template<>
int As () const
template<>
float As () const
template<typename T >
bool operator!= (const T &rhs) const
ActorAttributeValueAccess & operator= (ActorAttributeValueAccess &&)=default
ActorAttributeValueAccess & operator= (ActorAttributeValueAccess const &)=default
template<>
bool operator== (const ActorAttribute &rhs) const
template<>
bool operator== (const ActorAttributeValue &rhs) const
template<>
bool operator== (const ActorAttributeValueAccess &rhs) const
template<typename T >
bool operator== (const T &rhs) const
virtual ~ActorAttributeValueAccess ()=default
Private Attributes
rpc::ActorAttribute _attribute
Additional Inherited Members
Protected Member Functions inherited from carla::client::ActorAttributeValueAccess
void Validate () const
Detailed Description
An attribute of an ActorBlueprint.
Definition at line 184 of file LibCarla/source/carla/client/ActorAttribute.h.
Constructor & Destructor Documentation
ActorAttribute() [1/3]
carla::client::ActorAttribute::ActorAttribute (rpc::ActorAttribute attribute) inline
Definition at line 187 of file LibCarla/source/carla/client/ActorAttribute.h.
References carla::client::ActorAttributeValueAccess::Validate().
ActorAttribute() [2/3]
carla::client::ActorAttribute::ActorAttribute (ActorAttribute const &) default
ActorAttribute() [3/3]
carla::client::ActorAttribute::ActorAttribute (ActorAttribute &&) default
~ActorAttribute()
virtual carla::client::ActorAttribute::~ActorAttribute () virtual default
Member Function Documentation
GetId()
virtual const std::string & carla::client::ActorAttribute::GetId () const inline override virtual
Implements carla::client::ActorAttributeValueAccess.
Definition at line 200 of file LibCarla/source/carla/client/ActorAttribute.h.
References _attribute, and carla::rpc::ActorAttribute::id.
GetRecommendedValues()
const std::vector< std::string > & carla::client::ActorAttribute::GetRecommendedValues () const inline
Definition at line 208 of file LibCarla/source/carla/client/ActorAttribute.h.
References _attribute, and carla::rpc::ActorAttribute::recommended_values.
Referenced by carla::client::BlueprintLibrary::FilterByAttribute().
GetType()
virtual rpc::ActorAttributeType carla::client::ActorAttribute::GetType () const inline override virtual
Implements carla::client::ActorAttributeValueAccess.
Definition at line 204 of file LibCarla/source/carla/client/ActorAttribute.h.
References _attribute, and carla::rpc::ActorAttribute::type.
Referenced by Set().
GetValue()
virtual const std::string & carla::client::ActorAttribute::GetValue () const inline override virtual
Implements carla::client::ActorAttributeValueAccess.
Definition at line 227 of file LibCarla/source/carla/client/ActorAttribute.h.
References _attribute, and carla::rpc::ActorAttribute::value.
Referenced by carla::client::BlueprintLibrary::FilterByAttribute().
IsModifiable()
bool carla::client::ActorAttribute::IsModifiable () const inline
Definition at line 212 of file LibCarla/source/carla/client/ActorAttribute.h.
References _attribute, and carla::rpc::ActorAttribute::is_modifiable.
operator rpc::ActorAttributeValue()
carla::client::ActorAttribute::operator rpc::ActorAttributeValue () const inline
Serialize this object as a carla::rpc::ActorAttributeValue.
Definition at line 223 of file LibCarla/source/carla/client/ActorAttribute.h.
References _attribute.
operator=() [1/2]
ActorAttribute & carla::client::ActorAttribute::operator= (ActorAttribute &&) default
operator=() [2/2]
ActorAttribute & carla::client::ActorAttribute::operator= (ActorAttribute const &) default
Set()
void carla::client::ActorAttribute::Set (std::string value)
Set the value of this attribute.
Exceptions
InvalidAttributeValue if attribute is not modifiable.
InvalidAttributeValue if format does not match this type.
Definition at line 22 of file ActorAttribute.cpp.
References _attribute, carla::rpc::Bool, GetType(), carla::rpc::ActorAttribute::is_modifiable, LIBCARLA_THROW_INVALID_VALUE, carla::StringUtil::ToLower(), carla::client::ActorAttributeValueAccess::Validate(), and carla::rpc::ActorAttribute::value.
Member Data Documentation
_attribute
rpc::ActorAttribute carla::client::ActorAttribute::_attribute private
Definition at line 232 of file LibCarla/source/carla/client/ActorAttribute.h.
Referenced by GetId(), GetRecommendedValues(), GetType(), GetValue(), IsModifiable(), operator rpc::ActorAttributeValue(), and Set().
The documentation for this class was generated from the following files:
LibCarla/source/carla/client/ActorAttribute.h
ActorAttribute.cpp