CARLA: carla::ros2::CarlaGNSSPublisher Class Reference
carla::ros2::CarlaGNSSPublisher Class Reference
#include <CarlaGNSSPublisher.h>
Public Member Functions
CarlaGNSSPublisher (CarlaGNSSPublisher &&)
CarlaGNSSPublisher (const CarlaGNSSPublisher &)
CarlaGNSSPublisher (const char *ros_name="", const char *parent="")
bool Init ()
CarlaGNSSPublisher & operator= (CarlaGNSSPublisher &&)
CarlaGNSSPublisher & operator= (const CarlaGNSSPublisher &)
bool Publish ()
void SetData (int32_t seconds, uint32_t nanoseconds, const double *data)
const char * type () const override
~CarlaGNSSPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Attributes
std::shared_ptr< CarlaGNSSPublisherImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 17 of file CarlaGNSSPublisher.h.
Constructor & Destructor Documentation
CarlaGNSSPublisher() [1/3]
carla::ros2::CarlaGNSSPublisher::CarlaGNSSPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 166 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaGNSSPublisher()
carla::ros2::CarlaGNSSPublisher::~CarlaGNSSPublisher ()
Definition at line 172 of file CarlaGNSSPublisher.cpp.
References _impl.
CarlaGNSSPublisher() [2/3]
carla::ros2::CarlaGNSSPublisher::CarlaGNSSPublisher (const CarlaGNSSPublisher & other)
Definition at line 189 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaGNSSPublisher() [3/3]
carla::ros2::CarlaGNSSPublisher::CarlaGNSSPublisher (CarlaGNSSPublisher && other)
Definition at line 205 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
Init()
bool carla::ros2::CarlaGNSSPublisher::Init ()
Definition at line 42 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [1/2]
CarlaGNSSPublisher & carla::ros2::CarlaGNSSPublisher::operator= (CarlaGNSSPublisher && other)
Definition at line 212 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaGNSSPublisher & carla::ros2::CarlaGNSSPublisher::operator= (const CarlaGNSSPublisher & other)
Definition at line 196 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaGNSSPublisher::Publish ()
Definition at line 89 of file CarlaGNSSPublisher.cpp.
References _impl.
SetData()
void carla::ros2::CarlaGNSSPublisher::SetData (int32_t seconds, uint32_t nanoseconds, const double * data)
Definition at line 151 of file CarlaGNSSPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
type()
const char * carla::ros2::CarlaGNSSPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 29 of file CarlaGNSSPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaGNSSPublisherImpl> carla::ros2::CarlaGNSSPublisher::_impl private
Definition at line 32 of file CarlaGNSSPublisher.h.
Referenced by CarlaGNSSPublisher(), CarlaGNSSPublisher(), Init(), operator=(), operator=(), Publish(), SetData(), and ~CarlaGNSSPublisher().
The documentation for this class was generated from the following files:
CarlaGNSSPublisher.h
CarlaGNSSPublisher.cpp