CARLA: ASensor Class Reference
ASensor Class Reference
Base class for sensors.
#include <Sensor.h>
Public Member Functions
ASensor (const FObjectInitializer &ObjectInitializer)
virtual void BeginPlay ()
boost::optional< FActorAttribute > GetAttribute (const FString Name)
const UCarlaEpisode & GetEpisode () const
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
bool IsStreamReady ()
FDataStream MoveDataStream ()
virtual void OnFirstClientConnected ()
virtual void OnLastClientDisconnected ()
virtual void PostPhysTick (UWorld *World, ELevelTick TickType, float DeltaSeconds)
void PostPhysTickInternal (UWorld *World, ELevelTick TickType, float DeltaSeconds)
virtual void PrePhysTick (float DeltaSeconds)
virtual void Set (const FActorDescription &Description)
void SetDataStream (FDataStream InStream)
Replace the FDataStream associated with this sensor.
void SetEpisode (const UCarlaEpisode &InEpisode)
void SetSeed (int32 InSeed)
void Tick (const float DeltaTime) final
Protected Member Functions
void EndPlay (EEndPlayReason::Type EndPlayReason) override
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
void PostActorCreated () override
Protected Attributes
bool bIsActive = false
URandomEngine * RandomEngine = nullptr
Random Engine used to provide noise for sensor output.
int32 Seed = 123456789
Seed of the pseudo-random engine.
Private Attributes
bool bClientsListening = false
const UCarlaEpisode * Episode = nullptr
FDelegateHandle OnPostTickDelegate
bool ReadyToTick = false
Allows the sensor to tick with the tick rate from UE4.
FActorDescription SensorDescription
FDataStream Stream
Detailed Description
Base class for sensors.
Definition at line 23 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Constructor & Destructor Documentation
ASensor()
ASensor::ASensor (const FObjectInitializer & ObjectInitializer)
Definition at line 17 of file Sensor.cpp.
Member Function Documentation
BeginPlay()
void ASensor::BeginPlay () virtual
Reimplemented in AGnssSensor, AInertialMeasurementUnit, ARadar, ASceneCaptureCamera, and ASceneCaptureSensor.
Definition at line 27 of file Sensor.cpp.
References Episode, UCarlaStatics::GetCurrentEpisode(), UCarlaEpisode::GetSensorManager(), and FSensorManager::RegisterSensor().
EndPlay()
void ASensor::EndPlay (EEndPlayReason::Type EndPlayReason) override protected
Definition at line 113 of file Sensor.cpp.
References FSensorManager::DeRegisterSensor(), Episode, carla::streaming::detail::token_type::get_stream_id(), UCarlaStatics::GetCurrentEpisode(), GetEpisode(), UCarlaStatics::GetGameInstance(), UCarlaEpisode::GetSensorManager(), FDataStreamTmpl< T >::GetToken(), and Stream.
GetAttribute()
boost::optional< FActorAttribute > ASensor::GetAttribute (const FString Name)
Definition at line 49 of file Sensor.cpp.
References SensorDescription, and FActorDescription::Variations.
Referenced by ADVSCamera::PostPhysTick().
GetDataStream()
template<typename SensorT > FAsyncDataStream ASensor::GetDataStream (const SensorT & Self) inline protected
Return the FDataStream associated with this sensor.
You need to provide a reference to self, this is necessary for template deduction.
Definition at line 110 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by ACollisionSensor::OnCollisionEvent(), AObstacleDetectionSensor::OnObstacleDetectionEvent(), AGnssSensor::PostPhysTick(), ARayCastLidar::PostPhysTick(), ACustomV2XSensor::PostPhysTick(), ADVSCamera::PostPhysTick(), AInertialMeasurementUnit::PostPhysTick(), ARadar::PostPhysTick(), ARayCastSemanticLidar::PostPhysTick(), and AV2XSensor::PostPhysTick().
GetEpisode()
const UCarlaEpisode & ASensor::GetEpisode () const inline
Definition at line 93 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by ASceneCaptureSensor::BeginPlay(), ARayCastSemanticLidar::ComputeRawDetection(), EndPlay(), ACollisionSensor::OnCollisionEvent(), AObstacleDetectionSensor::OnObstacleDetectionEvent(), and ADVSCamera::Simulation().
GetRandomEngine()
URandomEngine * ASensor::GetRandomEngine () inline
Definition at line 79 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by UActorBlueprintFunctionLibrary::SetCustomV2X(), UActorBlueprintFunctionLibrary::SetGnss(), UActorBlueprintFunctionLibrary::SetIMU(), and UActorBlueprintFunctionLibrary::SetV2X().
GetSeed()
int32 ASensor::GetSeed () const inline
Definition at line 85 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
GetToken()
auto ASensor::GetToken () const inline
Return the token that allows subscribing to this sensor's stream.
Definition at line 56 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by FActorRegistry::GetDescriptionFromStream(), ACollisionSensor::OnCollisionEvent(), AObstacleDetectionSensor::OnObstacleDetectionEvent(), AGnssSensor::PostPhysTick(), ARayCastLidar::PostPhysTick(), ADVSCamera::PostPhysTick(), AInertialMeasurementUnit::PostPhysTick(), ARadar::PostPhysTick(), and ARayCastSemanticLidar::PostPhysTick().
IsStreamReady()
bool ASensor::IsStreamReady () inline
Definition at line 61 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by AObstacleDetectionSensor::OnObstacleDetectionEvent().
MoveDataStream()
FDataStream ASensor::MoveDataStream () inline
Definition at line 50 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by FActorSensorData::RecordActorData().
OnFirstClientConnected()
virtual void ASensor::OnFirstClientConnected () inline virtual
Reimplemented in ASceneCaptureCamera.
Definition at line 71 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by Tick().
OnLastClientDisconnected()
virtual void ASensor::OnLastClientDisconnected () inline virtual
Reimplemented in ASceneCaptureCamera.
Definition at line 73 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by Tick().
PostActorCreated()
void ASensor::PostActorCreated () override protected
Definition at line 94 of file Sensor.cpp.
PostPhysTick()
virtual void ASensor::PostPhysTick (UWorld * World, ELevelTick TickType, float DeltaSeconds) inline virtual
Reimplemented in ADepthCamera, AGnssSensor, AInstanceSegmentationCamera, ANormalsCamera, AObstacleDetectionSensor, AOpticalFlowCamera, ASceneCaptureCamera, ASemanticSegmentationCamera, ARayCastLidar, ACustomV2XSensor, ADVSCamera, AInertialMeasurementUnit, ARadar, ARayCastSemanticLidar, ASceneCaptureSensor, and AV2XSensor.
Definition at line 69 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by PostPhysTickInternal().
PostPhysTickInternal()
void ASensor::PostPhysTickInternal (UWorld * World, ELevelTick TickType, float DeltaSeconds)
Definition at line 131 of file Sensor.cpp.
References PostPhysTick(), PostPhysTickInternal(), and ReadyToTick.
Referenced by PostPhysTickInternal().
PrePhysTick()
virtual void ASensor::PrePhysTick (float DeltaSeconds) inline virtual
Reimplemented in ACollisionSensor, ACustomV2XSensor, ASceneCaptureSensor, and AV2XSensor.
Definition at line 68 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by Tick().
Set()
void ASensor::Set (const FActorDescription & Description) virtual
Reimplemented in AGnssSensor, ACustomV2XSensor, ADVSCamera, AInertialMeasurementUnit, ASceneCaptureSensor, AShaderBasedSensor, AV2XSensor, AObstacleDetectionSensor, ARadar, ARayCastLidar, and ARayCastSemanticLidar.
Definition at line 35 of file Sensor.cpp.
References UActorBlueprintFunctionLibrary::ActorAttributeToFloat(), SensorDescription, and FActorDescription::Variations.
Referenced by ARayCastLidar::Set().
SetDataStream()
void ASensor::SetDataStream (FDataStream InStream) inline
Replace the FDataStream associated with this sensor.
Warning
Do not change the stream after BeginPlay. It is not thread-safe.
Definition at line 45 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by FActorSensorData::RestoreActorData().
SetEpisode()
void ASensor::SetEpisode (const UCarlaEpisode & InEpisode) inline
Definition at line 31 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
SetSeed()
void ASensor::SetSeed (int32 InSeed)
Definition at line 87 of file Sensor.cpp.
References RandomEngine, Seed, and URandomEngine::Seed().
Referenced by ARayCastLidar::ARayCastLidar(), UActorBlueprintFunctionLibrary::SetCustomV2X(), UActorBlueprintFunctionLibrary::SetGnss(), UActorBlueprintFunctionLibrary::SetIMU(), and UActorBlueprintFunctionLibrary::SetV2X().
Tick()
void ASensor::Tick (const float DeltaTime) final
Definition at line 59 of file Sensor.cpp.
References FDataStreamTmpl< T >::AreClientsListening(), bClientsListening, OnFirstClientConnected(), OnLastClientDisconnected(), PrePhysTick(), ReadyToTick, Stream, and Tick().
Referenced by Tick().
Member Data Documentation
bClientsListening
bool ASensor::bClientsListening = false private
Definition at line 139 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by Tick().
bIsActive
bool ASensor::bIsActive = false protected
Definition at line 124 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Episode
const UCarlaEpisode* ASensor::Episode = nullptr private
Definition at line 134 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by BeginPlay(), EndPlay(), and AObstacleDetectionSensor::OnObstacleDetectionEvent().
OnPostTickDelegate
FDelegateHandle ASensor::OnPostTickDelegate private
Definition at line 130 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
RandomEngine
URandomEngine* ASensor::RandomEngine = nullptr protected
Random Engine used to provide noise for sensor output.
Definition at line 121 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by ACustomV2XSensor::ACustomV2XSensor(), ADVSCamera::ADVSCamera(), AGnssSensor::AGnssSensor(), AInertialMeasurementUnit::AInertialMeasurementUnit(), ARadar::ARadar(), ARayCastLidar::ARayCastLidar(), AV2XSensor::AV2XSensor(), AInertialMeasurementUnit::ComputeAccelerometerNoise(), AInertialMeasurementUnit::ComputeGyroscopeNoise(), AGnssSensor::PostPhysTick(), ARayCastLidar::PostprocessDetection(), ARayCastLidar::PreprocessRays(), ARadar::SendLineTraces(), SetSeed(), and ADVSCamera::Simulation().
ReadyToTick
bool ASensor::ReadyToTick = false private
Allows the sensor to tick with the tick rate from UE4.
Definition at line 137 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by PostPhysTickInternal(), and Tick().
Seed
int32 ASensor::Seed = 123456789 protected
Seed of the pseudo-random engine.
Definition at line 117 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by SetSeed().
SensorDescription
FActorDescription ASensor::SensorDescription private
Definition at line 132 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by GetAttribute(), and Set().
Stream
FDataStream ASensor::Stream private
Definition at line 128 of file Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h.
Referenced by EndPlay(), AGnssSensor::PostPhysTick(), ADVSCamera::PostPhysTick(), AInertialMeasurementUnit::PostPhysTick(), and Tick().
The documentation for this class was generated from the following files:
Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Sensor/Sensor.h
Sensor.cpp