CARLA: sensor_msgs::msg::CameraInfoPubSubType Class Reference
sensor_msgs::msg::CameraInfoPubSubType Class Reference
This class represents the TopicDataType of the type CameraInfo defined by the user in the IDL file.
#include <CameraInfoPubSubTypes.h>
Public Types
typedef CameraInfo type
Public Member Functions
eProsima_user_DllExport CameraInfoPubSubType ()
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~CameraInfoPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type CameraInfo defined by the user in the IDL file.
Definition at line 46 of file CameraInfoPubSubTypes.h.
Member Typedef Documentation
type
typedef CameraInfo sensor_msgs::msg::CameraInfoPubSubType::type
Definition at line 50 of file CameraInfoPubSubTypes.h.
Constructor & Destructor Documentation
CameraInfoPubSubType()
sensor_msgs::msg::CameraInfoPubSubType::CameraInfoPubSubType ()
Definition at line 32 of file CameraInfoPubSubTypes.cpp.
References sensor_msgs::msg::CameraInfo::getKeyMaxCdrSerializedSize(), sensor_msgs::msg::CameraInfo::getMaxCdrSerializedSize(), sensor_msgs::msg::CameraInfo::isKeyDefined(), and m_keyBuffer.
~CameraInfoPubSubType()
sensor_msgs::msg::CameraInfoPubSubType::~CameraInfoPubSubType () override virtual
Definition at line 45 of file CameraInfoPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * sensor_msgs::msg::CameraInfoPubSubType::createData () override virtual
Definition at line 122 of file CameraInfoPubSubTypes.cpp.
deleteData()
void sensor_msgs::msg::CameraInfoPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file CameraInfoPubSubTypes.cpp.
deserialize()
bool sensor_msgs::msg::CameraInfoPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file CameraInfoPubSubTypes.cpp.
References sensor_msgs::msg::CameraInfo::deserialize().
getKey()
bool sensor_msgs::msg::CameraInfoPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file CameraInfoPubSubTypes.cpp.
References sensor_msgs::msg::CameraInfo::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and sensor_msgs::msg::CameraInfo::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> sensor_msgs::msg::CameraInfoPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file CameraInfoPubSubTypes.cpp.
References sensor_msgs::msg::CameraInfo::getCdrSerializedSize().
serialize()
bool sensor_msgs::msg::CameraInfoPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file CameraInfoPubSubTypes.cpp.
References sensor_msgs::msg::CameraInfo::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* sensor_msgs::msg::CameraInfoPubSubType::m_keyBuffer
Definition at line 103 of file CameraInfoPubSubTypes.h.
Referenced by CameraInfoPubSubType(), getKey(), and ~CameraInfoPubSubType().
m_md5
MD5 sensor_msgs::msg::CameraInfoPubSubType::m_md5
Definition at line 102 of file CameraInfoPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
CameraInfoPubSubTypes.h
CameraInfoPubSubTypes.cpp