CARLA: xml_buffered_writer Class Reference
xml_buffered_writer Class Reference
Public Types
enum { bufcapacitybytes , bufcapacity = bufcapacitybytes / (sizeof(char_t) + 4) }
Public Member Functions
size_t flush ()
void flush (const char_t *data, size_t size)
void write (char_t d0)
void write (char_t d0, char_t d1)
void write (char_t d0, char_t d1, char_t d2)
void write (char_t d0, char_t d1, char_t d2, char_t d3)
void write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4)
void write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4, char_t d5)
void write_buffer (const char_t *data, size_t length)
void write_direct (const char_t *data, size_t length)
void write_string (const char_t *data)
xml_buffered_writer (xml_writer &writer_, xml_encoding user_encoding)
Public Attributes
char_t buffer [bufcapacity]
size_t bufsize
xml_encoding encoding
union {
char_t data_char [bufcapacity]
uint16_t data_u16 [2 *bufcapacity]
uint32_t data_u32 [bufcapacity]
uint8_t data_u8 [4 *bufcapacity]
} scratch
xml_writer & writer
Private Member Functions
xml_buffered_writer & operator= (const xml_buffered_writer &)
xml_buffered_writer (const xml_buffered_writer &)
Detailed Description
Definition at line 3698 of file pugixml.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
bufcapacitybytes
bufcapacity
Definition at line 3885 of file pugixml.cpp.
Constructor & Destructor Documentation
xml_buffered_writer() [1/2]
xml_buffered_writer::xml_buffered_writer (const xml_buffered_writer &) private
xml_buffered_writer() [2/2]
xml_buffered_writer::xml_buffered_writer (xml_writer & writer_, xml_encoding user_encoding) inline
Definition at line 3704 of file pugixml.cpp.
References bufcapacity, and PUGI__STATIC_ASSERT.
Member Function Documentation
flush() [1/2]
size_t xml_buffered_writer::flush () inline
Definition at line 3709 of file pugixml.cpp.
References buffer, bufsize, and flush().
Referenced by flush(), write(), write(), write(), write(), write(), write(), and write_direct().
flush() [2/2]
void xml_buffered_writer::flush (const char_t * data, size_t size) inline
Definition at line 3716 of file pugixml.cpp.
References convert_buffer_output(), encoding, get_write_native_encoding(), scratch, and writer.
operator=()
xml_buffered_writer & xml_buffered_writer::operator= (const xml_buffered_writer &) private
write() [1/6]
void xml_buffered_writer::write (char_t d0) inline
Definition at line 3813 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
Referenced by node_output(), node_output_attributes(), node_output_comment(), node_output_end(), node_output_pi_value(), node_output_simple(), node_output_start(), text_output_cdata(), text_output_escaped(), and text_output_indent().
write() [2/6]
void xml_buffered_writer::write (char_t d0, char_t d1) inline
Definition at line 3822 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [3/6]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2) inline
Definition at line 3832 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [4/6]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2, char_t d3) inline
Definition at line 3843 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [5/6]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4) inline
Definition at line 3855 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write() [6/6]
void xml_buffered_writer::write (char_t d0, char_t d1, char_t d2, char_t d3, char_t d4, char_t d5) inline
Definition at line 3868 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and flush().
write_buffer()
void xml_buffered_writer::write_buffer (const char_t * data, size_t length) inline
Definition at line 3773 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, and write_direct().
Referenced by node_output_comment(), node_output_pi_value(), text_output_cdata(), text_output_escaped(), and text_output_indent().
write_direct()
void xml_buffered_writer::write_direct (const char_t * data, size_t length) inline
Definition at line 3734 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, encoding, flush(), get_valid_length(), get_write_native_encoding(), and writer.
Referenced by write_buffer(), and write_string().
write_string()
void xml_buffered_writer::write_string (const char_t * data) inline
Definition at line 3788 of file pugixml.cpp.
References bufcapacity, buffer, bufsize, get_valid_length(), strlength(), and write_direct().
Referenced by node_output_attributes(), node_output_end(), node_output_simple(), node_output_start(), and text_output().
Member Data Documentation
buffer
char_t xml_buffered_writer::buffer[bufcapacity]
Definition at line 3897 of file pugixml.cpp.
Referenced by flush(), write(), write(), write(), write(), write(), write(), write_buffer(), write_direct(), and write_string().
bufsize
size_t xml_buffered_writer::bufsize
Definition at line 3908 of file pugixml.cpp.
Referenced by flush(), write(), write(), write(), write(), write(), write(), write_buffer(), write_direct(), and write_string().
data_char
char_t xml_buffered_writer::data_char[bufcapacity]
Definition at line 3904 of file pugixml.cpp.
data_u16
uint16_t xml_buffered_writer::data_u16[2 *bufcapacity]
Definition at line 3902 of file pugixml.cpp.
data_u32
uint32_t xml_buffered_writer::data_u32[bufcapacity]
Definition at line 3903 of file pugixml.cpp.
data_u8
uint8_t xml_buffered_writer::data_u8[4 *bufcapacity]
Definition at line 3901 of file pugixml.cpp.
encoding
xml_encoding xml_buffered_writer::encoding
Definition at line 3909 of file pugixml.cpp.
Referenced by flush(), and write_direct().
[union]
union { ... } xml_buffered_writer::scratch
Referenced by flush().
writer
xml_writer& xml_buffered_writer::writer
Definition at line 3907 of file pugixml.cpp.
Referenced by flush(), and write_direct().
The documentation for this class was generated from the following file:
pugixml.cpp