CARLA: sensor_msgs::msg::PointCloud2PubSubType Class Reference
sensor_msgs::msg::PointCloud2PubSubType Class Reference
This class represents the TopicDataType of the type PointCloud2 defined by the user in the IDL file.
#include <PointCloud2PubSubTypes.h>
Public Types
typedef PointCloud2 type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport PointCloud2PubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~PointCloud2PubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type PointCloud2 defined by the user in the IDL file.
Definition at line 47 of file PointCloud2PubSubTypes.h.
Member Typedef Documentation
type
typedef PointCloud2 sensor_msgs::msg::PointCloud2PubSubType::type
Definition at line 51 of file PointCloud2PubSubTypes.h.
Constructor & Destructor Documentation
PointCloud2PubSubType()
sensor_msgs::msg::PointCloud2PubSubType::PointCloud2PubSubType ()
Definition at line 32 of file PointCloud2PubSubTypes.cpp.
References sensor_msgs::msg::PointCloud2::getKeyMaxCdrSerializedSize(), sensor_msgs::msg::PointCloud2::getMaxCdrSerializedSize(), sensor_msgs::msg::PointCloud2::isKeyDefined(), and m_keyBuffer.
~PointCloud2PubSubType()
sensor_msgs::msg::PointCloud2PubSubType::~PointCloud2PubSubType () override virtual
Definition at line 45 of file PointCloud2PubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * sensor_msgs::msg::PointCloud2PubSubType::createData () override virtual
Definition at line 122 of file PointCloud2PubSubTypes.cpp.
deleteData()
void sensor_msgs::msg::PointCloud2PubSubType::deleteData (void * data) override virtual
Definition at line 127 of file PointCloud2PubSubTypes.cpp.
deserialize()
bool sensor_msgs::msg::PointCloud2PubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file PointCloud2PubSubTypes.cpp.
References sensor_msgs::msg::PointCloud2::deserialize().
getKey()
bool sensor_msgs::msg::PointCloud2PubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file PointCloud2PubSubTypes.cpp.
References sensor_msgs::msg::PointCloud2::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and sensor_msgs::msg::PointCloud2::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> sensor_msgs::msg::PointCloud2PubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file PointCloud2PubSubTypes.cpp.
References sensor_msgs::msg::PointCloud2::getCdrSerializedSize().
serialize()
bool sensor_msgs::msg::PointCloud2PubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file PointCloud2PubSubTypes.cpp.
References sensor_msgs::msg::PointCloud2::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* sensor_msgs::msg::PointCloud2PubSubType::m_keyBuffer
Definition at line 104 of file PointCloud2PubSubTypes.h.
Referenced by getKey(), PointCloud2PubSubType(), and ~PointCloud2PubSubType().
m_md5
MD5 sensor_msgs::msg::PointCloud2PubSubType::m_md5
Definition at line 103 of file PointCloud2PubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
PointCloud2PubSubTypes.h
PointCloud2PubSubTypes.cpp