CARLA: FWorldObserver Class Reference
FWorldObserver Class Reference
Serializes and sends all the actors in the current UCarlaEpisode.
#include <WorldObserver.h>
Public Types
using not_spawnable = void
Prevent this sensor to be spawned by users.
Public Member Functions
void BroadcastTick (const UCarlaEpisode &Episode, float DeltaSeconds, bool MapChange, bool PendingLightUpdate)
Send a message to every connected client with the info about the given Episode.
FTransform GetActorTransform () const
Dummy. Required for compatibility with other sensors only.
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
void SetStream (FDataMultiStream InStream)
Replace the Stream associated with this sensor.
Private Attributes
FDataMultiStream Stream
Detailed Description
Serializes and sends all the actors in the current UCarlaEpisode.
Definition at line 14 of file WorldObserver.h.
Member Typedef Documentation
not_spawnable
using FWorldObserver::not_spawnable = void
Prevent this sensor to be spawned by users.
Definition at line 19 of file WorldObserver.h.
Member Function Documentation
BroadcastTick()
void FWorldObserver::BroadcastTick (const UCarlaEpisode & Episode, float DeltaSeconds, bool MapChange, bool PendingLightUpdate)
Send a message to every connected client with the info about the given Episode.
Definition at line 367 of file WorldObserver.cpp.
References FWorldObserver_Serialize(), UCarlaEpisode::GetElapsedGameTime(), FDataStreamTmpl< T >::IsStreamReady(), FDataStreamTmpl< T >::MakeAsyncDataStream(), and Stream.
Referenced by FCarlaEngine::OnPostTick().
GetActorTransform()
FTransform FWorldObserver::GetActorTransform () const inline
Dummy. Required for compatibility with other sensors only.
Definition at line 42 of file WorldObserver.h.
GetToken()
auto FWorldObserver::GetToken () const inline
Return the token that allows subscribing to this sensor's stream.
Definition at line 28 of file WorldObserver.h.
References FDataStreamTmpl< T >::GetToken(), and Stream.
SetStream()
void FWorldObserver::SetStream (FDataMultiStream InStream) inline
Replace the Stream associated with this sensor.
Definition at line 22 of file WorldObserver.h.
References Stream.
Referenced by FCarlaEngine::NotifyInitGame().
Member Data Documentation
Stream
FDataMultiStream FWorldObserver::Stream private
Definition at line 49 of file WorldObserver.h.
Referenced by BroadcastTick(), GetToken(), and SetStream().
The documentation for this class was generated from the following files:
WorldObserver.h
WorldObserver.cpp