CARLA: CarlaRecorderQuery Class Reference
CarlaRecorderQuery Class Reference
#include <CarlaRecorderQuery.h>
Classes
struct Header
Public Member Functions
std::string QueryBlocked (std::string Filename, double MinTime=30, double MinDistance=10)
std::string QueryCollisions (std::string Filename, char Category1='a', char Category2='a')
std::string QueryInfo (std::string Filename, bool bShowAll=false)
Private Member Functions
bool CheckFileInfo (std::stringstream &Info)
bool ReadHeader (void)
void SkipPacket (void)
Private Attributes
CarlaRecorderActorBoundingBox ActorBoundingBox
CarlaRecorderCollision Collision
CarlaRecorderDoorVehicle DoorVehicle
CarlaRecorderEventAdd EventAdd
CarlaRecorderEventDel EventDel
CarlaRecorderEventParent EventParent
std::ifstream File
CarlaRecorderFrame Frame
Header Header
CarlaRecorderKinematics Kinematics
CarlaRecorderLightScene LightScene
CarlaRecorderLightVehicle LightVehicle
CarlaRecorderPhysicsControl PhysicsControl
CarlaRecorderPlatformTime PlatformTime
CarlaRecorderPosition Position
CarlaRecorderInfo RecInfo
CarlaRecorderStateTrafficLight StateTraffic
CarlaRecorderTrafficLightTime TrafficLightTime
CarlaRecorderAnimVehicle Vehicle
CarlaRecorderAnimWalker Walker
CarlaRecorderWalkerBones WalkerBones
Detailed Description
Definition at line 31 of file CarlaRecorderQuery.h.
Member Function Documentation
CheckFileInfo()
bool CarlaRecorderQuery::CheckFileInfo (std::stringstream & Info) inline private
Definition at line 42 of file CarlaRecorderQuery.cpp.
References CarlaRecorderInfo::Date, File, CarlaRecorderInfo::Magic, CarlaRecorderInfo::Mapfile, CarlaRecorderInfo::Read(), RecInfo, and CarlaRecorderInfo::Version.
Referenced by QueryBlocked(), QueryCollisions(), and QueryInfo().
QueryBlocked()
std::string CarlaRecorderQuery::QueryBlocked (std::string Filename, double MinTime = 30, double MinDistance = 10)
Definition at line 821 of file CarlaRecorderQuery.cpp.
References CheckFileInfo(), Collision, CarlaRecorderEventAdd::DatabaseId, CarlaRecorderPosition::DatabaseId, CarlaRecorderEventAdd::Description, CarlaRecorderFrame::DurationThis, CarlaRecorderFrame::Elapsed, EventAdd, EventAdd, EventDel, EventDel, EventParent, File, Frame, FrameEnd, FrameStart, GetRecorderFilename(), CarlaRecorderActorDescription::Id, CarlaRecorderFrame::Id, CarlaRecorderQuery::Header::Id, CarlaRecorderPosition::Location, Position, Position, CarlaRecorderEventAdd::Read(), CarlaRecorderEventDel::Read(), CarlaRecorderFrame::Read(), CarlaRecorderPosition::Read(), ReadHeader(), SkipPacket(), State, and CarlaRecorderEventAdd::Type.
Referenced by ACarlaRecorder::ShowFileActorsBlocked().
QueryCollisions()
std::string CarlaRecorderQuery::QueryCollisions (std::string Filename, char Category1 = 'a', char Category2 = 'a')
Definition at line 641 of file CarlaRecorderQuery.cpp.
References CheckFileInfo(), Collision, Collision, CarlaRecorderEventAdd::DatabaseId, CarlaRecorderCollision::DatabaseId1, CarlaRecorderCollision::DatabaseId2, CarlaRecorderEventAdd::Description, CarlaRecorderFrame::Elapsed, EventAdd, EventAdd, EventDel, EventDel, EventParent, File, Frame, FrameEnd, FrameStart, GetRecorderFilename(), CarlaRecorderActorDescription::Id, CarlaRecorderFrame::Id, CarlaRecorderQuery::Header::Id, CarlaRecorderCollision::IsActor1Hero, CarlaRecorderCollision::IsActor2Hero, Position, CarlaRecorderCollision::Read(), CarlaRecorderEventAdd::Read(), CarlaRecorderEventDel::Read(), CarlaRecorderFrame::Read(), ReadHeader(), SkipPacket(), State, and CarlaRecorderEventAdd::Type.
Referenced by ACarlaRecorder::ShowFileCollisions().
QueryInfo()
std::string CarlaRecorderQuery::QueryInfo (std::string Filename, bool bShowAll = false)
Definition at line 65 of file CarlaRecorderQuery.cpp.
References ActorBoundingBox, All, CarlaRecorderKinematics::AngularVelocity, AnimVehicle, AnimWalker, CarlaRecorderActorDescription::Attributes, CarlaRecorderAnimVehicle::bHandbrake, CarlaRecorderLightScene::bOn, CarlaRecorderWalkerBones::Bones, BoundingBox, CarlaRecorderActorBoundingBox::BoundingBox, CarlaRecorderAnimVehicle::Brake, carla::rpc::VehiclePhysicsControl::center_of_mass, CheckFileInfo(), CarlaRecorderWalkerBones::Clear(), carla::rpc::VehiclePhysicsControl::clutch_strength, Collision, Collision, CarlaRecorderLightScene::Color, carla::rpc::VehiclePhysicsControl::damping_rate_full_throttle, carla::rpc::VehiclePhysicsControl::damping_rate_zero_throttle_clutch_disengaged, carla::rpc::VehiclePhysicsControl::damping_rate_zero_throttle_clutch_engaged, CarlaRecorderAnimVehicle::DatabaseId, CarlaRecorderAnimWalker::DatabaseId, CarlaRecorderActorBoundingBox::DatabaseId, CarlaRecorderDoorVehicle::DatabaseId, CarlaRecorderEventAdd::DatabaseId, CarlaRecorderEventDel::DatabaseId, CarlaRecorderEventParent::DatabaseId, CarlaRecorderKinematics::DatabaseId, CarlaRecorderLightVehicle::DatabaseId, CarlaRecorderPhysicsControl::DatabaseId, CarlaRecorderPosition::DatabaseId, CarlaRecorderStateTrafficLight::DatabaseId, CarlaRecorderTrafficLightTime::DatabaseId, CarlaRecorderWalkerBones::DatabaseId, CarlaRecorderCollision::DatabaseId1, CarlaRecorderCollision::DatabaseId2, CarlaRecorderEventParent::DatabaseIdParent, CarlaRecorderEventAdd::Description, CarlaRecorderDoorVehicle::Doors, DoorVehicle, carla::rpc::VehiclePhysicsControl::drag_coefficient, CarlaRecorderFrame::Elapsed, CarlaRecorderStateTrafficLight::ElapsedTime, EventAdd, EventAdd, EventDel, EventDel, EventParent, EventParent, CarlaRecorderBoundingBox::Extension, File, carla::rpc::VehiclePhysicsControl::final_ratio, FL, carla::rpc::VehiclePhysicsControl::forward_gears, FR, Frame, FrameEnd, FrameStart, CarlaRecorderAnimVehicle::Gear, carla::rpc::VehiclePhysicsControl::gear_switch_time, GetRecorderFilename(), CarlaRecorderTrafficLightTime::GreenTime, Hood, CarlaRecorderCollision::Id, CarlaRecorderActorDescription::Id, CarlaRecorderFrame::Id, CarlaRecorderQuery::Header::Id, CarlaRecorderLightScene::Intensity, CarlaRecorderCollision::IsActor1Hero, CarlaRecorderCollision::IsActor2Hero, CarlaRecorderStateTrafficLight::IsFrozen, Kinematics, Kinematics, CarlaRecorderLightScene::LightId, LightScene, LightVehicle, CarlaRecorderKinematics::LinearVelocity, CarlaRecorderEventAdd::Location, CarlaRecorderPosition::Location, carla::rpc::VehiclePhysicsControl::mass, carla::rpc::VehiclePhysicsControl::max_rpm, carla::rpc::VehiclePhysicsControl::moi, CarlaRecorderBoundingBox::Origin, PhysicsControl, PhysicsControl, PlatformTime, PlatformTime, Position, Position, CarlaRecorderWalkerBones::Read(), CarlaRecorderAnimVehicle::Read(), CarlaRecorderAnimWalker::Read(), CarlaRecorderActorBoundingBox::Read(), CarlaRecorderCollision::Read(), CarlaRecorderDoorVehicle::Read(), CarlaRecorderEventAdd::Read(), CarlaRecorderEventDel::Read(), CarlaRecorderEventParent::Read(), CarlaRecorderFrame::Read(), CarlaRecorderKinematics::Read(), CarlaRecorderLightScene::Read(), CarlaRecorderLightVehicle::Read(), CarlaRecorderPhysicsControl::Read(), CarlaRecorderPlatformTime::Read(), CarlaRecorderPosition::Read(), CarlaRecorderStateTrafficLight::Read(), CarlaRecorderTrafficLightTime::Read(), ReadHeader(), CarlaRecorderTrafficLightTime::RedTime, RL, CarlaRecorderPosition::Rotation, RR, SceneLight, SkipPacket(), CarlaRecorderAnimWalker::Speed, State, CarlaRecorderLightVehicle::State, CarlaRecorderStateTrafficLight::State, StateTraffic, CarlaRecorderAnimVehicle::Steering, carla::rpc::VehiclePhysicsControl::steering_curve, CarlaRecorderAnimVehicle::Throttle, CarlaRecorderPlatformTime::Time, carla::rpc::VehiclePhysicsControl::torque_curve, TrafficLightTime, TrafficLightTime, TriggerVolume, Trunk, CarlaRecorderEventAdd::Type, carla::rpc::VehiclePhysicsControl::use_gear_autobox, Vehicle, VehicleDoor, VehicleLight, CarlaRecorderPhysicsControl::VehiclePhysicsControl, Walker, WalkerBones, WalkerBones, carla::rpc::VehiclePhysicsControl::wheels, carla::geom::Vector3D::x, carla::geom::Vector3D::y, CarlaRecorderTrafficLightTime::YellowTime, and carla::geom::Vector3D::z.
Referenced by ACarlaRecorder::ShowFileInfo().
ReadHeader()
bool CarlaRecorderQuery::ReadHeader (void) inline private
Definition at line 24 of file CarlaRecorderQuery.cpp.
References File, CarlaRecorderQuery::Header::Id, and CarlaRecorderQuery::Header::Size.
Referenced by QueryBlocked(), QueryCollisions(), and QueryInfo().
SkipPacket()
void CarlaRecorderQuery::SkipPacket (void) inline private
Definition at line 37 of file CarlaRecorderQuery.cpp.
References File, and CarlaRecorderQuery::Header::Size.
Referenced by QueryBlocked(), QueryCollisions(), and QueryInfo().
Member Data Documentation
ActorBoundingBox
CarlaRecorderActorBoundingBox CarlaRecorderQuery::ActorBoundingBox private
Definition at line 68 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
Collision
CarlaRecorderCollision CarlaRecorderQuery::Collision private
Definition at line 61 of file CarlaRecorderQuery.h.
Referenced by QueryCollisions(), and QueryInfo().
DoorVehicle
CarlaRecorderDoorVehicle CarlaRecorderQuery::DoorVehicle private
Definition at line 73 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
EventAdd
CarlaRecorderEventAdd CarlaRecorderQuery::EventAdd private
Definition at line 57 of file CarlaRecorderQuery.h.
Referenced by QueryBlocked(), QueryCollisions(), and QueryInfo().
EventDel
CarlaRecorderEventDel CarlaRecorderQuery::EventDel private
Definition at line 58 of file CarlaRecorderQuery.h.
Referenced by QueryBlocked(), QueryCollisions(), and QueryInfo().
EventParent
CarlaRecorderEventParent CarlaRecorderQuery::EventParent private
Definition at line 59 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
File
std::ifstream CarlaRecorderQuery::File private
Definition at line 53 of file CarlaRecorderQuery.h.
Referenced by CheckFileInfo(), QueryBlocked(), QueryCollisions(), QueryInfo(), ReadHeader(), and SkipPacket().
Frame
CarlaRecorderFrame CarlaRecorderQuery::Frame private
Definition at line 56 of file CarlaRecorderQuery.h.
Referenced by QueryBlocked(), QueryCollisions(), and QueryInfo().
Header
Header CarlaRecorderQuery::Header private
Definition at line 54 of file CarlaRecorderQuery.h.
Kinematics
CarlaRecorderKinematics CarlaRecorderQuery::Kinematics private
Definition at line 67 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
LightScene
CarlaRecorderLightScene CarlaRecorderQuery::LightScene private
Definition at line 66 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
LightVehicle
CarlaRecorderLightVehicle CarlaRecorderQuery::LightVehicle private
Definition at line 65 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
PhysicsControl
CarlaRecorderPhysicsControl CarlaRecorderQuery::PhysicsControl private
Definition at line 70 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
PlatformTime
CarlaRecorderPlatformTime CarlaRecorderQuery::PlatformTime private
Definition at line 69 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
Position
CarlaRecorderPosition CarlaRecorderQuery::Position private
Definition at line 60 of file CarlaRecorderQuery.h.
Referenced by QueryBlocked(), and QueryInfo().
RecInfo
CarlaRecorderInfo CarlaRecorderQuery::RecInfo private
Definition at line 55 of file CarlaRecorderQuery.h.
Referenced by CheckFileInfo().
StateTraffic
CarlaRecorderStateTrafficLight CarlaRecorderQuery::StateTraffic private
Definition at line 62 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
TrafficLightTime
CarlaRecorderTrafficLightTime CarlaRecorderQuery::TrafficLightTime private
Definition at line 71 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
Vehicle
CarlaRecorderAnimVehicle CarlaRecorderQuery::Vehicle private
Definition at line 63 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
Walker
CarlaRecorderAnimWalker CarlaRecorderQuery::Walker private
Definition at line 64 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
WalkerBones
CarlaRecorderWalkerBones CarlaRecorderQuery::WalkerBones private
Definition at line 72 of file CarlaRecorderQuery.h.
Referenced by QueryInfo().
The documentation for this class was generated from the following files:
CarlaRecorderQuery.h
CarlaRecorderQuery.cpp