CARLA: FFoliageBlueprint Struct Reference
FFoliageBlueprint Struct Reference
#include <VegetationManager.h>
Public Member Functions
bool IsValid () const
bool SetBPClassName (const FString &Path)
bool SetSpawnedClass ()
Public Attributes
FString BPFullClassName {}
TSubclassOf< AActor > SpawnedClass { nullptr }
Detailed Description
Definition at line 49 of file VegetationManager.h.
Member Function Documentation
IsValid()
bool FFoliageBlueprint::IsValid () const
Definition at line 135 of file VegetationManager.cpp.
References BPFullClassName, and SpawnedClass.
Referenced by AVegetationManager::UpdateFoliageBlueprintCache().
SetBPClassName()
bool FFoliageBlueprint::SetBPClassName (const FString & Path)
Definition at line 142 of file VegetationManager.cpp.
References BPFullClassName, GetVersionFromFString(), and Position.
Referenced by AVegetationManager::UpdateFoliageBlueprintCache().
SetSpawnedClass()
bool FFoliageBlueprint::SetSpawnedClass ()
Definition at line 166 of file VegetationManager.cpp.
References BPFullClassName, and SpawnedClass.
Referenced by AVegetationManager::UpdateFoliageBlueprintCache().
Member Data Documentation
BPFullClassName
FString FFoliageBlueprint::BPFullClassName {}
Definition at line 52 of file VegetationManager.h.
Referenced by AVegetationManager::CreatePoolForBPClass(), IsValid(), SetBPClassName(), SetSpawnedClass(), and AVegetationManager::UpdateFoliageBlueprintCache().
SpawnedClass
TSubclassOf<AActor> FFoliageBlueprint::SpawnedClass { nullptr }
Definition at line 53 of file VegetationManager.h.
Referenced by AVegetationManager::CreateFoliage(), IsValid(), and SetSpawnedClass().
The documentation for this struct was generated from the following files:
VegetationManager.h
VegetationManager.cpp