CARLA: carla::traffic_manager::RandomGenerator Class Reference
carla::traffic_manager::RandomGenerator Class Reference
#include <RandomGenerator.h>
Public Member Functions
double next ()
RandomGenerator (const uint64_t seed)
Private Attributes
std::uniform_real_distribution< double > dist
std::mt19937 mt
Detailed Description
Definition at line 12 of file RandomGenerator.h.
Constructor & Destructor Documentation
RandomGenerator()
carla::traffic_manager::RandomGenerator::RandomGenerator (const uint64_t seed) inline
Definition at line 14 of file RandomGenerator.h.
Member Function Documentation
next()
double carla::traffic_manager::RandomGenerator::next () inline
Definition at line 15 of file RandomGenerator.h.
References dist, and mt.
Referenced by carla::traffic_manager::MotionPlanStage::Update(), carla::traffic_manager::CollisionStage::Update(), carla::traffic_manager::LocalizationStage::Update(), and carla::traffic_manager::TrafficLightStage::Update().
Member Data Documentation
dist
std::uniform_real_distribution<double> carla::traffic_manager::RandomGenerator::dist private
Definition at line 18 of file RandomGenerator.h.
Referenced by next().
mt
std::mt19937 carla::traffic_manager::RandomGenerator::mt private
Definition at line 17 of file RandomGenerator.h.
Referenced by next().
The documentation for this class was generated from the following file:
RandomGenerator.h