CARLA: carla::sensor::s11n::SensorHeaderSerializer Class Reference
carla::sensor::s11n::SensorHeaderSerializer Class Reference
Serializes the meta-information (header) sent with all the sensor data.
#include <SensorHeaderSerializer.h>
Classes
struct Header
Static Public Member Functions
static const Header & Deserialize (const Buffer &message)
static Buffer Serialize (uint64_t index, uint64_t frame, double timestamp, rpc::Transform transform)
Static Public Attributes
static constexpr auto header_offset = sizeof(Header)
Detailed Description
Serializes the meta-information (header) sent with all the sensor data.
Definition at line 17 of file SensorHeaderSerializer.h.
Member Function Documentation
Deserialize()
static const Header & carla::sensor::s11n::SensorHeaderSerializer::Deserialize (const Buffer & message) inline static
Definition at line 37 of file SensorHeaderSerializer.h.
References carla::Buffer::data().
Referenced by carla::sensor::RawData::GetHeader().
Serialize()
Buffer carla::sensor::s11n::SensorHeaderSerializer::Serialize (uint64_t index, uint64_t frame, double timestamp, rpc::Transform transform) static
Definition at line 24 of file SensorHeaderSerializer.cpp.
References carla::sensor::s11n::SensorHeaderSerializer::Header::frame, carla::sensor::s11n::PopBufferFromPool(), carla::sensor::s11n::SensorHeaderSerializer::Header::sensor_transform, carla::sensor::s11n::SensorHeaderSerializer::Header::sensor_type, and carla::sensor::s11n::SensorHeaderSerializer::Header::timestamp.
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::SensorHeaderSerializer::header_offset = sizeof(Header) static constexpr
Definition at line 29 of file SensorHeaderSerializer.h.
Referenced by carla::sensor::RawData::begin(), and carla::sensor::RawData::begin().
The documentation for this class was generated from the following files:
SensorHeaderSerializer.h
SensorHeaderSerializer.cpp