CARLA: carla::road::LaneSectionMap Class Reference
carla::road::LaneSectionMap Class Reference
#include <LaneSectionMap.h>
Public Member Functions
LaneSection & Emplace (SectionId id, double s)
LaneSection & GetById (SectionId id)
const LaneSection & GetById (SectionId id) const
Private Types
using Super = std::multimap<double, LaneSection>
Private Attributes
std::unordered_map< SectionId, LaneSection * > _by_id
Additional Inherited Members
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Detailed Description
Definition at line 18 of file LaneSectionMap.h.
Member Typedef Documentation
Super
using carla::road::LaneSectionMap::Super = std::multimap<double, LaneSection> private
Definition at line 21 of file LaneSectionMap.h.
Member Function Documentation
Emplace()
LaneSection & carla::road::LaneSectionMap::Emplace (SectionId id, double s) inline
Definition at line 24 of file LaneSectionMap.h.
References _by_id, and carla::road::LaneSection::GetId().
Referenced by carla::road::MapBuilder::AddRoadSection().
GetById() [1/2]
LaneSection & carla::road::LaneSectionMap::GetById (SectionId id) inline
Definition at line 30 of file LaneSectionMap.h.
References _by_id.
Referenced by carla::road::MapBuilder::GetLaneNext(), carla::road::Road::GetLaneSectionById(), and carla::road::Road::GetLaneSectionById().
GetById() [2/2]
const LaneSection & carla::road::LaneSectionMap::GetById (SectionId id) const inline
Definition at line 34 of file LaneSectionMap.h.
References _by_id.
Member Data Documentation
_by_id
std::unordered_map<SectionId, LaneSection *> carla::road::LaneSectionMap::_by_id private
Definition at line 49 of file LaneSectionMap.h.
Referenced by Emplace(), GetById(), and GetById().
The documentation for this class was generated from the following file:
LaneSectionMap.h