CARLA: ACarlaRecorder Class Reference
ACarlaRecorder Class Reference
Recorder for the simulation.
#include <CarlaRecorder.h>
Public Member Functions
ACarlaRecorder (const FObjectInitializer &InObjectInitializer)
ACarlaRecorder (void)
void AddActorBones (FCarlaActor *CarlaActor)
void AddAnimBiker (const CarlaRecorderAnimBiker &Biker)
void AddAnimVehicle (const CarlaRecorderAnimVehicle &Vehicle)
void AddAnimVehicleWheels (const CarlaRecorderAnimWheels &VehicleWheels)
void AddAnimWalker (const CarlaRecorderAnimWalker &Walker)
void AddBoundingBox (const CarlaRecorderActorBoundingBox &ActorBoundingBox)
void AddCollision (AActor *Actor1, AActor *Actor2)
void AddDoorVehicle (const CarlaRecorderDoorVehicle &DoorVehicle)
void AddEvent (const CarlaRecorderEventAdd &Event)
void AddEvent (const CarlaRecorderEventDel &Event)
void AddEvent (const CarlaRecorderEventParent &Event)
void AddEventLightSceneChanged (const UCarlaLight *Light)
void AddKinematics (const CarlaRecorderKinematics &ActorKinematics)
void AddLightVehicle (const CarlaRecorderLightVehicle &LightVehicle)
void AddPhysicsControl (const ACarlaWheeledVehicle &Vehicle)
void AddPosition (const CarlaRecorderPosition &Position)
void AddState (const CarlaRecorderStateTrafficLight &State)
void AddTrafficLightTime (const ATrafficLightBase &TrafficLight)
void AddTriggerVolume (const ATrafficSignBase &TrafficSign)
void AddVehicleDoor (const ACarlaWheeledVehicle &Vehicle, const EVehicleDoor SDoors, bool bIsOpen)
void Clear (void)
void CreateRecorderEventAdd (uint32_t DatabaseId, uint8_t Type, const FTransform &Transform, FActorDescription ActorDescription)
void Disable (void)
void Enable (void)
CarlaReplayer * GetReplayer (void)
bool IsEnabled (void)
std::string ReplayFile (std::string Name, double TimeStart, double Duration, uint32_t FollowId, bool ReplaySensors)
void SetEpisode (UCarlaEpisode *ThisEpisode)
void SetReplayerIgnoreHero (bool IgnoreHero)
void SetReplayerIgnoreSpectator (bool IgnoreSpectator)
void SetReplayerTimeFactor (double TimeFactor)
std::string ShowFileActorsBlocked (std::string Name, double MinTime=30, double MinDistance=10)
std::string ShowFileCollisions (std::string Name, char Type1, char Type2)
std::string ShowFileInfo (std::string Name, bool bShowAll=false)
std::string Start (std::string Name, FString MapName, bool AdditionalData=false)
void Stop (void)
void StopReplayer (bool KeepActors=false)
void Ticking (float DeltaSeconds)
void Write (double DeltaSeconds)
Private Member Functions
void AddActorBoundingBox (FCarlaActor *CarlaActor)
void AddActorKinematics (FCarlaActor *CarlaActor)
void AddActorPosition (FCarlaActor *CarlaActor)
void AddBikerAnimation (FCarlaActor *CarlaActor)
void AddExistingActors (void)
void AddTrafficLightState (FCarlaActor *CarlaActor)
void AddVehicleAnimation (FCarlaActor *CarlaActor)
void AddVehicleLight (FCarlaActor *CarlaActor)
void AddVehicleWheelsAnimation (FCarlaActor *CarlaActor)
void AddWalkerAnimation (FCarlaActor *CarlaActor)
Private Attributes
bool bAdditionalData = false
CarlaRecorderAnimBikers Bikers
CarlaRecorderActorBoundingBoxes BoundingBoxes
CarlaRecorderCollisions Collisions
CarlaRecorderDoorVehicles DoorVehicles
bool Enabled
UCarlaEpisode * Episode = nullptr
CarlaRecorderEventsAdd EventsAdd
CarlaRecorderEventsDel EventsDel
CarlaRecorderEventsParent EventsParent
std::ofstream File
CarlaRecorderFrames Frames
CarlaRecorderInfo Info
CarlaRecorderActorsKinematics Kinematics
CarlaRecorderLightScenes LightScenes
CarlaRecorderLightVehicles LightVehicles
uint32_t NextCollisionId = 0
CarlaRecorderPhysicsControls PhysicsControls
CarlaRecorderPlatformTime PlatformTime
CarlaRecorderPositions Positions
CarlaRecorderQuery Query
CarlaReplayer Replayer
CarlaRecorderStates States
CarlaRecorderTrafficLightTimes TrafficLightTimes
CarlaRecorderActorTriggerVolumes TriggerVolumes
CarlaRecorderAnimVehicles Vehicles
CarlaRecorderVisualTime VisualTime
CarlaRecorderAnimWalkers Walkers
CarlaRecorderWalkersBones WalkersBones
CarlaRecorderAnimVehicleWheels Wheels
Detailed Description
Recorder for the simulation.
Definition at line 79 of file CarlaRecorder.h.
Constructor & Destructor Documentation
ACarlaRecorder() [1/2]
ACarlaRecorder::ACarlaRecorder (void)
Definition at line 33 of file CarlaRecorder.cpp.
References Disable().
ACarlaRecorder() [2/2]
ACarlaRecorder::ACarlaRecorder (const FObjectInitializer & InObjectInitializer)
Definition at line 39 of file CarlaRecorder.cpp.
References Disable().
Member Function Documentation
AddActorBones()
void ACarlaRecorder::AddActorBones (FCarlaActor * CarlaActor)
Definition at line 394 of file CarlaRecorder.cpp.
References CarlaRecorderWalkersBones::Add(), CarlaRecorderWalkerBones::Bones, FWalkerBoneControlOut::BoneTransforms, CarlaRecorderWalkerBones::DatabaseId, FCarlaActor::GetActorId(), FCarlaActor::GetBonesTransform(), and WalkersBones.
Referenced by Ticking().
AddActorBoundingBox()
void ACarlaRecorder::AddActorBoundingBox (FCarlaActor * CarlaActor) private
Definition at line 333 of file CarlaRecorder.cpp.
References AddBoundingBox(), FActorInfo::BoundingBox, BoundingBox, FCarlaActor::GetActorId(), and FCarlaActor::GetActorInfo().
Referenced by CreateRecorderEventAdd().
AddActorKinematics()
void ACarlaRecorder::AddActorKinematics (FCarlaActor * CarlaActor) private
Definition at line 316 of file CarlaRecorder.cpp.
References AddKinematics(), FCarlaActor::GetActorAngularVelocity(), FCarlaActor::GetActorId(), and FCarlaActor::GetActorVelocity().
Referenced by Ticking().
AddActorPosition()
void ACarlaRecorder::AddActorPosition (FCarlaActor * CarlaActor) private
Definition at line 168 of file CarlaRecorder.cpp.
References AddPosition(), FCarlaActor::GetActorGlobalTransform(), and FCarlaActor::GetActorId().
Referenced by Ticking().
AddAnimBiker()
void ACarlaRecorder::AddAnimBiker (const CarlaRecorderAnimBiker & Biker)
Definition at line 650 of file CarlaRecorder.cpp.
References CarlaRecorderAnimBikers::Add(), Bikers, and Enabled.
Referenced by AddVehicleWheelsAnimation().
AddAnimVehicle()
void ACarlaRecorder::AddAnimVehicle (const CarlaRecorderAnimVehicle & Vehicle)
Definition at line 626 of file CarlaRecorder.cpp.
References CarlaRecorderAnimVehicles::Add(), Enabled, Vehicle, and Vehicles.
Referenced by AddVehicleAnimation().
AddAnimVehicleWheels()
void ACarlaRecorder::AddAnimVehicleWheels (const CarlaRecorderAnimWheels & VehicleWheels)
Definition at line 634 of file CarlaRecorder.cpp.
References CarlaRecorderAnimVehicleWheels::Add(), Enabled, and Wheels.
Referenced by AddVehicleWheelsAnimation().
AddAnimWalker()
void ACarlaRecorder::AddAnimWalker (const CarlaRecorderAnimWalker & Walker)
Definition at line 642 of file CarlaRecorder.cpp.
References CarlaRecorderAnimWalkers::Add(), Enabled, and Walkers.
Referenced by AddWalkerAnimation().
AddBikerAnimation()
void ACarlaRecorder::AddBikerAnimation (FCarlaActor * CarlaActor) private
AddBoundingBox()
void ACarlaRecorder::AddBoundingBox (const CarlaRecorderActorBoundingBox & ActorBoundingBox)
Definition at line 699 of file CarlaRecorder.cpp.
References CarlaRecorderActorBoundingBoxes::Add(), BoundingBoxes, and Enabled.
Referenced by AddActorBoundingBox().
AddCollision()
void ACarlaRecorder::AddCollision (AActor * Actor1, AActor * Actor2)
Definition at line 573 of file CarlaRecorder.cpp.
References CarlaRecorderCollisions::Add(), Collision, Collisions, FActorInfo::Description, Enabled, Episode, FActorRegistry::FindCarlaActor(), FCarlaActor::GetActorId(), FCarlaActor::GetActorInfo(), UCarlaEpisode::GetActorRegistry(), CarlaRecorderCollision::Id, NextCollisionId, and FActorDescription::Variations.
AddDoorVehicle()
void ACarlaRecorder::AddDoorVehicle (const CarlaRecorderDoorVehicle & DoorVehicle)
Definition at line 666 of file CarlaRecorder.cpp.
References CarlaRecorderDoorVehicles::Add(), DoorVehicles, and Enabled.
Referenced by AddVehicleDoor().
AddEvent() [1/3]
void ACarlaRecorder::AddEvent (const CarlaRecorderEventAdd & Event)
Definition at line 549 of file CarlaRecorder.cpp.
References CarlaRecorderEventsAdd::Add(), Enabled, and EventsAdd.
Referenced by UCarlaEpisode::AttachActors(), and CreateRecorderEventAdd().
AddEvent() [2/3]
void ACarlaRecorder::AddEvent (const CarlaRecorderEventDel & Event)
Definition at line 557 of file CarlaRecorder.cpp.
References CarlaRecorderEventsDel::Add(), Enabled, and EventsDel.
AddEvent() [3/3]
void ACarlaRecorder::AddEvent (const CarlaRecorderEventParent & Event)
Definition at line 565 of file CarlaRecorder.cpp.
References CarlaRecorderEventsParent::Add(), Enabled, and EventsParent.
AddEventLightSceneChanged()
void ACarlaRecorder::AddEventLightSceneChanged (const UCarlaLight * Light)
Definition at line 674 of file CarlaRecorder.cpp.
References CarlaRecorderLightScenes::Add(), Enabled, and LightScenes.
Referenced by AddExistingActors().
AddExistingActors()
void ACarlaRecorder::AddExistingActors (void) private
Definition at line 707 of file CarlaRecorder.cpp.
References AddEventLightSceneChanged(), CreateRecorderEventAdd(), FActorInfo::Description, Episode, FCarlaActor::GetActorGlobalTransform(), FCarlaActor::GetActorId(), FCarlaActor::GetActorInfo(), UCarlaEpisode::GetActorRegistry(), FCarlaActor::GetActorType(), and UCarlaLightSubsystem::GetLights().
Referenced by Start().
AddKinematics()
void ACarlaRecorder::AddKinematics (const CarlaRecorderKinematics & ActorKinematics)
Definition at line 691 of file CarlaRecorder.cpp.
References CarlaRecorderActorsKinematics::Add(), Enabled, and Kinematics.
Referenced by AddActorKinematics().
AddLightVehicle()
void ACarlaRecorder::AddLightVehicle (const CarlaRecorderLightVehicle & LightVehicle)
Definition at line 658 of file CarlaRecorder.cpp.
References CarlaRecorderLightVehicles::Add(), Enabled, and LightVehicles.
Referenced by AddVehicleLight().
AddPhysicsControl()
void ACarlaRecorder::AddPhysicsControl (const ACarlaWheeledVehicle & Vehicle)
Definition at line 368 of file CarlaRecorder.cpp.
References CarlaRecorderPhysicsControls::Add(), bAdditionalData, CarlaRecorderPhysicsControl::DatabaseId, Episode, FActorRegistry::FindCarlaActor(), FCarlaActor::GetActorId(), UCarlaEpisode::GetActorRegistry(), PhysicsControls, Vehicle, and CarlaRecorderPhysicsControl::VehiclePhysicsControl.
Referenced by CreateRecorderEventAdd().
AddPosition()
void ACarlaRecorder::AddPosition (const CarlaRecorderPosition & Position)
Definition at line 541 of file CarlaRecorder.cpp.
References CarlaRecorderPositions::Add(), Enabled, Position, and Positions.
Referenced by AddActorPosition().
AddState()
void ACarlaRecorder::AddState (const CarlaRecorderStateTrafficLight & State)
Definition at line 618 of file CarlaRecorder.cpp.
References CarlaRecorderStates::Add(), Enabled, State, and States.
Referenced by AddTrafficLightState().
AddTrafficLightState()
void ACarlaRecorder::AddTrafficLightState (FCarlaActor * CarlaActor) private
Definition at line 273 of file CarlaRecorder.cpp.
References AddState(), FCarlaActor::GetActorId(), UTrafficLightController::GetElapsedTime(), UTrafficLightController::GetGroup(), FCarlaActor::GetTrafficLightController(), FCarlaActor::GetTrafficLightState(), and ATrafficLightGroup::IsFrozen().
Referenced by Ticking().
AddTrafficLightTime()
void ACarlaRecorder::AddTrafficLightTime (const ATrafficLightBase & TrafficLight)
Definition at line 379 of file CarlaRecorder.cpp.
References CarlaRecorderTrafficLightTimes::Add(), bAdditionalData, Episode, FActorRegistry::FindCarlaActor(), FCarlaActor::GetActorId(), UCarlaEpisode::GetActorRegistry(), TrafficLight, TrafficLightTime, and TrafficLightTimes.
Referenced by CreateRecorderEventAdd().
AddTriggerVolume()
void ACarlaRecorder::AddTriggerVolume (const ATrafficSignBase & TrafficSign)
Definition at line 347 of file CarlaRecorder.cpp.
References CarlaRecorderActorTriggerVolumes::Add(), bAdditionalData, Episode, FActorRegistry::FindCarlaActor(), FCarlaActor::GetActorId(), UCarlaEpisode::GetActorRegistry(), ATrafficSignBase::GetTriggerVolumes(), TriggerVolume, and TriggerVolumes.
Referenced by CreateRecorderEventAdd().
AddVehicleAnimation()
void ACarlaRecorder::AddVehicleAnimation (FCarlaActor * CarlaActor) private
Definition at line 182 of file CarlaRecorder.cpp.
References AddAnimVehicle(), CarlaRecorderAnimVehicle::bHandbrake, FVehicleControl::bHandBrake, CarlaRecorderAnimVehicle::Brake, FVehicleControl::Brake, CarlaRecorderAnimVehicle::DatabaseId, CarlaRecorderAnimVehicle::Gear, FVehicleControl::Gear, FCarlaActor::GetActorId(), FCarlaActor::GetVehicleControl(), FCarlaActor::IsPendingKill(), FVehicleControl::Steer, CarlaRecorderAnimVehicle::Steering, CarlaRecorderAnimVehicle::Throttle, and FVehicleControl::Throttle.
Referenced by Ticking().
AddVehicleDoor()
void ACarlaRecorder::AddVehicleDoor (const ACarlaWheeledVehicle & Vehicle, const EVehicleDoor SDoors, bool bIsOpen)
Definition at line 307 of file CarlaRecorder.cpp.
References AddDoorVehicle(), CarlaRecorderDoorVehicle::bIsOpen, CarlaRecorderDoorVehicle::DatabaseId, CarlaRecorderDoorVehicle::Doors, Episode, FActorRegistry::FindCarlaActor(), FCarlaActor::GetActorId(), UCarlaEpisode::GetActorRegistry(), and Vehicle.
AddVehicleLight()
void ACarlaRecorder::AddVehicleLight (FCarlaActor * CarlaActor) private
Definition at line 295 of file CarlaRecorder.cpp.
References AddLightVehicle(), CarlaRecorderLightVehicle::DatabaseId, FCarlaActor::GetActorId(), FCarlaActor::GetVehicleLightState(), carla::rpc::VehicleLightState::light_state, and CarlaRecorderLightVehicle::State.
Referenced by Ticking().
AddVehicleWheelsAnimation()
void ACarlaRecorder::AddVehicleWheelsAnimation (FCarlaActor * CarlaActor) private
Definition at line 205 of file CarlaRecorder.cpp.
References AddAnimBiker(), AddAnimVehicleWheels(), CarlaRecorderAnimWheels::DatabaseId, FCarlaActor::GetActor(), FCarlaActor::GetActorId(), FCarlaActor::GetActorType(), ACarlaWheeledVehicle::GetWheelSteerAngle(), Info, FCarlaActor::IsPendingKill(), ACarlaWheeledVehicle::IsTwoWheeledVehicle(), FCarlaActor::Vehicle, and CarlaRecorderAnimWheels::WheelValues.
Referenced by Ticking().
AddWalkerAnimation()
void ACarlaRecorder::AddWalkerAnimation (FCarlaActor * CarlaActor) private
Definition at line 257 of file CarlaRecorder.cpp.
References AddAnimWalker(), FCarlaActor::GetActorId(), FCarlaActor::GetWalkerControl(), FCarlaActor::IsPendingKill(), and FWalkerControl::Speed.
Referenced by Ticking().
Clear()
void ACarlaRecorder::Clear (void)
Definition at line 472 of file CarlaRecorder.cpp.
References Bikers, BoundingBoxes, CarlaRecorderAnimBikers::Clear(), CarlaRecorderAnimVehicles::Clear(), CarlaRecorderAnimVehicleWheels::Clear(), CarlaRecorderAnimWalkers::Clear(), CarlaRecorderActorBoundingBoxes::Clear(), CarlaRecorderActorTriggerVolumes::Clear(), CarlaRecorderCollisions::Clear(), CarlaRecorderDoorVehicles::Clear(), CarlaRecorderEventsAdd::Clear(), CarlaRecorderEventsDel::Clear(), CarlaRecorderEventsParent::Clear(), CarlaRecorderActorsKinematics::Clear(), CarlaRecorderLightScenes::Clear(), CarlaRecorderLightVehicles::Clear(), CarlaRecorderPhysicsControls::Clear(), CarlaRecorderPositions::Clear(), CarlaRecorderStates::Clear(), CarlaRecorderTrafficLightTimes::Clear(), CarlaRecorderWalkersBones::Clear(), Collisions, DoorVehicles, EventsAdd, EventsDel, EventsParent, Kinematics, LightScenes, LightVehicles, PhysicsControls, Positions, States, TrafficLightTimes, TriggerVolumes, Vehicles, Walkers, WalkersBones, and Wheels.
Referenced by Stop(), and Write().
CreateRecorderEventAdd()
void ACarlaRecorder::CreateRecorderEventAdd (uint32_t DatabaseId, uint8_t Type, const FTransform & Transform, FActorDescription ActorDescription)
Definition at line 739 of file CarlaRecorder.cpp.
References AddActorBoundingBox(), AddEvent(), AddPhysicsControl(), AddTrafficLightTime(), AddTriggerVolume(), CarlaRecorderActorDescription::Attributes, Episode, UCarlaEpisode::FindCarlaActor(), FCarlaActor::GetActor(), FActorDescription::Id, CarlaRecorderActorAttribute::Id, CarlaRecorderActorDescription::Id, TrafficLight, CarlaRecorderActorAttribute::Type, FActorDescription::UId, CarlaRecorderActorDescription::UId, CarlaRecorderActorAttribute::Value, FActorDescription::Variations, and Vehicle.
Referenced by AddExistingActors(), and UCarlaEpisode::SpawnActorWithInfo().
Disable()
void ACarlaRecorder::Disable (void)
Definition at line 162 of file CarlaRecorder.cpp.
References Enabled.
Referenced by ACarlaRecorder(), ACarlaRecorder(), and Stop().
Enable()
void ACarlaRecorder::Enable (void)
Definition at line 156 of file CarlaRecorder.cpp.
References Enabled.
Referenced by Start().
GetReplayer()
CarlaReplayer * ACarlaRecorder::GetReplayer (void) inline
Definition at line 161 of file CarlaRecorder.h.
Referenced by ACarlaGameModeBase::BeginPlay(), UCarlaEpisode::EndPlay(), and FCarlaEngine::NotifyBeginEpisode().
IsEnabled()
bool ACarlaRecorder::IsEnabled (void) inline
Definition at line 89 of file CarlaRecorder.h.
Referenced by UCarlaEpisode::AttachActors(), and UCarlaEpisode::SpawnActorWithInfo().
ReplayFile()
std::string ACarlaRecorder::ReplayFile (std::string Name, double TimeStart, double Duration, uint32_t FollowId, bool ReplaySensors)
Definition at line 61 of file CarlaRecorder.cpp.
References Replayer, CarlaReplayer::ReplayFile(), and Stop().
Referenced by FCarlaServer::FPimpl::BindActions().
SetEpisode()
void ACarlaRecorder::SetEpisode (UCarlaEpisode * ThisEpisode) inline
Definition at line 148 of file CarlaRecorder.h.
Referenced by ACarlaGameModeBase::InitGame(), and FCarlaEngine::NotifyBeginEpisode().
SetReplayerIgnoreHero()
void ACarlaRecorder::SetReplayerIgnoreHero (bool IgnoreHero)
Definition at line 73 of file CarlaRecorder.cpp.
References Replayer, and CarlaReplayer::SetIgnoreHero().
Referenced by FCarlaServer::FPimpl::BindActions().
SetReplayerIgnoreSpectator()
void ACarlaRecorder::SetReplayerIgnoreSpectator (bool IgnoreSpectator)
Definition at line 78 of file CarlaRecorder.cpp.
References Replayer, and CarlaReplayer::SetIgnoreSpectator().
Referenced by FCarlaServer::FPimpl::BindActions().
SetReplayerTimeFactor()
void ACarlaRecorder::SetReplayerTimeFactor (double TimeFactor)
Definition at line 68 of file CarlaRecorder.cpp.
References Replayer, and CarlaReplayer::SetTimeFactor().
Referenced by FCarlaServer::FPimpl::BindActions().
ShowFileActorsBlocked()
std::string ACarlaRecorder::ShowFileActorsBlocked (std::string Name, double MinTime = 30, double MinDistance = 10)
Definition at line 56 of file CarlaRecorder.cpp.
References Query, and CarlaRecorderQuery::QueryBlocked().
Referenced by FCarlaServer::FPimpl::BindActions().
ShowFileCollisions()
std::string ACarlaRecorder::ShowFileCollisions (std::string Name, char Type1, char Type2)
Definition at line 51 of file CarlaRecorder.cpp.
References Query, and CarlaRecorderQuery::QueryCollisions().
Referenced by FCarlaServer::FPimpl::BindActions().
ShowFileInfo()
std::string ACarlaRecorder::ShowFileInfo (std::string Name, bool bShowAll = false)
Definition at line 46 of file CarlaRecorder.cpp.
References Query, and CarlaRecorderQuery::QueryInfo().
Referenced by FCarlaServer::FPimpl::BindActions().
Start()
std::string ACarlaRecorder::Start (std::string Name, FString MapName, bool AdditionalData = false)
Definition at line 416 of file CarlaRecorder.cpp.
References AddExistingActors(), bAdditionalData, CarlaRecorderInfo::Date, Enable(), File, Frames, GetRecorderFilename(), Info, CarlaReplayer::IsEnabled(), CarlaRecorderInfo::Magic, CarlaRecorderInfo::Mapfile, NextCollisionId, PlatformTime, Replayer, CarlaRecorderFrames::Reset(), CarlaRecorderPlatformTime::SetStartTime(), CarlaReplayer::Stop(), Stop(), CarlaRecorderInfo::Version, and CarlaRecorderInfo::Write().
Referenced by UCarlaEpisode::StartRecorder().
Stop()
void ACarlaRecorder::Stop (void)
Definition at line 460 of file CarlaRecorder.cpp.
References Clear(), Disable(), and File.
Referenced by FCarlaServer::FPimpl::BindActions(), UCarlaEpisode::EndPlay(), ReplayFile(), and Start().
StopReplayer()
void ACarlaRecorder::StopReplayer (bool KeepActors = false)
Definition at line 83 of file CarlaRecorder.cpp.
References Replayer, and CarlaReplayer::Stop().
Referenced by FCarlaServer::FPimpl::BindActions().
Ticking()
void ACarlaRecorder::Ticking (float DeltaSeconds)
Definition at line 88 of file CarlaRecorder.cpp.
References AddActorBones(), AddActorKinematics(), AddActorPosition(), AddTrafficLightState(), AddVehicleAnimation(), AddVehicleLight(), AddVehicleWheelsAnimation(), AddWalkerAnimation(), bAdditionalData, FActorRegistry::begin(), Enabled, FActorRegistry::end(), Episode, UCarlaEpisode::GetActorRegistry(), FCarlaActor::GetActorType(), UCarlaEpisode::GetReplayer(), UCarlaEpisode::GetVisualGameTime(), CarlaReplayer::IsEnabled(), FCarlaActor::Other, PlatformTime, CarlaRecorderVisualTime::SetTime(), CarlaReplayer::Tick(), Ticking(), FCarlaActor::TrafficLight, CarlaRecorderPlatformTime::UpdateTime(), FCarlaActor::Vehicle, VisualTime, FCarlaActor::Walker, and Write().
Referenced by FCarlaEngine::OnPostTick(), and Ticking().
Write()
void ACarlaRecorder::Write (double DeltaSeconds)
Definition at line 495 of file CarlaRecorder.cpp.
References bAdditionalData, Bikers, BoundingBoxes, Clear(), Collisions, DoorVehicles, EventsAdd, EventsDel, EventsParent, File, Frames, Kinematics, LightScenes, LightVehicles, PhysicsControls, PlatformTime, Positions, CarlaRecorderFrames::SetFrame(), States, TrafficLightTimes, TriggerVolumes, Vehicles, VisualTime, Walkers, WalkersBones, Wheels, CarlaRecorderVisualTime::Write(), CarlaRecorderWalkersBones::Write(), CarlaRecorderAnimVehicles::Write(), CarlaRecorderAnimVehicleWheels::Write(), CarlaRecorderAnimWalkers::Write(), CarlaRecorderActorBoundingBoxes::Write(), CarlaRecorderActorTriggerVolumes::Write(), CarlaRecorderCollisions::Write(), CarlaRecorderDoorVehicles::Write(), CarlaRecorderEventsAdd::Write(), CarlaRecorderEventsDel::Write(), CarlaRecorderEventsParent::Write(), CarlaRecorderActorsKinematics::Write(), CarlaRecorderLightScenes::Write(), CarlaRecorderLightVehicles::Write(), CarlaRecorderPhysicsControls::Write(), CarlaRecorderPlatformTime::Write(), CarlaRecorderPositions::Write(), CarlaRecorderStates::Write(), CarlaRecorderTrafficLightTimes::Write(), CarlaRecorderAnimBikers::Write(), CarlaRecorderFrames::WriteEnd(), and CarlaRecorderFrames::WriteStart().
Referenced by Ticking().
Member Data Documentation
bAdditionalData
bool ACarlaRecorder::bAdditionalData = false private
Definition at line 186 of file CarlaRecorder.h.
Referenced by AddPhysicsControl(), AddTrafficLightTime(), AddTriggerVolume(), Start(), Ticking(), and Write().
Bikers
CarlaRecorderAnimBikers ACarlaRecorder::Bikers private
Definition at line 207 of file CarlaRecorder.h.
Referenced by AddAnimBiker(), Clear(), and Write().
BoundingBoxes
CarlaRecorderActorBoundingBoxes ACarlaRecorder::BoundingBoxes private
Definition at line 211 of file CarlaRecorder.h.
Referenced by AddBoundingBox(), Clear(), and Write().
Collisions
CarlaRecorderCollisions ACarlaRecorder::Collisions private
Definition at line 201 of file CarlaRecorder.h.
Referenced by AddCollision(), Clear(), and Write().
DoorVehicles
CarlaRecorderDoorVehicles ACarlaRecorder::DoorVehicles private
Definition at line 218 of file CarlaRecorder.h.
Referenced by AddDoorVehicle(), Clear(), and Write().
Enabled
bool ACarlaRecorder::Enabled private
Definition at line 183 of file CarlaRecorder.h.
Referenced by AddAnimBiker(), AddAnimVehicle(), AddAnimVehicleWheels(), AddAnimWalker(), AddBoundingBox(), AddCollision(), AddDoorVehicle(), AddEvent(), AddEvent(), AddEvent(), AddEventLightSceneChanged(), AddKinematics(), AddLightVehicle(), AddPosition(), AddState(), Disable(), Enable(), and Ticking().
Episode
UCarlaEpisode* ACarlaRecorder::Episode = nullptr private
Definition at line 193 of file CarlaRecorder.h.
Referenced by AddCollision(), AddExistingActors(), AddPhysicsControl(), AddTrafficLightTime(), AddTriggerVolume(), AddVehicleDoor(), CreateRecorderEventAdd(), and Ticking().
EventsAdd
CarlaRecorderEventsAdd ACarlaRecorder::EventsAdd private
Definition at line 198 of file CarlaRecorder.h.
Referenced by AddEvent(), Clear(), and Write().
EventsDel
CarlaRecorderEventsDel ACarlaRecorder::EventsDel private
Definition at line 199 of file CarlaRecorder.h.
Referenced by AddEvent(), Clear(), and Write().
EventsParent
CarlaRecorderEventsParent ACarlaRecorder::EventsParent private
Definition at line 200 of file CarlaRecorder.h.
Referenced by AddEvent(), Clear(), and Write().
File
std::ofstream ACarlaRecorder::File private
Definition at line 191 of file CarlaRecorder.h.
Referenced by Start(), Stop(), and Write().
Frames
CarlaRecorderFrames ACarlaRecorder::Frames private
Definition at line 197 of file CarlaRecorder.h.
Referenced by Start(), and Write().
Info
CarlaRecorderInfo ACarlaRecorder::Info private
Definition at line 196 of file CarlaRecorder.h.
Referenced by AddVehicleWheelsAnimation(), and Start().
Kinematics
CarlaRecorderActorsKinematics ACarlaRecorder::Kinematics private
Definition at line 210 of file CarlaRecorder.h.
Referenced by AddKinematics(), Clear(), and Write().
LightScenes
CarlaRecorderLightScenes ACarlaRecorder::LightScenes private
Definition at line 209 of file CarlaRecorder.h.
Referenced by AddEventLightSceneChanged(), Clear(), and Write().
LightVehicles
CarlaRecorderLightVehicles ACarlaRecorder::LightVehicles private
Definition at line 208 of file CarlaRecorder.h.
Referenced by AddLightVehicle(), Clear(), and Write().
NextCollisionId
uint32_t ACarlaRecorder::NextCollisionId = 0 private
Definition at line 188 of file CarlaRecorder.h.
Referenced by AddCollision(), and Start().
PhysicsControls
CarlaRecorderPhysicsControls ACarlaRecorder::PhysicsControls private
Definition at line 214 of file CarlaRecorder.h.
Referenced by AddPhysicsControl(), Clear(), and Write().
PlatformTime
CarlaRecorderPlatformTime ACarlaRecorder::PlatformTime private
Definition at line 213 of file CarlaRecorder.h.
Referenced by Start(), Ticking(), and Write().
Positions
CarlaRecorderPositions ACarlaRecorder::Positions private
Definition at line 202 of file CarlaRecorder.h.
Referenced by AddPosition(), Clear(), and Write().
Query
CarlaRecorderQuery ACarlaRecorder::Query private
Definition at line 224 of file CarlaRecorder.h.
Referenced by ShowFileActorsBlocked(), ShowFileCollisions(), and ShowFileInfo().
Replayer
CarlaReplayer ACarlaRecorder::Replayer private
Definition at line 221 of file CarlaRecorder.h.
Referenced by ReplayFile(), SetReplayerIgnoreHero(), SetReplayerIgnoreSpectator(), SetReplayerTimeFactor(), Start(), and StopReplayer().
States
CarlaRecorderStates ACarlaRecorder::States private
Definition at line 203 of file CarlaRecorder.h.
Referenced by AddState(), Clear(), and Write().
TrafficLightTimes
CarlaRecorderTrafficLightTimes ACarlaRecorder::TrafficLightTimes private
Definition at line 215 of file CarlaRecorder.h.
Referenced by AddTrafficLightTime(), Clear(), and Write().
TriggerVolumes
CarlaRecorderActorTriggerVolumes ACarlaRecorder::TriggerVolumes private
Definition at line 212 of file CarlaRecorder.h.
Referenced by AddTriggerVolume(), Clear(), and Write().
Vehicles
CarlaRecorderAnimVehicles ACarlaRecorder::Vehicles private
Definition at line 204 of file CarlaRecorder.h.
Referenced by AddAnimVehicle(), Clear(), and Write().
VisualTime
CarlaRecorderVisualTime ACarlaRecorder::VisualTime private
Definition at line 217 of file CarlaRecorder.h.
Referenced by Ticking(), and Write().
Walkers
CarlaRecorderAnimWalkers ACarlaRecorder::Walkers private
Definition at line 206 of file CarlaRecorder.h.
Referenced by AddAnimWalker(), Clear(), and Write().
WalkersBones
CarlaRecorderWalkersBones ACarlaRecorder::WalkersBones private
Definition at line 216 of file CarlaRecorder.h.
Referenced by AddActorBones(), Clear(), and Write().
Wheels
CarlaRecorderAnimVehicleWheels ACarlaRecorder::Wheels private
Definition at line 205 of file CarlaRecorder.h.
Referenced by AddAnimVehicleWheels(), Clear(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorder.h
CarlaRecorder.cpp