CARLA: carla::rpc::Response< T > Class Template Reference
carla::rpc::Response< T > Class Template Reference
#include <Response.h>
Public Types
using error_type = ResponseError
using value_type = T
Public Member Functions
value_type & Get ()
const value_type & Get () const
const error_type & GetError () const
bool HasError () const
operator bool () const
template<typename TValue >
void Reset (TValue &&value)
Response ()=default
template<typename TValue >
Response (TValue &&value)
template<typename... Ts>
void SetError (Ts &&... args)
Private Attributes
boost::variant2::variant< error_type, value_type > _data
Detailed Description
template<typename T>
class carla::rpc::Response< T >
Definition at line 52 of file Response.h.
Member Typedef Documentation
error_type
template<typename T > using carla::rpc::Response< T >::error_type = ResponseError
Definition at line 57 of file Response.h.
value_type
template<typename T > using carla::rpc::Response< T >::value_type = T
Definition at line 55 of file Response.h.
Constructor & Destructor Documentation
Response() [1/2]
template<typename T > carla::rpc::Response< T >::Response () default
Response() [2/2]
template<typename T > template<typename TValue > carla::rpc::Response< T >::Response (TValue && value) inline
Definition at line 62 of file Response.h.
Member Function Documentation
Get() [1/2]
template<typename T > value_type & carla::rpc::Response< T >::Get () inline
Definition at line 83 of file Response.h.
References carla::rpc::Response< T >::_data, DEBUG_ASSERT, and carla::rpc::Response< T >::HasError().
Referenced by carla::client::detail::Get(), and TEST().
Get() [2/2]
template<typename T > const value_type & carla::rpc::Response< T >::Get () const inline
Definition at line 88 of file Response.h.
References carla::rpc::Response< T >::_data, DEBUG_ASSERT, and carla::rpc::Response< T >::HasError().
GetError()
template<typename T > const error_type & carla::rpc::Response< T >::GetError () const inline
Definition at line 78 of file Response.h.
References carla::rpc::Response< T >::_data, DEBUG_ASSERT, and carla::rpc::Response< T >::HasError().
Referenced by TEST().
HasError()
template<typename T > bool carla::rpc::Response< T >::HasError () const inline
Definition at line 69 of file Response.h.
References carla::rpc::Response< T >::_data.
Referenced by carla::rpc::Response< T >::Get(), carla::rpc::Response< T >::Get(), carla::rpc::Response< T >::GetError(), carla::rpc::Response< void >::GetError(), carla::rpc::Response< T >::operator bool(), carla::rpc::Response< void >::operator bool(), and TEST().
operator bool()
template<typename T > carla::rpc::Response< T >::operator bool () const inline
Definition at line 93 of file Response.h.
References carla::rpc::Response< T >::HasError().
Reset()
template<typename T > template<typename TValue > void carla::rpc::Response< T >::Reset (TValue && value) inline
Definition at line 65 of file Response.h.
References carla::rpc::Response< T >::_data.
Referenced by TEST().
SetError()
template<typename T > template<typename... Ts> void carla::rpc::Response< T >::SetError (Ts &&... args) inline
Definition at line 74 of file Response.h.
References carla::rpc::Response< T >::_data.
Referenced by TEST().
Member Data Documentation
_data
template<typename T > boost::variant2::variant<error_type, value_type> carla::rpc::Response< T >::_data private
Definition at line 101 of file Response.h.
Referenced by carla::rpc::Response< T >::Get(), carla::rpc::Response< T >::Get(), carla::rpc::Response< T >::GetError(), carla::rpc::Response< void >::GetError(), carla::rpc::Response< T >::HasError(), carla::rpc::Response< void >::HasError(), carla::rpc::Response< T >::Reset(), carla::rpc::Response< T >::SetError(), and carla::rpc::Response< void >::SetError().
The documentation for this class was generated from the following file:
Response.h