CARLA: carla::traffic_manager::AtomicMap< Key, Value > Class Template Reference
carla::traffic_manager::AtomicMap< Key, Value > Class Template Reference
#include <AtomicMap.h>
Public Member Functions
void AddEntry (const std::pair< Key, Value > &entry)
AtomicMap ()
bool Contains (const Key &key) const
const Value & GetValue (const Key &key) const
void RemoveEntry (const Key &key)
Private Attributes
std::unordered_map< Key, Value > map
std::mutex map_mutex
Detailed Description
template<typename Key, typename Value>
class carla::traffic_manager::AtomicMap< Key, Value >
Definition at line 16 of file AtomicMap.h.
Constructor & Destructor Documentation
AtomicMap()
template<typename Key , typename Value > carla::traffic_manager::AtomicMap< Key, Value >::AtomicMap () inline
Definition at line 25 of file AtomicMap.h.
Member Function Documentation
AddEntry()
template<typename Key , typename Value > void carla::traffic_manager::AtomicMap< Key, Value >::AddEntry (const std::pair< Key, Value > & entry) inline
Definition at line 27 of file AtomicMap.h.
References carla::traffic_manager::AtomicMap< Key, Value >::map, and carla::traffic_manager::AtomicMap< Key, Value >::map_mutex.
Referenced by carla::traffic_manager::Parameters::SetAutoLaneChange(), carla::traffic_manager::Parameters::SetCustomPath(), carla::traffic_manager::Parameters::SetDesiredSpeed(), carla::traffic_manager::Parameters::SetDistanceToLeadingVehicle(), carla::traffic_manager::Parameters::SetImportedRoute(), carla::traffic_manager::Parameters::SetKeepRightPercentage(), carla::traffic_manager::Parameters::SetLaneOffset(), carla::traffic_manager::Parameters::SetPercentageIgnoreVehicles(), carla::traffic_manager::Parameters::SetPercentageIgnoreWalkers(), carla::traffic_manager::Parameters::SetPercentageRunningLight(), carla::traffic_manager::Parameters::SetPercentageRunningSign(), carla::traffic_manager::Parameters::SetPercentageSpeedDifference(), carla::traffic_manager::Parameters::SetRandomLeftLaneChangePercentage(), carla::traffic_manager::Parameters::SetRandomRightLaneChangePercentage(), carla::traffic_manager::Parameters::SetUpdateVehicleLights(), carla::traffic_manager::Parameters::UpdateImportedRoute(), and carla::traffic_manager::Parameters::UpdateUploadPath().
Contains()
template<typename Key , typename Value > bool carla::traffic_manager::AtomicMap< Key, Value >::Contains (const Key & key) const inline
Definition at line 38 of file AtomicMap.h.
References carla::traffic_manager::AtomicMap< Key, Value >::map, and carla::traffic_manager::AtomicMap< Key, Value >::map_mutex.
Referenced by carla::traffic_manager::Parameters::GetAutoLaneChange(), carla::traffic_manager::Parameters::GetCustomPath(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), carla::traffic_manager::Parameters::GetImportedRoute(), carla::traffic_manager::Parameters::GetKeepRightPercentage(), carla::traffic_manager::Parameters::GetLaneOffset(), carla::traffic_manager::Parameters::GetPercentageIgnoreVehicles(), carla::traffic_manager::Parameters::GetPercentageIgnoreWalkers(), carla::traffic_manager::Parameters::GetPercentageRunningLight(), carla::traffic_manager::Parameters::GetPercentageRunningSign(), carla::traffic_manager::Parameters::GetRandomLeftLaneChangePercentage(), carla::traffic_manager::Parameters::GetRandomRightLaneChangePercentage(), carla::traffic_manager::Parameters::GetUpdateVehicleLights(), carla::traffic_manager::Parameters::GetUploadPath(), carla::traffic_manager::Parameters::GetUploadRoute(), carla::traffic_manager::Parameters::GetVehicleTargetVelocity(), carla::traffic_manager::Parameters::SetDesiredSpeed(), and carla::traffic_manager::Parameters::SetPercentageSpeedDifference().
GetValue()
template<typename Key , typename Value > const Value & carla::traffic_manager::AtomicMap< Key, Value >::GetValue (const Key & key) const inline
Definition at line 44 of file AtomicMap.h.
References carla::traffic_manager::AtomicMap< Key, Value >::map, and carla::traffic_manager::AtomicMap< Key, Value >::map_mutex.
Referenced by carla::traffic_manager::Parameters::GetAutoLaneChange(), carla::traffic_manager::Parameters::GetCustomPath(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), carla::traffic_manager::Parameters::GetImportedRoute(), carla::traffic_manager::Parameters::GetKeepRightPercentage(), carla::traffic_manager::Parameters::GetLaneOffset(), carla::traffic_manager::Parameters::GetPercentageIgnoreVehicles(), carla::traffic_manager::Parameters::GetPercentageIgnoreWalkers(), carla::traffic_manager::Parameters::GetPercentageRunningLight(), carla::traffic_manager::Parameters::GetPercentageRunningSign(), carla::traffic_manager::Parameters::GetRandomLeftLaneChangePercentage(), carla::traffic_manager::Parameters::GetRandomRightLaneChangePercentage(), carla::traffic_manager::Parameters::GetUpdateVehicleLights(), carla::traffic_manager::Parameters::GetUploadPath(), carla::traffic_manager::Parameters::GetUploadRoute(), and carla::traffic_manager::Parameters::GetVehicleTargetVelocity().
RemoveEntry()
template<typename Key , typename Value > void carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry (const Key & key) inline
Definition at line 50 of file AtomicMap.h.
References carla::traffic_manager::AtomicMap< Key, Value >::map, and carla::traffic_manager::AtomicMap< Key, Value >::map_mutex.
Referenced by carla::traffic_manager::Parameters::RemoveImportedRoute(), carla::traffic_manager::Parameters::RemoveUploadPath(), carla::traffic_manager::Parameters::SetDesiredSpeed(), carla::traffic_manager::Parameters::SetPercentageSpeedDifference(), carla::traffic_manager::Parameters::UpdateImportedRoute(), and carla::traffic_manager::Parameters::UpdateUploadPath().
Member Data Documentation
map
template<typename Key , typename Value > std::unordered_map<Key, Value> carla::traffic_manager::AtomicMap< Key, Value >::map private
Definition at line 21 of file AtomicMap.h.
Referenced by carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry().
map_mutex
template<typename Key , typename Value > std::mutex carla::traffic_manager::AtomicMap< Key, Value >::map_mutex mutable private
Definition at line 20 of file AtomicMap.h.
Referenced by carla::traffic_manager::AtomicMap< Key, Value >::AddEntry(), carla::traffic_manager::AtomicMap< Key, Value >::Contains(), carla::traffic_manager::AtomicMap< Key, Value >::GetValue(), and carla::traffic_manager::AtomicMap< Key, Value >::RemoveEntry().
The documentation for this class was generated from the following file:
AtomicMap.h