CARLA: geometry_msgs::msg::Transform Class Reference
geometry_msgs::msg::Transform Class Reference
This class represents the structure Transform defined by the user in the IDL file.
#include <Transform.h>
Public Member Functions
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const Transform &x) const
Comparison operator.
eProsima_user_DllExport Transform & operator= (const Transform &x)
Copy assignment.
eProsima_user_DllExport Transform & operator= (Transform &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Transform &x) const
Comparison operator.
eProsima_user_DllExport geometry_msgs::msg::Quaternion & rotation ()
This function returns a reference to member rotation.
eProsima_user_DllExport const geometry_msgs::msg::Quaternion & rotation () const
This function returns a constant reference to member rotation.
eProsima_user_DllExport void rotation (const geometry_msgs::msg::Quaternion &_rotation)
This function copies the value in member rotation.
eProsima_user_DllExport void rotation (geometry_msgs::msg::Quaternion &&_rotation)
This function moves the value in member rotation.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport Transform ()
Default constructor.
eProsima_user_DllExport Transform (const Transform &x)
Copy constructor.
eProsima_user_DllExport Transform (Transform &&x) noexcept
Move constructor.
eProsima_user_DllExport geometry_msgs::msg::Vector3 & translation ()
This function returns a reference to member translation.
eProsima_user_DllExport const geometry_msgs::msg::Vector3 & translation () const
This function returns a constant reference to member translation.
eProsima_user_DllExport void translation (const geometry_msgs::msg::Vector3 &_translation)
This function copies the value in member translation.
eProsima_user_DllExport void translation (geometry_msgs::msg::Vector3 &&_translation)
This function moves the value in member translation.
eProsima_user_DllExport ~Transform ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::Transform &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
geometry_msgs::msg::Quaternion m_rotation
geometry_msgs::msg::Vector3 m_translation
Detailed Description
This class represents the structure Transform defined by the user in the IDL file.
Definition at line 73 of file ros2/types/Transform.h.
Constructor & Destructor Documentation
Transform() [1/3]
geometry_msgs::msg::Transform::Transform ()
Default constructor.
Definition at line 44 of file Transform.cpp.
~Transform()
geometry_msgs::msg::Transform::~Transform ()
Default destructor.
Definition at line 48 of file Transform.cpp.
Transform() [2/3]
geometry_msgs::msg::Transform::Transform (const Transform & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::Transform that will be copied.
Definition at line 52 of file Transform.cpp.
References m_rotation, and m_translation.
Transform() [3/3]
geometry_msgs::msg::Transform::Transform (Transform && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::Transform that will be copied.
Definition at line 59 of file Transform.cpp.
Member Function Documentation
deserialize()
void geometry_msgs::msg::Transform::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 121 of file Transform.cpp.
Referenced by geometry_msgs::msg::TransformPubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::Transform::getCdrSerializedSize (const geometry_msgs::msg::Transform & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 103 of file Transform.cpp.
References geometry_msgs::msg::Quaternion::getCdrSerializedSize(), geometry_msgs::msg::Vector3::getCdrSerializedSize(), rotation(), and translation().
Referenced by geometry_msgs::msg::TransformStamped::getCdrSerializedSize(), and geometry_msgs::msg::TransformPubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::Transform::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 203 of file Transform.cpp.
References geometry_msgs_msg_Transform_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::TransformPubSubType::getKey(), and geometry_msgs::msg::TransformPubSubType::TransformPubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::Transform::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 96 of file Transform.cpp.
References geometry_msgs_msg_Transform_max_cdr_typesize.
Referenced by geometry_msgs::msg::TransformPubSubType::TransformPubSubType().
isKeyDefined()
bool geometry_msgs::msg::Transform::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 210 of file Transform.cpp.
Referenced by geometry_msgs::msg::TransformPubSubType::TransformPubSubType().
operator!=()
bool geometry_msgs::msg::Transform::operator!= (const Transform & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Transform object to compare.
Definition at line 90 of file Transform.cpp.
operator=() [1/2]
geometry_msgs::msg::Transform & geometry_msgs::msg::Transform::operator= (const Transform & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::Transform that will be copied.
Definition at line 66 of file Transform.cpp.
References m_rotation, and m_translation.
operator=() [2/2]
geometry_msgs::msg::Transform & geometry_msgs::msg::Transform::operator= (Transform && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::Transform that will be copied.
Definition at line 75 of file Transform.cpp.
operator==()
bool geometry_msgs::msg::Transform::operator== (const Transform & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Transform object to compare.
Definition at line 84 of file Transform.cpp.
References m_rotation, and m_translation.
rotation() [1/4]
geometry_msgs::msg::Quaternion & geometry_msgs::msg::Transform::rotation ()
This function returns a reference to member rotation.
Returns
Reference to member rotation
Definition at line 198 of file Transform.cpp.
rotation() [2/4]
const geometry_msgs::msg::Quaternion & geometry_msgs::msg::Transform::rotation () const
This function returns a constant reference to member rotation.
Returns
Constant reference to member rotation
Definition at line 189 of file Transform.cpp.
rotation() [3/4]
void geometry_msgs::msg::Transform::rotation (const geometry_msgs::msg::Quaternion & _rotation)
This function copies the value in member rotation.
Parameters
_rotation New value to be copied in member rotation
Definition at line 169 of file Transform.cpp.
Referenced by getCdrSerializedSize(), and carla::ros2::CarlaTransformPublisher::SetData().
rotation() [4/4]
void geometry_msgs::msg::Transform::rotation (geometry_msgs::msg::Quaternion && _rotation)
This function moves the value in member rotation.
Parameters
_rotation New value to be moved in member rotation
Definition at line 179 of file Transform.cpp.
serialize()
void geometry_msgs::msg::Transform::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 114 of file Transform.cpp.
Referenced by geometry_msgs::msg::TransformPubSubType::serialize().
serializeKey()
void geometry_msgs::msg::Transform::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 215 of file Transform.cpp.
Referenced by geometry_msgs::msg::TransformPubSubType::getKey().
translation() [1/4]
geometry_msgs::msg::Vector3 & geometry_msgs::msg::Transform::translation ()
This function returns a reference to member translation.
Returns
Reference to member translation
Definition at line 161 of file Transform.cpp.
translation() [2/4]
const geometry_msgs::msg::Vector3 & geometry_msgs::msg::Transform::translation () const
This function returns a constant reference to member translation.
Returns
Constant reference to member translation
Definition at line 152 of file Transform.cpp.
translation() [3/4]
void geometry_msgs::msg::Transform::translation (const geometry_msgs::msg::Vector3 & _translation)
This function copies the value in member translation.
Parameters
_translation New value to be copied in member translation
Definition at line 132 of file Transform.cpp.
Referenced by getCdrSerializedSize(), and carla::ros2::CarlaTransformPublisher::SetData().
translation() [4/4]
void geometry_msgs::msg::Transform::translation (geometry_msgs::msg::Vector3 && _translation)
This function moves the value in member translation.
Parameters
_translation New value to be moved in member translation
Definition at line 142 of file Transform.cpp.
Member Data Documentation
m_rotation
geometry_msgs::msg::Quaternion geometry_msgs::msg::Transform::m_rotation private
Definition at line 236 of file ros2/types/Transform.h.
Referenced by operator=(), operator==(), and Transform().
m_translation
geometry_msgs::msg::Vector3 geometry_msgs::msg::Transform::m_translation private
Definition at line 235 of file ros2/types/Transform.h.
Referenced by operator=(), operator==(), and Transform().
The documentation for this class was generated from the following files:
ros2/types/Transform.h
Transform.cpp