CARLA: carla::nav::WalkerEventVisitor Class Reference
carla::nav::WalkerEventVisitor Class Reference
visitor class
#include <WalkerEvent.h>
Public Member Functions
EventResult operator() (WalkerEventIgnore &event)
EventResult operator() (WalkerEventStopAndCheck &event)
EventResult operator() (WalkerEventWait &event)
WalkerEventVisitor (WalkerManager *manager, ActorId id, double delta)
Private Attributes
double _delta { 0 }
ActorId _id { 0 }
WalkerManager * _manager { nullptr }
Detailed Description
visitor class
Definition at line 58 of file WalkerEvent.h.
Constructor & Destructor Documentation
WalkerEventVisitor()
carla::nav::WalkerEventVisitor::WalkerEventVisitor (WalkerManager * manager, ActorId id, double delta) inline
Definition at line 60 of file WalkerEvent.h.
Member Function Documentation
operator()() [1/3]
EventResult carla::nav::WalkerEventVisitor::operator() (WalkerEventIgnore & event)
Definition at line 15 of file WalkerEvent.cpp.
References carla::nav::End.
operator()() [2/3]
EventResult carla::nav::WalkerEventVisitor::operator() (WalkerEventStopAndCheck & event)
Definition at line 28 of file WalkerEvent.cpp.
References _delta, _id, _manager, carla::nav::WalkerEventStopAndCheck::actor, carla::nav::WalkerEventStopAndCheck::check_for_trafficlight, carla::nav::Continue, carla::nav::End, carla::nav::WalkerManager::GetNavigation(), carla::nav::WalkerManager::GetTrafficLightAffecting(), carla::nav::WalkerManager::GetWalkerCrosswalkEnd(), carla::nav::Navigation::GetWalkerPosition(), carla::rpc::Green, carla::nav::Navigation::HasVehicleNear(), carla::nav::Navigation::PauseAgent(), carla::nav::WalkerEventStopAndCheck::time, carla::nav::TimeOut, carla::geom::Vector3D::x, carla::geom::Vector3D::y, carla::rpc::Yellow, and carla::geom::Vector3D::z.
operator()() [3/3]
EventResult carla::nav::WalkerEventVisitor::operator() (WalkerEventWait & event)
Definition at line 19 of file WalkerEvent.cpp.
References _delta, carla::nav::Continue, carla::nav::End, and carla::nav::WalkerEventWait::time.
Member Data Documentation
_delta
double carla::nav::WalkerEventVisitor::_delta { 0 } private
Definition at line 67 of file WalkerEvent.h.
Referenced by operator()(), and operator()().
_id
ActorId carla::nav::WalkerEventVisitor::_id { 0 } private
Definition at line 66 of file WalkerEvent.h.
Referenced by operator()().
_manager
WalkerManager* carla::nav::WalkerEventVisitor::_manager { nullptr } private
Definition at line 65 of file WalkerEvent.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
WalkerEvent.h
WalkerEvent.cpp