CARLA: CarlaRecorderAnimVehicleWheels Class Reference
CarlaRecorderAnimVehicleWheels Class Reference
#include <CarlaRecorderAnimVehicleWheels.h>
Public Member Functions
void Add (const CarlaRecorderAnimWheels &InObj)
void Clear (void)
const std::vector< CarlaRecorderAnimWheels > & GetVehicleWheels ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderAnimWheels > VehicleWheels
Detailed Description
Definition at line 36 of file CarlaRecorderAnimVehicleWheels.h.
Member Function Documentation
Add()
void CarlaRecorderAnimVehicleWheels::Add (const CarlaRecorderAnimWheels & InObj)
Definition at line 56 of file CarlaRecorderAnimVehicleWheels.cpp.
References Vehicle, and VehicleWheels.
Referenced by FFrameData::AddAnimVehicleWheels(), ACarlaRecorder::AddAnimVehicleWheels(), and Read().
Clear()
void CarlaRecorderAnimVehicleWheels::Clear (void)
Definition at line 51 of file CarlaRecorderAnimVehicleWheels.cpp.
References VehicleWheels.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetVehicleWheels()
const std::vector< CarlaRecorderAnimWheels > & CarlaRecorderAnimVehicleWheels::GetVehicleWheels ()
Definition at line 101 of file CarlaRecorderAnimVehicleWheels.cpp.
References VehicleWheels.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderAnimVehicleWheels::Read (std::istream & InFile)
Definition at line 87 of file CarlaRecorderAnimVehicleWheels.cpp.
References Add(), and CarlaRecorderAnimWheels::Read().
Referenced by FFrameData::Read().
Write()
void CarlaRecorderAnimVehicleWheels::Write (std::ostream & OutFile)
Definition at line 61 of file CarlaRecorderAnimVehicleWheels.cpp.
References AnimVehicleWheels, VehicleWheels, and Write().
Referenced by ACarlaRecorder::Write(), Write(), and FFrameData::Write().
Member Data Documentation
VehicleWheels
std::vector<CarlaRecorderAnimWheels> CarlaRecorderAnimVehicleWheels::VehicleWheels private
Definition at line 51 of file CarlaRecorderAnimVehicleWheels.h.
Referenced by Add(), Clear(), GetVehicleWheels(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderAnimVehicleWheels.h
CarlaRecorderAnimVehicleWheels.cpp