CARLA: FActorDefinitionValidator Class Reference
FActorDefinitionValidator Class Reference
Checks validity of FActorDefinition.
Public Member Functions
bool AreValid (const TArray< FActorDefinition > &ActorDefinitions)
Iterate all actor definitions and their properties and display messages on error.
bool SingleIsValid (const FActorDefinition &Definition)
Validate ActorDefinition and display messages on error.
Private Member Functions
bool AreTagsValid (const FString &Tags)
template<typename T >
bool AreValid (const FString &Type, const TArray< T > &Array)
Applies IsValid to each item in Array.
template<typename T , typename F >
bool ForEach (const FString &Type, const TArray< T > &Array, F Validator)
Applies Validator to each item in Array.
FString GetDisplayId (const FString &Type, size_t Index, const FString &Item)
template<typename T >
FString GetDisplayId (const FString &Type, size_t Index, const T &Item)
bool IsIdValid (const FString &Id)
bool IsValid (const EActorAttributeType Type)
bool IsValid (const FActorAttribute &Attribute)
bool IsValid (const FActorDefinition &ActorDefinition)
bool IsValid (const FActorVariation &Variation)
template<typename T , typename ... ARGS>
bool OnScreenAssert (bool Predicate, const T &Format, ARGS &&... Args) const
If Predicate is false, print an error message.
bool ValueIsValid (const EActorAttributeType Type, const FString &Value)
Private Attributes
FScopedStack< FString > Stack
Detailed Description
Checks validity of FActorDefinition.
Definition at line 21 of file ActorBlueprintFunctionLibrary.cpp.
Member Function Documentation
AreTagsValid()
bool FActorDefinitionValidator::AreTagsValid (const FString & Tags) inline private
Todo
Do more checks.
Definition at line 109 of file ActorBlueprintFunctionLibrary.cpp.
References OnScreenAssert().
Referenced by IsValid().
AreValid() [1/2]
template<typename T > bool FActorDefinitionValidator::AreValid (const FString & Type, const TArray< T > & Array) inline private
Applies IsValid to each item in Array.
Pushes a new context to the stack for each item.
Definition at line 98 of file ActorBlueprintFunctionLibrary.cpp.
References ForEach(), and IsValid().
AreValid() [2/2]
bool FActorDefinitionValidator::AreValid (const TArray< FActorDefinition > & ActorDefinitions) inline
Iterate all actor definitions and their properties and display messages on error.
Definition at line 27 of file ActorBlueprintFunctionLibrary.cpp.
References AreValid().
Referenced by AreValid(), UActorBlueprintFunctionLibrary::CheckActorDefinitions(), and IsValid().
ForEach()
template<typename T , typename F > bool FActorDefinitionValidator::ForEach (const FString & Type, const TArray< T > & Array, F Validator) inline private
Applies Validator to each item in Array.
Pushes a new context to the stack for each item.
Definition at line 82 of file ActorBlueprintFunctionLibrary.cpp.
References GetDisplayId(), FScopedStack< T >::PushScope(), and Stack.
Referenced by AreValid(), and IsValid().
GetDisplayId() [1/2]
FString FActorDefinitionValidator::GetDisplayId (const FString & Type, size_t Index, const FString & Item) inline private
Definition at line 74 of file ActorBlueprintFunctionLibrary.cpp.
GetDisplayId() [2/2]
template<typename T > FString FActorDefinitionValidator::GetDisplayId (const FString & Type, size_t Index, const T & Item) inline private
Definition at line 69 of file ActorBlueprintFunctionLibrary.cpp.
Referenced by ForEach().
IsIdValid()
bool FActorDefinitionValidator::IsIdValid (const FString & Id) inline private
Todo
Do more checks.
Definition at line 103 of file ActorBlueprintFunctionLibrary.cpp.
References OnScreenAssert().
Referenced by IsValid(), IsValid(), and IsValid().
IsValid() [1/4]
bool FActorDefinitionValidator::IsValid (const EActorAttributeType Type) inline private
Todo
Do more checks.
Definition at line 115 of file ActorBlueprintFunctionLibrary.cpp.
References OnScreenAssert().
Referenced by AreValid(), IsValid(), IsValid(), and SingleIsValid().
IsValid() [2/4]
bool FActorDefinitionValidator::IsValid (const FActorAttribute & Attribute) inline private
Definition at line 138 of file ActorBlueprintFunctionLibrary.cpp.
References FActorAttribute::Id, IsIdValid(), IsValid(), FActorAttribute::Type, FActorAttribute::Value, and ValueIsValid().
IsValid() [3/4]
bool FActorDefinitionValidator::IsValid (const FActorDefinition & ActorDefinition) inline private
Todo
Validate Class and make sure IDs are not repeated.
Definition at line 146 of file ActorBlueprintFunctionLibrary.cpp.
References AreTagsValid(), AreValid(), FActorDefinition::Attributes, FActorDefinition::Id, IsIdValid(), FActorDefinition::Tags, and FActorDefinition::Variations.
IsValid() [4/4]
bool FActorDefinitionValidator::IsValid (const FActorVariation & Variation) inline private
Definition at line 127 of file ActorBlueprintFunctionLibrary.cpp.
References ForEach(), FActorVariation::Id, IsIdValid(), IsValid(), OnScreenAssert(), FActorVariation::RecommendedValues, and FActorVariation::Type.
OnScreenAssert()
template<typename T , typename ... ARGS> bool FActorDefinitionValidator::OnScreenAssert (bool Predicate, const T & Format, ARGS &&... Args) const inline private
If Predicate is false, print an error message.
If possible the message is printed to the editor window.
Definition at line 45 of file ActorBlueprintFunctionLibrary.cpp.
References Stack, and String.
Referenced by AreTagsValid(), IsIdValid(), IsValid(), and IsValid().
SingleIsValid()
bool FActorDefinitionValidator::SingleIsValid (const FActorDefinition & Definition) inline
Validate ActorDefinition and display messages on error.
Definition at line 33 of file ActorBlueprintFunctionLibrary.cpp.
References FActorDefinition::Id, IsValid(), FScopedStack< T >::PushScope(), and Stack.
Referenced by UActorBlueprintFunctionLibrary::CheckActorDefinition().
ValueIsValid()
bool FActorDefinitionValidator::ValueIsValid (const EActorAttributeType Type, const FString & Value) inline private
Todo
Do more checks.
Definition at line 121 of file ActorBlueprintFunctionLibrary.cpp.
Referenced by IsValid().
Member Data Documentation
Stack
FScopedStack<FString> FActorDefinitionValidator::Stack private
Definition at line 156 of file ActorBlueprintFunctionLibrary.cpp.
Referenced by ForEach(), OnScreenAssert(), and SingleIsValid().
The documentation for this class was generated from the following file:
ActorBlueprintFunctionLibrary.cpp