CARLA: CarlaRecorderHelpers.h File Reference
CarlaRecorderHelpers.h File Reference
#include <sstream>
#include <vector>
Functions
std::string GetRecorderFilename (std::string Filename)
void ReadFString (std::istream &InFile, FString &OutObj)
void ReadFVector (std::istream &InFile, FVector &OutObj)
template<typename T >
void ReadStdVector (std::istream &InFile, std::vector< T > &OutVec)
template<typename T >
void ReadTArray (std::istream &InFile, TArray< T > &OutVec)
void ReadTransform (std::ifstream &InFile, FTransform &OutObj)
template<typename T >
void ReadValue (std::istream &InFile, T &OutObj)
void WriteFString (std::ostream &OutFile, const FString &InObj)
void WriteFTransform (std::ofstream &OutFile, const FTransform &InObj)
void WriteFVector (std::ostream &OutFile, const FVector &InObj)
template<typename T >
void WriteStdVector (std::ostream &OutFile, const std::vector< T > &InVec)
template<typename T >
void WriteTArray (std::ostream &OutFile, const TArray< T > &InVec)
template<typename T >
void WriteValue (std::ostream &OutFile, const T &InObj)
Function Documentation
GetRecorderFilename()
std::string GetRecorderFilename (std::string Filename)
Definition at line 17 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderQuery::QueryBlocked(), CarlaRecorderQuery::QueryCollisions(), CarlaRecorderQuery::QueryInfo(), CarlaReplayer::ReplayFile(), and ACarlaRecorder::Start().
ReadFString()
void ReadFString (std::istream & InFile, FString & OutObj)
Definition at line 86 of file CarlaRecorderHelpers.cpp.
References CarlaRecorderHelperBuffer.
Referenced by CarlaRecorderWalkerBones::Read(), CarlaRecorderInfo::Read(), and CarlaRecorderEventAdd::Read().
ReadFVector()
void ReadFVector (std::istream & InFile, FVector & OutObj)
Definition at line 68 of file CarlaRecorderHelpers.cpp.
Referenced by FDenseTile::InitializeTile(), CarlaRecorderWalkerBones::Read(), CarlaRecorderBoundingBox::Read(), CarlaRecorderEventAdd::Read(), CarlaRecorderKinematics::Read(), CarlaRecorderPosition::Read(), and ReadFTransform().
ReadStdVector()
template<typename T > void ReadStdVector (std::istream & InFile, std::vector< T > & OutVec)
Definition at line 66 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Read().
ReadTArray()
template<typename T > void ReadTArray (std::istream & InFile, TArray< T > & OutVec)
Definition at line 80 of file CarlaRecorderHelpers.h.
ReadTransform()
void ReadTransform (std::ifstream & InFile, FTransform & OutObj)
ReadValue()
template<typename T > void ReadValue (std::istream & InFile, T & OutObj)
Definition at line 60 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Read(), and CarlaRecorderTrafficLightTime::Read().
WriteFString()
void WriteFString (std::ostream & OutFile, const FString & InObj)
Definition at line 53 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderWalkerBones::Write(), CarlaRecorderInfo::Write(), and CarlaRecorderEventAdd::Write().
WriteFTransform()
void WriteFTransform (std::ofstream & OutFile, const FTransform & InObj)
Definition at line 46 of file CarlaRecorderHelpers.cpp.
References WriteFVector().
WriteFVector()
void WriteFVector (std::ostream & OutFile, const FVector & InObj)
Definition at line 38 of file CarlaRecorderHelpers.cpp.
Referenced by CarlaRecorderWalkerBones::Write(), CarlaRecorderBoundingBox::Write(), CarlaRecorderKinematics::Write(), CarlaRecorderPosition::Write(), CarlaRecorderEventAdd::Write(), and WriteFTransform().
WriteStdVector()
template<typename T > void WriteStdVector (std::ostream & OutFile, const std::vector< T > & InVec)
Definition at line 27 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Write().
WriteTArray()
template<typename T > void WriteTArray (std::ostream & OutFile, const TArray< T > & InVec)
Definition at line 37 of file CarlaRecorderHelpers.h.
WriteValue()
template<typename T > void WriteValue (std::ostream & OutFile, const T & InObj)
Definition at line 21 of file CarlaRecorderHelpers.h.
Referenced by CarlaRecorderPhysicsControl::Write(), and CarlaRecorderTrafficLightTime::Write().