CARLA: strconv_attribute_impl< opt_escape > Struct Template Reference
strconv_attribute_impl< opt_escape > Struct Template Reference
Static Public Member Functions
static char_t * parse_eol (char_t *s, char_t end_quote)
static char_t * parse_simple (char_t *s, char_t end_quote)
static char_t * parse_wconv (char_t *s, char_t end_quote)
static char_t * parse_wnorm (char_t *s, char_t end_quote)
Detailed Description
template<typename opt_escape>
struct strconv_attribute_impl< opt_escape >
Definition at line 2734 of file pugixml.cpp.
Member Function Documentation
parse_eol()
template<typename opt_escape > static char_t * strconv_attribute_impl< opt_escape >::parse_eol (char_t * s, char_t end_quote) inline static
Definition at line 2824 of file pugixml.cpp.
References ct_parse_attr, gap::flush(), PUGI__IS_CHARTYPE, PUGI__SCANWHILE_UNROLL, gap::push(), and strconv_escape().
parse_simple()
template<typename opt_escape > static char_t * strconv_attribute_impl< opt_escape >::parse_simple (char_t * s, char_t end_quote) inline static
Definition at line 2856 of file pugixml.cpp.
References ct_parse_attr, gap::flush(), PUGI__IS_CHARTYPE, PUGI__SCANWHILE_UNROLL, and strconv_escape().
parse_wconv()
template<typename opt_escape > static char_t * strconv_attribute_impl< opt_escape >::parse_wconv (char_t * s, char_t end_quote) inline static
Definition at line 2788 of file pugixml.cpp.
References ct_parse_attr_ws, ct_space, gap::flush(), PUGI__IS_CHARTYPE, PUGI__SCANWHILE_UNROLL, gap::push(), and strconv_escape().
parse_wnorm()
template<typename opt_escape > static char_t * strconv_attribute_impl< opt_escape >::parse_wnorm (char_t * s, char_t end_quote) inline static
Definition at line 2736 of file pugixml.cpp.
References ct_parse_attr_ws, ct_space, gap::flush(), PUGI__IS_CHARTYPE, PUGI__SCANWHILE_UNROLL, gap::push(), and strconv_escape().
The documentation for this struct was generated from the following file:
pugixml.cpp