CARLA: FCameraGBufferUint8 Struct Reference
FCameraGBufferUint8 Struct Reference
#include <SceneCaptureSensor.h>
Public Types
using not_spawnable = void
Prevent this sensor to be spawned by users.
Public Member Functions
FTransform GetActorTransform () const
Dummy. Required for compatibility with other sensors only.
template<typename SensorT >
FAsyncDataStream GetDataStream (const SensorT &Self)
Return the FDataStream associated with this sensor.
auto GetToken () const
Return the token that allows subscribing to this sensor's stream.
void SetDataStream (FDataStream InStream)
void SetStream (FDataMultiStream InStream)
Replace the Stream associated with this sensor.
Public Attributes
bool bIsUsed = false
FDataStream Stream
Detailed Description
Definition at line 29 of file SceneCaptureSensor.h.
Member Typedef Documentation
not_spawnable
using FCameraGBufferUint8::not_spawnable = void
Prevent this sensor to be spawned by users.
Definition at line 32 of file SceneCaptureSensor.h.
Member Function Documentation
GetActorTransform()
FTransform FCameraGBufferUint8::GetActorTransform () const inline
Dummy. Required for compatibility with other sensors only.
Definition at line 52 of file SceneCaptureSensor.h.
GetDataStream()
template<typename SensorT > FAsyncDataStream FCameraGBufferUint8::GetDataStream (const SensorT & Self) inline
Return the FDataStream associated with this sensor.
You need to provide a reference to self, this is necessary for template deduction.
Definition at line 61 of file SceneCaptureSensor.h.
References FDataStreamTmpl< T >::MakeAsyncDataStream(), and Stream.
GetToken()
auto FCameraGBufferUint8::GetToken () const inline
Return the token that allows subscribing to this sensor's stream.
Definition at line 45 of file SceneCaptureSensor.h.
References bIsUsed, FDataStreamTmpl< T >::GetToken(), and Stream.
Referenced by FCarlaServer::FPimpl::BindActions().
SetDataStream()
void FCameraGBufferUint8::SetDataStream (FDataStream InStream) inline
Definition at line 34 of file SceneCaptureSensor.h.
References Stream.
SetStream()
void FCameraGBufferUint8::SetStream (FDataMultiStream InStream) inline
Replace the Stream associated with this sensor.
Definition at line 40 of file SceneCaptureSensor.h.
References Stream.
Member Data Documentation
bIsUsed
bool FCameraGBufferUint8::bIsUsed = false mutable
Definition at line 66 of file SceneCaptureSensor.h.
Referenced by GetToken().
Stream
FDataStream FCameraGBufferUint8::Stream
Definition at line 67 of file SceneCaptureSensor.h.
Referenced by GetDataStream(), GetToken(), SetDataStream(), and SetStream().
The documentation for this struct was generated from the following file:
SceneCaptureSensor.h