CARLA: carla::road::SignalType Class Reference
carla::road::SignalType Class Reference
Using OpenDRIVE 1.5M (6.10 Country Codes)
#include <SignalType.h>
Static Public Member Functions
static const std::string AbsoluteNoStop ()
static const std::string AccessForbidden ()
static const std::string AccessForbiddenBicycle ()
static const std::string AccessForbiddenHeight ()
static const std::string AccessForbiddenMotorvehicles ()
static const std::string AccessForbiddenTrucks ()
static const std::string AccessForbiddenWeight ()
static const std::string AccessForbiddenWidth ()
static const std::string AccessForbiddenWrongDirection ()
static const std::string CautionBicycle ()
static const std::string CautionPedestrian ()
static const std::string CityBegin ()
static const std::string CityEnd ()
static const std::string Danger ()
static const std::string DeadEnd ()
static const std::string ForbiddenOvertakingMotorvehicles ()
static const std::string ForbiddenOvertakingTrucks ()
static const std::string ForbiddenUTurn ()
static const std::string HasWayNextIntersection ()
static const std::string Highway ()
static bool IsTrafficLight (const std::string &type)
static const std::string LanesMerging ()
static const std::string LevelCrossing ()
static const std::string MandatoryLeftRightDirection ()
static const std::string MandatoryTurnDirection ()
static const std::string MaximumSpeed ()
static const std::string PassRightLeft ()
static const std::string PriorityWay ()
static const std::string PriorityWayEnd ()
static const std::string RecomendedSpeed ()
static const std::string RecomendedSpeedEnd ()
static const std::string RestrictedStop ()
static const std::string Roundabout ()
static const std::string StopSign ()
static const std::string TwoChoiceTurnDirection ()
static const std::string YieldSign ()
Detailed Description
Using OpenDRIVE 1.5M (6.10 Country Codes)
Definition at line 16 of file SignalType.h.
Member Function Documentation
AbsoluteNoStop()
const std::string carla::road::SignalType::AbsoluteNoStop () static
Definition at line 87 of file SignalType.cpp.
AccessForbidden()
const std::string carla::road::SignalType::AccessForbidden () static
Definition at line 51 of file SignalType.cpp.
AccessForbiddenBicycle()
const std::string carla::road::SignalType::AccessForbiddenBicycle () static
Definition at line 60 of file SignalType.cpp.
AccessForbiddenHeight()
const std::string carla::road::SignalType::AccessForbiddenHeight () static
Definition at line 69 of file SignalType.cpp.
AccessForbiddenMotorvehicles()
const std::string carla::road::SignalType::AccessForbiddenMotorvehicles () static
Definition at line 54 of file SignalType.cpp.
AccessForbiddenTrucks()
const std::string carla::road::SignalType::AccessForbiddenTrucks () static
Definition at line 57 of file SignalType.cpp.
AccessForbiddenWeight()
const std::string carla::road::SignalType::AccessForbiddenWeight () static
Definition at line 63 of file SignalType.cpp.
AccessForbiddenWidth()
const std::string carla::road::SignalType::AccessForbiddenWidth () static
Definition at line 66 of file SignalType.cpp.
AccessForbiddenWrongDirection()
const std::string carla::road::SignalType::AccessForbiddenWrongDirection () static
Definition at line 72 of file SignalType.cpp.
CautionBicycle()
const std::string carla::road::SignalType::CautionBicycle () static
Definition at line 24 of file SignalType.cpp.
CautionPedestrian()
const std::string carla::road::SignalType::CautionPedestrian () static
Definition at line 21 of file SignalType.cpp.
CityBegin()
const std::string carla::road::SignalType::CityBegin () static
Definition at line 102 of file SignalType.cpp.
CityEnd()
const std::string carla::road::SignalType::CityEnd () static
Definition at line 105 of file SignalType.cpp.
Danger()
const std::string carla::road::SignalType::Danger () static
Definition at line 15 of file SignalType.cpp.
DeadEnd()
const std::string carla::road::SignalType::DeadEnd () static
Definition at line 111 of file SignalType.cpp.
ForbiddenOvertakingMotorvehicles()
const std::string carla::road::SignalType::ForbiddenOvertakingMotorvehicles () static
Definition at line 81 of file SignalType.cpp.
ForbiddenOvertakingTrucks()
const std::string carla::road::SignalType::ForbiddenOvertakingTrucks () static
Definition at line 84 of file SignalType.cpp.
ForbiddenUTurn()
const std::string carla::road::SignalType::ForbiddenUTurn () static
Definition at line 75 of file SignalType.cpp.
HasWayNextIntersection()
const std::string carla::road::SignalType::HasWayNextIntersection () static
Definition at line 93 of file SignalType.cpp.
Highway()
const std::string carla::road::SignalType::Highway () static
Definition at line 108 of file SignalType.cpp.
IsTrafficLight()
bool carla::road::SignalType::IsTrafficLight (const std::string & type) static
Definition at line 121 of file SignalType.cpp.
Referenced by carla::client::World::GetTrafficLightsFromWaypoint(), carla::road::MapBuilder::SolveSignalReferencesAndTransforms(), and ATrafficLightManager::SpawnTrafficLights().
LanesMerging()
const std::string carla::road::SignalType::LanesMerging () static
Definition at line 18 of file SignalType.cpp.
LevelCrossing()
const std::string carla::road::SignalType::LevelCrossing () static
Definition at line 27 of file SignalType.cpp.
MandatoryLeftRightDirection()
const std::string carla::road::SignalType::MandatoryLeftRightDirection () static
Definition at line 39 of file SignalType.cpp.
MandatoryTurnDirection()
const std::string carla::road::SignalType::MandatoryTurnDirection () static
Definition at line 36 of file SignalType.cpp.
MaximumSpeed()
const std::string carla::road::SignalType::MaximumSpeed () static
Definition at line 78 of file SignalType.cpp.
Referenced by ATrafficLightManager::SpawnSignals().
PassRightLeft()
const std::string carla::road::SignalType::PassRightLeft () static
Definition at line 48 of file SignalType.cpp.
PriorityWay()
const std::string carla::road::SignalType::PriorityWay () static
Definition at line 96 of file SignalType.cpp.
PriorityWayEnd()
const std::string carla::road::SignalType::PriorityWayEnd () static
Definition at line 99 of file SignalType.cpp.
RecomendedSpeed()
const std::string carla::road::SignalType::RecomendedSpeed () static
Definition at line 114 of file SignalType.cpp.
RecomendedSpeedEnd()
const std::string carla::road::SignalType::RecomendedSpeedEnd () static
Definition at line 117 of file SignalType.cpp.
RestrictedStop()
const std::string carla::road::SignalType::RestrictedStop () static
Definition at line 90 of file SignalType.cpp.
Roundabout()
const std::string carla::road::SignalType::Roundabout () static
Definition at line 45 of file SignalType.cpp.
StopSign()
const std::string carla::road::SignalType::StopSign () static
Definition at line 33 of file SignalType.cpp.
Referenced by ATrafficLightManager::ATrafficLightManager().
TwoChoiceTurnDirection()
const std::string carla::road::SignalType::TwoChoiceTurnDirection () static
Definition at line 42 of file SignalType.cpp.
YieldSign()
const std::string carla::road::SignalType::YieldSign () static
Definition at line 30 of file SignalType.cpp.
Referenced by ATrafficLightManager::ATrafficLightManager().
The documentation for this class was generated from the following files:
SignalType.h
SignalType.cpp