CARLA: geometry_msgs::msg::Vector3PubSubType Class Reference
geometry_msgs::msg::Vector3PubSubType Class Reference
This class represents the TopicDataType of the type Vector3 defined by the user in the IDL file.
#include <Vector3PubSubTypes.h>
Public Types
typedef Vector3 type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport Vector3PubSubType ()
virtual eProsima_user_DllExport ~Vector3PubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type Vector3 defined by the user in the IDL file.
Definition at line 73 of file Vector3PubSubTypes.h.
Member Typedef Documentation
type
typedef Vector3 geometry_msgs::msg::Vector3PubSubType::type
Definition at line 77 of file Vector3PubSubTypes.h.
Constructor & Destructor Documentation
Vector3PubSubType()
geometry_msgs::msg::Vector3PubSubType::Vector3PubSubType ()
Definition at line 32 of file Vector3PubSubTypes.cpp.
References geometry_msgs::msg::Vector3::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::Vector3::getMaxCdrSerializedSize(), geometry_msgs::msg::Vector3::isKeyDefined(), and m_keyBuffer.
~Vector3PubSubType()
geometry_msgs::msg::Vector3PubSubType::~Vector3PubSubType () override virtual
Definition at line 45 of file Vector3PubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::Vector3PubSubType::createData () override virtual
Definition at line 122 of file Vector3PubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::Vector3PubSubType::deleteData (void * data) override virtual
Definition at line 127 of file Vector3PubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::Vector3PubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file Vector3PubSubTypes.cpp.
References geometry_msgs::msg::Vector3::deserialize().
getKey()
bool geometry_msgs::msg::Vector3PubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file Vector3PubSubTypes.cpp.
References geometry_msgs::msg::Vector3::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::Vector3::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::Vector3PubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file Vector3PubSubTypes.cpp.
References geometry_msgs::msg::Vector3::getCdrSerializedSize().
is_plain_impl()
static constexpr bool geometry_msgs::msg::Vector3PubSubType::is_plain_impl () inline static constexpr private
Definition at line 132 of file Vector3PubSubTypes.h.
serialize()
bool geometry_msgs::msg::Vector3PubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file Vector3PubSubTypes.cpp.
References geometry_msgs::msg::Vector3::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::Vector3PubSubType::m_keyBuffer
Definition at line 130 of file Vector3PubSubTypes.h.
Referenced by getKey(), Vector3PubSubType(), and ~Vector3PubSubType().
m_md5
MD5 geometry_msgs::msg::Vector3PubSubType::m_md5
Definition at line 129 of file Vector3PubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
Vector3PubSubTypes.h
Vector3PubSubTypes.cpp