CARLA: CustomTerrainPhysicsComponent.cpp File Reference
CustomTerrainPhysicsComponent.cpp File Reference
#include "CustomTerrainPhysicsComponent.h"
#include "Runtime/Core/Public/Async/ParallelFor.h"
#include "Engine/CollisionProfile.h"
#include "Engine/StaticMeshActor.h"
#include "StaticMeshResources.h"
#include "CollisionQueryParams.h"
#include "Carla/MapGen/LargeMapManager.h"
#include "Carla/Game/CarlaStatics.h"
#include "Carla/MapGen/SoilTypeManager.h"
#include "Carla/Actor/ActorBlueprintFunctionLibrary.h"
#include "HAL/PlatformFilemanager.h"
#include "HAL/RunnableThread.h"
#include "Misc/Paths.h"
#include "Engine/World.h"
#include "Math/UnrealMathUtility.h"
#include "Landscape.h"
#include "LandscapeHeightfieldCollisionComponent.h"
#include "LandscapeComponent.h"
#include "RHICommandList.h"
#include "TextureResource.h"
#include "Rendering/Texture2DResource.h"
#include "GenericPlatform/GenericPlatformProcess.h"
#include "Materials/MaterialParameterCollection.h"
#include "Materials/MaterialParameterCollectionInstance.h"
#include "Materials/MaterialInterface.h"
#include "Materials/MaterialInstance.h"
#include "Components/SkinnedMeshComponent.h"
#include "GenericPlatform/GenericPlatformFile.h"
#include "Async/Async.h"
#include "Async/Future.h"
#include "LandscapeProxy.h"
#include "Engine/Texture2D.h"
#include "Engine/Texture.h"
#include "Engine/TextureRenderTarget2D.h"
#include "Components/PrimitiveComponent.h"
#include "DrawDebugHelpers.h"
#include "Kismet/KismetSystemLibrary.h"
#include "CommandLine.h"
#include "Components/LineBatchComponent.h"
#include "Math/OrientedBox.h"
#include "Misc/DateTime.h"
#include "EngineUtils.h"
#include <algorithm>
#include <fstream>
#include <thread>
#include <chrono>
#include <compiler/disable-ue4-macros.h>
#include "carla/rpc/String.h"
#include <compiler/enable-ue4-macros.h>
Functions
float SIToUEFrame (const float &In)
FVector SIToUEFrame (const FVector &In)
FVector SIToUEFrameDirection (const FVector &In)
float UEFrameToSI (const float &In)
FVector UEFrameToSI (const FVector &In)
FVector UEFrameToSIDirection (const FVector &In)
Variables
std::string _filesBaseFolder = std::string(getenv("HOME")) + "/carlaCache/"
const int CacheExtraRadius = 10
constexpr float CMToM = 0.01f
constexpr float MToCM = 100.f
Function Documentation
SIToUEFrame() [1/2]
float SIToUEFrame (const float & In)
Definition at line 92 of file CustomTerrainPhysicsComponent.cpp.
References MToCM.
SIToUEFrame() [2/2]
FVector SIToUEFrame (const FVector & In)
Definition at line 88 of file CustomTerrainPhysicsComponent.cpp.
References MToCM.
Referenced by FDenseTile::GetParticlesInBox().
SIToUEFrameDirection()
FVector SIToUEFrameDirection (const FVector & In)
Definition at line 93 of file CustomTerrainPhysicsComponent.cpp.
UEFrameToSI() [1/2]
float UEFrameToSI (const float & In)
Definition at line 102 of file CustomTerrainPhysicsComponent.cpp.
References CMToM.
UEFrameToSI() [2/2]
FVector UEFrameToSI (const FVector & In)
Definition at line 98 of file CustomTerrainPhysicsComponent.cpp.
References CMToM.
Referenced by FSparseHighDetailMap::GetIntersectingTiles(), and FHeightMapData::InitializeHeightmap().
UEFrameToSIDirection()
FVector UEFrameToSIDirection (const FVector & In)
Definition at line 103 of file CustomTerrainPhysicsComponent.cpp.
Referenced by FSparseHighDetailMap::GetIntersectingTiles().
Variable Documentation
_filesBaseFolder
std::string _filesBaseFolder = std::string(getenv("HOME")) + "/carlaCache/"
Definition at line 85 of file CustomTerrainPhysicsComponent.cpp.
CacheExtraRadius
const int CacheExtraRadius = 10
Definition at line 80 of file CustomTerrainPhysicsComponent.cpp.
CMToM
constexpr float CMToM = 0.01f constexpr
Definition at line 78 of file CustomTerrainPhysicsComponent.cpp.
Referenced by UEFrameToSI(), and UEFrameToSI().
MToCM
constexpr float MToCM = 100.f constexpr
Definition at line 77 of file CustomTerrainPhysicsComponent.cpp.
Referenced by SIToUEFrame(), and SIToUEFrame().