// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Point32PubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

#include "Point32PubSubTypes.h"

using SerializedPayload_t = eprosima::fastrtps::rtps::SerializedPayload_t;
using InstanceHandle_t = eprosima::fastrtps::rtps::InstanceHandle_t;

namespace geometry_msgs {
    namespace msg {
        Point32PubSubType::Point32PubSubType()
        {
            // 设置消息类型的名称为 "geometry_msgs::msg::dds_::Point32_"。
            // 该名称在 DDS 系统中唯一标识 Point32 消息类型。
            setName("geometry_msgs::msg::dds_::Point32_");

            // 获取 Point32 类型的最大 CDR 序列化大小。
            // CDR（Common Data Representation）是数据交换格式，用于序列化和反序列化消息数据。
            auto type_size = Point32::getMaxCdrSerializedSize();

            // 计算并调整序列化数据的对齐方式，将序列化大小对齐到 4 字节边界。
            type_size += eprosima::fastcdr::Cdr::alignment(type_size, 4);  // 可能的子消息对齐

            // 设置消息类型的总大小（包括封装头部）。封装是指在消息的实际数据前后添加的头部信息。
            m_typeSize = static_cast<uint32_t>(type_size) + 4;  // 封装（包括数据和头部）

            // 设置是否定义了该消息的键（Key）。在一些情况下，消息会定义一个唯一标识符（键），用于识别该消息。
            m_isGetKeyDefined = Point32::isKeyDefined();

            // 获取 Point32 消息类型的最大键 CDR 序列化大小。
            // 如果键的序列化大小大于 16 字节，则使用实际的键大小；否则，使用 16 字节。
            size_t keyLength = Point32::getKeyMaxCdrSerializedSize() > 16 ?
                    Point32::getKeyMaxCdrSerializedSize() : 16;

            // 为消息键分配内存，存储在 m_keyBuffer 中。
            // 键通常用于唯一标识某个消息实例。
            m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));

            // 将分配的内存初始化为零，确保 m_keyBuffer 在使用时不会包含任何未初始化的数据。
            memset(m_keyBuffer, 0, keyLength);
        }


        Point32PubSubType::~Point32PubSubType()
        {
            if (m_keyBuffer != nullptr)
            {
                free(m_keyBuffer);
            }
        }

        bool Point32PubSubType::serialize(
                void* data,
                SerializedPayload_t* payload)
        {
            Point32* p_type = static_cast<Point32*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->max_size);
            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN, eprosima::fastcdr::Cdr::DDS_CDR);
            payload->encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;
            // Serialize encapsulation
            ser.serialize_encapsulation();

            try
            {
                // Serialize the object.
                p_type->serialize(ser);
            }
            catch (eprosima::fastcdr::exception::NotEnoughMemoryException& /*exception*/)
            {
                return false;
            }

            // Get the serialized length
            payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());
            return true;
        }

        bool Point32PubSubType::deserialize(
                SerializedPayload_t* payload,
                void* data)
        {
            try
            {
                //Convert DATA to pointer of your type
                Point32* p_type = static_cast<Point32*>(data);

                // Object that manages the raw buffer.
                eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(payload->data), payload->length);

                // Object that deserializes the data.
                eprosima::fastcdr::Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN, eprosima::fastcdr::Cdr::DDS_CDR);

                // Deserialize encapsulation.
                deser.read_encapsulation();
                payload->encapsulation = deser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

                // Deserialize the object.
                p_type->deserialize(deser);
            }
            catch (eprosima::fastcdr::exception::NotEnoughMemoryException& /*exception*/)
            {
                return false;
            }

            return true;
        }

        std::function<uint32_t()> Point32PubSubType::getSerializedSizeProvider(
                void* data)
        {
            return [data]() -> uint32_t
                   {
                       return static_cast<uint32_t>(type::getCdrSerializedSize(*static_cast<Point32*>(data))) +
                              4u /*encapsulation*/;
                   };
        }

        void* Point32PubSubType::createData()
        {
            return reinterpret_cast<void*>(new Point32());
        }

        void Point32PubSubType::deleteData(
                void* data)
        {
            delete(reinterpret_cast<Point32*>(data));
        }

        bool Point32PubSubType::getKey(
                void* data,
                InstanceHandle_t* handle,
                bool force_md5)
        {
            if (!m_isGetKeyDefined)
            {
                return false;
            }

            Point32* p_type = static_cast<Point32*>(data);

            // Object that manages the raw buffer.
            eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
                    Point32::getKeyMaxCdrSerializedSize());

            // Object that serializes the data.
            eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS);
            p_type->serializeKey(ser);
            if (force_md5 || Point32::getKeyMaxCdrSerializedSize() > 16)
            {
                m_md5.init();
                m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
                m_md5.finalize();
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle->value[i] = m_md5.digest[i];
                }
            }
            else
            {
                for (uint8_t i = 0; i < 16; ++i)
                {
                    handle->value[i] = m_keyBuffer[i];
                }
            }
            return true;
        }
    } //End of namespace msg
} //End of namespace geometry_msgs
