CARLA: AVegetationManager Class Reference
AVegetationManager Class Reference
#include <VegetationManager.h>
Public Member Functions
void AddVehicle (ACarlaWheeledVehicle *Vehicle)
void RemoveVehicle (ACarlaWheeledVehicle *Vehicle)
void UpdatePoolBasePosition ()
Public Attributes
float ActiveActorDistance {500.0f}
bool DebugMaterials {false}
float HideMaterialDistance {500.0f}
int32 InitialPoolSize {10}
bool SpawnBushes {true}
bool SpawnPlants {true}
bool SpawnRocks {true}
float SpawnScale {1.0f}
bool SpawnTrees {true}
Overriden from AActor
float PoolTranslationTimer {30.0f}
FTransform InactivePoolTransform { FQuat(1.0f, 1.0f, 1.0f, 1.0f), FVector(1.0f, 1.0f, 1.0f), FVector(1.0f, 1.0f, 1.0f)}
ALargeMapManager * LargeMap {nullptr}
ACarlaWheeledVehicle * HeroVehicle {nullptr}
TMap< FString, FFoliageBlueprint > FoliageBlueprintCache {}
TMap< FString, FTileData > TileCache {}
TMap< FString, TArray< FPooledActor > > ActorPool {}
FTimerHandle UpdatePoolInactiveTransformTimer
virtual void BeginPlay () override
virtual void Tick (float DeltaTime) override
bool IsFoliageTypeEnabled (const FString &Path) const
bool CheckForNewTiles () const
TArray< FString > GetTilesInUse ()
void UpdateMaterials (FTileData *Tile)
TArray< FElementsToSpawn > GetElementsToSpawn (FTileData *Tile)
void SpawnSkeletalFoliages (TArray< FElementsToSpawn > &ElementsToSpawn)
void DestroySkeletalFoliages ()
void ActivePooledActors ()
bool EnableActorFromPool (const FTransform &Transform, int32 Index, std::shared_ptr< FTileMeshComponent > &TileMeshComponent, TArray< FPooledActor > &Pool)
void CreateOrUpdateTileCache (ULevel *InLevel)
void UpdateFoliageBlueprintCache (ULevel *InLevel)
void SetTileDataInternals (FTileData &TileData)
void SetInstancedStaticMeshComponentCache (FTileData &TileData)
void SetMaterialCache (FTileData &TileData)
void FreeTileCache (ULevel *InLevel)
void OnLevelAddedToWorld (ULevel *InLevel, UWorld *InWorld)
void OnLevelRemovedFromWorld (ULevel *InLevel, UWorld *InWorld)
void PostWorldOriginOffset (UWorld *, FIntVector, FIntVector InDstOrigin)
void CreatePoolForBPClass (const FFoliageBlueprint &BP)
AActor * CreateFoliage (const FFoliageBlueprint &BP, const FTransform &Transform) const
void GetSketalTemplates ()
Detailed Description
Definition at line 89 of file VegetationManager.h.
Member Function Documentation
ActivePooledActors()
void AVegetationManager::ActivePooledActors () private
Definition at line 591 of file VegetationManager.cpp.
References ActiveActorDistance, ActivePooledActors(), ActorPool, and HeroVehicle.
Referenced by ActivePooledActors(), and Tick().
AddVehicle()
void AVegetationManager::AddVehicle (ACarlaWheeledVehicle * Vehicle)
Definition at line 279 of file VegetationManager.cpp.
References AddVehicle(), HeroVehicle, IsValid(), and Vehicle.
Referenced by ACarlaWheeledVehicle::AddReferenceToManager(), and AddVehicle().
BeginPlay()
void AVegetationManager::BeginPlay () override protected virtual
Definition at line 231 of file VegetationManager.cpp.
References BeginPlay(), UCarlaStatics::GetLargeMapManager(), LargeMap, OnLevelAddedToWorld(), OnLevelRemovedFromWorld(), and PostWorldOriginOffset().
Referenced by BeginPlay().
CheckForNewTiles()
bool AVegetationManager::CheckForNewTiles () const private
Definition at line 771 of file VegetationManager.cpp.
References CheckForNewTiles(), IsValid(), and TileCache.
Referenced by CheckForNewTiles().
CreateFoliage()
AActor * AVegetationManager::CreateFoliage (const FFoliageBlueprint & BP, const FTransform & Transform) const private
Definition at line 691 of file VegetationManager.cpp.
References CreateFoliage(), FFoliageBlueprint::SpawnedClass, and SpawnScale.
Referenced by CreateFoliage(), CreatePoolForBPClass(), and SpawnSkeletalFoliages().
CreateOrUpdateTileCache()
void AVegetationManager::CreateOrUpdateTileCache (ULevel * InLevel) private
Definition at line 300 of file VegetationManager.cpp.
References CreateOrUpdateTileCache(), FTileData::InstancedFoliageActor, IsValid(), FTileData::MaterialInstanceDynamicCache, FTileData::ProceduralFoliageVolume, SetTileDataInternals(), TileCache, and FTileData::TileMeshesCache.
Referenced by CreateOrUpdateTileCache(), and OnLevelAddedToWorld().
CreatePoolForBPClass()
void AVegetationManager::CreatePoolForBPClass (const FFoliageBlueprint & BP) private
Definition at line 666 of file VegetationManager.cpp.
References FPooledActor::Actor, ActorPool, FFoliageBlueprint::BPFullClassName, CreateFoliage(), CreatePoolForBPClass(), FPooledActor::DisableActor(), InitialPoolSize, and IsValid().
Referenced by CreatePoolForBPClass(), and UpdateFoliageBlueprintCache().
DestroySkeletalFoliages()
void AVegetationManager::DestroySkeletalFoliages () private
Definition at line 617 of file VegetationManager.cpp.
References ActorPool, DestroySkeletalFoliages(), ACarlaWheeledVehicle::GetDetectionSize(), and HeroVehicle.
Referenced by DestroySkeletalFoliages(), and Tick().
EnableActorFromPool()
bool AVegetationManager::EnableActorFromPool (const FTransform & Transform, int32 Index, std::shared_ptr< FTileMeshComponent > & TileMeshComponent, TArray< FPooledActor > & Pool) private
Definition at line 641 of file VegetationManager.cpp.
References EnableActorFromPool(), and SpawnScale.
Referenced by EnableActorFromPool(), and SpawnSkeletalFoliages().
FreeTileCache()
void AVegetationManager::FreeTileCache (ULevel * InLevel) private
Definition at line 450 of file VegetationManager.cpp.
References FTileData::InstancedFoliageActor, IsValid(), FTileData::MaterialInstanceDynamicCache, FTileData::ProceduralFoliageVolume, TileCache, and FTileData::TileMeshesCache.
Referenced by OnLevelRemovedFromWorld().
GetElementsToSpawn()
TArray< FElementsToSpawn > AVegetationManager::GetElementsToSpawn (FTileData * Tile) private
Definition at line 498 of file VegetationManager.cpp.
References FoliageBlueprintCache, GetElementsToSpawn(), ACarlaWheeledVehicle::GetFoliageInstancesCloseToVehicle(), HeroVehicle, FTileMeshComponent::IndicesInUse, FTileMeshComponent::InstancedStaticMeshComponent, FElementsToSpawn::TileMeshComponent, and FTileData::TileMeshesCache.
Referenced by GetElementsToSpawn(), and Tick().
GetSketalTemplates()
void AVegetationManager::GetSketalTemplates () private
GetTilesInUse()
TArray< FString > AVegetationManager::GetTilesInUse () private
Definition at line 789 of file VegetationManager.cpp.
References GetTilesInUse(), HeroVehicle, FTileData::InstancedFoliageActor, IsValid(), FTileData::ProceduralFoliageVolume, and TileCache.
Referenced by GetTilesInUse(), and Tick().
IsFoliageTypeEnabled()
bool AVegetationManager::IsFoliageTypeEnabled (const FString & Path) const private
Definition at line 753 of file VegetationManager.cpp.
References IsFoliageTypeEnabled(), SpawnBushes, SpawnPlants, SpawnRocks, and SpawnTrees.
Referenced by IsFoliageTypeEnabled(), and UpdateFoliageBlueprintCache().
OnLevelAddedToWorld()
void AVegetationManager::OnLevelAddedToWorld (ULevel * InLevel, UWorld * InWorld) private
Definition at line 730 of file VegetationManager.cpp.
References CreateOrUpdateTileCache(), OnLevelAddedToWorld(), and UpdateFoliageBlueprintCache().
Referenced by BeginPlay(), and OnLevelAddedToWorld().
OnLevelRemovedFromWorld()
void AVegetationManager::OnLevelRemovedFromWorld (ULevel * InLevel, UWorld * InWorld) private
Definition at line 737 of file VegetationManager.cpp.
References FreeTileCache(), and OnLevelRemovedFromWorld().
Referenced by BeginPlay(), and OnLevelRemovedFromWorld().
PostWorldOriginOffset()
void AVegetationManager::PostWorldOriginOffset (UWorld * , FIntVector , FIntVector InDstOrigin) private
Definition at line 743 of file VegetationManager.cpp.
References InactivePoolTransform, PostWorldOriginOffset(), and UpdatePoolBasePosition().
Referenced by BeginPlay(), and PostWorldOriginOffset().
RemoveVehicle()
void AVegetationManager::RemoveVehicle (ACarlaWheeledVehicle * Vehicle)
Definition at line 288 of file VegetationManager.cpp.
References HeroVehicle, IsValid(), RemoveVehicle(), and Vehicle.
Referenced by ACarlaWheeledVehicle::RemoveReferenceToManager(), and RemoveVehicle().
SetInstancedStaticMeshComponentCache()
void AVegetationManager::SetInstancedStaticMeshComponentCache (FTileData & TileData) private
Definition at line 350 of file VegetationManager.cpp.
References FTileData::ContainsMesh(), FoliageBlueprintCache, FTileData::InstancedFoliageActor, IsValid(), SetInstancedStaticMeshComponentCache(), FTileData::TileMeshesCache, and FTileData::UpdateTileMeshComponent().
Referenced by SetInstancedStaticMeshComponentCache(), and SetTileDataInternals().
SetMaterialCache()
void AVegetationManager::SetMaterialCache (FTileData & TileData) private
Definition at line 379 of file VegetationManager.cpp.
References HideMaterialDistance, FTileMeshComponent::InstancedStaticMeshComponent, IsValid(), FTileData::MaterialInstanceDynamicCache, SetMaterialCache(), and FTileData::TileMeshesCache.
Referenced by SetMaterialCache(), and SetTileDataInternals().
SetTileDataInternals()
void AVegetationManager::SetTileDataInternals (FTileData & TileData) private
Definition at line 343 of file VegetationManager.cpp.
References SetInstancedStaticMeshComponentCache(), SetMaterialCache(), and SetTileDataInternals().
Referenced by CreateOrUpdateTileCache(), and SetTileDataInternals().
SpawnSkeletalFoliages()
void AVegetationManager::SpawnSkeletalFoliages (TArray< FElementsToSpawn > & ElementsToSpawn) private
Definition at line 543 of file VegetationManager.cpp.
References FPooledActor::Actor, ActorPool, CreateFoliage(), FPooledActor::EnableActor(), EnableActorFromPool(), ACarlaWheeledVehicle::GetDetectionSize(), HeroVehicle, IsValid(), and SpawnSkeletalFoliages().
Referenced by SpawnSkeletalFoliages(), and Tick().
Tick()
void AVegetationManager::Tick (float DeltaTime) override protected virtual
Definition at line 241 of file VegetationManager.cpp.
References ActivePooledActors(), DestroySkeletalFoliages(), GetElementsToSpawn(), ALargeMapManager::GetHeroVehicle(), GetTilesInUse(), HeroVehicle, IsValid(), LargeMap, SpawnSkeletalFoliages(), Tick(), TileCache, ACarlaWheeledVehicle::UpdateDetectionBox(), and UpdateMaterials().
Referenced by Tick().
UpdateFoliageBlueprintCache()
void AVegetationManager::UpdateFoliageBlueprintCache (ULevel * InLevel) private
Definition at line 412 of file VegetationManager.cpp.
References FFoliageBlueprint::BPFullClassName, CreatePoolForBPClass(), FoliageBlueprintCache, IsFoliageTypeEnabled(), FFoliageBlueprint::IsValid(), IsValid(), FFoliageBlueprint::SetBPClassName(), FFoliageBlueprint::SetSpawnedClass(), and UpdateFoliageBlueprintCache().
Referenced by OnLevelAddedToWorld(), and UpdateFoliageBlueprintCache().
UpdateMaterials()
void AVegetationManager::UpdateMaterials (FTileData * Tile) private
Definition at line 490 of file VegetationManager.cpp.
References DebugMaterials, HeroVehicle, Position, FTileData::UpdateMaterialCache(), and UpdateMaterials().
Referenced by Tick(), and UpdateMaterials().
UpdatePoolBasePosition()
void AVegetationManager::UpdatePoolBasePosition ()
Definition at line 712 of file VegetationManager.cpp.
References ActorPool, InactivePoolTransform, and UpdatePoolBasePosition().
Referenced by PostWorldOriginOffset(), and UpdatePoolBasePosition().
Member Data Documentation
ActiveActorDistance
float AVegetationManager::ActiveActorDistance {500.0f}
Definition at line 108 of file VegetationManager.h.
Referenced by ActivePooledActors().
ActorPool
TMap<FString, TArray<FPooledActor> > AVegetationManager::ActorPool {} private
Definition at line 182 of file VegetationManager.h.
Referenced by ActivePooledActors(), CreatePoolForBPClass(), DestroySkeletalFoliages(), SpawnSkeletalFoliages(), and UpdatePoolBasePosition().
DebugMaterials
bool AVegetationManager::DebugMaterials {false}
Definition at line 102 of file VegetationManager.h.
Referenced by UpdateMaterials().
FoliageBlueprintCache
TMap<FString, FFoliageBlueprint> AVegetationManager::FoliageBlueprintCache {} private
Definition at line 179 of file VegetationManager.h.
Referenced by GetElementsToSpawn(), SetInstancedStaticMeshComponentCache(), and UpdateFoliageBlueprintCache().
HeroVehicle
ACarlaWheeledVehicle* AVegetationManager::HeroVehicle {nullptr} private
Definition at line 177 of file VegetationManager.h.
Referenced by ActivePooledActors(), AddVehicle(), DestroySkeletalFoliages(), GetElementsToSpawn(), GetTilesInUse(), RemoveVehicle(), SpawnSkeletalFoliages(), Tick(), and UpdateMaterials().
HideMaterialDistance
float AVegetationManager::HideMaterialDistance {500.0f}
Definition at line 105 of file VegetationManager.h.
Referenced by SetMaterialCache().
InactivePoolTransform
FTransform AVegetationManager::InactivePoolTransform { FQuat(1.0f, 1.0f, 1.0f, 1.0f), FVector(1.0f, 1.0f, 1.0f), FVector(1.0f, 1.0f, 1.0f)} private
Definition at line 174 of file VegetationManager.h.
Referenced by PostWorldOriginOffset(), and UpdatePoolBasePosition().
InitialPoolSize
int32 AVegetationManager::InitialPoolSize {10}
Definition at line 127 of file VegetationManager.h.
Referenced by CreatePoolForBPClass().
LargeMap
ALargeMapManager* AVegetationManager::LargeMap {nullptr} private
Definition at line 176 of file VegetationManager.h.
Referenced by BeginPlay(), and Tick().
PoolTranslationTimer
float AVegetationManager::PoolTranslationTimer {30.0f} private
Definition at line 173 of file VegetationManager.h.
SpawnBushes
bool AVegetationManager::SpawnBushes {true}
Definition at line 112 of file VegetationManager.h.
Referenced by IsFoliageTypeEnabled().
SpawnPlants
bool AVegetationManager::SpawnPlants {true}
Definition at line 121 of file VegetationManager.h.
Referenced by IsFoliageTypeEnabled().
SpawnRocks
bool AVegetationManager::SpawnRocks {true}
Definition at line 118 of file VegetationManager.h.
Referenced by IsFoliageTypeEnabled().
SpawnScale
float AVegetationManager::SpawnScale {1.0f}
Definition at line 124 of file VegetationManager.h.
Referenced by CreateFoliage(), and EnableActorFromPool().
SpawnTrees
bool AVegetationManager::SpawnTrees {true}
Definition at line 115 of file VegetationManager.h.
Referenced by IsFoliageTypeEnabled().
TileCache
TMap<FString, FTileData> AVegetationManager::TileCache {} private
Definition at line 180 of file VegetationManager.h.
Referenced by CheckForNewTiles(), CreateOrUpdateTileCache(), FreeTileCache(), GetTilesInUse(), and Tick().
UpdatePoolInactiveTransformTimer
FTimerHandle AVegetationManager::UpdatePoolInactiveTransformTimer private
Definition at line 184 of file VegetationManager.h.
The documentation for this class was generated from the following files:
VegetationManager.h
VegetationManager.cpp