CARLA: FActorRegistry Class Reference
FActorRegistry Class Reference
A registry of all the Carla actors.
#include <ActorRegistry.h>
Public Types
using IdType = FCarlaActor::IdType
using ValueType = TSharedPtr<FCarlaActor>
Public Member Functions
Actor registry functions
FCarlaActor * Register (AActor &Actor, FActorDescription Description, IdType DesiredId=0)
Register the Actor in the database.
void Deregister (IdType Id)
void Deregister (AActor *Actor)
Look up functions
int32 Num () const
bool IsEmpty () const
bool Contains (uint32 Id) const
FCarlaActor * FindCarlaActor (IdType Id)
const FCarlaActor * FindCarlaActor (IdType Id) const
FCarlaActor * FindCarlaActor (const AActor *Actor)
const FCarlaActor * FindCarlaActor (const AActor *Actor) const
FString GetDescriptionFromStream (carla::streaming::detail::stream_id_type Id)
void PutActorToSleep (IdType Id, UCarlaEpisode *CarlaEpisode)
void WakeActorUp (IdType Id, UCarlaEpisode *CarlaEpisode)
Range iteration support
auto begin () const noexcept
auto end () const noexcept
Private Types
using DatabaseType = TMap<IdType, TSharedPtr<FCarlaActor>>
Private Member Functions
TSharedPtr< FCarlaActor > MakeCarlaActor (IdType Id, AActor &Actor, FActorDescription Description, carla::rpc::ActorState InState) const
FCarlaActor MakeFakeActor (AActor &Actor) const
Private Attributes
DatabaseType ActorDatabase
TMap< IdType, AActor * > Actors
TMap< AActor *, IdType > Ids
Static Private Attributes
static IdType ID_COUNTER = 0u
Detailed Description
A registry of all the Carla actors.
Definition at line 20 of file ActorRegistry.h.
Member Typedef Documentation
DatabaseType
using FActorRegistry::DatabaseType = TMap<IdType, TSharedPtr<FCarlaActor>> private
Definition at line 30 of file ActorRegistry.h.
IdType
using FActorRegistry::IdType = FCarlaActor::IdType
Definition at line 24 of file ActorRegistry.h.
ValueType
using FActorRegistry::ValueType = TSharedPtr<FCarlaActor>
Definition at line 25 of file ActorRegistry.h.
Member Function Documentation
begin()
auto FActorRegistry::begin () const inline noexcept
Definition at line 106 of file ActorRegistry.h.
References ActorDatabase.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::FindTrafficLightAt(), CarlaReplayerHelper::FindTrafficLightAt(), FFrameData::GetFrameData(), and ACarlaRecorder::Ticking().
Contains()
bool FActorRegistry::Contains (uint32 Id) const inline
Definition at line 64 of file ActorRegistry.h.
References ActorDatabase.
Referenced by FFrameData::CreateOrReuseActor(), and CarlaReplayerHelper::TryToCreateReplayerActor().
Deregister() [1/2]
void FActorRegistry::Deregister (AActor * Actor)
Definition at line 135 of file ActorRegistry.cpp.
References Deregister(), FindCarlaActor(), FCarlaActor::GetActor(), and FCarlaActor::GetActorId().
Deregister() [2/2]
void FActorRegistry::Deregister (IdType Id)
Definition at line 118 of file ActorRegistry.cpp.
References ActorDatabase, Actors, FindCarlaActor(), FCarlaActor::GetActor(), Ids, and FCarlaActor::TheActor.
Referenced by Deregister(), UActorDispatcher::DestroyActor(), and UActorDispatcher::OnActorDestroyed().
end()
auto FActorRegistry::end () const inline noexcept
Definition at line 111 of file ActorRegistry.h.
References ActorDatabase.
Referenced by FFrameData::FindTrafficLightAt(), CarlaReplayerHelper::FindTrafficLightAt(), FFrameData::GetFrameData(), and ACarlaRecorder::Ticking().
FindCarlaActor() [1/4]
FCarlaActor * FActorRegistry::FindCarlaActor (const AActor * Actor) inline
Definition at line 81 of file ActorRegistry.h.
References FindCarlaActor(), and Ids.
FindCarlaActor() [2/4]
const FCarlaActor * FActorRegistry::FindCarlaActor (const AActor * Actor) const inline
Definition at line 87 of file ActorRegistry.h.
References FindCarlaActor(), and Ids.
FindCarlaActor() [3/4]
FCarlaActor * FActorRegistry::FindCarlaActor (IdType Id) inline
Definition at line 69 of file ActorRegistry.h.
References ActorDatabase.
Referenced by ACarlaRecorder::AddCollision(), FFrameData::AddPhysicsControl(), ACarlaRecorder::AddPhysicsControl(), FFrameData::AddTrafficLightTime(), ACarlaRecorder::AddTrafficLightTime(), FFrameData::AddTriggerVolume(), ACarlaRecorder::AddTriggerVolume(), ACarlaRecorder::AddVehicleDoor(), ARayCastSemanticLidar::ComputeRawDetection(), Deregister(), Deregister(), UActorDispatcher::DestroyActor(), FindCarlaActor(), FindCarlaActor(), FWorldObserver_GetActorState(), PathLossModel::GetLocationIfVehicle(), PathLossModel::IsVehicle(), UActorDispatcher::OnActorDestroyed(), PutActorToSleep(), Register(), PathLossModel::Simulate(), and WakeActorUp().
FindCarlaActor() [4/4]
const FCarlaActor * FActorRegistry::FindCarlaActor (IdType Id) const inline
Definition at line 75 of file ActorRegistry.h.
References ActorDatabase.
GetDescriptionFromStream()
FString FActorRegistry::GetDescriptionFromStream (carla::streaming::detail::stream_id_type Id)
Definition at line 240 of file ActorRegistry.cpp.
References ActorDatabase, FActorInfo::Description, carla::streaming::detail::token_type::get_stream_id(), ASensor::GetToken(), and FActorDescription::Id.
IsEmpty()
bool FActorRegistry::IsEmpty () const inline
Definition at line 59 of file ActorRegistry.h.
References Num().
MakeCarlaActor()
TSharedPtr< FCarlaActor > FActorRegistry::MakeCarlaActor (IdType Id, AActor & Actor, FActorDescription Description, carla::rpc::ActorState InState) const private
Definition at line 143 of file ActorRegistry.cpp.
References CarlaGetRelevantTagAsString(), FCarlaActor::ConstructCarlaActor(), FActorRegistry_GetActorType(), UBoundingBoxCalculator::GetActorBoundingBox(), and ATagger::GetTagsOfTaggedActor().
Referenced by Register().
MakeFakeActor()
FCarlaActor FActorRegistry::MakeFakeActor (AActor & Actor) const private
Num()
int32 FActorRegistry::Num () const inline
Definition at line 54 of file ActorRegistry.h.
References Actors.
Referenced by FWorldObserver_Serialize(), and IsEmpty().
PutActorToSleep()
void FActorRegistry::PutActorToSleep (FCarlaActor::IdType Id, UCarlaEpisode * CarlaEpisode)
Definition at line 186 of file ActorRegistry.cpp.
References Actors, FindCarlaActor(), FCarlaActor::GetActor(), FCarlaActor::GetChildren(), Ids, PutActorToSleep(), and FCarlaActor::PutActorToSleep().
Referenced by UActorDispatcher::PutActorToSleep(), and PutActorToSleep().
Register()
FCarlaActor * FActorRegistry::Register (AActor & Actor, FActorDescription Description, IdType DesiredId = 0)
Register the Actor in the database.
A new ID will be assign to this actor.
Warning
Undefined if an actor is registered more than once.
Definition at line 72 of file ActorRegistry.cpp.
References ActorDatabase, Actors, FindCarlaActor(), ID_COUNTER, Ids, FCarlaActor::IsDormant(), MakeCarlaActor(), and FCarlaActor::TheActor.
Referenced by UActorDispatcher::RegisterActor().
WakeActorUp()
void FActorRegistry::WakeActorUp (FCarlaActor::IdType Id, UCarlaEpisode * CarlaEpisode)
Definition at line 206 of file ActorRegistry.cpp.
References Actors, UCarlaEpisode::AttachActors(), FindCarlaActor(), FCarlaActor::GetActor(), FCarlaActor::GetAttachmentType(), FCarlaActor::GetChildren(), FCarlaActor::GetParent(), Ids, FCarlaActor::IsDormant(), WakeActorUp(), and FCarlaActor::WakeActorUp().
Referenced by UActorDispatcher::WakeActorUp(), and WakeActorUp().
Member Data Documentation
ActorDatabase
DatabaseType FActorRegistry::ActorDatabase private
Definition at line 132 of file ActorRegistry.h.
Referenced by begin(), Contains(), Deregister(), end(), FindCarlaActor(), FindCarlaActor(), GetDescriptionFromStream(), and Register().
Actors
TMap<IdType, AActor *> FActorRegistry::Actors private
Definition at line 128 of file ActorRegistry.h.
Referenced by Deregister(), Num(), PutActorToSleep(), Register(), and WakeActorUp().
ID_COUNTER
FActorRegistry::IdType FActorRegistry::ID_COUNTER = 0u static private
Definition at line 134 of file ActorRegistry.h.
Referenced by Register().
Ids
TMap<AActor *, IdType> FActorRegistry::Ids private
Definition at line 130 of file ActorRegistry.h.
Referenced by Deregister(), FindCarlaActor(), FindCarlaActor(), PutActorToSleep(), Register(), and WakeActorUp().
The documentation for this class was generated from the following files:
ActorRegistry.h
ActorRegistry.cpp