CARLA: UTaggerDelegate Class Reference
UTaggerDelegate Class Reference
Used to tag every actor that is spawned into the world.
#include <TaggerDelegate.h>
Public Member Functions
void OnActorSpawned (AActor *Actor)
void RegisterSpawnHandler (UWorld *World)
void SetSemanticSegmentationEnabled (bool Enable=true)
UTaggerDelegate ()
Private Attributes
FOnActorSpawned::FDelegate ActorSpawnedDelegate
bool bSemanticSegmentationEnabled = false
Detailed Description
Used to tag every actor that is spawned into the world.
Definition at line 15 of file TaggerDelegate.h.
Constructor & Destructor Documentation
UTaggerDelegate()
UTaggerDelegate::UTaggerDelegate ()
Definition at line 14 of file TaggerDelegate.cpp.
Member Function Documentation
OnActorSpawned()
void UTaggerDelegate::OnActorSpawned (AActor * Actor)
Definition at line 22 of file TaggerDelegate.cpp.
References bSemanticSegmentationEnabled, and ATagger::TagActor().
RegisterSpawnHandler()
void UTaggerDelegate::RegisterSpawnHandler (UWorld * World)
Definition at line 17 of file TaggerDelegate.cpp.
References ActorSpawnedDelegate.
Referenced by ACarlaGameModeBase::InitGame().
SetSemanticSegmentationEnabled()
void UTaggerDelegate::SetSemanticSegmentationEnabled (bool Enable = true) inline
Definition at line 25 of file TaggerDelegate.h.
Referenced by ACarlaGameModeBase::BeginPlay().
Member Data Documentation
ActorSpawnedDelegate
FOnActorSpawned::FDelegate UTaggerDelegate::ActorSpawnedDelegate private
Definition at line 34 of file TaggerDelegate.h.
Referenced by RegisterSpawnHandler().
bSemanticSegmentationEnabled
bool UTaggerDelegate::bSemanticSegmentationEnabled = false private
Definition at line 36 of file TaggerDelegate.h.
Referenced by OnActorSpawned().
The documentation for this class was generated from the following files:
TaggerDelegate.h
TaggerDelegate.cpp