CARLA: CarlaRecorderPositions Class Reference
CarlaRecorderPositions Class Reference
#include <CarlaRecorderPosition.h>
Public Member Functions
void Add (const CarlaRecorderPosition &InObj)
void Clear (void)
const std::vector< CarlaRecorderPosition > & GetPositions ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderPosition > Positions
Detailed Description
Definition at line 26 of file CarlaRecorderPosition.h.
Member Function Documentation
Add()
void CarlaRecorderPositions::Add (const CarlaRecorderPosition & InObj)
Definition at line 35 of file CarlaRecorderPosition.cpp.
References Position, and Positions.
Referenced by FFrameData::AddPosition(), ACarlaRecorder::AddPosition(), and Read().
Clear()
void CarlaRecorderPositions::Clear (void)
Definition at line 30 of file CarlaRecorderPosition.cpp.
References Positions.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetPositions()
const std::vector< CarlaRecorderPosition > & CarlaRecorderPositions::GetPositions ()
Definition at line 75 of file CarlaRecorderPosition.cpp.
References Positions.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderPositions::Read (std::istream & InFile)
Definition at line 61 of file CarlaRecorderPosition.cpp.
References Add(), and CarlaRecorderPosition::Read().
Referenced by FFrameData::Read().
Write()
void CarlaRecorderPositions::Write (std::ostream & OutFile)
Definition at line 40 of file CarlaRecorderPosition.cpp.
References Position, and Positions.
Referenced by ACarlaRecorder::Write(), and FFrameData::Write().
Member Data Documentation
Positions
std::vector<CarlaRecorderPosition> CarlaRecorderPositions::Positions private
Definition at line 42 of file CarlaRecorderPosition.h.
Referenced by Add(), Clear(), GetPositions(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderPosition.h
CarlaRecorderPosition.cpp