CARLA: carla::client::detail::Simulator Class Reference
carla::client::detail::Simulator Class Reference
Connects and controls a CARLA Simulator.
#include <Simulator.h>
Public Member Functions
Constructor
Simulator (const std::string &host, uint16_t port, size_t worker_threads=0u, bool enable_garbage_collection=false)
Load a new episode
EpisodeProxy ReloadEpisode (bool reset_settings=true)
EpisodeProxy LoadEpisode (std::string map_name, bool reset_settings=true, rpc::MapLayer map_layers=rpc::MapLayer::All)
void LoadLevelLayer (rpc::MapLayer map_layers) const
void UnloadLevelLayer (rpc::MapLayer map_layers) const
EpisodeProxy LoadOpenDriveEpisode (std::string opendrive, const rpc::OpendriveGenerationParameters &params, bool reset_settings=true)
Access to current episode
auto GetCurrentEpisodeId ()
void GetReadyCurrentEpisode ()
EpisodeProxy GetCurrentEpisode ()
World snapshot
World GetWorld ()
WorldSnapshot GetWorldSnapshot () const
Map related methods
SharedPtr< Map > GetCurrentMap ()
std::vector< std::string > GetAvailableMaps ()
Required files related methods
bool SetFilesBaseFolder (const std::string &path)
std::vector< std::string > GetRequiredFiles (const std::string &folder="", const bool download=true) const
void RequestFile (const std::string &name) const
std::vector< uint8_t > GetCacheFile (const std::string &name, const bool request_otherwise) const
Garbage collection policy
GarbageCollectionPolicy GetGarbageCollectionPolicy () const
Pure networking operations
void SetNetworkingTimeout (time_duration timeout)
time_duration GetNetworkingTimeout ()
std::string GetClientVersion ()
std::string GetServerVersion ()
Tick
WorldSnapshot WaitForTick (time_duration timeout)
size_t RegisterOnTickEvent (std::function< void(WorldSnapshot)> callback)
void RemoveOnTickEvent (size_t id)
uint64_t Tick (time_duration timeout)
Access to global objects in the episode
std::string GetEndpoint ()
bool IsTrafficManagerRunning (uint16_t port) const
Query to know if a Traffic Manager is running on port.
std::pair< std::string, uint16_t > GetTrafficManagerRunning (uint16_t port) const
Gets a pair filled with the <IP, port> of the Trafic Manager running on port.
bool AddTrafficManagerRunning (std::pair< std::string, uint16_t > trafficManagerInfo) const
Informs that a Traffic Manager is running on <IP, port>
void DestroyTrafficManager (uint16_t port) const
void AddPendingException (std::string e)
SharedPtr< BlueprintLibrary > GetBlueprintLibrary ()
rpc::VehicleLightStateList GetVehiclesLightStates ()
Returns a list of pairs where the firts element is the vehicle ID and the second one is the light state.
SharedPtr< Actor > GetSpectator ()
rpc::EpisodeSettings GetEpisodeSettings ()
uint64_t SetEpisodeSettings (const rpc::EpisodeSettings &settings)
rpc::WeatherParameters GetWeatherParameters ()
void SetWeatherParameters (const rpc::WeatherParameters &weather)
float GetIMUISensorGravity () const
void SetIMUISensorGravity (float NewIMUISensorGravity)
rpc::VehiclePhysicsControl GetVehiclePhysicsControl (const Vehicle &vehicle) const
rpc::VehicleLightState GetVehicleLightState (const Vehicle &vehicle) const
std::vector< geom::BoundingBox > GetLevelBBs (uint8_t queried_tag) const
Returns all the BBs of all the elements of the level.
std::vector< rpc::EnvironmentObject > GetEnvironmentObjects (uint8_t queried_tag) const
void EnableEnvironmentObjects (std::vector< uint64_t > env_objects_ids, bool enable) const
std::pair< bool, rpc::LabelledPoint > ProjectPoint (geom::Location location, geom::Vector3D direction, float search_distance) const
std::vector< rpc::LabelledPoint > CastRay (geom::Location start_location, geom::Location end_location) const
AI
std::shared_ptr< WalkerNavigation > GetNavigation ()
void NavigationTick ()
void RegisterAIController (const WalkerAIController &controller)
void UnregisterAIController (const WalkerAIController &controller)
boost::optional< geom::Location > GetRandomLocationFromNavigation ()
void SetPedestriansCrossFactor (float percentage)
void SetPedestriansSeed (unsigned int seed)
General operations with actors
boost::optional< rpc::Actor > GetActorById (ActorId id) const
std::vector< rpc::Actor > GetActorsById (const std::vector< ActorId > &actor_ids) const
std::vector< rpc::Actor > GetAllTheActorsInTheEpisode () const
SharedPtr< Actor > MakeActor (rpc::Actor actor_description, GarbageCollectionPolicy gc=GarbageCollectionPolicy::Disabled)
Creates an actor instance out of a description of an existing actor.
SharedPtr< Actor > SpawnActor (const ActorBlueprint &blueprint, const geom::Transform &transform, Actor *parent=nullptr, rpc::AttachmentType attachment_type=rpc::AttachmentType::Rigid, GarbageCollectionPolicy gc=GarbageCollectionPolicy::Inherit, const std::string &socket_name="")
Spawns an actor into the simulation.
bool DestroyActor (Actor &actor)
bool DestroyActor (ActorId actor_id)
ActorSnapshot GetActorSnapshot (ActorId actor_id) const
ActorSnapshot GetActorSnapshot (const Actor &actor) const
rpc::ActorState GetActorState (const Actor &actor) const
geom::Location GetActorLocation (const Actor &actor) const
geom::Transform GetActorTransform (const Actor &actor) const
geom::Vector3D GetActorVelocity (const Actor &actor) const
void SetActorTargetVelocity (const Actor &actor, const geom::Vector3D &vector)
geom::Vector3D GetActorAngularVelocity (const Actor &actor) const
void SetActorTargetAngularVelocity (const Actor &actor, const geom::Vector3D &vector)
void EnableActorConstantVelocity (const Actor &actor, const geom::Vector3D &vector)
void DisableActorConstantVelocity (const Actor &actor)
void AddActorImpulse (const Actor &actor, const geom::Vector3D &impulse)
void AddActorImpulse (const Actor &actor, const geom::Vector3D &impulse, const geom::Vector3D &location)
void AddActorForce (const Actor &actor, const geom::Vector3D &force)
void AddActorForce (const Actor &actor, const geom::Vector3D &force, const geom::Vector3D &location)
void AddActorAngularImpulse (const Actor &actor, const geom::Vector3D &vector)
void AddActorTorque (const Actor &actor, const geom::Vector3D &torque)
geom::Vector3D GetActorAcceleration (const Actor &actor) const
geom::Transform GetActorComponentWorldTransform (const Actor &actor, const std::string componentName)
geom::Transform GetActorComponentRelativeTransform (const Actor &actor, std::string componentName)
std::vector< geom::Transform > GetActorBoneWorldTransforms (const Actor &actor)
std::vector< geom::Transform > GetActorBoneRelativeTransforms (const Actor &actor)
std::vector< std::string > GetActorComponentNames (const Actor &actor)
std::vector< std::string > GetActorBoneNames (const Actor &actor)
std::vector< geom::Transform > GetActorSocketWorldTransforms (const Actor &actor)
std::vector< geom::Transform > GetActorSocketRelativeTransforms (const Actor &actor)
std::vector< std::string > GetActorSocketNames (const Actor &actor)
void SetActorLocation (Actor &actor, const geom::Location &location)
void SetActorTransform (Actor &actor, const geom::Transform &transform)
void SetActorSimulatePhysics (Actor &actor, bool enabled)
void SetActorCollisions (Actor &actor, bool enabled)
void SetActorCollisions (ActorId actor_id, bool enabled)
void SetActorDead (Actor &actor)
void SetActorDead (ActorId actor_id)
void SetActorEnableGravity (Actor &actor, bool enabled)
Operations with vehicles
void SetVehicleAutopilot (Vehicle &vehicle, bool enabled=true)
void ShowVehicleDebugTelemetry (Vehicle &vehicle, bool enabled=true)
void SetLightsToVehicle (Vehicle &vehicle, const rpc::VehicleControl &control)
void ApplyControlToVehicle (Vehicle &vehicle, const rpc::VehicleControl &control)
void ApplyAckermannControlToVehicle (Vehicle &vehicle, const rpc::VehicleAckermannControl &control)
rpc::AckermannControllerSettings GetAckermannControllerSettings (const Vehicle &vehicle) const
void ApplyAckermannControllerSettings (Vehicle &vehicle, const rpc::AckermannControllerSettings &settings)
void ApplyControlToWalker (Walker &walker, const rpc::WalkerControl &control)
rpc::WalkerBoneControlOut GetBonesTransform (Walker &walker)
void SetBonesTransform (Walker &walker, const rpc::WalkerBoneControlIn &bones)
void BlendPose (Walker &walker, float blend)
void GetPoseFromAnimation (Walker &walker)
void ApplyPhysicsControlToVehicle (Vehicle &vehicle, const rpc::VehiclePhysicsControl &physicsControl)
void SetLightStateToVehicle (Vehicle &vehicle, const rpc::VehicleLightState light_state)
void OpenVehicleDoor (Vehicle &vehicle, const rpc::VehicleDoor door_idx)
void CloseVehicleDoor (Vehicle &vehicle, const rpc::VehicleDoor door_idx)
void SetWheelSteerDirection (Vehicle &vehicle, rpc::VehicleWheelLocation wheel_location, float angle_in_deg)
float GetWheelSteerAngle (Vehicle &vehicle, rpc::VehicleWheelLocation wheel_location)
void EnableCarSim (Vehicle &vehicle, std::string simfile_path)
void UseCarSimRoad (Vehicle &vehicle, bool enabled)
void EnableChronoPhysics (Vehicle &vehicle, uint64_t MaxSubsteps, float MaxSubstepDeltaTime, std::string VehicleJSON, std::string PowertrainJSON, std::string TireJSON, std::string BaseJSONPath)
void RestorePhysXPhysics (Vehicle &vehicle)
Operations with the recorder
std::string StartRecorder (std::string name, bool additional_data)
void StopRecorder (void)
std::string ShowRecorderFileInfo (std::string name, bool show_all)
std::string ShowRecorderCollisions (std::string name, char type1, char type2)
std::string ShowRecorderActorsBlocked (std::string name, double min_time, double min_distance)
std::string ReplayFile (std::string name, double start, double duration, uint32_t follow_id, bool replay_sensors)
void SetReplayerTimeFactor (double time_factor)
void SetReplayerIgnoreHero (bool ignore_hero)
void SetReplayerIgnoreSpectator (bool ignore_spectator)
void StopReplayer (bool keep_actors)
Operations with sensors
void SubscribeToSensor (const Sensor &sensor, std::function< void(SharedPtr< sensor::SensorData >)> callback)
void UnSubscribeFromSensor (Actor &sensor)
void EnableForROS (const Sensor &sensor)
void DisableForROS (const Sensor &sensor)
bool IsEnabledForROS (const Sensor &sensor)
void SubscribeToGBuffer (Actor &sensor, uint32_t gbuffer_id, std::function< void(SharedPtr< sensor::SensorData >)> callback)
void UnSubscribeFromGBuffer (Actor &sensor, uint32_t gbuffer_id)
void Send (const Sensor &sensor, std::string message)
Operations with traffic lights
void SetTrafficLightState (TrafficLight &trafficLight, const rpc::TrafficLightState trafficLightState)
void SetTrafficLightGreenTime (TrafficLight &trafficLight, float greenTime)
void SetTrafficLightYellowTime (TrafficLight &trafficLight, float yellowTime)
void SetTrafficLightRedTime (TrafficLight &trafficLight, float redTime)
void FreezeTrafficLight (TrafficLight &trafficLight, bool freeze)
void ResetTrafficLightGroup (TrafficLight &trafficLight)
void ResetAllTrafficLights ()
std::vector< geom::BoundingBox > GetLightBoxes (const TrafficLight &trafficLight) const
std::vector< ActorId > GetGroupTrafficLights (TrafficLight &trafficLight)
Debug
void DrawDebugShape (const rpc::DebugShape &shape)
Apply commands in batch
void ApplyBatch (std::vector< rpc::Command > commands, bool do_tick_cue)
auto ApplyBatchSync (std::vector< rpc::Command > commands, bool do_tick_cue)
Operations lights
SharedPtr< LightManager > GetLightManager () const
std::vector< rpc::LightState > QueryLightsStateToServer () const
void UpdateServerLightsState (std::vector< rpc::LightState > &lights, bool discard_client=false) const
void UpdateDayNightCycle (const bool active) const
size_t RegisterLightUpdateChangeEvent (std::function< void(WorldSnapshot)> callback)
void RemoveLightUpdateChangeEvent (size_t id)
void FreezeAllTrafficLights (bool frozen)
Texture updating operations
void ApplyColorTextureToObjects (const std::vector< std::string > &objects_name, const rpc::MaterialParameter &parameter, const rpc::TextureColor &Texture)
– Texture updating operations
void ApplyColorTextureToObjects (const std::vector< std::string > &objects_name, const rpc::MaterialParameter &parameter, const rpc::TextureFloatColor &Texture)
std::vector< std::string > GetNamesOfAllObjects () const
Private Member Functions
bool ShouldUpdateMap (rpc::MapInfo &map_info)
Private Member Functions inherited from carla::profiler::LifetimeProfiled
LifetimeProfiled ()=default
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Private Attributes
SharedPtr< Map > _cached_map
Client _client
std::shared_ptr< Episode > _episode
const GarbageCollectionPolicy _gc_policy
SharedPtr< LightManager > _light_manager
std::string _open_drive_file
Detailed Description
Connects and controls a CARLA Simulator.
Definition at line 49 of file Simulator.h.
Constructor & Destructor Documentation
Simulator()
carla::client::detail::Simulator::Simulator (const std::string & host, uint16_t port, size_t worker_threads = 0u, bool enable_garbage_collection = false) explicit
Definition at line 72 of file Simulator.cpp.
Member Function Documentation
AddActorAngularImpulse()
void carla::client::detail::Simulator::AddActorAngularImpulse (const Actor & actor, const geom::Vector3D & vector) inline
Definition at line 438 of file Simulator.h.
References _client, carla::client::detail::Client::AddActorAngularImpulse(), and carla::client::detail::ActorState::GetId().
AddActorForce() [1/2]
void carla::client::detail::Simulator::AddActorForce (const Actor & actor, const geom::Vector3D & force) inline
Definition at line 430 of file Simulator.h.
References _client, carla::client::detail::Client::AddActorForce(), and carla::client::detail::ActorState::GetId().
AddActorForce() [2/2]
void carla::client::detail::Simulator::AddActorForce (const Actor & actor, const geom::Vector3D & force, const geom::Vector3D & location) inline
Definition at line 434 of file Simulator.h.
References _client, carla::client::detail::Client::AddActorForce(), and carla::client::detail::ActorState::GetId().
AddActorImpulse() [1/2]
void carla::client::detail::Simulator::AddActorImpulse (const Actor & actor, const geom::Vector3D & impulse) inline
Definition at line 422 of file Simulator.h.
References _client, carla::client::detail::Client::AddActorImpulse(), and carla::client::detail::ActorState::GetId().
AddActorImpulse() [2/2]
void carla::client::detail::Simulator::AddActorImpulse (const Actor & actor, const geom::Vector3D & impulse, const geom::Vector3D & location) inline
Definition at line 426 of file Simulator.h.
References _client, carla::client::detail::Client::AddActorImpulse(), and carla::client::detail::ActorState::GetId().
AddActorTorque()
void carla::client::detail::Simulator::AddActorTorque (const Actor & actor, const geom::Vector3D & torque) inline
Definition at line 442 of file Simulator.h.
References _client, carla::client::detail::Client::AddActorAngularImpulse(), and carla::client::detail::ActorState::GetId().
AddPendingException()
void carla::client::detail::Simulator::AddPendingException (std::string e) inline
Definition at line 236 of file Simulator.h.
References _episode.
AddTrafficManagerRunning()
bool carla::client::detail::Simulator::AddTrafficManagerRunning (std::pair< std::string, uint16_t > trafficManagerInfo) const inline
Informs that a Traffic Manager is running on <IP, port>
Definition at line 228 of file Simulator.h.
References _client, and carla::client::detail::Client::AddTrafficManagerRunning().
ApplyAckermannControllerSettings()
void carla::client::detail::Simulator::ApplyAckermannControllerSettings (Vehicle & vehicle, const rpc::AckermannControllerSettings & settings) inline
Definition at line 548 of file Simulator.h.
References _client, carla::client::detail::Client::ApplyAckermannControllerSettings(), and carla::client::detail::ActorState::GetId().
ApplyAckermannControlToVehicle()
void carla::client::detail::Simulator::ApplyAckermannControlToVehicle (Vehicle & vehicle, const rpc::VehicleAckermannControl & control) inline
Definition at line 540 of file Simulator.h.
References _client, carla::client::detail::Client::ApplyAckermannControlToVehicle(), and carla::client::detail::ActorState::GetId().
ApplyBatch()
void carla::client::detail::Simulator::ApplyBatch (std::vector< rpc::Command > commands, bool do_tick_cue) inline
Definition at line 758 of file Simulator.h.
References _client, and carla::client::detail::Client::ApplyBatch().
ApplyBatchSync()
auto carla::client::detail::Simulator::ApplyBatchSync (std::vector< rpc::Command > commands, bool do_tick_cue) inline
Definition at line 762 of file Simulator.h.
References _client, and carla::client::detail::Client::ApplyBatchSync().
ApplyColorTextureToObjects() [1/2]
void carla::client::detail::Simulator::ApplyColorTextureToObjects (const std::vector< std::string > & objects_name, const rpc::MaterialParameter & parameter, const rpc::TextureColor & Texture)
– Texture updating operations
Definition at line 452 of file Simulator.cpp.
References _client, and carla::client::detail::Client::ApplyColorTextureToObjects().
ApplyColorTextureToObjects() [2/2]
void carla::client::detail::Simulator::ApplyColorTextureToObjects (const std::vector< std::string > & objects_name, const rpc::MaterialParameter & parameter, const rpc::TextureFloatColor & Texture)
Definition at line 459 of file Simulator.cpp.
References _client, and carla::client::detail::Client::ApplyColorTextureToObjects().
ApplyControlToVehicle()
void carla::client::detail::Simulator::ApplyControlToVehicle (Vehicle & vehicle, const rpc::VehicleControl & control) inline
Definition at line 536 of file Simulator.h.
References _client, carla::client::detail::Client::ApplyControlToVehicle(), and carla::client::detail::ActorState::GetId().
ApplyControlToWalker()
void carla::client::detail::Simulator::ApplyControlToWalker (Walker & walker, const rpc::WalkerControl & control) inline
Definition at line 552 of file Simulator.h.
References _client, carla::client::detail::Client::ApplyControlToWalker(), and carla::client::detail::ActorState::GetId().
ApplyPhysicsControlToVehicle()
void carla::client::detail::Simulator::ApplyPhysicsControlToVehicle (Vehicle & vehicle, const rpc::VehiclePhysicsControl & physicsControl) inline
Definition at line 572 of file Simulator.h.
References _client, carla::client::detail::Client::ApplyPhysicsControlToVehicle(), and carla::client::detail::ActorState::GetId().
BlendPose()
void carla::client::detail::Simulator::BlendPose (Walker & walker, float blend) inline
Definition at line 564 of file Simulator.h.
References _client, carla::client::detail::Client::BlendPose(), and carla::client::detail::ActorState::GetId().
CastRay()
std::vector< rpc::LabelledPoint > carla::client::detail::Simulator::CastRay (geom::Location start_location, geom::Location end_location) const inline
Definition at line 298 of file Simulator.h.
References _client, and carla::client::detail::Client::CastRay().
CloseVehicleDoor()
void carla::client::detail::Simulator::CloseVehicleDoor (Vehicle & vehicle, const rpc::VehicleDoor door_idx) inline
Definition at line 584 of file Simulator.h.
References _client, carla::client::detail::Client::CloseVehicleDoor(), and carla::client::detail::ActorState::GetId().
DestroyActor() [1/2]
bool carla::client::detail::Simulator::DestroyActor (Actor & actor)
Definition at line 377 of file Simulator.cpp.
References _client, carla::client::detail::EpisodeProxyImpl< PointerT >::Clear(), carla::client::detail::Client::DestroyActor(), carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetEpisode(), carla::client::detail::ActorState::GetId(), and carla::log_debug().
DestroyActor() [2/2]
bool carla::client::detail::Simulator::DestroyActor (ActorId actor_id) inline
Definition at line 373 of file Simulator.h.
References _client, and carla::client::detail::Client::DestroyActor().
DestroyTrafficManager()
void carla::client::detail::Simulator::DestroyTrafficManager (uint16_t port) const inline
Definition at line 232 of file Simulator.h.
References _client, and carla::client::detail::Client::DestroyTrafficManager().
DisableActorConstantVelocity()
void carla::client::detail::Simulator::DisableActorConstantVelocity (const Actor & actor) inline
Definition at line 418 of file Simulator.h.
References _client, carla::client::detail::Client::DisableActorConstantVelocity(), and carla::client::detail::ActorState::GetId().
DisableForROS()
void carla::client::detail::Simulator::DisableForROS (const Sensor & sensor)
Definition at line 416 of file Simulator.cpp.
References _client, carla::client::detail::Client::DisableForROS(), carla::client::detail::ActorState::GetActorDescription(), and carla::rpc::Actor::GetStreamToken().
DrawDebugShape()
void carla::client::detail::Simulator::DrawDebugShape (const rpc::DebugShape & shape) inline
Definition at line 748 of file Simulator.h.
References _client, and carla::client::detail::Client::DrawDebugShape().
EnableActorConstantVelocity()
void carla::client::detail::Simulator::EnableActorConstantVelocity (const Actor & actor, const geom::Vector3D & vector) inline
Definition at line 414 of file Simulator.h.
References _client, carla::client::detail::Client::EnableActorConstantVelocity(), and carla::client::detail::ActorState::GetId().
EnableCarSim()
void carla::client::detail::Simulator::EnableCarSim (Vehicle & vehicle, std::string simfile_path) inline
Definition at line 596 of file Simulator.h.
References _client, carla::client::detail::Client::EnableCarSim(), and carla::client::detail::ActorState::GetId().
EnableChronoPhysics()
void carla::client::detail::Simulator::EnableChronoPhysics (Vehicle & vehicle, uint64_t MaxSubsteps, float MaxSubstepDeltaTime, std::string VehicleJSON, std::string PowertrainJSON, std::string TireJSON, std::string BaseJSONPath) inline
Definition at line 604 of file Simulator.h.
References _client, carla::client::detail::Client::EnableChronoPhysics(), and carla::client::detail::ActorState::GetId().
EnableEnvironmentObjects()
void carla::client::detail::Simulator::EnableEnvironmentObjects (std::vector< uint64_t > env_objects_ids, bool enable) const inline
Definition at line 287 of file Simulator.h.
References _client, and carla::client::detail::Client::EnableEnvironmentObjects().
EnableForROS()
void carla::client::detail::Simulator::EnableForROS (const Sensor & sensor)
Definition at line 412 of file Simulator.cpp.
References _client, carla::client::detail::Client::EnableForROS(), carla::client::detail::ActorState::GetActorDescription(), and carla::rpc::Actor::GetStreamToken().
FreezeAllTrafficLights()
void carla::client::detail::Simulator::FreezeAllTrafficLights (bool frozen)
Definition at line 440 of file Simulator.cpp.
References _client, and carla::client::detail::Client::FreezeAllTrafficLights().
FreezeTrafficLight()
void carla::client::detail::Simulator::FreezeTrafficLight (TrafficLight & trafficLight, bool freeze) inline
Definition at line 722 of file Simulator.h.
References _client, carla::client::detail::Client::FreezeTrafficLight(), and carla::client::detail::ActorState::GetId().
GetAckermannControllerSettings()
rpc::AckermannControllerSettings carla::client::detail::Simulator::GetAckermannControllerSettings (const Vehicle & vehicle) const inline
Definition at line 544 of file Simulator.h.
References _client, carla::client::detail::Client::GetAckermannControllerSettings(), and carla::client::detail::ActorState::GetId().
GetActorAcceleration()
geom::Vector3D carla::client::detail::Simulator::GetActorAcceleration (const Actor & actor) const inline
Definition at line 446 of file Simulator.h.
References carla::client::ActorSnapshot::acceleration, and GetActorSnapshot().
GetActorAngularVelocity()
geom::Vector3D carla::client::detail::Simulator::GetActorAngularVelocity (const Actor & actor) const inline
Definition at line 407 of file Simulator.h.
References carla::client::ActorSnapshot::angular_velocity, and GetActorSnapshot().
GetActorBoneNames()
std::vector< std::string > carla::client::detail::Simulator::GetActorBoneNames (const Actor & actor) inline
Definition at line 470 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorBoneNames(), and carla::client::detail::ActorState::GetId().
GetActorBoneRelativeTransforms()
std::vector< geom::Transform > carla::client::detail::Simulator::GetActorBoneRelativeTransforms (const Actor & actor) inline
Definition at line 462 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorBoneRelativeTransforms(), and carla::client::detail::ActorState::GetId().
GetActorBoneWorldTransforms()
std::vector< geom::Transform > carla::client::detail::Simulator::GetActorBoneWorldTransforms (const Actor & actor) inline
Definition at line 458 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorBoneWorldTransforms(), and carla::client::detail::ActorState::GetId().
GetActorById()
boost::optional< rpc::Actor > carla::client::detail::Simulator::GetActorById (ActorId id) const inline
Definition at line 329 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
GetActorComponentNames()
std::vector< std::string > carla::client::detail::Simulator::GetActorComponentNames (const Actor & actor) inline
Definition at line 466 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorComponentNames(), and carla::client::detail::ActorState::GetId().
GetActorComponentRelativeTransform()
geom::Transform carla::client::detail::Simulator::GetActorComponentRelativeTransform (const Actor & actor, std::string componentName) inline
Definition at line 454 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorComponentRelativeTransform(), and carla::client::detail::ActorState::GetId().
GetActorComponentWorldTransform()
geom::Transform carla::client::detail::Simulator::GetActorComponentWorldTransform (const Actor & actor, const std::string componentName) inline
Definition at line 450 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorComponentWorldTransform(), and carla::client::detail::ActorState::GetId().
GetActorLocation()
geom::Location carla::client::detail::Simulator::GetActorLocation (const Actor & actor) const inline
Definition at line 391 of file Simulator.h.
References GetActorSnapshot(), carla::geom::Transform::location, and carla::client::ActorSnapshot::transform.
GetActorsById()
std::vector< rpc::Actor > carla::client::detail::Simulator::GetActorsById (const std::vector< ActorId > & actor_ids) const inline
Definition at line 334 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
GetActorSnapshot() [1/2]
ActorSnapshot carla::client::detail::Simulator::GetActorSnapshot (ActorId actor_id) const inline
Definition at line 378 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
Referenced by GetActorAcceleration(), GetActorAngularVelocity(), GetActorLocation(), GetActorSnapshot(), GetActorState(), GetActorTransform(), and GetActorVelocity().
GetActorSnapshot() [2/2]
ActorSnapshot carla::client::detail::Simulator::GetActorSnapshot (const Actor & actor) const inline
Definition at line 383 of file Simulator.h.
References GetActorSnapshot(), and carla::client::detail::ActorState::GetId().
GetActorSocketNames()
std::vector< std::string > carla::client::detail::Simulator::GetActorSocketNames (const Actor & actor) inline
Definition at line 482 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorSocketNames(), and carla::client::detail::ActorState::GetId().
GetActorSocketRelativeTransforms()
std::vector< geom::Transform > carla::client::detail::Simulator::GetActorSocketRelativeTransforms (const Actor & actor) inline
Definition at line 478 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorSocketRelativeTransforms(), and carla::client::detail::ActorState::GetId().
GetActorSocketWorldTransforms()
std::vector< geom::Transform > carla::client::detail::Simulator::GetActorSocketWorldTransforms (const Actor & actor) inline
Definition at line 474 of file Simulator.h.
References _client, carla::client::detail::Client::GetActorSocketWorldTransforms(), and carla::client::detail::ActorState::GetId().
GetActorState()
rpc::ActorState carla::client::detail::Simulator::GetActorState (const Actor & actor) const inline
Definition at line 387 of file Simulator.h.
References carla::client::ActorSnapshot::actor_state, and GetActorSnapshot().
GetActorTransform()
geom::Transform carla::client::detail::Simulator::GetActorTransform (const Actor & actor) const inline
Definition at line 395 of file Simulator.h.
References GetActorSnapshot(), and carla::client::ActorSnapshot::transform.
GetActorVelocity()
geom::Vector3D carla::client::detail::Simulator::GetActorVelocity (const Actor & actor) const inline
Definition at line 399 of file Simulator.h.
References GetActorSnapshot(), and carla::client::ActorSnapshot::velocity.
GetAllTheActorsInTheEpisode()
std::vector< rpc::Actor > carla::client::detail::Simulator::GetAllTheActorsInTheEpisode () const inline
Definition at line 339 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
GetAvailableMaps()
std::vector< std::string > carla::client::detail::Simulator::GetAvailableMaps () inline
Definition at line 136 of file Simulator.h.
References _client, and carla::client::detail::Client::GetAvailableMaps().
GetBlueprintLibrary()
SharedPtr< BlueprintLibrary > carla::client::detail::Simulator::GetBlueprintLibrary ()
Definition at line 242 of file Simulator.cpp.
References _client, and carla::client::detail::Client::GetActorDefinitions().
GetBonesTransform()
rpc::WalkerBoneControlOut carla::client::detail::Simulator::GetBonesTransform (Walker & walker) inline
Definition at line 556 of file Simulator.h.
References _client, carla::client::detail::Client::GetBonesTransform(), and carla::client::detail::ActorState::GetId().
GetCacheFile()
std::vector< uint8_t > carla::client::detail::Simulator::GetCacheFile (const std::string & name, const bool request_otherwise) const
Definition at line 200 of file Simulator.cpp.
References _client, and carla::client::detail::Client::GetCacheFile().
GetClientVersion()
std::string carla::client::detail::Simulator::GetClientVersion () inline
Definition at line 178 of file Simulator.h.
References _client, and carla::client::detail::Client::GetClientVersion().
GetCurrentEpisode()
EpisodeProxy carla::client::detail::Simulator::GetCurrentEpisode ()
Definition at line 141 of file Simulator.cpp.
References GetReadyCurrentEpisode().
Referenced by GetWorld(), LoadEpisode(), MakeActor(), and SpawnActor().
GetCurrentEpisodeId()
auto carla::client::detail::Simulator::GetCurrentEpisodeId () inline
Precondition
Cannot be called previous to GetCurrentEpisode.
Definition at line 98 of file Simulator.h.
References _episode, DEBUG_ASSERT, and GetReadyCurrentEpisode().
GetCurrentMap()
SharedPtr< Map > carla::client::detail::Simulator::GetCurrentMap ()
Definition at line 157 of file Simulator.cpp.
References _cached_map, _client, _episode, _open_drive_file, DEBUG_ASSERT, carla::client::FileTransfer::FileExists(), carla::client::detail::Client::GetMapData(), carla::client::detail::Client::GetMapInfo(), carla::client::detail::Client::GetRequiredFiles(), and carla::rpc::MapInfo::name.
GetEndpoint()
std::string carla::client::detail::Simulator::GetEndpoint () inline
Definition at line 212 of file Simulator.h.
References _client, and carla::client::detail::Client::GetEndpoint().
GetEnvironmentObjects()
std::vector< rpc::EnvironmentObject > carla::client::detail::Simulator::GetEnvironmentObjects (uint8_t queried_tag) const inline
Definition at line 283 of file Simulator.h.
References _client, and carla::client::detail::Client::GetEnvironmentObjects().
GetEpisodeSettings()
rpc::EpisodeSettings carla::client::detail::Simulator::GetEpisodeSettings () inline
Definition at line 248 of file Simulator.h.
References _client, and carla::client::detail::Client::GetEpisodeSettings().
Referenced by GetReadyCurrentEpisode().
GetGarbageCollectionPolicy()
GarbageCollectionPolicy carla::client::detail::Simulator::GetGarbageCollectionPolicy () const inline
Definition at line 160 of file Simulator.h.
References _gc_policy.
GetGroupTrafficLights()
std::vector< ActorId > carla::client::detail::Simulator::GetGroupTrafficLights (TrafficLight & trafficLight) inline
Definition at line 738 of file Simulator.h.
References _client, carla::client::detail::Client::GetGroupTrafficLights(), and carla::client::detail::ActorState::GetId().
GetIMUISensorGravity()
float carla::client::detail::Simulator::GetIMUISensorGravity () const inline
Definition at line 262 of file Simulator.h.
References _client, and carla::client::detail::Client::GetIMUISensorGravity().
GetLevelBBs()
std::vector< geom::BoundingBox > carla::client::detail::Simulator::GetLevelBBs (uint8_t queried_tag) const inline
Returns all the BBs of all the elements of the level.
Definition at line 279 of file Simulator.h.
References _client, and carla::client::detail::Client::GetLevelBBs().
GetLightBoxes()
std::vector< geom::BoundingBox > carla::client::detail::Simulator::GetLightBoxes (const TrafficLight & trafficLight) const inline
Definition at line 734 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::GetLightBoxes().
GetLightManager()
SharedPtr< LightManager > carla::client::detail::Simulator::GetLightManager () const inline
Definition at line 772 of file Simulator.h.
References _light_manager.
GetNamesOfAllObjects()
std::vector< std::string > carla::client::detail::Simulator::GetNamesOfAllObjects () const
Definition at line 466 of file Simulator.cpp.
References _client, and carla::client::detail::Client::GetNamesOfAllObjects().
GetNavigation()
std::shared_ptr< WalkerNavigation > carla::client::detail::Simulator::GetNavigation ()
Definition at line 288 of file Simulator.cpp.
References _episode, and DEBUG_ASSERT.
GetNetworkingTimeout()
time_duration carla::client::detail::Simulator::GetNetworkingTimeout () inline
Definition at line 174 of file Simulator.h.
References _client, and carla::client::detail::Client::GetTimeout().
GetPoseFromAnimation()
void carla::client::detail::Simulator::GetPoseFromAnimation (Walker & walker) inline
Definition at line 568 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::GetPoseFromAnimation().
GetRandomLocationFromNavigation()
boost::optional< geom::Location > carla::client::detail::Simulator::GetRandomLocationFromNavigation ()
Definition at line 323 of file Simulator.cpp.
References _episode, and DEBUG_ASSERT.
GetReadyCurrentEpisode()
void carla::client::detail::Simulator::GetReadyCurrentEpisode ()
Definition at line 130 of file Simulator.cpp.
References _client, _episode, _light_manager, GetEpisodeSettings(), carla::client::detail::Client::GetTimeout(), carla::client::detail::ValidateVersions(), and WaitForTick().
Referenced by GetCurrentEpisode(), and GetCurrentEpisodeId().
GetRequiredFiles()
std::vector< std::string > carla::client::detail::Simulator::GetRequiredFiles (const std::string & folder = "", const bool download = true) const
Definition at line 192 of file Simulator.cpp.
References _client, and carla::client::detail::Client::GetRequiredFiles().
GetServerVersion()
std::string carla::client::detail::Simulator::GetServerVersion () inline
Definition at line 182 of file Simulator.h.
References _client, and carla::client::detail::Client::GetServerVersion().
GetSpectator()
SharedPtr< Actor > carla::client::detail::Simulator::GetSpectator ()
Definition at line 251 of file Simulator.cpp.
References _client, carla::client::detail::Client::GetSpectator(), and MakeActor().
GetTrafficManagerRunning()
std::pair< std::string, uint16_t > carla::client::detail::Simulator::GetTrafficManagerRunning (uint16_t port) const inline
Gets a pair filled with the <IP, port> of the Trafic Manager running on port.
If there is no Traffic Manager running the pair will be ("", 0)
Definition at line 223 of file Simulator.h.
References _client, and carla::client::detail::Client::GetTrafficManagerRunning().
GetVehicleLightState()
rpc::VehicleLightState carla::client::detail::Simulator::GetVehicleLightState (const Vehicle & vehicle) const inline
Definition at line 274 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::GetVehicleLightState().
GetVehiclePhysicsControl()
rpc::VehiclePhysicsControl carla::client::detail::Simulator::GetVehiclePhysicsControl (const Vehicle & vehicle) const inline
Definition at line 270 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::GetVehiclePhysicsControl().
GetVehiclesLightStates()
rpc::VehicleLightStateList carla::client::detail::Simulator::GetVehiclesLightStates ()
Returns a list of pairs where the firts element is the vehicle ID and the second one is the light state.
Definition at line 247 of file Simulator.cpp.
References _client, and carla::client::detail::Client::GetVehiclesLightStates().
GetWeatherParameters()
rpc::WeatherParameters carla::client::detail::Simulator::GetWeatherParameters () inline
Definition at line 254 of file Simulator.h.
References _client, and carla::client::detail::Client::GetWeatherParameters().
GetWheelSteerAngle()
float carla::client::detail::Simulator::GetWheelSteerAngle (Vehicle & vehicle, rpc::VehicleWheelLocation wheel_location) inline
Definition at line 592 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::GetWheelSteerAngle().
GetWorld()
World carla::client::detail::Simulator::GetWorld () inline
Definition at line 113 of file Simulator.h.
References GetCurrentEpisode().
GetWorldSnapshot()
WorldSnapshot carla::client::detail::Simulator::GetWorldSnapshot () const inline
Definition at line 123 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
IsEnabledForROS()
bool carla::client::detail::Simulator::IsEnabledForROS (const Sensor & sensor)
Definition at line 420 of file Simulator.cpp.
References _client, carla::client::detail::ActorState::GetActorDescription(), carla::rpc::Actor::GetStreamToken(), and carla::client::detail::Client::IsEnabledForROS().
IsTrafficManagerRunning()
bool carla::client::detail::Simulator::IsTrafficManagerRunning (uint16_t port) const inline
Query to know if a Traffic Manager is running on port.
Definition at line 217 of file Simulator.h.
References _client, and carla::client::detail::Client::IsTrafficManagerRunning().
LoadEpisode()
EpisodeProxy carla::client::detail::Simulator::LoadEpisode (std::string map_name, bool reset_settings = true, rpc::MapLayer map_layers = rpc::MapLayer::All)
Definition at line 87 of file Simulator.cpp.
References _client, _episode, GetCurrentEpisode(), carla::client::detail::Client::GetEpisodeSettings(), carla::client::detail::EpisodeProxyImpl< PointerT >::GetId(), carla::client::detail::Client::GetTimeout(), carla::client::detail::Client::LoadEpisode(), carla::time_duration::milliseconds(), carla::client::detail::Client::SendTickCue(), carla::rpc::EpisodeSettings::synchronous_mode, and carla::throw_exception().
Referenced by LoadOpenDriveEpisode(), and ReloadEpisode().
LoadLevelLayer()
void carla::client::detail::Simulator::LoadLevelLayer (rpc::MapLayer map_layers) const inline
Definition at line 78 of file Simulator.h.
References _client, and carla::client::detail::Client::LoadLevelLayer().
LoadOpenDriveEpisode()
EpisodeProxy carla::client::detail::Simulator::LoadOpenDriveEpisode (std::string opendrive, const rpc::OpendriveGenerationParameters & params, bool reset_settings = true)
Definition at line 115 of file Simulator.cpp.
References _client, carla::client::detail::Client::CopyOpenDriveToServer(), and LoadEpisode().
MakeActor()
SharedPtr< Actor > carla::client::detail::Simulator::MakeActor (rpc::Actor actor_description, GarbageCollectionPolicy gc = GarbageCollectionPolicy::Disabled) inline
Creates an actor instance out of a description of an existing actor.
Note that this does not spawn an actor.
If gc is GarbageCollectionPolicy::Enabled, the shared pointer returned is provided with a custom deleter that calls Destroy() on the actor. This method does not support GarbageCollectionPolicy::Inherit.
Definition at line 350 of file Simulator.h.
References GetCurrentEpisode(), carla::client::Inherit, carla::client::detail::ActorFactory::MakeActor(), and RELEASE_ASSERT.
Referenced by GetSpectator().
NavigationTick()
void carla::client::detail::Simulator::NavigationTick ()
Definition at line 295 of file Simulator.cpp.
References _episode, and DEBUG_ASSERT.
Referenced by Tick(), and WaitForTick().
OpenVehicleDoor()
void carla::client::detail::Simulator::OpenVehicleDoor (Vehicle & vehicle, const rpc::VehicleDoor door_idx) inline
Definition at line 580 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::OpenVehicleDoor().
ProjectPoint()
std::pair< bool, rpc::LabelledPoint > carla::client::detail::Simulator::ProjectPoint (geom::Location location, geom::Vector3D direction, float search_distance) const inline
Definition at line 293 of file Simulator.h.
References _client, and carla::client::detail::Client::ProjectPoint().
QueryLightsStateToServer()
std::vector< rpc::LightState > carla::client::detail::Simulator::QueryLightsStateToServer () const inline
Definition at line 776 of file Simulator.h.
References _client, and carla::client::detail::Client::QueryLightsStateToServer().
RegisterAIController()
void carla::client::detail::Simulator::RegisterAIController (const WalkerAIController & controller)
Definition at line 301 of file Simulator.cpp.
References _episode, DEBUG_ASSERT, carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetId(), carla::client::detail::ActorState::GetParent(), and carla::throw_exception().
RegisterLightUpdateChangeEvent()
size_t carla::client::detail::Simulator::RegisterLightUpdateChangeEvent (std::function< void(WorldSnapshot)> callback) inline
Definition at line 790 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
RegisterOnTickEvent()
size_t carla::client::detail::Simulator::RegisterOnTickEvent (std::function< void(WorldSnapshot)> callback) inline
Definition at line 194 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
ReloadEpisode()
EpisodeProxy carla::client::detail::Simulator::ReloadEpisode (bool reset_settings = true) inline
Definition at line 72 of file Simulator.h.
References LoadEpisode().
RemoveLightUpdateChangeEvent()
void carla::client::detail::Simulator::RemoveLightUpdateChangeEvent (size_t id) inline
Definition at line 795 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
RemoveOnTickEvent()
void carla::client::detail::Simulator::RemoveOnTickEvent (size_t id) inline
Definition at line 199 of file Simulator.h.
References _episode, and DEBUG_ASSERT.
ReplayFile()
std::string carla::client::detail::Simulator::ReplayFile (std::string name, double start, double duration, uint32_t follow_id, bool replay_sensors) inline
Definition at line 650 of file Simulator.h.
References _client, and carla::client::detail::Client::ReplayFile().
RequestFile()
void carla::client::detail::Simulator::RequestFile (const std::string & name) const
Definition at line 196 of file Simulator.cpp.
References _client, and carla::client::detail::Client::RequestFile().
ResetAllTrafficLights()
void carla::client::detail::Simulator::ResetAllTrafficLights () inline
Definition at line 730 of file Simulator.h.
References _client, and carla::client::detail::Client::ResetAllTrafficLights().
ResetTrafficLightGroup()
void carla::client::detail::Simulator::ResetTrafficLightGroup (TrafficLight & trafficLight) inline
Definition at line 726 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::ResetTrafficLightGroup().
RestorePhysXPhysics()
void carla::client::detail::Simulator::RestorePhysXPhysics (Vehicle & vehicle) inline
Definition at line 620 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::RestorePhysXPhysics().
Send()
void carla::client::detail::Simulator::Send (const Sensor & sensor, std::string message)
Definition at line 444 of file Simulator.cpp.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::Send().
SetActorCollisions() [1/2]
void carla::client::detail::Simulator::SetActorCollisions (Actor & actor, bool enabled) inline
Definition at line 498 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorCollisions().
SetActorCollisions() [2/2]
void carla::client::detail::Simulator::SetActorCollisions (ActorId actor_id, bool enabled) inline
Definition at line 502 of file Simulator.h.
References _client, and carla::client::detail::Client::SetActorCollisions().
SetActorDead() [1/2]
void carla::client::detail::Simulator::SetActorDead (Actor & actor) inline
Definition at line 506 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorDead().
SetActorDead() [2/2]
void carla::client::detail::Simulator::SetActorDead (ActorId actor_id) inline
Definition at line 510 of file Simulator.h.
References _client, and carla::client::detail::Client::SetActorDead().
SetActorEnableGravity()
void carla::client::detail::Simulator::SetActorEnableGravity (Actor & actor, bool enabled) inline
Definition at line 514 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorEnableGravity().
SetActorLocation()
void carla::client::detail::Simulator::SetActorLocation (Actor & actor, const geom::Location & location) inline
Definition at line 486 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorLocation().
SetActorSimulatePhysics()
void carla::client::detail::Simulator::SetActorSimulatePhysics (Actor & actor, bool enabled) inline
Definition at line 494 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorSimulatePhysics().
SetActorTargetAngularVelocity()
void carla::client::detail::Simulator::SetActorTargetAngularVelocity (const Actor & actor, const geom::Vector3D & vector) inline
Definition at line 411 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorTargetAngularVelocity().
SetActorTargetVelocity()
void carla::client::detail::Simulator::SetActorTargetVelocity (const Actor & actor, const geom::Vector3D & vector) inline
Definition at line 403 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorTargetVelocity().
SetActorTransform()
void carla::client::detail::Simulator::SetActorTransform (Actor & actor, const geom::Transform & transform) inline
Definition at line 490 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorTransform().
SetBonesTransform()
void carla::client::detail::Simulator::SetBonesTransform (Walker & walker, const rpc::WalkerBoneControlIn & bones) inline
Definition at line 560 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetBonesTransform().
SetEpisodeSettings()
uint64_t carla::client::detail::Simulator::SetEpisodeSettings (const rpc::EpisodeSettings & settings)
Definition at line 255 of file Simulator.cpp.
References _client, _episode, carla::rpc::EpisodeSettings::fixed_delta_seconds, carla::log_warning(), carla::rpc::EpisodeSettings::max_substep_delta_time, carla::rpc::EpisodeSettings::max_substeps, carla::client::detail::Client::SetEpisodeSettings(), carla::rpc::EpisodeSettings::substepping, carla::client::detail::SynchronizeFrame(), and carla::rpc::EpisodeSettings::synchronous_mode.
SetFilesBaseFolder()
bool carla::client::detail::Simulator::SetFilesBaseFolder (const std::string & path)
Definition at line 188 of file Simulator.cpp.
References _client, and carla::client::detail::Client::SetFilesBaseFolder().
SetIMUISensorGravity()
void carla::client::detail::Simulator::SetIMUISensorGravity (float NewIMUISensorGravity) inline
Definition at line 266 of file Simulator.h.
References _client, and carla::client::detail::Client::SetIMUISensorGravity().
SetLightStateToVehicle()
void carla::client::detail::Simulator::SetLightStateToVehicle (Vehicle & vehicle, const rpc::VehicleLightState light_state) inline
Definition at line 576 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetLightStateToVehicle().
SetLightsToVehicle()
void carla::client::detail::Simulator::SetLightsToVehicle (Vehicle & vehicle, const rpc::VehicleControl & control) inline
Definition at line 532 of file Simulator.h.
References _client, carla::client::detail::Client::ApplyControlToVehicle(), and carla::client::detail::ActorState::GetId().
SetNetworkingTimeout()
void carla::client::detail::Simulator::SetNetworkingTimeout (time_duration timeout) inline
Definition at line 170 of file Simulator.h.
References _client, and carla::client::detail::Client::SetTimeout().
SetPedestriansCrossFactor()
void carla::client::detail::Simulator::SetPedestriansCrossFactor (float percentage)
Definition at line 329 of file Simulator.cpp.
References _episode, and DEBUG_ASSERT.
SetPedestriansSeed()
void carla::client::detail::Simulator::SetPedestriansSeed (unsigned int seed)
Definition at line 335 of file Simulator.cpp.
References _episode, and DEBUG_ASSERT.
SetReplayerIgnoreHero()
void carla::client::detail::Simulator::SetReplayerIgnoreHero (bool ignore_hero) inline
Definition at line 659 of file Simulator.h.
References _client, and carla::client::detail::Client::SetReplayerIgnoreHero().
SetReplayerIgnoreSpectator()
void carla::client::detail::Simulator::SetReplayerIgnoreSpectator (bool ignore_spectator) inline
Definition at line 663 of file Simulator.h.
References _client, and carla::client::detail::Client::SetReplayerIgnoreSpectator().
SetReplayerTimeFactor()
void carla::client::detail::Simulator::SetReplayerTimeFactor (double time_factor) inline
Definition at line 655 of file Simulator.h.
References _client, and carla::client::detail::Client::SetReplayerTimeFactor().
SetTrafficLightGreenTime()
void carla::client::detail::Simulator::SetTrafficLightGreenTime (TrafficLight & trafficLight, float greenTime) inline
Definition at line 710 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetTrafficLightGreenTime().
SetTrafficLightRedTime()
void carla::client::detail::Simulator::SetTrafficLightRedTime (TrafficLight & trafficLight, float redTime) inline
Definition at line 718 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetTrafficLightRedTime().
SetTrafficLightState()
void carla::client::detail::Simulator::SetTrafficLightState (TrafficLight & trafficLight, const rpc::TrafficLightState trafficLightState) inline
Definition at line 706 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetTrafficLightState().
SetTrafficLightYellowTime()
void carla::client::detail::Simulator::SetTrafficLightYellowTime (TrafficLight & trafficLight, float yellowTime) inline
Definition at line 714 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetTrafficLightYellowTime().
SetVehicleAutopilot()
void carla::client::detail::Simulator::SetVehicleAutopilot (Vehicle & vehicle, bool enabled = true) inline
Definition at line 524 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetActorAutopilot().
SetWeatherParameters()
void carla::client::detail::Simulator::SetWeatherParameters (const rpc::WeatherParameters & weather) inline
Definition at line 258 of file Simulator.h.
References _client, and carla::client::detail::Client::SetWeatherParameters().
SetWheelSteerDirection()
void carla::client::detail::Simulator::SetWheelSteerDirection (Vehicle & vehicle, rpc::VehicleWheelLocation wheel_location, float angle_in_deg) inline
Definition at line 588 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SetWheelSteerDirection().
ShouldUpdateMap()
bool carla::client::detail::Simulator::ShouldUpdateMap (rpc::MapInfo & map_info) private
Definition at line 146 of file Simulator.cpp.
References _cached_map, _open_drive_file, and carla::rpc::MapInfo::name.
ShowRecorderActorsBlocked()
std::string carla::client::detail::Simulator::ShowRecorderActorsBlocked (std::string name, double min_time, double min_distance) inline
Definition at line 646 of file Simulator.h.
References _client, and carla::client::detail::Client::ShowRecorderActorsBlocked().
ShowRecorderCollisions()
std::string carla::client::detail::Simulator::ShowRecorderCollisions (std::string name, char type1, char type2) inline
Definition at line 642 of file Simulator.h.
References _client, and carla::client::detail::Client::ShowRecorderCollisions().
ShowRecorderFileInfo()
std::string carla::client::detail::Simulator::ShowRecorderFileInfo (std::string name, bool show_all) inline
Definition at line 638 of file Simulator.h.
References _client, and carla::client::detail::Client::ShowRecorderFileInfo().
ShowVehicleDebugTelemetry()
void carla::client::detail::Simulator::ShowVehicleDebugTelemetry (Vehicle & vehicle, bool enabled = true) inline
Definition at line 528 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::ShowVehicleDebugTelemetry().
SpawnActor()
SharedPtr< Actor > carla::client::detail::Simulator::SpawnActor (const ActorBlueprint & blueprint, const geom::Transform & transform, Actor * parent = nullptr, rpc::AttachmentType attachment_type = rpc::AttachmentType::Rigid, GarbageCollectionPolicy gc = GarbageCollectionPolicy::Inherit, const std::string & socket_name = "")
Spawns an actor into the simulation.
If gc is GarbageCollectionPolicy::Enabled, the shared pointer returned is provided with a custom deleter that calls Destroy() on the actor. If @gc is GarbageCollectionPolicy::Inherit, the default garbage collection policy is used.
Definition at line 345 of file Simulator.cpp.
References _client, _episode, _gc_policy, DEBUG_ASSERT, carla::client::Enabled, GetCurrentEpisode(), carla::client::detail::ActorState::GetId(), carla::client::Inherit, carla::log_debug(), carla::client::detail::ActorFactory::MakeActor(), carla::client::ActorBlueprint::MakeActorDescription(), carla::client::detail::Client::SpawnActor(), and carla::client::detail::Client::SpawnActorWithParent().
StartRecorder()
std::string carla::client::detail::Simulator::StartRecorder (std::string name, bool additional_data) inline
Definition at line 630 of file Simulator.h.
References _client, and carla::client::detail::Client::StartRecorder().
StopRecorder()
void carla::client::detail::Simulator::StopRecorder (void) inline
Definition at line 634 of file Simulator.h.
References _client, and carla::client::detail::Client::StopRecorder().
StopReplayer()
void carla::client::detail::Simulator::StopReplayer (bool keep_actors) inline
Definition at line 667 of file Simulator.h.
References _client, and carla::client::detail::Client::StopReplayer().
SubscribeToGBuffer()
void carla::client::detail::Simulator::SubscribeToGBuffer (Actor & sensor, uint32_t gbuffer_id, std::function< void(SharedPtr< sensor::SensorData >)> callback)
Definition at line 424 of file Simulator.cpp.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::SubscribeToGBuffer().
SubscribeToSensor()
void carla::client::detail::Simulator::SubscribeToSensor (const Sensor & sensor, std::function< void(SharedPtr< sensor::SensorData >)> callback)
Definition at line 394 of file Simulator.cpp.
References _client, _episode, DEBUG_ASSERT, carla::client::detail::ActorState::GetActorDescription(), carla::rpc::Actor::GetStreamToken(), and carla::client::detail::Client::SubscribeToStream().
Tick()
uint64_t carla::client::detail::Simulator::Tick (time_duration timeout)
Definition at line 221 of file Simulator.cpp.
References _client, _episode, DEBUG_ASSERT, carla::client::detail::Client::GetEndpoint(), NavigationTick(), carla::client::detail::Client::SendTickCue(), carla::client::detail::SynchronizeFrame(), and carla::throw_exception().
UnloadLevelLayer()
void carla::client::detail::Simulator::UnloadLevelLayer (rpc::MapLayer map_layers) const inline
Definition at line 82 of file Simulator.h.
References _client, and carla::client::detail::Client::UnloadLevelLayer().
UnregisterAIController()
void carla::client::detail::Simulator::UnregisterAIController (const WalkerAIController & controller)
Definition at line 312 of file Simulator.cpp.
References _episode, DEBUG_ASSERT, carla::client::detail::ActorState::GetDisplayId(), carla::client::detail::ActorState::GetId(), carla::client::detail::ActorState::GetParent(), and carla::throw_exception().
UnSubscribeFromGBuffer()
void carla::client::detail::Simulator::UnSubscribeFromGBuffer (Actor & sensor, uint32_t gbuffer_id)
Definition at line 436 of file Simulator.cpp.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::UnSubscribeFromGBuffer().
UnSubscribeFromSensor()
void carla::client::detail::Simulator::UnSubscribeFromSensor (Actor & sensor)
Definition at line 407 of file Simulator.cpp.
References _client, carla::client::detail::ActorState::GetActorDescription(), carla::rpc::Actor::GetStreamToken(), and carla::client::detail::Client::UnSubscribeFromStream().
UpdateDayNightCycle()
void carla::client::detail::Simulator::UpdateDayNightCycle (const bool active) const inline
Definition at line 786 of file Simulator.h.
References _client, and carla::client::detail::Client::UpdateDayNightCycle().
UpdateServerLightsState()
void carla::client::detail::Simulator::UpdateServerLightsState (std::vector< rpc::LightState > & lights, bool discard_client = false) const inline
Definition at line 780 of file Simulator.h.
References _client, and carla::client::detail::Client::UpdateServerLightsState().
UseCarSimRoad()
void carla::client::detail::Simulator::UseCarSimRoad (Vehicle & vehicle, bool enabled) inline
Definition at line 600 of file Simulator.h.
References _client, carla::client::detail::ActorState::GetId(), and carla::client::detail::Client::UseCarSimRoad().
WaitForTick()
WorldSnapshot carla::client::detail::Simulator::WaitForTick (time_duration timeout)
Definition at line 208 of file Simulator.cpp.
References _client, _episode, DEBUG_ASSERT, carla::client::detail::Client::GetEndpoint(), NavigationTick(), and carla::throw_exception().
Referenced by GetReadyCurrentEpisode().
Member Data Documentation
_cached_map
SharedPtr<Map> carla::client::detail::Simulator::_cached_map private
Definition at line 834 of file Simulator.h.
Referenced by GetCurrentMap(), and ShouldUpdateMap().
_client
Client carla::client::detail::Simulator::_client private
Definition at line 826 of file Simulator.h.
Referenced by AddActorAngularImpulse(), AddActorForce(), AddActorForce(), AddActorImpulse(), AddActorImpulse(), AddActorTorque(), AddTrafficManagerRunning(), ApplyAckermannControllerSettings(), ApplyAckermannControlToVehicle(), ApplyBatch(), ApplyBatchSync(), ApplyColorTextureToObjects(), ApplyColorTextureToObjects(), ApplyControlToVehicle(), ApplyControlToWalker(), ApplyPhysicsControlToVehicle(), BlendPose(), CastRay(), CloseVehicleDoor(), DestroyActor(), DestroyActor(), DestroyTrafficManager(), DisableActorConstantVelocity(), DisableForROS(), DrawDebugShape(), EnableActorConstantVelocity(), EnableCarSim(), EnableChronoPhysics(), EnableEnvironmentObjects(), EnableForROS(), FreezeAllTrafficLights(), FreezeTrafficLight(), GetAckermannControllerSettings(), GetActorBoneNames(), GetActorBoneRelativeTransforms(), GetActorBoneWorldTransforms(), GetActorComponentNames(), GetActorComponentRelativeTransform(), GetActorComponentWorldTransform(), GetActorSocketNames(), GetActorSocketRelativeTransforms(), GetActorSocketWorldTransforms(), GetAvailableMaps(), GetBlueprintLibrary(), GetBonesTransform(), GetCacheFile(), GetClientVersion(), GetCurrentMap(), GetEndpoint(), GetEnvironmentObjects(), GetEpisodeSettings(), GetGroupTrafficLights(), GetIMUISensorGravity(), GetLevelBBs(), GetLightBoxes(), GetNamesOfAllObjects(), GetNetworkingTimeout(), GetPoseFromAnimation(), GetReadyCurrentEpisode(), GetRequiredFiles(), GetServerVersion(), GetSpectator(), GetTrafficManagerRunning(), GetVehicleLightState(), GetVehiclePhysicsControl(), GetVehiclesLightStates(), GetWeatherParameters(), GetWheelSteerAngle(), IsEnabledForROS(), IsTrafficManagerRunning(), LoadEpisode(), LoadLevelLayer(), LoadOpenDriveEpisode(), OpenVehicleDoor(), ProjectPoint(), QueryLightsStateToServer(), ReplayFile(), RequestFile(), ResetAllTrafficLights(), ResetTrafficLightGroup(), RestorePhysXPhysics(), Send(), SetActorCollisions(), SetActorCollisions(), SetActorDead(), SetActorDead(), SetActorEnableGravity(), SetActorLocation(), SetActorSimulatePhysics(), SetActorTargetAngularVelocity(), SetActorTargetVelocity(), SetActorTransform(), SetBonesTransform(), SetEpisodeSettings(), SetFilesBaseFolder(), SetIMUISensorGravity(), SetLightStateToVehicle(), SetLightsToVehicle(), SetNetworkingTimeout(), SetReplayerIgnoreHero(), SetReplayerIgnoreSpectator(), SetReplayerTimeFactor(), SetTrafficLightGreenTime(), SetTrafficLightRedTime(), SetTrafficLightState(), SetTrafficLightYellowTime(), SetVehicleAutopilot(), SetWeatherParameters(), SetWheelSteerDirection(), ShowRecorderActorsBlocked(), ShowRecorderCollisions(), ShowRecorderFileInfo(), ShowVehicleDebugTelemetry(), SpawnActor(), StartRecorder(), StopRecorder(), StopReplayer(), SubscribeToGBuffer(), SubscribeToSensor(), Tick(), UnloadLevelLayer(), UnSubscribeFromGBuffer(), UnSubscribeFromSensor(), UpdateDayNightCycle(), UpdateServerLightsState(), UseCarSimRoad(), and WaitForTick().
_episode
std::shared_ptr<Episode> carla::client::detail::Simulator::_episode private
Definition at line 830 of file Simulator.h.
Referenced by AddPendingException(), GetActorById(), GetActorsById(), GetActorSnapshot(), GetAllTheActorsInTheEpisode(), GetCurrentEpisodeId(), GetCurrentMap(), GetNavigation(), GetRandomLocationFromNavigation(), GetReadyCurrentEpisode(), GetWorldSnapshot(), LoadEpisode(), NavigationTick(), RegisterAIController(), RegisterLightUpdateChangeEvent(), RegisterOnTickEvent(), RemoveLightUpdateChangeEvent(), RemoveOnTickEvent(), SetEpisodeSettings(), SetPedestriansCrossFactor(), SetPedestriansSeed(), SpawnActor(), SubscribeToSensor(), Tick(), UnregisterAIController(), and WaitForTick().
_gc_policy
const GarbageCollectionPolicy carla::client::detail::Simulator::_gc_policy private
Definition at line 832 of file Simulator.h.
Referenced by GetGarbageCollectionPolicy(), and SpawnActor().
_light_manager
SharedPtr<LightManager> carla::client::detail::Simulator::_light_manager private
Definition at line 828 of file Simulator.h.
Referenced by GetLightManager(), and GetReadyCurrentEpisode().
_open_drive_file
std::string carla::client::detail::Simulator::_open_drive_file private
Definition at line 836 of file Simulator.h.
Referenced by GetCurrentMap(), and ShouldUpdateMap().
The documentation for this class was generated from the following files:
Simulator.h
Simulator.cpp