CARLA: carla::geom::MeshFactory Class Reference
carla::geom::MeshFactory Class Reference
Mesh helper generator.
#include <MeshFactory.h>
Classes
struct RoadParameters
Parameters for the road generation.
Public Member Functions
std::unique_ptr< Mesh > Generate (const road::Lane &lane) const
Generates a mesh that defines the whole lane.
std::unique_ptr< Mesh > Generate (const road::Lane &lane, const double s_start, const double s_end) const
Generates a mesh that defines a lane from a given s start and end.
std::unique_ptr< Mesh > Generate (const road::LaneSection &lane_section) const
Generates a mesh that defines a lane section.
std::unique_ptr< Mesh > Generate (const road::Road &road) const
Generates a mesh that defines a road.
void GenerateAllOrderedWithMaxLen (const road::Road &road, std::map< road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > &roads) const
std::vector< std::unique_ptr< Mesh > > GenerateAllWithMaxLen (const road::Road &road) const
Generates a chunked road with all the features needed for simulation.
void GenerateLaneMarkForRoad (const road::Road &road, std::vector< std::unique_ptr< Mesh > > &inout, std::vector< std::string > &outinfo) const
void GenerateLaneMarksForCenterLine (const road::Road &road, const road::LaneSection &lane_section, const road::Lane &lane, std::vector< std::unique_ptr< Mesh > > &inout, std::vector< std::string > &outinfo) const
void GenerateLaneMarksForNotCenterLine (const road::LaneSection &lane_section, const road::Lane &lane, std::vector< std::unique_ptr< Mesh > > &inout, std::vector< std::string > &outinfo) const
void GenerateLaneSectionOrdered (const road::LaneSection &lane_section, std::map< carla::road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > &result) const
Generates a mesh that defines a lane section.
std::unique_ptr< Mesh > GenerateLeftWall (const road::Lane &lane, const double s_start, const double s_end) const
Generates a wall-like mesh at the left side of the lane.
std::map< carla::road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > GenerateOrderedWithMaxLen (const road::LaneSection &lane_section) const
Generates a list of meshes that defines a lane_section with a maximum length.
std::map< carla::road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > GenerateOrderedWithMaxLen (const road::Road &road) const
Generates a list of meshes that defines a road with a maximum length.
std::unique_ptr< Mesh > GenerateRightWall (const road::Lane &lane, const double s_start, const double s_end) const
Generates a wall-like mesh at the right side of the lane.
std::unique_ptr< Mesh > GenerateSidewalk (const road::Lane &lane) const
std::unique_ptr< Mesh > GenerateSidewalk (const road::Lane &lane, const double s_start, const double s_end) const
std::unique_ptr< Mesh > GenerateSidewalk (const road::LaneSection &lane_section) const
std::unique_ptr< Mesh > GenerateTesselated (const road::Lane &lane) const
Generates a mesh that defines the whole lane with bigger tesselation.
std::unique_ptr< Mesh > GenerateTesselated (const road::Lane &lane, const double s_start, const double s_end) const
Generates a mesh that defines a lane from a given s start and end with bigger tesselation.
std::unique_ptr< Mesh > GenerateWalls (const road::LaneSection &lane_section) const
Genrates a mesh representing a wall on the road corners to avoid cars falling down.
std::vector< std::unique_ptr< Mesh > > GenerateWallsWithMaxLen (const road::LaneSection &lane_section) const
Generates a list of meshes that defines a lane_section safety wall with a maximum length.
std::vector< std::unique_ptr< Mesh > > GenerateWallsWithMaxLen (const road::Road &road) const
Generates a list of meshes that defines a road safety wall with a maximum length.
std::vector< std::unique_ptr< Mesh > > GenerateWithMaxLen (const road::LaneSection &lane_section) const
Generates a list of meshes that defines a lane_section with a maximum length.
std::vector< std::unique_ptr< Mesh > > GenerateWithMaxLen (const road::Road &road) const
Generates a list of meshes that defines a road with a maximum length.
std::unique_ptr< Mesh > MergeAndSmooth (std::vector< std::unique_ptr< Mesh > > &lane_meshes) const
MeshFactory (rpc::OpendriveGenerationParameters params=rpc::OpendriveGenerationParameters())
Static Public Member Functions
static uint32_t SelectVerticesInWidth (uint32_t default_num_vertices, road::Lane::LaneType type)
Public Attributes
RoadParameters road_param
Private Member Functions
std::pair< geom::Vector3D, geom::Vector3D > ComputeEdgesForLanemark (const road::LaneSection &lane_section, const road::Lane &lane, const double s_current, const double lanemark_width) const
Detailed Description
Mesh helper generator.
Definition at line 22 of file MeshFactory.h.
Constructor & Destructor Documentation
MeshFactory()
carla::geom::MeshFactory::MeshFactory (rpc::OpendriveGenerationParameters params = rpc::OpendriveGenerationParameters())
Definition at line 21 of file MeshFactory.cpp.
References carla::rpc::OpendriveGenerationParameters::additional_width, carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::geom::MeshFactory::RoadParameters::max_road_len, carla::rpc::OpendriveGenerationParameters::max_road_length, carla::geom::MeshFactory::RoadParameters::resolution, road_param, carla::rpc::OpendriveGenerationParameters::vertex_distance, carla::geom::MeshFactory::RoadParameters::vertex_width_resolution, carla::rpc::OpendriveGenerationParameters::vertex_width_resolution, carla::geom::MeshFactory::RoadParameters::wall_height, and carla::rpc::OpendriveGenerationParameters::wall_height.
Member Function Documentation
ComputeEdgesForLanemark()
std::pair< geom::Vector3D, geom::Vector3D > carla::geom::MeshFactory::ComputeEdgesForLanemark (const road::LaneSection & lane_section, const road::Lane & lane, const double s_current, const double lanemark_width) const private
Definition at line 1192 of file MeshFactory.cpp.
References carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::road::Lane::GetCornerPositions(), carla::road::LaneSection::GetLanes(), carla::geom::Vector3D::Length(), and road_param.
Referenced by GenerateLaneMarksForCenterLine(), and GenerateLaneMarksForNotCenterLine().
Generate() [1/4]
std::unique_ptr< Mesh > carla::geom::MeshFactory::Generate (const road::Lane & lane) const
Generates a mesh that defines the whole lane.
Definition at line 50 of file MeshFactory.cpp.
References carla::geom::EPSILON, Generate(), carla::road::Lane::GetDistance(), and carla::road::Lane::GetLength().
Generate() [2/4]
std::unique_ptr< Mesh > carla::geom::MeshFactory::Generate (const road::Lane & lane, const double s_start, const double s_end) const
Generates a mesh that defines a lane from a given s start and end.
Definition at line 62 of file MeshFactory.cpp.
References carla::geom::Mesh::AddMaterial(), carla::geom::Mesh::AddTriangleStrip(), DEBUG_ASSERT, carla::geom::Mesh::EndMaterial(), carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::road::Lane::GetCornerPositions(), carla::road::Lane::GetDistance(), carla::road::Lane::GetId(), carla::road::Lane::GetLength(), carla::road::Lane::GetType(), carla::road::Lane::IsStraight(), carla::geom::MESH_EPSILON, RELEASE_ASSERT, carla::geom::MeshFactory::RoadParameters::resolution, road_param, and carla::road::Lane::Sidewalk.
Generate() [3/4]
std::unique_ptr< Mesh > carla::geom::MeshFactory::Generate (const road::LaneSection & lane_section) const
Generates a mesh that defines a lane section.
Definition at line 42 of file MeshFactory.cpp.
References Generate(), and carla::road::LaneSection::GetLanes().
Generate() [4/4]
std::unique_ptr< Mesh > carla::geom::MeshFactory::Generate (const road::Road & road) const
Generates a mesh that defines a road.
Definition at line 34 of file MeshFactory.cpp.
References Generate(), and carla::road::Road::GetLaneSections().
Referenced by Generate(), Generate(), Generate(), carla::road::Map::GenerateChunkedMesh(), carla::road::Map::GenerateMesh(), and GenerateWithMaxLen().
GenerateAllOrderedWithMaxLen()
void carla::geom::MeshFactory::GenerateAllOrderedWithMaxLen (const road::Road & road, std::map< road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > & roads) const
Definition at line 733 of file MeshFactory.cpp.
References GenerateOrderedWithMaxLen().
Referenced by carla::road::Map::GenerateRoadsMultithreaded().
GenerateAllWithMaxLen()
std::vector< std::unique_ptr< Mesh > > carla::geom::MeshFactory::GenerateAllWithMaxLen (const road::Road & road) const
Generates a chunked road with all the features needed for simulation.
Definition at line 703 of file MeshFactory.cpp.
References GenerateWallsWithMaxLen(), GenerateWithMaxLen(), and carla::road::Road::IsJunction().
Referenced by carla::road::Map::GenerateChunkedMesh().
GenerateLaneMarkForRoad()
void carla::geom::MeshFactory::GenerateLaneMarkForRoad (const road::Road & road, std::vector< std::unique_ptr< Mesh > > & inout, std::vector< std::string > & outinfo) const
Definition at line 748 of file MeshFactory.cpp.
References carla::road::Lane::Bidirectional, carla::road::Lane::Driving, GenerateLaneMarksForCenterLine(), GenerateLaneMarksForNotCenterLine(), carla::road::Road::GetLaneSections(), carla::road::Lane::None, and carla::road::Lane::Parking.
Referenced by carla::road::Map::GenerateLineMarkings().
GenerateLaneMarksForCenterLine()
void carla::geom::MeshFactory::GenerateLaneMarksForCenterLine (const road::Road & road, const road::LaneSection & lane_section, const road::Lane & lane, std::vector< std::unique_ptr< Mesh > > & inout, std::vector< std::string > & outinfo) const
Definition at line 903 of file MeshFactory.cpp.
References carla::geom::Mesh::AddIndex(), carla::geom::Mesh::AddVertex(), carla::road::element::DirectedPoint::ApplyLateralOffset(), carla::road::element::LaneMarking::BottsDots, carla::road::element::LaneMarking::Broken, carla::road::element::LaneMarking::BrokenBroken, carla::road::element::LaneMarking::BrokenSolid, ComputeEdgesForLanemark(), carla::road::element::LaneMarking::Curb, carla::road::Road::GetDirectedPointIn(), carla::road::LaneSection::GetDistance(), carla::road::Lane::GetInfo(), carla::road::LaneSection::GetLength(), carla::geom::Mesh::GetVertices(), carla::road::element::LaneMarking::Grass, carla::geom::Mesh::IsValid(), carla::road::element::DirectedPoint::location, carla::road::element::LaneMarking::Other, carla::geom::MeshFactory::RoadParameters::resolution, road_param, carla::road::element::LaneMarking::Solid, carla::road::element::LaneMarking::SolidBroken, carla::road::element::LaneMarking::SolidSolid, carla::road::element::LaneMarking::type, carla::road::element::LaneMarking::width, and carla::geom::Vector3D::y.
Referenced by GenerateLaneMarkForRoad().
GenerateLaneMarksForNotCenterLine()
void carla::geom::MeshFactory::GenerateLaneMarksForNotCenterLine (const road::LaneSection & lane_section, const road::Lane & lane, std::vector< std::unique_ptr< Mesh > > & inout, std::vector< std::string > & outinfo) const
Definition at line 777 of file MeshFactory.cpp.
References carla::geom::Mesh::AddIndex(), carla::geom::Mesh::AddVertex(), carla::road::element::LaneMarking::BottsDots, carla::road::element::LaneMarking::Broken, carla::road::element::LaneMarking::BrokenBroken, carla::road::element::LaneMarking::BrokenSolid, ComputeEdgesForLanemark(), carla::road::element::LaneMarking::Curb, carla::road::LaneSection::GetDistance(), carla::road::Lane::GetInfo(), carla::road::LaneSection::GetLength(), carla::geom::Mesh::GetVertices(), carla::road::element::LaneMarking::Grass, carla::geom::Mesh::IsValid(), carla::road::element::LaneMarking::Other, carla::geom::MeshFactory::RoadParameters::resolution, road_param, carla::road::element::LaneMarking::Solid, carla::road::element::LaneMarking::SolidBroken, carla::road::element::LaneMarking::SolidSolid, carla::road::element::LaneMarking::type, and carla::road::element::LaneMarking::width.
Referenced by GenerateLaneMarkForRoad().
GenerateLaneSectionOrdered()
void carla::geom::MeshFactory::GenerateLaneSectionOrdered (const road::LaneSection & lane_section, std::map< carla::road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > & result) const
Generates a mesh that defines a lane section.
Definition at line 194 of file MeshFactory.cpp.
References carla::road::Lane::Bidirectional, carla::road::Lane::Biking, carla::road::Lane::Driving, GenerateSidewalk(), GenerateTesselated(), carla::road::LaneSection::GetLanes(), carla::road::Lane::Parking, road_param, SelectVerticesInWidth(), carla::road::Lane::Shoulder, carla::road::Lane::Sidewalk, and carla::geom::MeshFactory::RoadParameters::vertex_width_resolution.
Referenced by GenerateOrderedWithMaxLen().
GenerateLeftWall()
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateLeftWall (const road::Lane & lane, const double s_start, const double s_end) const
Generates a wall-like mesh at the left side of the lane.
Definition at line 441 of file MeshFactory.cpp.
References carla::geom::Mesh::AddMaterial(), carla::geom::Mesh::AddTriangleStrip(), DEBUG_ASSERT, carla::geom::Mesh::EndMaterial(), carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::road::Lane::GetCornerPositions(), carla::road::Lane::GetDistance(), carla::road::Lane::GetId(), carla::road::Lane::GetLength(), carla::road::Lane::GetType(), carla::road::Lane::IsStraight(), carla::geom::MESH_EPSILON, RELEASE_ASSERT, carla::geom::MeshFactory::RoadParameters::resolution, road_param, carla::road::Lane::Sidewalk, and carla::geom::MeshFactory::RoadParameters::wall_height.
Referenced by GenerateWalls(), and GenerateWallsWithMaxLen().
GenerateOrderedWithMaxLen() [1/2]
std::map< road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > carla::geom::MeshFactory::GenerateOrderedWithMaxLen (const road::LaneSection & lane_section) const
Generates a list of meshes that defines a lane_section with a maximum length.
Definition at line 545 of file MeshFactory.cpp.
References carla::road::Lane::Bidirectional, carla::road::Lane::Biking, carla::road::Lane::Driving, carla::geom::EPSILON, GenerateLaneSectionOrdered(), GenerateSidewalk(), GenerateTesselated(), carla::road::LaneSection::GetDistance(), carla::road::LaneSection::GetLanes(), carla::road::LaneSection::GetLength(), carla::geom::MeshFactory::RoadParameters::max_road_len, carla::road::Lane::Parking, road_param, SelectVerticesInWidth(), carla::road::Lane::Shoulder, carla::road::Lane::Sidewalk, and carla::geom::MeshFactory::RoadParameters::vertex_width_resolution.
GenerateOrderedWithMaxLen() [2/2]
std::map< road::Lane::LaneType, std::vector< std::unique_ptr< Mesh > > > carla::geom::MeshFactory::GenerateOrderedWithMaxLen (const road::Road & road) const
Generates a list of meshes that defines a road with a maximum length.
Definition at line 533 of file MeshFactory.cpp.
References GenerateOrderedWithMaxLen(), and carla::road::Road::GetLaneSections().
Referenced by GenerateAllOrderedWithMaxLen(), and GenerateOrderedWithMaxLen().
GenerateRightWall()
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateRightWall (const road::Lane & lane, const double s_start, const double s_end) const
Generates a wall-like mesh at the right side of the lane.
Definition at line 390 of file MeshFactory.cpp.
References carla::geom::Mesh::AddMaterial(), carla::geom::Mesh::AddTriangleStrip(), DEBUG_ASSERT, carla::geom::Mesh::EndMaterial(), carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::road::Lane::GetCornerPositions(), carla::road::Lane::GetDistance(), carla::road::Lane::GetId(), carla::road::Lane::GetLength(), carla::road::Lane::GetType(), carla::road::Lane::IsStraight(), carla::geom::MESH_EPSILON, RELEASE_ASSERT, carla::geom::MeshFactory::RoadParameters::resolution, road_param, carla::road::Lane::Sidewalk, and carla::geom::MeshFactory::RoadParameters::wall_height.
Referenced by GenerateWalls(), and GenerateWallsWithMaxLen().
GenerateSidewalk() [1/3]
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateSidewalk (const road::Lane & lane) const
Definition at line 251 of file MeshFactory.cpp.
References carla::geom::EPSILON, GenerateSidewalk(), carla::road::Lane::GetDistance(), and carla::road::Lane::GetLength().
GenerateSidewalk() [2/3]
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateSidewalk (const road::Lane & lane, const double s_start, const double s_end) const
Definition at line 256 of file MeshFactory.cpp.
References carla::geom::Mesh::AddIndex(), carla::geom::Mesh::AddMaterial(), carla::geom::Mesh::AddUVs(), carla::geom::Mesh::AddVertices(), DEBUG_ASSERT, carla::geom::Mesh::EndMaterial(), carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::road::Lane::GetCornerPositions(), carla::road::Lane::GetDistance(), carla::road::Lane::GetId(), carla::road::Lane::GetLength(), carla::road::Lane::GetType(), carla::geom::MESH_EPSILON, RELEASE_ASSERT, carla::geom::MeshFactory::RoadParameters::resolution, road_param, and carla::road::Lane::Sidewalk.
GenerateSidewalk() [3/3]
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateSidewalk (const road::LaneSection & lane_section) const
Definition at line 242 of file MeshFactory.cpp.
References carla::geom::EPSILON, GenerateSidewalk(), and carla::road::LaneSection::GetLanes().
Referenced by GenerateLaneSectionOrdered(), GenerateOrderedWithMaxLen(), GenerateSidewalk(), GenerateSidewalk(), and carla::road::Map::GenerateSingleJunction().
GenerateTesselated() [1/2]
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateTesselated (const road::Lane & lane) const
Generates a mesh that defines the whole lane with bigger tesselation.
Definition at line 56 of file MeshFactory.cpp.
References carla::geom::EPSILON, GenerateTesselated(), carla::road::Lane::GetDistance(), and carla::road::Lane::GetLength().
GenerateTesselated() [2/2]
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateTesselated (const road::Lane & lane, const double s_start, const double s_end) const
Generates a mesh that defines a lane from a given s start and end with bigger tesselation.
Definition at line 112 of file MeshFactory.cpp.
References carla::geom::Mesh::AddIndex(), carla::geom::Mesh::AddMaterial(), carla::geom::Mesh::AddUVs(), carla::geom::Mesh::AddVertices(), DEBUG_ASSERT, carla::geom::Mesh::EndMaterial(), carla::geom::EPSILON, carla::geom::MeshFactory::RoadParameters::extra_lane_width, carla::road::Lane::GetCornerPositions(), carla::road::Lane::GetDistance(), carla::road::Lane::GetId(), carla::road::Lane::GetLength(), carla::road::Lane::GetType(), carla::geom::MESH_EPSILON, RELEASE_ASSERT, carla::geom::MeshFactory::RoadParameters::resolution, road_param, carla::road::Lane::Sidewalk, and carla::geom::MeshFactory::RoadParameters::vertex_width_resolution.
Referenced by GenerateLaneSectionOrdered(), GenerateOrderedWithMaxLen(), carla::road::Map::GenerateSingleJunction(), and GenerateTesselated().
GenerateWalls()
std::unique_ptr< Mesh > carla::geom::MeshFactory::GenerateWalls (const road::LaneSection & lane_section) const
Genrates a mesh representing a wall on the road corners to avoid cars falling down.
Definition at line 368 of file MeshFactory.cpp.
References carla::geom::EPSILON, GenerateLeftWall(), GenerateRightWall(), and carla::road::LaneSection::GetLanes().
Referenced by GenerateWallsWithMaxLen().
GenerateWallsWithMaxLen() [1/2]
std::vector< std::unique_ptr< Mesh > > carla::geom::MeshFactory::GenerateWallsWithMaxLen (const road::LaneSection & lane_section) const
Generates a list of meshes that defines a lane_section safety wall with a maximum length.
Definition at line 657 of file MeshFactory.cpp.
References carla::geom::EPSILON, GenerateLeftWall(), GenerateRightWall(), GenerateWalls(), carla::road::LaneSection::GetDistance(), carla::road::LaneSection::GetLanes(), carla::road::LaneSection::GetLength(), carla::geom::MeshFactory::RoadParameters::max_road_len, and road_param.
GenerateWallsWithMaxLen() [2/2]
std::vector< std::unique_ptr< Mesh > > carla::geom::MeshFactory::GenerateWallsWithMaxLen (const road::Road & road) const
Generates a list of meshes that defines a road safety wall with a maximum length.
Definition at line 644 of file MeshFactory.cpp.
References GenerateWallsWithMaxLen(), and carla::road::Road::GetLaneSections().
Referenced by GenerateAllWithMaxLen(), and GenerateWallsWithMaxLen().
GenerateWithMaxLen() [1/2]
std::vector< std::unique_ptr< Mesh > > carla::geom::MeshFactory::GenerateWithMaxLen (const road::LaneSection & lane_section) const
Generates a list of meshes that defines a lane_section with a maximum length.
Definition at line 505 of file MeshFactory.cpp.
References carla::geom::EPSILON, Generate(), carla::road::LaneSection::GetDistance(), carla::road::LaneSection::GetLanes(), carla::road::LaneSection::GetLength(), carla::geom::MeshFactory::RoadParameters::max_road_len, and road_param.
GenerateWithMaxLen() [2/2]
std::vector< std::unique_ptr< Mesh > > carla::geom::MeshFactory::GenerateWithMaxLen (const road::Road & road) const
Generates a list of meshes that defines a road with a maximum length.
Definition at line 492 of file MeshFactory.cpp.
References GenerateWithMaxLen(), and carla::road::Road::GetLaneSections().
Referenced by GenerateAllWithMaxLen(), and GenerateWithMaxLen().
MergeAndSmooth()
std::unique_ptr< Mesh > carla::geom::MeshFactory::MergeAndSmooth (std::vector< std::unique_ptr< Mesh > > & lane_meshes) const
Definition at line 1134 of file MeshFactory.cpp.
References carla::geom::GetVertexNeighborhoodAndWeights(), road_param, and carla::geom::Vector3D::z.
Referenced by carla::road::Map::GenerateChunkedMesh(), and carla::road::Map::GenerateMesh().
SelectVerticesInWidth()
uint32_t carla::geom::MeshFactory::SelectVerticesInWidth (uint32_t default_num_vertices, road::Lane::LaneType type) static
Definition at line 1169 of file MeshFactory.cpp.
References carla::road::Lane::Bidirectional, carla::road::Lane::Biking, carla::road::Lane::Driving, carla::road::Lane::Parking, carla::road::Lane::Shoulder, and carla::road::Lane::Sidewalk.
Referenced by GenerateLaneSectionOrdered(), and GenerateOrderedWithMaxLen().
Member Data Documentation
road_param
RoadParameters carla::geom::MeshFactory::road_param
Definition at line 150 of file MeshFactory.h.
Referenced by ComputeEdgesForLanemark(), Generate(), GenerateLaneMarksForCenterLine(), GenerateLaneMarksForNotCenterLine(), GenerateLaneSectionOrdered(), GenerateLeftWall(), carla::road::Map::GenerateMesh(), GenerateOrderedWithMaxLen(), GenerateRightWall(), GenerateSidewalk(), GenerateTesselated(), GenerateWallsWithMaxLen(), GenerateWithMaxLen(), MergeAndSmooth(), and MeshFactory().
The documentation for this class was generated from the following files:
MeshFactory.h
MeshFactory.cpp