CARLA: carla::opendrive::OpenDriveParser Class Reference
carla::opendrive::OpenDriveParser Class Reference
#include <OpenDriveParser.h>
Static Public Member Functions
static boost::optional< road::Map > Load (const std::string &opendrive)
Detailed Description
Definition at line 18 of file OpenDriveParser.h.
Member Function Documentation
Load()
boost::optional< road::Map > carla::opendrive::OpenDriveParser::Load (const std::string & opendrive) static
Definition at line 27 of file OpenDriveParser.cpp.
References carla::road::MapBuilder::Build(), pugi::xml_document::load_string(), carla::log_error(), carla::opendrive::parser::ControllerParser::Parse(), carla::opendrive::parser::GeometryParser::Parse(), carla::opendrive::parser::GeoReferenceParser::Parse(), carla::opendrive::parser::JunctionParser::Parse(), carla::opendrive::parser::LaneParser::Parse(), carla::opendrive::parser::ObjectParser::Parse(), carla::opendrive::parser::ProfilesParser::Parse(), carla::opendrive::parser::RoadParser::Parse(), carla::opendrive::parser::SignalParser::Parse(), and carla::opendrive::parser::TrafficGroupParser::Parse().
Referenced by AOpenDriveActor::BuildRoutes(), UOpenDriveMap::Load(), UCarlaEpisode::LoadNewOpendriveEpisode(), carla::client::MakeMap(), ATrafficLightManager::MatchTrafficLightActorsWithOpenDriveSignals(), ACarlaGameModeBase::ParseOpenDrive(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
The documentation for this class was generated from the following files:
OpenDriveParser.h
OpenDriveParser.cpp