CARLA: ABaseVegetationActor Class Reference
ABaseVegetationActor Class Reference
#include <BaseVegetationActor.h>
Public Member Functions
virtual void BeginPlay () override
void GetParametersFromComponent ()
void SetParametersToComponent ()
void UpdateSkeletonAndParameters ()
Public Attributes
FSpringBasedVegetationParameters SpringParameters
Detailed Description
Definition at line 77 of file BaseVegetationActor.h.
Member Function Documentation
BeginPlay()
void ABaseVegetationActor::BeginPlay () override virtual
Definition at line 12 of file BaseVegetationActor.cpp.
References BeginPlay().
Referenced by BeginPlay().
GetParametersFromComponent()
void ABaseVegetationActor::GetParametersFromComponent ()
Definition at line 18 of file BaseVegetationActor.cpp.
References FSpringBasedVegetationParameters::Alpha, FSpringBasedVegetationParameters::BaseSpringStrength, FSpringBasedVegetationParameters::bAutoComputeStrength, FSpringBasedVegetationParameters::Beta, FSpringBasedVegetationParameters::CapsuleRadius, FSpringBasedVegetationParameters::CollisionForceMinVel, FSpringBasedVegetationParameters::CollisionForceParameter, FSpringBasedVegetationParameters::DeltaTimeOverride, FSpringBasedVegetationParameters::ForceDistanceFalloffExponent, FSpringBasedVegetationParameters::ForceMaxDistance, FSpringBasedVegetationParameters::Gravity, FSpringBasedVegetationParameters::HorizontalFallof, FSpringBasedVegetationParameters::LineTraceMaxDistance, FSpringBasedVegetationParameters::MinBoneLength, FSpringBasedVegetationParameters::MinForceFactor, FSpringBasedVegetationParameters::MinSpringStrength, FSpringBasedVegetationParameters::RestFactor, FSpringBasedVegetationParameters::Skeleton, SpringParameters, FSpringBasedVegetationParameters::SpringStrengthMulFactor, FSpringBasedVegetationParameters::VehicleCenterZOffset, and FSpringBasedVegetationParameters::VerticalFallof.
Referenced by UpdateSkeletonAndParameters().
SetParametersToComponent()
void ABaseVegetationActor::SetParametersToComponent ()
Definition at line 58 of file BaseVegetationActor.cpp.
References FSpringBasedVegetationParameters::Alpha, FSpringBasedVegetationParameters::BaseSpringStrength, FSpringBasedVegetationParameters::bAutoComputeStrength, FSpringBasedVegetationParameters::Beta, FSpringBasedVegetationParameters::CapsuleRadius, FSpringBasedVegetationParameters::CollisionForceMinVel, FSpringBasedVegetationParameters::CollisionForceParameter, FSpringBasedVegetationParameters::DeltaTimeOverride, FSpringBasedVegetationParameters::ForceDistanceFalloffExponent, FSpringBasedVegetationParameters::ForceMaxDistance, FSpringBasedVegetationParameters::Gravity, FSpringBasedVegetationParameters::HorizontalFallof, FSpringBasedVegetationParameters::LineTraceMaxDistance, FSpringBasedVegetationParameters::MinBoneLength, FSpringBasedVegetationParameters::MinForceFactor, FSpringBasedVegetationParameters::MinSpringStrength, FSpringBasedVegetationParameters::RestFactor, FSpringBasedVegetationParameters::Skeleton, SpringParameters, FSpringBasedVegetationParameters::SpringStrengthMulFactor, FSpringBasedVegetationParameters::VehicleCenterZOffset, and FSpringBasedVegetationParameters::VerticalFallof.
Referenced by UpdateSkeletonAndParameters().
UpdateSkeletonAndParameters()
void ABaseVegetationActor::UpdateSkeletonAndParameters ()
Definition at line 94 of file BaseVegetationActor.cpp.
References GetParametersFromComponent(), and SetParametersToComponent().
Member Data Documentation
SpringParameters
FSpringBasedVegetationParameters ABaseVegetationActor::SpringParameters
Definition at line 86 of file BaseVegetationActor.h.
Referenced by GetParametersFromComponent(), and SetParametersToComponent().
The documentation for this class was generated from the following files:
BaseVegetationActor.h
BaseVegetationActor.cpp