CARLA: carla::profiler::detail::StaticProfiler Class Reference
carla::profiler::detail::StaticProfiler Class Reference
Public Member Functions
StaticProfiler (std::string filename)
template<typename ... Args>
void write_line (Args &&... args)
Private Member Functions
template<typename ... Args>
void write_to_file (std::ios_base::openmode mode, Args &&... args)
Private Attributes
const std::string _filename
Detailed Description
Definition at line 35 of file Profiler.cpp.
Constructor & Destructor Documentation
StaticProfiler()
carla::profiler::detail::StaticProfiler::StaticProfiler (std::string filename) inline
Definition at line 38 of file Profiler.cpp.
References _filename, carla::logging::log(), write_line(), and write_to_file().
Member Function Documentation
write_line()
template<typename ... Args> void carla::profiler::detail::StaticProfiler::write_line (Args &&... args) inline
Definition at line 53 of file Profiler.cpp.
References write_to_file().
Referenced by StaticProfiler().
write_to_file()
template<typename ... Args> void carla::profiler::detail::StaticProfiler::write_to_file (std::ios_base::openmode mode, Args &&... args) inline private
Definition at line 60 of file Profiler.cpp.
References _filename, and carla::profiler::detail::write_csv_to_stream().
Referenced by StaticProfiler(), and write_line().
Member Data Documentation
_filename
const std::string carla::profiler::detail::StaticProfiler::_filename private
Definition at line 70 of file Profiler.cpp.
Referenced by StaticProfiler(), and write_to_file().
The documentation for this class was generated from the following file:
Profiler.cpp