CARLA: carla::traffic_manager::CollisionStage Class Reference
carla::traffic_manager::CollisionStage Class Reference
This class has functionality to detect potential collision with a nearby actor.
#include <CollisionStage.h>
Public Member Functions
void ClearCycleCache ()
CollisionStage (const std::vector< ActorId > &vehicle_id_list, const SimulationState &simulation_state, const BufferMap &buffer_map, const TrackTraffic &track_traffic, const Parameters &parameters, CollisionFrame &output_array, RandomGenerator &random_device)
void RemoveActor (const ActorId actor_id) override
void Reset () override
void Update (const unsigned long index) override
Private Member Functions
void DrawBoundary (const LocationVector &boundary)
LocationVector GetBoundary (const ActorId actor_id)
float GetBoundingBoxExtention (const ActorId actor_id)
LocationVector GetGeodesicBoundary (const ActorId actor_id)
GeometryComparison GetGeometryBetweenActors (const ActorId reference_vehicle_id, const ActorId other_actor_id)
Polygon GetPolygon (const LocationVector &boundary)
std::pair< bool, float > NegotiateCollision (const ActorId reference_vehicle_id, const ActorId other_actor_id, const uint64_t reference_junction_look_ahead_index)
Private Member Functions inherited from carla::traffic_manager::Stage
Stage ()
Stage (const Stage &)
virtual ~Stage ()
Private Attributes
const BufferMap & buffer_map
CollisionLockMap collision_locks
GeodesicBoundaryMap geodesic_boundary_map
GeometryComparisonMap geometry_cache
CollisionFrame & output_array
const Parameters & parameters
RandomGenerator & random_device
const SimulationState & simulation_state
const TrackTraffic & track_traffic
const std::vector< ActorId > & vehicle_id_list
Detailed Description
This class has functionality to detect potential collision with a nearby actor.
Definition at line 52 of file CollisionStage.h.
Constructor & Destructor Documentation
CollisionStage()
carla::traffic_manager::CollisionStage::CollisionStage (const std::vector< ActorId > & vehicle_id_list, const SimulationState & simulation_state, const BufferMap & buffer_map, const TrackTraffic & track_traffic, const Parameters & parameters, CollisionFrame & output_array, RandomGenerator & random_device)
Definition at line 18 of file CollisionStage.cpp.
Member Function Documentation
ClearCycleCache()
void carla::traffic_manager::CollisionStage::ClearCycleCache ()
Definition at line 422 of file CollisionStage.cpp.
References geodesic_boundary_map, and geometry_cache.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run().
DrawBoundary()
void carla::traffic_manager::CollisionStage::DrawBoundary (const LocationVector & boundary) private
GetBoundary()
LocationVector carla::traffic_manager::CollisionStage::GetBoundary (const ActorId actor_id) private
Definition at line 141 of file CollisionStage.cpp.
References carla::traffic_manager::SimulationState::GetDimensions(), carla::traffic_manager::SimulationState::GetHeading(), carla::traffic_manager::SimulationState::GetLocation(), carla::traffic_manager::SimulationState::GetType(), carla::traffic_manager::SimulationState::GetVelocity(), carla::geom::Vector3D::Length(), carla::geom::Vector3D::MakeSafeUnitVector(), carla::traffic_manager::Pedestrian, simulation_state, carla::traffic_manager::constants::Collision::WALKER_TIME_EXTENSION, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by GetGeodesicBoundary(), and GetGeometryBetweenActors().
GetBoundingBoxExtention()
float carla::traffic_manager::CollisionStage::GetBoundingBoxExtention (const ActorId actor_id) private
Definition at line 120 of file CollisionStage.cpp.
References carla::traffic_manager::constants::Collision::BOUNDARY_EXTENSION_MINIMUM, collision_locks, carla::traffic_manager::CollisionLock::distance_to_lead_vehicle, carla::traffic_manager::SimulationState::GetHeading(), carla::traffic_manager::SimulationState::GetVelocity(), carla::traffic_manager::CollisionLock::initial_lock_distance, carla::traffic_manager::constants::Collision::LOCKING_DISTANCE_PADDING, carla::traffic_manager::constants::Collision::MAX_LOCKING_EXTENSION, simulation_state, and carla::traffic_manager::constants::Collision::VEL_EXT_FACTOR.
Referenced by GetGeodesicBoundary(), and NegotiateCollision().
GetGeodesicBoundary()
LocationVector carla::traffic_manager::CollisionStage::GetGeodesicBoundary (const ActorId actor_id) private
Definition at line 172 of file CollisionStage.cpp.
References buffer_map, carla::traffic_manager::constants::Collision::COS_10_DEGREES, geodesic_boundary_map, GetBoundary(), GetBoundingBoxExtention(), carla::traffic_manager::SimulationState::GetDimensions(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), carla::traffic_manager::GetTargetWaypoint(), carla::geom::Vector3D::MakeSafeUnitVector(), parameters, simulation_state, SQUARE, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Referenced by GetGeometryBetweenActors().
GetGeometryBetweenActors()
GeometryComparison carla::traffic_manager::CollisionStage::GetGeometryBetweenActors (const ActorId reference_vehicle_id, const ActorId other_actor_id) private
Definition at line 256 of file CollisionStage.cpp.
References geometry_cache, GetBoundary(), GetGeodesicBoundary(), GetPolygon(), and carla::traffic_manager::GeometryComparison::reference_vehicle_to_other_geodesic.
Referenced by NegotiateCollision().
GetPolygon()
Polygon carla::traffic_manager::CollisionStage::GetPolygon (const LocationVector & boundary) private
Definition at line 245 of file CollisionStage.cpp.
Referenced by GetGeometryBetweenActors().
NegotiateCollision()
std::pair< bool, float > carla::traffic_manager::CollisionStage::NegotiateCollision (const ActorId reference_vehicle_id, const ActorId other_actor_id, const uint64_t reference_junction_look_ahead_index) private
Definition at line 305 of file CollisionStage.cpp.
References carla::traffic_manager::TrafficLightState::at_traffic_light, buffer_map, collision_locks, carla::traffic_manager::CollisionLock::distance_to_lead_vehicle, GetBoundingBoxExtention(), carla::traffic_manager::SimulationState::GetDimensions(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), GetGeometryBetweenActors(), carla::traffic_manager::SimulationState::GetHeading(), carla::traffic_manager::SimulationState::GetLocation(), carla::traffic_manager::SimulationState::GetTLS(), carla::traffic_manager::GeometryComparison::inter_bbox_distance, carla::traffic_manager::GeometryComparison::inter_geodesic_distance, carla::traffic_manager::CollisionLock::lead_vehicle_id, carla::geom::Vector3D::MakeSafeUnitVector(), carla::traffic_manager::constants::Collision::MIN_REFERENCE_DISTANCE, carla::traffic_manager::GeometryComparison::other_vehicle_to_reference_geodesic, carla::traffic_manager::constants::Collision::OVERLAP_THRESHOLD, parameters, carla::traffic_manager::GeometryComparison::reference_vehicle_to_other_geodesic, simulation_state, SQUARE, carla::traffic_manager::constants::Collision::SQUARE_ROOT_OF_TWO, carla::traffic_manager::TrafficLightState::tl_state, and carla::geom::Vector3D::x.
Referenced by Update().
RemoveActor()
void carla::traffic_manager::CollisionStage::RemoveActor (const ActorId actor_id) override virtual
Implements carla::traffic_manager::Stage.
Definition at line 112 of file CollisionStage.cpp.
References collision_locks.
Referenced by carla::traffic_manager::ALSM::RemoveActor().
Reset()
void carla::traffic_manager::CollisionStage::Reset () override virtual
Implements carla::traffic_manager::Stage.
Definition at line 116 of file CollisionStage.cpp.
References collision_locks.
Referenced by carla::traffic_manager::TrafficManagerLocal::Stop().
Update()
void carla::traffic_manager::CollisionStage::Update (const unsigned long index) override virtual
Implements carla::traffic_manager::Stage.
Definition at line 34 of file CollisionStage.cpp.
References carla::traffic_manager::CollisionHazardData::available_distance_margin, buffer_map, carla::traffic_manager::constants::Collision::COLLISION_RADIUS_MIN, carla::traffic_manager::constants::Collision::COLLISION_RADIUS_RATE, carla::traffic_manager::constants::Collision::COLLISION_RADIUS_STOP, carla::traffic_manager::SimulationState::ContainsActor(), carla::traffic_manager::Parameters::GetCollisionDetection(), carla::traffic_manager::SimulationState::GetDimensions(), carla::traffic_manager::Parameters::GetDistanceToLeadingVehicle(), carla::traffic_manager::SimulationState::GetLocation(), carla::traffic_manager::TrackTraffic::GetOverlappingVehicles(), carla::traffic_manager::Parameters::GetPercentageIgnoreVehicles(), carla::traffic_manager::Parameters::GetPercentageIgnoreWalkers(), carla::traffic_manager::GetTargetWaypoint(), carla::traffic_manager::SimulationState::GetType(), carla::traffic_manager::SimulationState::GetVelocity(), carla::traffic_manager::CollisionHazardData::hazard, carla::traffic_manager::CollisionHazardData::hazard_actor_id, carla::geom::Vector3D::Length(), NegotiateCollision(), carla::traffic_manager::RandomGenerator::next(), output_array, parameters, carla::traffic_manager::Pedestrian, random_device, simulation_state, SQUARE, track_traffic, carla::traffic_manager::Vehicle, vehicle_id_list, carla::traffic_manager::constants::Collision::VERTICAL_OVERLAP_THRESHOLD, carla::geom::Vector3D::x, and carla::geom::Vector3D::z.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run().
Member Data Documentation
buffer_map
const BufferMap& carla::traffic_manager::CollisionStage::buffer_map private
Definition at line 56 of file CollisionStage.h.
Referenced by GetGeodesicBoundary(), NegotiateCollision(), and Update().
collision_locks
CollisionLockMap carla::traffic_manager::CollisionStage::collision_locks private
Definition at line 61 of file CollisionStage.h.
Referenced by GetBoundingBoxExtention(), NegotiateCollision(), RemoveActor(), and Reset().
geodesic_boundary_map
GeodesicBoundaryMap carla::traffic_manager::CollisionStage::geodesic_boundary_map private
Definition at line 66 of file CollisionStage.h.
Referenced by ClearCycleCache(), and GetGeodesicBoundary().
geometry_cache
GeometryComparisonMap carla::traffic_manager::CollisionStage::geometry_cache private
Definition at line 65 of file CollisionStage.h.
Referenced by ClearCycleCache(), and GetGeometryBetweenActors().
output_array
CollisionFrame& carla::traffic_manager::CollisionStage::output_array private
Definition at line 59 of file CollisionStage.h.
Referenced by Update().
parameters
const Parameters& carla::traffic_manager::CollisionStage::parameters private
Definition at line 58 of file CollisionStage.h.
Referenced by GetGeodesicBoundary(), NegotiateCollision(), and Update().
random_device
RandomGenerator& carla::traffic_manager::CollisionStage::random_device private
Definition at line 67 of file CollisionStage.h.
Referenced by Update().
simulation_state
const SimulationState& carla::traffic_manager::CollisionStage::simulation_state private
Definition at line 55 of file CollisionStage.h.
Referenced by GetBoundary(), GetBoundingBoxExtention(), GetGeodesicBoundary(), NegotiateCollision(), and Update().
track_traffic
const TrackTraffic& carla::traffic_manager::CollisionStage::track_traffic private
Definition at line 57 of file CollisionStage.h.
Referenced by Update().
vehicle_id_list
const std::vector<ActorId>& carla::traffic_manager::CollisionStage::vehicle_id_list private
Definition at line 54 of file CollisionStage.h.
Referenced by Update().
The documentation for this class was generated from the following files:
CollisionStage.h
CollisionStage.cpp