CARLA: CarlaRecorderTrafficLightTimes Class Reference
CarlaRecorderTrafficLightTimes Class Reference
#include <CarlaRecorderTraficLightTime.h>
Public Member Functions
void Add (const CarlaRecorderTrafficLightTime &InObj)
void Clear (void)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderTrafficLightTime > TrafficLightTimes
Detailed Description
Definition at line 26 of file CarlaRecorderTraficLightTime.h.
Member Function Documentation
Add()
void CarlaRecorderTrafficLightTimes::Add (const CarlaRecorderTrafficLightTime & InObj)
Definition at line 35 of file CarlaRecorderTraficLightTime.cpp.
References TrafficLightTimes.
Referenced by FFrameData::AddTrafficLightTime(), and ACarlaRecorder::AddTrafficLightTime().
Clear()
void CarlaRecorderTrafficLightTimes::Clear (void)
Definition at line 30 of file CarlaRecorderTraficLightTime.cpp.
References TrafficLightTimes.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
Write()
void CarlaRecorderTrafficLightTimes::Write (std::ostream & OutFile)
Definition at line 40 of file CarlaRecorderTraficLightTime.cpp.
References TrafficLightTime, and TrafficLightTimes.
Referenced by ACarlaRecorder::Write(), and FFrameData::Write().
Member Data Documentation
TrafficLightTimes
std::vector<CarlaRecorderTrafficLightTime> CarlaRecorderTrafficLightTimes::TrafficLightTimes private
Definition at line 38 of file CarlaRecorderTraficLightTime.h.
Referenced by Add(), Clear(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderTraficLightTime.h
CarlaRecorderTraficLightTime.cpp