CARLA: carla::sensor::data::SemanticLidarMeasurement Class Reference
carla::sensor::data::SemanticLidarMeasurement Class Reference
Measurement produced by a Lidar.
#include <SemanticLidarMeasurement.h>
Public Member Functions
auto GetChannelCount () const
Number of channels of the Lidar.
auto GetHorizontalAngle () const
Horizontal angle of the Lidar at the time of the measurement.
auto GetPointCount (size_t channel) const
Retrieve the number of points that channel generated.
Public Member Functions inherited from carla::sensor::data::Array< data::SemanticLidarDetection >
reference at (size_type pos)
const_reference at (size_type pos) const
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
value_type * data ()
const value_type * data () const
bool empty () const
iterator end ()
const_iterator end () const
reference operator[] (size_type pos)
const_reference operator[] (size_type pos) const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
Public Member Functions inherited from carla::sensor::SensorData
size_t GetFrame () const
Frame count when the data was generated.
const rpc::Transform & GetSensorTransform () const
Sensor's transform when the data was generated.
double GetTimestamp () const
Simulation-time when the data was generated.
virtual ~SensorData ()=default
Protected Types
using Serializer = s11n::SemanticLidarSerializer
Protected Member Functions
SemanticLidarMeasurement (RawData &&data)
Protected Member Functions inherited from carla::sensor::data::Array< data::SemanticLidarDetection >
Array (RawData &&data, FuncT get_offset)
Array (size_t offset, RawData &&data)
const RawData & GetRawData () const
Protected Member Functions inherited from carla::sensor::SensorData
const auto & GetEpisode () const
SensorData (const RawData &data)
SensorData (size_t frame, double timestamp, const rpc::Transform &sensor_transform)
Protected Attributes
friend Serializer
Private Types
using Super = Array<data::SemanticLidarDetection>
Private Member Functions
auto GetHeader () const
Additional Inherited Members
Public Types inherited from carla::sensor::data::Array< data::SemanticLidarDetection >
using const_iterator
using const_pointer
using const_reference
using const_reverse_iterator
using iterator
using pointer
using reference
using reverse_iterator
using size_type
using value_type
Detailed Description
Measurement produced by a Lidar.
Consists of an array of 3D points plus some extra meta-information about the Lidar.
Definition at line 20 of file SemanticLidarMeasurement.h.
Member Typedef Documentation
Serializer
using carla::sensor::data::SemanticLidarMeasurement::Serializer = s11n::SemanticLidarSerializer protected
Definition at line 25 of file SemanticLidarMeasurement.h.
Super
using carla::sensor::data::SemanticLidarMeasurement::Super = Array<data::SemanticLidarDetection> private
Definition at line 22 of file SemanticLidarMeasurement.h.
Constructor & Destructor Documentation
SemanticLidarMeasurement()
carla::sensor::data::SemanticLidarMeasurement::SemanticLidarMeasurement (RawData && data) inline explicit protected
Definition at line 29 of file SemanticLidarMeasurement.h.
References carla::sensor::s11n::SemanticLidarSerializer::GetHeaderOffset().
Member Function Documentation
GetChannelCount()
auto carla::sensor::data::SemanticLidarMeasurement::GetChannelCount () const inline
Number of channels of the Lidar.
Definition at line 48 of file SemanticLidarMeasurement.h.
References GetHeader().
GetHeader()
auto carla::sensor::data::SemanticLidarMeasurement::GetHeader () const inline private
Definition at line 36 of file SemanticLidarMeasurement.h.
References carla::sensor::s11n::SemanticLidarSerializer::DeserializeHeader(), and carla::sensor::data::Array< data::SemanticLidarDetection >::GetRawData().
Referenced by GetChannelCount(), GetHorizontalAngle(), and GetPointCount().
GetHorizontalAngle()
auto carla::sensor::data::SemanticLidarMeasurement::GetHorizontalAngle () const inline
Horizontal angle of the Lidar at the time of the measurement.
Definition at line 43 of file SemanticLidarMeasurement.h.
References GetHeader().
GetPointCount()
auto carla::sensor::data::SemanticLidarMeasurement::GetPointCount (size_t channel) const inline
Retrieve the number of points that channel generated.
Points are sorted by channel, so this method allows to identify the channel that generated each point.
Definition at line 55 of file SemanticLidarMeasurement.h.
References GetHeader().
Member Data Documentation
Serializer
friend carla::sensor::data::SemanticLidarMeasurement::Serializer protected
Definition at line 27 of file SemanticLidarMeasurement.h.
The documentation for this class was generated from the following file:
SemanticLidarMeasurement.h