CARLA: FCarlaActor Class Reference
FCarlaActor Class Reference
A view over an actor and its properties.
#include <CarlaActor.h>
Public Types
enum class ActorType : uint8 {
Other , Vehicle , Walker , TrafficLight ,
TrafficSign , Sensor , INVALID
}
using IdType = uint32
Public Member Functions
ECarlaServerResponse AddActorAngularImpulse (const FVector &AngularInpulse)
ECarlaServerResponse AddActorForce (const FVector &Force)
ECarlaServerResponse AddActorForceAtLocation (const FVector &Force, const FVector &Location)
ECarlaServerResponse AddActorImpulse (const FVector &Impulse)
ECarlaServerResponse AddActorImpulseAtLocation (const FVector &Impulse, const FVector &Location)
ECarlaServerResponse AddActorTorque (const FVector &Torque)
void AddChildren (IdType ChildId)
virtual ECarlaServerResponse ApplyAckermannControllerSettings (const FAckermannControllerSettings &)
virtual ECarlaServerResponse ApplyAckermannControlToVehicle (const FVehicleAckermannControl &, const EVehicleInputPriority &)
virtual ECarlaServerResponse ApplyControlToVehicle (const FVehicleControl &, const EVehicleInputPriority &)
virtual ECarlaServerResponse ApplyControlToWalker (const FWalkerControl &)
virtual ECarlaServerResponse ApplyPhysicsControl (const FVehiclePhysicsControl &)
virtual ECarlaServerResponse BlendPose (float Blend)
void BuildActorData ()
virtual ECarlaServerResponse CloseVehicleDoor (const EVehicleDoor)
virtual ECarlaServerResponse DisableActorConstantVelocity ()
virtual ECarlaServerResponse EnableActorConstantVelocity (const FVector &)
virtual ECarlaServerResponse EnableCarSim (const FString &)
virtual ECarlaServerResponse EnableChronoPhysics (uint64_t, float, const FString &, const FString &, const FString &, const FString &)
FCarlaActor ()=default
FCarlaActor (IdType ActorId, AActor *Actor, TSharedPtr< const FActorInfo > Info, carla::rpc::ActorState InState, UWorld *World)
virtual ECarlaServerResponse FreezeTrafficLight (bool)
virtual ECarlaServerResponse GetAckermannControllerSettings (FAckermannControllerSettings &)
AActor * GetActor ()
const AActor * GetActor () const
FVector GetActorAngularVelocity () const
FActorData * GetActorData ()
template<typename T >
T * GetActorData ()
const FActorData * GetActorData () const
template<typename T >
const T * GetActorData () const
FVector GetActorGlobalLocation () const
FTransform GetActorGlobalTransform () const
IdType GetActorId () const
const FActorInfo * GetActorInfo () const
FVector GetActorLocalLocation () const
FTransform GetActorLocalTransform () const
carla::rpc::ActorState GetActorState () const
ActorType GetActorType () const
FVector GetActorVelocity () const
carla::rpc::AttachmentType GetAttachmentType () const
virtual ECarlaServerResponse GetBonesTransform (FWalkerBoneControlOut &)
const TArray< IdType > & GetChildren () const
virtual ECarlaServerResponse GetFailureState (carla::rpc::VehicleFailureState &)
IdType GetParent () const
virtual ECarlaServerResponse GetPhysicsControl (FVehiclePhysicsControl &)
virtual ECarlaServerResponse GetPoseFromAnimation ()
virtual UTrafficLightController * GetTrafficLightController ()
virtual ETrafficLightState GetTrafficLightState () const
virtual ECarlaServerResponse GetVehicleAckermannControl (FVehicleAckermannControl &)
virtual ECarlaServerResponse GetVehicleControl (FVehicleControl &)
virtual ECarlaServerResponse GetVehicleLightState (FVehicleLightState &)
virtual ECarlaServerResponse GetWalkerControl (FWalkerControl &)
virtual ECarlaServerResponse GetWheelSteerAngle (const EVehicleWheelLocation &, float &)
bool IsActive () const
bool IsAlive () const
bool IsDormant () const
bool IsInValid () const
bool IsPendingKill () const
virtual ECarlaServerResponse OpenVehicleDoor (const EVehicleDoor)
void PutActorToSleep (UCarlaEpisode *CarlaEpisode)
void RemoveChildren (IdType ChildId)
virtual ECarlaServerResponse ResetTrafficLightGroup ()
virtual ECarlaServerResponse RestorePhysXPhysics ()
virtual ECarlaServerResponse SetActorAutopilot (bool, bool bKeepState=false)
virtual ECarlaServerResponse SetActorCollisions (bool bEnabled)
virtual ECarlaServerResponse SetActorDead ()
virtual ECarlaServerResponse SetActorEnableGravity (bool bEnabled)
void SetActorGlobalLocation (const FVector &Location, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorGlobalTransform (const FTransform &Transform, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorLocalLocation (const FVector &Location, ETeleportType Teleport=ETeleportType::TeleportPhysics)
void SetActorLocalTransform (const FTransform &Transform, ETeleportType Teleport=ETeleportType::TeleportPhysics)
virtual ECarlaServerResponse SetActorSimulatePhysics (bool bEnabled)
void SetActorState (carla::rpc::ActorState InState)
ECarlaServerResponse SetActorTargetAngularVelocity (const FVector &AngularVelocity)
ECarlaServerResponse SetActorTargetVelocity (const FVector &Velocity)
void SetAttachmentType (carla::rpc::AttachmentType InAttachmentType)
virtual ECarlaServerResponse SetBonesTransform (const FWalkerBoneControlIn &)
virtual ECarlaServerResponse SetLightGreenTime (float)
virtual ECarlaServerResponse SetLightRedTime (float)
virtual ECarlaServerResponse SetLightYellowTime (float)
void SetParent (IdType InParentId)
virtual ECarlaServerResponse SetTrafficLightState (const ETrafficLightState &)
virtual ECarlaServerResponse SetVehicleLightState (const FVehicleLightState &)
virtual ECarlaServerResponse SetWalkerState (const FTransform &Transform, carla::rpc::WalkerControl WalkerControl)
virtual ECarlaServerResponse SetWheelSteerDirection (const EVehicleWheelLocation &, float)
virtual ECarlaServerResponse ShowVehicleDebugTelemetry (bool)
virtual ECarlaServerResponse UseCarSimRoad (bool)
void WakeActorUp (UCarlaEpisode *CarlaEpisode)
virtual ~FCarlaActor ()
Static Public Member Functions
static TSharedPtr< FCarlaActor > ConstructCarlaActor (IdType ActorId, AActor *Actor, TSharedPtr< const FActorInfo > Info, ActorType Type, carla::rpc::ActorState InState, UWorld *World)
Protected Attributes
TSharedPtr< FActorData > ActorData = nullptr
ActorType Type = ActorType::INVALID
UWorld * World = nullptr
Private Attributes
carla::rpc::AttachmentType Attachment = carla::rpc::AttachmentType::INVALID
TArray< IdType > Children
IdType Id = 0u
TSharedPtr< const FActorInfo > Info = nullptr
IdType ParentId = 0u
carla::rpc::ActorState State = carla::rpc::ActorState::Invalid
AActor * TheActor = nullptr
Friends
class FActorRegistry
Detailed Description
A view over an actor and its properties.
Definition at line 23 of file CarlaActor.h.
Member Typedef Documentation
IdType
using FCarlaActor::IdType = uint32
Definition at line 27 of file CarlaActor.h.
Member Enumeration Documentation
ActorType
enum class FCarlaActor::ActorType : uint8 strong
Enumerator
Other
Vehicle
Walker
TrafficLight
TrafficSign
Sensor
INVALID
Definition at line 29 of file CarlaActor.h.
Constructor & Destructor Documentation
FCarlaActor() [1/2]
FCarlaActor::FCarlaActor () default
FCarlaActor() [2/2]
FCarlaActor::FCarlaActor (IdType ActorId, AActor * Actor, TSharedPtr< const FActorInfo > Info, carla::rpc::ActorState InState, UWorld * World)
Definition at line 41 of file CarlaActor.cpp.
~FCarlaActor()
virtual FCarlaActor::~FCarlaActor () inline virtual
Definition at line 51 of file CarlaActor.h.
Member Function Documentation
AddActorAngularImpulse()
ECarlaServerResponse FCarlaActor::AddActorAngularImpulse (const FVector & AngularInpulse)
Definition at line 520 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
AddActorForce()
ECarlaServerResponse FCarlaActor::AddActorForce (const FVector & Force)
Definition at line 476 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
AddActorForceAtLocation()
ECarlaServerResponse FCarlaActor::AddActorForceAtLocation (const FVector & Force, const FVector & Location)
Definition at line 496 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
AddActorImpulse()
ECarlaServerResponse FCarlaActor::AddActorImpulse (const FVector & Impulse)
Definition at line 432 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
AddActorImpulseAtLocation()
ECarlaServerResponse FCarlaActor::AddActorImpulseAtLocation (const FVector & Impulse, const FVector & Location)
Definition at line 452 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
AddActorTorque()
ECarlaServerResponse FCarlaActor::AddActorTorque (const FVector & Torque)
Definition at line 540 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
AddChildren()
void FCarlaActor::AddChildren (IdType ChildId) inline
Definition at line 125 of file CarlaActor.h.
References Children.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerEventParent(), and CarlaReplayerHelper::ProcessReplayerEventParent().
ApplyAckermannControllerSettings()
virtual ECarlaServerResponse FCarlaActor::ApplyAckermannControllerSettings (const FAckermannControllerSettings &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 315 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
ApplyAckermannControlToVehicle()
virtual ECarlaServerResponse FCarlaActor::ApplyAckermannControlToVehicle (const FVehicleAckermannControl & , const EVehicleInputPriority &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 294 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
ApplyControlToVehicle()
virtual ECarlaServerResponse FCarlaActor::ApplyControlToVehicle (const FVehicleControl & , const EVehicleInputPriority &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 288 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerAnimVehicle(), CarlaReplayerHelper::ProcessReplayerAnimVehicle(), FFrameData::ProcessReplayerFinish(), and CarlaReplayerHelper::ProcessReplayerFinish().
ApplyControlToWalker()
virtual ECarlaServerResponse FCarlaActor::ApplyControlToWalker (const FWalkerControl &) inline virtual
Reimplemented in FWalkerActor.
Definition at line 393 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::SetWalkerSpeed(), and CarlaReplayerHelper::SetWalkerSpeed().
ApplyPhysicsControl()
virtual ECarlaServerResponse FCarlaActor::ApplyPhysicsControl (const FVehiclePhysicsControl &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 268 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
BlendPose()
virtual ECarlaServerResponse FCarlaActor::BlendPose (float Blend) inline virtual
Reimplemented in FWalkerActor.
Definition at line 413 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
BuildActorData()
void FCarlaActor::BuildActorData ()
CloseVehicleDoor()
virtual ECarlaServerResponse FCarlaActor::CloseVehicleDoor (const EVehicleDoor) inline virtual
Reimplemented in FVehicleActor.
Definition at line 263 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
ConstructCarlaActor()
TSharedPtr< FCarlaActor > FCarlaActor::ConstructCarlaActor (IdType ActorId, AActor * Actor, TSharedPtr< const FActorInfo > Info, ActorType Type, carla::rpc::ActorState InState, UWorld * World) static
Definition at line 121 of file CarlaActor.cpp.
References Info, Sensor, TrafficLight, TrafficSign, Vehicle, Walker, and World.
Referenced by FActorRegistry::MakeCarlaActor().
DisableActorConstantVelocity()
virtual ECarlaServerResponse FCarlaActor::DisableActorConstantVelocity () inline virtual
Reimplemented in FVehicleActor.
Definition at line 238 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
EnableActorConstantVelocity()
virtual ECarlaServerResponse FCarlaActor::EnableActorConstantVelocity (const FVector &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 233 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
EnableCarSim()
virtual ECarlaServerResponse FCarlaActor::EnableCarSim (const FString &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 330 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
EnableChronoPhysics()
virtual ECarlaServerResponse FCarlaActor::EnableChronoPhysics (uint64_t , float , const FString & , const FString & , const FString & , const FString &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 340 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
FreezeTrafficLight()
virtual ECarlaServerResponse FCarlaActor::FreezeTrafficLight (bool) inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 428 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
GetAckermannControllerSettings()
virtual ECarlaServerResponse FCarlaActor::GetAckermannControllerSettings (FAckermannControllerSettings &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 310 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
GetActor() [1/2]
AActor * FCarlaActor::GetActor () inline
Definition at line 90 of file CarlaActor.h.
References TheActor.
Referenced by AddActorAngularImpulse(), AddActorForce(), AddActorForceAtLocation(), AddActorImpulse(), AddActorImpulseAtLocation(), AddActorTorque(), FFrameData::AddVehicleWheelsAnimation(), ACarlaRecorder::AddVehicleWheelsAnimation(), FVehicleActor::ApplyAckermannControllerSettings(), FVehicleActor::ApplyAckermannControlToVehicle(), FVehicleActor::ApplyControlToVehicle(), FWalkerActor::ApplyControlToWalker(), FVehicleActor::ApplyPhysicsControl(), FCarlaServer::FPimpl::BindActions(), FWalkerActor::BlendPose(), ALargeMapManager::CheckActiveActors(), FVehicleActor::CloseVehicleDoor(), ALargeMapManager::ConvertDormantToActiveActors(), ACarlaRecorder::CreateRecorderEventAdd(), FFrameData::CreateRecorderEventAdd(), FActorRegistry::Deregister(), FActorRegistry::Deregister(), UActorDispatcher::DestroyActor(), FVehicleActor::DisableActorConstantVelocity(), FVehicleActor::EnableActorConstantVelocity(), FVehicleActor::EnableCarSim(), FVehicleActor::EnableChronoPhysics(), FTrafficLightActor::FreezeTrafficLight(), FWorldObserver_GetActorState(), FWorldObserver_Serialize(), FVehicleActor::GetAckermannControllerSettings(), GetActorAngularVelocity(), GetActorGlobalLocation(), GetActorGlobalTransform(), GetActorLocalLocation(), GetActorLocalTransform(), GetActorVelocity(), FWalkerActor::GetBonesTransform(), FVehicleActor::GetFailureState(), FVehicleActor::GetPhysicsControl(), FWalkerActor::GetPoseFromAnimation(), FTrafficLightActor::GetTrafficLightController(), FTrafficLightActor::GetTrafficLightState(), FVehicleActor::GetVehicleAckermannControl(), FVehicleActor::GetVehicleControl(), FVehicleActor::GetVehicleLightState(), FWalkerActor::GetWalkerControl(), FVehicleActor::GetWheelSteerAngle(), ALargeMapManager::OnActorSpawned(), FVehicleActor::OpenVehicleDoor(), FFrameData::ProcessReplayerAnimBiker(), CarlaReplayerHelper::ProcessReplayerAnimBiker(), FFrameData::ProcessReplayerAnimVehicleWheels(), CarlaReplayerHelper::ProcessReplayerAnimVehicleWheels(), CarlaReplayerHelper::ProcessReplayerDoorVehicle(), FFrameData::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerWalkerBones(), FActorRegistry::PutActorToSleep(), FActorData::RecordActorData(), FVehicleData::RecordActorData(), FWalkerData::RecordActorData(), FTrafficSignData::RecordActorData(), FTrafficLightData::RecordActorData(), FActorSensorData::RecordActorData(), FTrafficLightActor::ResetTrafficLightGroup(), FActorData::RestoreActorData(), FVehicleData::RestoreActorData(), FWalkerData::RestoreActorData(), FTrafficSignData::RestoreActorData(), FTrafficLightData::RestoreActorData(), FActorSensorData::RestoreActorData(), FVehicleActor::RestorePhysXPhysics(), FVehicleActor::SetActorAutopilot(), SetActorCollisions(), FWalkerActor::SetActorDead(), SetActorEnableGravity(), FWalkerActor::SetActorEnableGravity(), SetActorGlobalLocation(), SetActorGlobalTransform(), SetActorLocalLocation(), SetActorLocalTransform(), SetActorSimulatePhysics(), FVehicleActor::SetActorSimulatePhysics(), FWalkerActor::SetActorSimulatePhysics(), SetActorTargetAngularVelocity(), SetActorTargetVelocity(), FWalkerActor::SetBonesTransform(), FTrafficLightActor::SetLightGreenTime(), FTrafficLightActor::SetLightRedTime(), FTrafficLightActor::SetLightYellowTime(), FTrafficLightActor::SetTrafficLightState(), FVehicleActor::SetVehicleLightState(), FWalkerActor::SetWalkerState(), FVehicleActor::SetWheelSteerDirection(), FVehicleActor::ShowVehicleDebugTelemetry(), UActorDispatcher::SpawnActor(), FVehicleActor::UseCarSimRoad(), and FActorRegistry::WakeActorUp().
GetActor() [2/2]
const AActor * FCarlaActor::GetActor () const inline
Definition at line 95 of file CarlaActor.h.
References TheActor.
GetActorAngularVelocity()
FVector FCarlaActor::GetActorAngularVelocity () const
Definition at line 372 of file CarlaActor.cpp.
References ActorData, GetActor(), and IsDormant().
Referenced by FFrameData::AddActorKinematics(), and ACarlaRecorder::AddActorKinematics().
GetActorData() [1/4]
FActorData * FCarlaActor::GetActorData () inline
Definition at line 156 of file CarlaActor.h.
References ActorData.
Referenced by ALargeMapManager::CheckDormantActors(), FWorldObserver_GetDormantActorState(), and FWorldObserver_Serialize().
GetActorData() [2/4]
template<typename T > T * FCarlaActor::GetActorData () inline
Definition at line 167 of file CarlaActor.h.
References ActorData.
GetActorData() [3/4]
const FActorData * FCarlaActor::GetActorData () const inline
Definition at line 161 of file CarlaActor.h.
References ActorData.
GetActorData() [4/4]
template<typename T > const T * FCarlaActor::GetActorData () const inline
Definition at line 173 of file CarlaActor.h.
References ActorData.
GetActorGlobalLocation()
FVector FCarlaActor::GetActorGlobalLocation () const
Definition at line 240 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), IsDormant(), ALargeMapManager::LocalToGlobalLocation(), and World.
Referenced by FFrameData::FindTrafficLightAt(), CarlaReplayerHelper::FindTrafficLightAt(), and FWalkerActor::SetWalkerState().
GetActorGlobalTransform()
FTransform FCarlaActor::GetActorGlobalTransform () const
Definition at line 199 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), IsDormant(), ALargeMapManager::LocalToGlobalTransform(), and World.
Referenced by FFrameData::AddActorPosition(), ACarlaRecorder::AddActorPosition(), FFrameData::AddExistingActors(), ACarlaRecorder::AddExistingActors(), FWorldObserver_Serialize(), FFrameData::SetCameraPosition(), and CarlaReplayerHelper::SetCameraPosition().
GetActorId()
IdType FCarlaActor::GetActorId () const inline
Definition at line 80 of file CarlaActor.h.
References Id.
Referenced by ACarlaRecorder::AddActorBones(), FFrameData::AddActorBoundingBox(), ACarlaRecorder::AddActorBoundingBox(), FFrameData::AddActorKinematics(), ACarlaRecorder::AddActorKinematics(), FFrameData::AddActorPosition(), ACarlaRecorder::AddActorPosition(), ACarlaRecorder::AddCollision(), FFrameData::AddExistingActors(), ACarlaRecorder::AddExistingActors(), FFrameData::AddPhysicsControl(), ACarlaRecorder::AddPhysicsControl(), FFrameData::AddTrafficLightState(), ACarlaRecorder::AddTrafficLightState(), FFrameData::AddTrafficLightTime(), ACarlaRecorder::AddTrafficLightTime(), FFrameData::AddTriggerVolume(), ACarlaRecorder::AddTriggerVolume(), FFrameData::AddVehicleAnimation(), ACarlaRecorder::AddVehicleAnimation(), ACarlaRecorder::AddVehicleDoor(), FFrameData::AddVehicleLight(), ACarlaRecorder::AddVehicleLight(), FFrameData::AddVehicleWheelsAnimation(), ACarlaRecorder::AddVehicleWheelsAnimation(), FFrameData::AddWalkerAnimation(), ACarlaRecorder::AddWalkerAnimation(), UCarlaEpisode::AttachActors(), FCarlaServer::FPimpl::BindActions(), ALargeMapManager::CheckDormantActors(), ARayCastSemanticLidar::ComputeRawDetection(), FActorRegistry::Deregister(), UCarlaEpisode::DestroyActor(), FWorldObserver_GetActorState(), FWorldObserver_Serialize(), UActorDispatcher::OnActorDestroyed(), ALargeMapManager::OnActorSpawned(), FFrameData::ProcessReplayerEventDel(), CarlaReplayerHelper::ProcessReplayerEventDel(), FFrameData::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerEventParent(), FFrameData::ProcessReplayerFinish(), CarlaReplayerHelper::ProcessReplayerFinish(), UActorDispatcher::RegisterActor(), ACustomV2XSensor::SetOwner(), CaService::SetOwner(), and WakeActorUp().
GetActorInfo()
const FActorInfo * FCarlaActor::GetActorInfo () const inline
Definition at line 100 of file CarlaActor.h.
References Info.
Referenced by FFrameData::AddActorBoundingBox(), ACarlaRecorder::AddActorBoundingBox(), ACarlaRecorder::AddCollision(), FFrameData::AddExistingActors(), ACarlaRecorder::AddExistingActors(), FCarlaServer::FPimpl::BindActions(), UActorDispatcher::DestroyActor(), FWorldObserver_GetAcceleration(), FWorldObserver_Serialize(), CaService::GetStationType(), ALargeMapManager::OnActorDestroyed(), ALargeMapManager::OnActorSpawned(), and UCarlaEpisode::SerializeActor().
GetActorLocalLocation()
FVector FCarlaActor::GetActorLocalLocation () const
Definition at line 221 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalLocation(), IsDormant(), and World.
GetActorLocalTransform()
FTransform FCarlaActor::GetActorLocalTransform () const
Definition at line 177 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalTransform(), IsDormant(), and World.
GetActorState()
carla::rpc::ActorState FCarlaActor::GetActorState () const inline
Definition at line 105 of file CarlaActor.h.
References State.
Referenced by FWorldObserver_Serialize().
GetActorType()
ActorType FCarlaActor::GetActorType () const inline
Definition at line 85 of file CarlaActor.h.
References Type.
Referenced by FFrameData::AddExistingActors(), ACarlaRecorder::AddExistingActors(), FFrameData::AddVehicleWheelsAnimation(), ACarlaRecorder::AddVehicleWheelsAnimation(), FCarlaServer::FPimpl::BindActions(), ALargeMapManager::CheckActiveActors(), FFrameData::FindTrafficLightAt(), CarlaReplayerHelper::FindTrafficLightAt(), FWorldObserver_GetActorState(), FWorldObserver_GetDormantActorState(), FFrameData::GetFrameData(), PathLossModel::GetLocationIfVehicle(), CaService::GetStationType(), PathLossModel::IsVehicle(), FFrameData::ProcessReplayerAnimVehicleWheels(), CarlaReplayerHelper::ProcessReplayerAnimVehicleWheels(), FFrameData::ProcessReplayerFinish(), CarlaReplayerHelper::ProcessReplayerFinish(), CaService::SetOwner(), and ACarlaRecorder::Ticking().
GetActorVelocity()
FVector FCarlaActor::GetActorVelocity () const
Definition at line 360 of file CarlaActor.cpp.
References ActorData, GetActor(), and IsDormant().
Referenced by FFrameData::AddActorKinematics(), and ACarlaRecorder::AddActorKinematics().
GetAttachmentType()
carla::rpc::AttachmentType FCarlaActor::GetAttachmentType () const inline
Definition at line 145 of file CarlaActor.h.
References Attachment.
Referenced by FActorRegistry::WakeActorUp().
GetBonesTransform()
virtual ECarlaServerResponse FCarlaActor::GetBonesTransform (FWalkerBoneControlOut &) inline virtual
Reimplemented in FWalkerActor.
Definition at line 403 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by ACarlaRecorder::AddActorBones(), and FCarlaServer::FPimpl::BindActions().
GetChildren()
const TArray< IdType > & FCarlaActor::GetChildren () const inline
Definition at line 135 of file CarlaActor.h.
References Children.
Referenced by FActorRegistry::PutActorToSleep(), and FActorRegistry::WakeActorUp().
GetFailureState()
virtual ECarlaServerResponse FCarlaActor::GetFailureState (carla::rpc::VehicleFailureState &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 248 of file CarlaActor.h.
References ActorTypeMismatch.
GetParent()
IdType FCarlaActor::GetParent () const inline
Definition at line 120 of file CarlaActor.h.
References ParentId.
Referenced by FCarlaServer::FPimpl::BindActions(), UCarlaEpisode::SerializeActor(), and FActorRegistry::WakeActorUp().
GetPhysicsControl()
virtual ECarlaServerResponse FCarlaActor::GetPhysicsControl (FVehiclePhysicsControl &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 243 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
GetPoseFromAnimation()
virtual ECarlaServerResponse FCarlaActor::GetPoseFromAnimation () inline virtual
Reimplemented in FWalkerActor.
Definition at line 418 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
GetTrafficLightController()
virtual UTrafficLightController * FCarlaActor::GetTrafficLightController () inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 363 of file CarlaActor.h.
Referenced by FFrameData::AddTrafficLightState(), ACarlaRecorder::AddTrafficLightState(), FFrameData::ProcessReplayerStateTrafficLight(), and CarlaReplayerHelper::ProcessReplayerStateTrafficLight().
GetTrafficLightState()
virtual ETrafficLightState FCarlaActor::GetTrafficLightState () const inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 358 of file CarlaActor.h.
Referenced by FFrameData::AddTrafficLightState(), and ACarlaRecorder::AddTrafficLightState().
GetVehicleAckermannControl()
virtual ECarlaServerResponse FCarlaActor::GetVehicleAckermannControl (FVehicleAckermannControl &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 305 of file CarlaActor.h.
References ActorTypeMismatch.
GetVehicleControl()
virtual ECarlaServerResponse FCarlaActor::GetVehicleControl (FVehicleControl &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 300 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FFrameData::AddVehicleAnimation(), and ACarlaRecorder::AddVehicleAnimation().
GetVehicleLightState()
virtual ECarlaServerResponse FCarlaActor::GetVehicleLightState (FVehicleLightState &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 253 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FFrameData::AddVehicleLight(), ACarlaRecorder::AddVehicleLight(), and FCarlaServer::FPimpl::BindActions().
GetWalkerControl()
virtual ECarlaServerResponse FCarlaActor::GetWalkerControl (FWalkerControl &) inline virtual
Reimplemented in FWalkerActor.
Definition at line 398 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FFrameData::AddWalkerAnimation(), and ACarlaRecorder::AddWalkerAnimation().
GetWheelSteerAngle()
virtual ECarlaServerResponse FCarlaActor::GetWheelSteerAngle (const EVehicleWheelLocation & , float &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 283 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
IsActive()
bool FCarlaActor::IsActive () const inline
Definition at line 65 of file CarlaActor.h.
References carla::rpc::Active, and State.
Referenced by ALargeMapManager::ConvertDormantToActiveActors(), and UActorDispatcher::OnActorDestroyed().
IsAlive()
bool FCarlaActor::IsAlive () const inline
Definition at line 59 of file CarlaActor.h.
References carla::rpc::Invalid, carla::rpc::PendingKill, and State.
IsDormant()
bool FCarlaActor::IsDormant () const inline
Definition at line 70 of file CarlaActor.h.
References carla::rpc::Dormant, and State.
Referenced by AddActorAngularImpulse(), AddActorForce(), AddActorForceAtLocation(), AddActorImpulse(), AddActorImpulseAtLocation(), AddActorTorque(), FVehicleActor::ApplyAckermannControllerSettings(), FVehicleActor::ApplyAckermannControlToVehicle(), FVehicleActor::ApplyControlToVehicle(), FWalkerActor::ApplyControlToWalker(), FVehicleActor::ApplyPhysicsControl(), FCarlaServer::FPimpl::BindActions(), FWalkerActor::BlendPose(), ALargeMapManager::CheckDormantActors(), FVehicleActor::CloseVehicleDoor(), FVehicleActor::DisableActorConstantVelocity(), FVehicleActor::EnableActorConstantVelocity(), FVehicleActor::EnableCarSim(), FVehicleActor::EnableChronoPhysics(), FTrafficLightActor::FreezeTrafficLight(), FWorldObserver_Serialize(), FVehicleActor::GetAckermannControllerSettings(), GetActorAngularVelocity(), GetActorGlobalLocation(), GetActorGlobalTransform(), GetActorLocalLocation(), GetActorLocalTransform(), GetActorVelocity(), FWalkerActor::GetBonesTransform(), FVehicleActor::GetFailureState(), FVehicleActor::GetPhysicsControl(), FWalkerActor::GetPoseFromAnimation(), FTrafficLightActor::GetTrafficLightController(), FTrafficLightActor::GetTrafficLightState(), FVehicleActor::GetVehicleAckermannControl(), FVehicleActor::GetVehicleControl(), FVehicleActor::GetVehicleLightState(), FWalkerActor::GetWalkerControl(), FVehicleActor::GetWheelSteerAngle(), FVehicleActor::OpenVehicleDoor(), FFrameData::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerEventParent(), FActorRegistry::Register(), FTrafficLightActor::ResetTrafficLightGroup(), FVehicleActor::RestorePhysXPhysics(), FVehicleActor::SetActorAutopilot(), SetActorCollisions(), FWalkerActor::SetActorDead(), SetActorEnableGravity(), FWalkerActor::SetActorEnableGravity(), SetActorGlobalLocation(), SetActorGlobalTransform(), SetActorLocalLocation(), SetActorLocalTransform(), SetActorSimulatePhysics(), FVehicleActor::SetActorSimulatePhysics(), FWalkerActor::SetActorSimulatePhysics(), SetActorTargetAngularVelocity(), SetActorTargetVelocity(), FWalkerActor::SetBonesTransform(), FTrafficLightActor::SetLightGreenTime(), FTrafficLightActor::SetLightRedTime(), FTrafficLightActor::SetLightYellowTime(), FTrafficLightActor::SetTrafficLightState(), FVehicleActor::SetVehicleLightState(), FWalkerActor::SetWalkerState(), FVehicleActor::SetWheelSteerDirection(), FVehicleActor::ShowVehicleDebugTelemetry(), FVehicleActor::UseCarSimRoad(), and FActorRegistry::WakeActorUp().
IsInValid()
bool FCarlaActor::IsInValid () const inline
Definition at line 54 of file CarlaActor.h.
References carla::rpc::Invalid, and State.
IsPendingKill()
bool FCarlaActor::IsPendingKill () const inline
Definition at line 75 of file CarlaActor.h.
References carla::rpc::PendingKill, and State.
Referenced by FFrameData::AddVehicleAnimation(), ACarlaRecorder::AddVehicleAnimation(), FFrameData::AddVehicleWheelsAnimation(), ACarlaRecorder::AddVehicleWheelsAnimation(), FFrameData::AddWalkerAnimation(), and ACarlaRecorder::AddWalkerAnimation().
OpenVehicleDoor()
virtual ECarlaServerResponse FCarlaActor::OpenVehicleDoor (const EVehicleDoor) inline virtual
Reimplemented in FVehicleActor.
Definition at line 258 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
PutActorToSleep()
void FCarlaActor::PutActorToSleep (UCarlaEpisode * CarlaEpisode)
Definition at line 154 of file CarlaActor.cpp.
References ActorData, carla::rpc::Dormant, State, and TheActor.
Referenced by FActorRegistry::PutActorToSleep().
RemoveChildren()
void FCarlaActor::RemoveChildren (IdType ChildId) inline
Definition at line 130 of file CarlaActor.h.
References Children.
ResetTrafficLightGroup()
virtual ECarlaServerResponse FCarlaActor::ResetTrafficLightGroup () inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 433 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
RestorePhysXPhysics()
virtual ECarlaServerResponse FCarlaActor::RestorePhysXPhysics () inline virtual
Reimplemented in FVehicleActor.
Definition at line 346 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorAutopilot()
virtual ECarlaServerResponse FCarlaActor::SetActorAutopilot (bool , bool bKeepState = false) inline virtual
Reimplemented in FVehicleActor.
Definition at line 320 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions(), and CarlaReplayerHelper::SetActorAutopilot().
SetActorCollisions()
ECarlaServerResponse FCarlaActor::SetActorCollisions (bool bEnabled) virtual
Definition at line 582 of file CarlaActor.cpp.
References GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorDead()
virtual ECarlaServerResponse FCarlaActor::SetActorDead () inline virtual
Reimplemented in FWalkerActor.
Definition at line 423 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorEnableGravity()
ECarlaServerResponse FCarlaActor::SetActorEnableGravity (bool bEnabled) virtual
Reimplemented in FWalkerActor.
Definition at line 594 of file CarlaActor.cpp.
References FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorGlobalLocation()
void FCarlaActor::SetActorGlobalLocation (const FVector & Location, ETeleportType Teleport = ETeleportType::TeleportPhysics)
Definition at line 282 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalLocation(), IsDormant(), and World.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorGlobalTransform()
void FCarlaActor::SetActorGlobalTransform (const FTransform & Transform, ETeleportType Teleport = ETeleportType::TeleportPhysics)
Definition at line 333 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalTransform(), IsDormant(), and World.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerPosition(), CarlaReplayerHelper::ProcessReplayerPosition(), FFrameData::SetCameraPosition(), CarlaReplayerHelper::SetCameraPosition(), and FWalkerActor::SetWalkerState().
SetActorLocalLocation()
void FCarlaActor::SetActorLocalLocation (const FVector & Location, ETeleportType Teleport = ETeleportType::TeleportPhysics)
Definition at line 259 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), IsDormant(), ALargeMapManager::LocalToGlobalLocation(), and World.
SetActorLocalTransform()
void FCarlaActor::SetActorLocalTransform (const FTransform & Transform, ETeleportType Teleport = ETeleportType::TeleportPhysics)
Definition at line 306 of file CarlaActor.cpp.
References ActorData, GetActor(), UCarlaStatics::GetLargeMapManager(), IsDormant(), ALargeMapManager::LocalToGlobalTransform(), and World.
SetActorSimulatePhysics()
ECarlaServerResponse FCarlaActor::SetActorSimulatePhysics (bool bEnabled) virtual
Reimplemented in FVehicleActor, and FWalkerActor.
Definition at line 560 of file CarlaActor.cpp.
References ActorData, FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::SetActorSimulatePhysics(), and CarlaReplayerHelper::SetActorSimulatePhysics().
SetActorState()
void FCarlaActor::SetActorState (carla::rpc::ActorState InState) inline
Definition at line 110 of file CarlaActor.h.
References State.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorTargetAngularVelocity()
ECarlaServerResponse FCarlaActor::SetActorTargetAngularVelocity (const FVector & AngularVelocity)
Definition at line 411 of file CarlaActor.cpp.
References ActorData, FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions().
SetActorTargetVelocity()
ECarlaServerResponse FCarlaActor::SetActorTargetVelocity (const FVector & Velocity)
Definition at line 390 of file CarlaActor.cpp.
References ActorData, FunctionNotSupported, GetActor(), IsDormant(), and Success.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::SetActorVelocity(), and CarlaReplayerHelper::SetActorVelocity().
SetAttachmentType()
void FCarlaActor::SetAttachmentType (carla::rpc::AttachmentType InAttachmentType) inline
Definition at line 140 of file CarlaActor.h.
References Attachment.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerEventParent(), and CarlaReplayerHelper::ProcessReplayerEventParent().
SetBonesTransform()
virtual ECarlaServerResponse FCarlaActor::SetBonesTransform (const FWalkerBoneControlIn &) inline virtual
Reimplemented in FWalkerActor.
Definition at line 408 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetLightGreenTime()
virtual ECarlaServerResponse FCarlaActor::SetLightGreenTime (float) inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 368 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetLightRedTime()
virtual ECarlaServerResponse FCarlaActor::SetLightRedTime (float) inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 378 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetLightYellowTime()
virtual ECarlaServerResponse FCarlaActor::SetLightYellowTime (float) inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 373 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetParent()
void FCarlaActor::SetParent (IdType InParentId) inline
Definition at line 115 of file CarlaActor.h.
References ParentId.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerEventParent(), and CarlaReplayerHelper::ProcessReplayerEventParent().
SetTrafficLightState()
virtual ECarlaServerResponse FCarlaActor::SetTrafficLightState (const ETrafficLightState &) inline virtual
Reimplemented in FTrafficLightActor.
Definition at line 353 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerStateTrafficLight(), and CarlaReplayerHelper::ProcessReplayerStateTrafficLight().
SetVehicleLightState()
virtual ECarlaServerResponse FCarlaActor::SetVehicleLightState (const FVehicleLightState &) inline virtual
Reimplemented in FVehicleActor.
Definition at line 273 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerLightVehicle(), and CarlaReplayerHelper::ProcessReplayerLightVehicle().
SetWalkerState()
virtual ECarlaServerResponse FCarlaActor::SetWalkerState (const FTransform & Transform, carla::rpc::WalkerControl WalkerControl) inline virtual
Reimplemented in FWalkerActor.
Definition at line 386 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
SetWheelSteerDirection()
virtual ECarlaServerResponse FCarlaActor::SetWheelSteerDirection (const EVehicleWheelLocation & , float) inline virtual
Reimplemented in FVehicleActor.
Definition at line 278 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
ShowVehicleDebugTelemetry()
virtual ECarlaServerResponse FCarlaActor::ShowVehicleDebugTelemetry (bool) inline virtual
Reimplemented in FVehicleActor.
Definition at line 325 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
UseCarSimRoad()
virtual ECarlaServerResponse FCarlaActor::UseCarSimRoad (bool) inline virtual
Reimplemented in FVehicleActor.
Definition at line 335 of file CarlaActor.h.
References ActorTypeMismatch.
Referenced by FCarlaServer::FPimpl::BindActions().
WakeActorUp()
void FCarlaActor::WakeActorUp (UCarlaEpisode * CarlaEpisode)
Definition at line 165 of file CarlaActor.cpp.
References carla::rpc::Active, ActorData, GetActorId(), Info, State, and TheActor.
Referenced by FActorRegistry::WakeActorUp().
Friends And Related Symbol Documentation
FActorRegistry
friend class FActorRegistry friend
Definition at line 450 of file CarlaActor.h.
Member Data Documentation
ActorData
TSharedPtr<FActorData> FCarlaActor::ActorData = nullptr protected
Definition at line 470 of file CarlaActor.h.
Referenced by FVehicleActor::ApplyAckermannControllerSettings(), FVehicleActor::ApplyAckermannControlToVehicle(), FVehicleActor::ApplyControlToVehicle(), FWalkerActor::ApplyControlToWalker(), FVehicleActor::ApplyPhysicsControl(), FOtherActor::FOtherActor(), FSensorActor::FSensorActor(), FTrafficLightActor::FTrafficLightActor(), FTrafficSignActor::FTrafficSignActor(), FVehicleActor::FVehicleActor(), FWalkerActor::FWalkerActor(), FVehicleActor::GetAckermannControllerSettings(), GetActorAngularVelocity(), GetActorData(), GetActorData(), GetActorGlobalLocation(), GetActorGlobalTransform(), GetActorLocalLocation(), GetActorLocalTransform(), GetActorVelocity(), FVehicleActor::GetFailureState(), FVehicleActor::GetPhysicsControl(), FTrafficLightActor::GetTrafficLightController(), FTrafficLightActor::GetTrafficLightState(), FVehicleActor::GetVehicleAckermannControl(), FVehicleActor::GetVehicleControl(), FVehicleActor::GetVehicleLightState(), PutActorToSleep(), SetActorGlobalLocation(), SetActorGlobalTransform(), SetActorLocalLocation(), SetActorLocalTransform(), SetActorSimulatePhysics(), FVehicleActor::SetActorSimulatePhysics(), FWalkerActor::SetActorSimulatePhysics(), SetActorTargetAngularVelocity(), SetActorTargetVelocity(), FTrafficLightActor::SetTrafficLightState(), FVehicleActor::SetVehicleLightState(), and WakeActorUp().
Attachment
carla::rpc::AttachmentType FCarlaActor::Attachment = carla::rpc::AttachmentType::INVALID private
Definition at line 462 of file CarlaActor.h.
Referenced by GetAttachmentType(), and SetAttachmentType().
Children
TArray<IdType> FCarlaActor::Children private
Definition at line 464 of file CarlaActor.h.
Referenced by AddChildren(), GetChildren(), and RemoveChildren().
Id
IdType FCarlaActor::Id = 0u private
Definition at line 456 of file CarlaActor.h.
Referenced by GetActorId().
Info
TSharedPtr<const FActorInfo> FCarlaActor::Info = nullptr private
Definition at line 454 of file CarlaActor.h.
Referenced by ConstructCarlaActor(), GetActorInfo(), and WakeActorUp().
ParentId
IdType FCarlaActor::ParentId = 0u private
Definition at line 458 of file CarlaActor.h.
Referenced by GetParent(), and SetParent().
State
carla::rpc::ActorState FCarlaActor::State = carla::rpc::ActorState::Invalid private
Definition at line 460 of file CarlaActor.h.
Referenced by GetActorState(), IsActive(), IsAlive(), IsDormant(), IsInValid(), IsPendingKill(), PutActorToSleep(), SetActorState(), FTrafficLightActor::SetTrafficLightState(), and WakeActorUp().
TheActor
AActor* FCarlaActor::TheActor = nullptr private
Definition at line 452 of file CarlaActor.h.
Referenced by FActorRegistry::Deregister(), GetActor(), GetActor(), PutActorToSleep(), FActorRegistry::Register(), and WakeActorUp().
Type
ActorType FCarlaActor::Type = ActorType::INVALID protected
Definition at line 468 of file CarlaActor.h.
Referenced by GetActorType().
World
UWorld* FCarlaActor::World = nullptr protected
Definition at line 472 of file CarlaActor.h.
Referenced by ConstructCarlaActor(), GetActorGlobalLocation(), GetActorGlobalTransform(), GetActorLocalLocation(), GetActorLocalTransform(), SetActorGlobalLocation(), SetActorGlobalTransform(), SetActorLocalLocation(), and SetActorLocalTransform().
The documentation for this class was generated from the following files:
CarlaActor.h
CarlaActor.cpp