CARLA: geometry_msgs::msg::Vector3 Class Reference
geometry_msgs::msg::Vector3 Class Reference
This class represents the structure Vector3 defined by the user in the IDL file.
#include <Vector3.h>
Public Member Functions
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const Vector3 &x) const
Comparison operator.
eProsima_user_DllExport Vector3 & operator= (const Vector3 &x)
Copy assignment.
eProsima_user_DllExport Vector3 & operator= (Vector3 &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Vector3 &x) const
Comparison operator.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport Vector3 ()
Default constructor.
eProsima_user_DllExport Vector3 (const Vector3 &x)
Copy constructor.
eProsima_user_DllExport Vector3 (Vector3 &&x) noexcept
Move constructor.
eProsima_user_DllExport double & x ()
This function returns a reference to member x.
eProsima_user_DllExport double x () const
This function returns the value of member x.
eProsima_user_DllExport void x (double _x)
This function sets a value in member x.
eProsima_user_DllExport double & y ()
This function returns a reference to member y.
eProsima_user_DllExport double y () const
This function returns the value of member y.
eProsima_user_DllExport void y (double _y)
This function sets a value in member y.
eProsima_user_DllExport double & z ()
This function returns a reference to member z.
eProsima_user_DllExport double z () const
This function returns the value of member z.
eProsima_user_DllExport void z (double _z)
This function sets a value in member z.
eProsima_user_DllExport ~Vector3 ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::Vector3 &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
double m_x
double m_y
double m_z
Detailed Description
This class represents the structure Vector3 defined by the user in the IDL file.
Definition at line 71 of file Vector3.h.
Constructor & Destructor Documentation
Vector3() [1/3]
geometry_msgs::msg::Vector3::Vector3 ()
Default constructor.
Definition at line 40 of file Vector3.cpp.
References m_x, m_y, and m_z.
~Vector3()
geometry_msgs::msg::Vector3::~Vector3 ()
Default destructor.
Definition at line 50 of file Vector3.cpp.
Vector3() [2/3]
geometry_msgs::msg::Vector3::Vector3 (const Vector3 & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::Vector3 that will be copied.
Definition at line 54 of file Vector3.cpp.
References m_x, m_y, and m_z.
Vector3() [3/3]
geometry_msgs::msg::Vector3::Vector3 (Vector3 && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::Vector3 that will be copied.
Definition at line 62 of file Vector3.cpp.
Member Function Documentation
deserialize()
void geometry_msgs::msg::Vector3::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 131 of file Vector3.cpp.
Referenced by geometry_msgs::msg::Vector3PubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::Vector3::getCdrSerializedSize (const geometry_msgs::msg::Vector3 & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 110 of file Vector3.cpp.
Referenced by carla_msgs::msg::CarlaCollisionEvent::getCdrSerializedSize(), geometry_msgs::msg::Transform::getCdrSerializedSize(), geometry_msgs::msg::Twist::getCdrSerializedSize(), sensor_msgs::msg::Imu::getCdrSerializedSize(), and geometry_msgs::msg::Vector3PubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::Vector3::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 223 of file Vector3.cpp.
References geometry_msgs_msg_Vector3_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::Vector3PubSubType::getKey(), and geometry_msgs::msg::Vector3PubSubType::Vector3PubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::Vector3::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 103 of file Vector3.cpp.
References geometry_msgs_msg_Vector3_max_cdr_typesize.
Referenced by geometry_msgs::msg::Vector3PubSubType::Vector3PubSubType().
isKeyDefined()
bool geometry_msgs::msg::Vector3::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 230 of file Vector3.cpp.
Referenced by geometry_msgs::msg::Vector3PubSubType::Vector3PubSubType().
operator!=()
bool geometry_msgs::msg::Vector3::operator!= (const Vector3 & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Vector3 object to compare.
Definition at line 97 of file Vector3.cpp.
operator=() [1/2]
geometry_msgs::msg::Vector3 & geometry_msgs::msg::Vector3::operator= (const Vector3 & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::Vector3 that will be copied.
Definition at line 70 of file Vector3.cpp.
References m_x, m_y, and m_z.
operator=() [2/2]
geometry_msgs::msg::Vector3 & geometry_msgs::msg::Vector3::operator= (Vector3 && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::Vector3 that will be copied.
Definition at line 81 of file Vector3.cpp.
References m_x.
operator==()
bool geometry_msgs::msg::Vector3::operator== (const Vector3 & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Vector3 object to compare.
Definition at line 91 of file Vector3.cpp.
References m_x, m_y, and m_z.
serialize()
void geometry_msgs::msg::Vector3::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 123 of file Vector3.cpp.
Referenced by geometry_msgs::msg::Vector3PubSubType::serialize().
serializeKey()
void geometry_msgs::msg::Vector3::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 235 of file Vector3.cpp.
Referenced by geometry_msgs::msg::Vector3PubSubType::getKey().
x() [1/3]
double & geometry_msgs::msg::Vector3::x ()
This function returns a reference to member x.
Returns
Reference to member x
Definition at line 162 of file Vector3.cpp.
x() [2/3]
double geometry_msgs::msg::Vector3::x () const
This function returns the value of member x.
Returns
Value of member x
Definition at line 153 of file Vector3.cpp.
x() [3/3]
void geometry_msgs::msg::Vector3::x (double _x)
This function sets a value in member x.
Parameters
_x New value for member x
Definition at line 143 of file Vector3.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData(), and carla::ros2::CarlaCollisionPublisher::SetData().
y() [1/3]
double & geometry_msgs::msg::Vector3::y ()
This function returns a reference to member y.
Returns
Reference to member y
Definition at line 190 of file Vector3.cpp.
y() [2/3]
double geometry_msgs::msg::Vector3::y () const
This function returns the value of member y.
Returns
Value of member y
Definition at line 181 of file Vector3.cpp.
y() [3/3]
void geometry_msgs::msg::Vector3::y (double _y)
This function sets a value in member y.
Parameters
_y New value for member y
Definition at line 171 of file Vector3.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData(), and carla::ros2::CarlaCollisionPublisher::SetData().
z() [1/3]
double & geometry_msgs::msg::Vector3::z ()
This function returns a reference to member z.
Returns
Reference to member z
Definition at line 218 of file Vector3.cpp.
z() [2/3]
double geometry_msgs::msg::Vector3::z () const
This function returns the value of member z.
Returns
Value of member z
Definition at line 209 of file Vector3.cpp.
z() [3/3]
void geometry_msgs::msg::Vector3::z (double _z)
This function sets a value in member z.
Parameters
_z New value for member z
Definition at line 199 of file Vector3.cpp.
Referenced by carla::ros2::CarlaIMUPublisher::SetData(), and carla::ros2::CarlaCollisionPublisher::SetData().
Member Data Documentation
m_x
double geometry_msgs::msg::Vector3::m_x private
Definition at line 239 of file Vector3.h.
Referenced by operator=(), operator=(), operator==(), Vector3(), and Vector3().
m_y
double geometry_msgs::msg::Vector3::m_y private
Definition at line 240 of file Vector3.h.
Referenced by operator=(), operator==(), Vector3(), and Vector3().
m_z
double geometry_msgs::msg::Vector3::m_z private
Definition at line 241 of file Vector3.h.
Referenced by operator=(), operator==(), Vector3(), and Vector3().
The documentation for this class was generated from the following files:
Vector3.h
Vector3.cpp