CARLA: URayTracer Class Reference
URayTracer Class Reference
#include <RayTracer.h>
Static Public Member Functions
static std::vector< carla::rpc::LabelledPoint > CastRay (FVector StartLocation, FVector EndLocation, UWorld *World)
static std::pair< bool, carla::rpc::LabelledPoint > ProjectPoint (FVector StartLocation, FVector Direction, float MaxDistance, UWorld *World)
Detailed Description
Definition at line 24 of file RayTracer.h.
Member Function Documentation
CastRay()
std::vector< crp::LabelledPoint > URayTracer::CastRay (FVector StartLocation, FVector EndLocation, UWorld * World) static
Definition at line 15 of file RayTracer.cpp.
References UCarlaStatics::GetGameMode(), ACarlaGameModeBase::GetLMManager(), ATagger::GetTagOfTaggedComponent(), and ALargeMapManager::LocalToGlobalLocation().
Referenced by FCarlaServer::FPimpl::BindActions().
ProjectPoint()
std::pair< bool, crp::LabelledPoint > URayTracer::ProjectPoint (FVector StartLocation, FVector Direction, float MaxDistance, UWorld * World) static
Definition at line 46 of file RayTracer.cpp.
References UCarlaStatics::GetGameMode(), ACarlaGameModeBase::GetLMManager(), ATagger::GetTagOfTaggedComponent(), and ALargeMapManager::LocalToGlobalLocation().
Referenced by FCarlaServer::FPimpl::BindActions().
The documentation for this class was generated from the following files:
RayTracer.h
RayTracer.cpp