CARLA: carla::geom Namespace Reference
carla::geom Namespace Reference
Namespaces
namespace deformation
Classes
class BoundingBox
class CubicPolynomial
Describes a Cubic Polynomial so: f(x) = a + bx + cx^2 + dx^3.
class GeoLocation
class Location
class Math
class Mesh
Mesh data container, validator and exporter.
class MeshFactory
Mesh helper generator.
struct MeshMaterial
Material that references the vertex index start and end of a mesh where it is affecting.
class PointCloudRtree
Rtree class working with 3D point clouds.
class Rotation
class SegmentCloudRtree
Rtree class working with 3D segment clouds.
class Simplification
class Transform
class Vector2D
class Vector3D
class Vector3DInt
struct VertexInfo
struct VertexNeighbors
struct VertexWeight
Functions
static VertexWeight ComputeVertexWeight (const MeshFactory::RoadParameters &road_param, const VertexInfo &vertex_info, const VertexInfo &neighbor_info)
std::vector< VertexNeighbors > GetVertexNeighborhoodAndWeights (const MeshFactory::RoadParameters &road_param, std::vector< std::unique_ptr< Mesh > > &lane_meshes)
static void LatLonAddMeters (double lat_start, double lon_start, double dx, double dy, double &lat_end, double &lon_end)
Adds meters dx/dy to given lat/lon and returns new lat/lon.
template<class float_type >
static void LatLonToMercator (double lat, double lon, double scale, float_type &mx, float_type &my)
Converts lat/lon/scale to mx/my (mx/my in meters if correct scale is given).
static double LatToScale (double lat)
Convert latitude to scale, which is needed by mercator transformations.
static void MercatorToLatLon (double mx, double my, double scale, double &lat, double &lon)
Converts mx/my/scale to lat/lon (mx/my in meters if correct scale is given).
Mesh operator+ (const Mesh &lhs, const Mesh &rhs)
std::ostream & operator<< (std::ostream &out, const Vector3D &vector3D)
Variables
static constexpr double EARTH_RADIUS_EQUA = 6378137.0
Earth radius at equator [m].
static constexpr double EPSILON = 10.0 * std::numeric_limits<double>::epsilon()
We use this epsilon to shift the waypoints away from the edges of the lane sections to avoid floating point precision errors.
static constexpr double MESH_EPSILON = 50.0 * std::numeric_limits<double>::epsilon()
Function Documentation
ComputeVertexWeight()
static VertexWeight carla::geom::ComputeVertexWeight (const MeshFactory::RoadParameters & road_param, const VertexInfo & vertex_info, const VertexInfo & neighbor_info) static
Definition at line 1025 of file MeshFactory.cpp.
References carla::geom::Math::Distance(), carla::geom::VertexInfo::is_static, carla::geom::MeshFactory::RoadParameters::lane_ends_multiplier, carla::geom::VertexInfo::lane_mesh_idx, carla::geom::MeshFactory::RoadParameters::max_weight_distance, carla::geom::MeshFactory::RoadParameters::same_lane_weight_multiplier, and carla::geom::VertexInfo::vertex.
Referenced by GetVertexNeighborhoodAndWeights().
GetVertexNeighborhoodAndWeights()
std::vector< VertexNeighbors > carla::geom::GetVertexNeighborhoodAndWeights (const MeshFactory::RoadParameters & road_param, std::vector< std::unique_ptr< Mesh > > & lane_meshes)
Definition at line 1051 of file MeshFactory.cpp.
References ComputeVertexWeight(), carla::geom::VertexNeighbors::neighbors, and carla::geom::VertexNeighbors::vertex.
Referenced by carla::geom::MeshFactory::MergeAndSmooth().
LatLonAddMeters()
static void carla::geom::LatLonAddMeters (double lat_start, double lon_start, double dx, double dy, double & lat_end, double & lon_end) static
Adds meters dx/dy to given lat/lon and returns new lat/lon.
Definition at line 51 of file GeoLocation.cpp.
References LatLonToMercator(), LatToScale(), and MercatorToLatLon().
Referenced by carla::geom::GeoLocation::Transform().
LatLonToMercator()
template<class float_type > static void carla::geom::LatLonToMercator (double lat, double lon, double scale, float_type & mx, float_type & my) static
Converts lat/lon/scale to mx/my (mx/my in meters if correct scale is given).
Definition at line 38 of file GeoLocation.cpp.
References EARTH_RADIUS_EQUA, and carla::geom::Math::ToRadians().
Referenced by LatLonAddMeters().
LatToScale()
static double carla::geom::LatToScale (double lat) static
Convert latitude to scale, which is needed by mercator transformations.
Parameters
lat latitude in degrees (DEG)
Returns
scale factor
Note
when converting from lat/lon -> mercator and back again, or vice versa, use the same scale in both transformations!
Definition at line 31 of file GeoLocation.cpp.
References carla::geom::Math::ToRadians().
Referenced by LatLonAddMeters().
MercatorToLatLon()
static void carla::geom::MercatorToLatLon (double mx, double my, double scale, double & lat, double & lon) static
Converts mx/my/scale to lat/lon (mx/my in meters if correct scale is given).
Definition at line 45 of file GeoLocation.cpp.
References EARTH_RADIUS_EQUA.
Referenced by LatLonAddMeters().
operator+()
Mesh carla::geom::operator+ (const Mesh & lhs, const Mesh & rhs)
Definition at line 385 of file Mesh.cpp.
operator<<()
std::ostream & carla::geom::operator<< (std::ostream & out, const Vector3D & vector3D)
Definition at line 18 of file test_geom.cpp.
References carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
Variable Documentation
EARTH_RADIUS_EQUA
constexpr double carla::geom::EARTH_RADIUS_EQUA = 6378137.0 static constexpr
Earth radius at equator [m].
Definition at line 23 of file GeoLocation.cpp.
Referenced by LatLonToMercator(), and MercatorToLatLon().
EPSILON
constexpr double carla::geom::EPSILON = 10.0 * std::numeric_limits<double>::epsilon() static constexpr
We use this epsilon to shift the waypoints away from the edges of the lane sections to avoid floating point precision errors.
Definition at line 31 of file MeshFactory.cpp.
Referenced by carla::geom::MeshFactory::Generate(), carla::geom::MeshFactory::GenerateOrderedWithMaxLen(), carla::geom::MeshFactory::GenerateSidewalk(), carla::geom::MeshFactory::GenerateSidewalk(), carla::geom::MeshFactory::GenerateTesselated(), carla::geom::MeshFactory::GenerateTesselated(), carla::geom::MeshFactory::GenerateWalls(), carla::geom::MeshFactory::GenerateWallsWithMaxLen(), and carla::geom::MeshFactory::GenerateWithMaxLen().
MESH_EPSILON
constexpr double carla::geom::MESH_EPSILON = 50.0 * std::numeric_limits<double>::epsilon() static constexpr
Definition at line 32 of file MeshFactory.cpp.
Referenced by carla::geom::MeshFactory::Generate(), carla::geom::MeshFactory::GenerateLeftWall(), carla::geom::MeshFactory::GenerateRightWall(), carla::geom::MeshFactory::GenerateSidewalk(), and carla::geom::MeshFactory::GenerateTesselated().