CARLA: pugi::xml_text Class Reference
pugi::xml_text Class Reference
#include <pugixml.hpp>
Public Member Functions
bool as_bool (bool def=false) const
double as_double (double def=0) const
float as_float (float def=0) const
int as_int (int def=0) const
const char_t * as_string (const char_t *def=PUGIXML_TEXT("")) const
unsigned int as_uint (unsigned int def=0) const
xml_node data () const
bool empty () const
const char_t * get () const
operator unspecified_bool_type () const
bool operator! () const
xml_text & operator= (bool rhs)
xml_text & operator= (const char_t *rhs)
xml_text & operator= (double rhs)
xml_text & operator= (float rhs)
xml_text & operator= (int rhs)
xml_text & operator= (long rhs)
xml_text & operator= (unsigned int rhs)
xml_text & operator= (unsigned long rhs)
bool set (bool rhs)
bool set (const char_t *rhs)
bool set (double rhs)
bool set (float rhs)
bool set (int rhs)
bool set (long rhs)
bool set (unsigned int rhs)
bool set (unsigned long rhs)
xml_text ()
Private Types
typedef void(* unspecified_bool_type) (xml_text ***)
Private Member Functions
xml_node_struct * _data () const
xml_node_struct * _data_new ()
xml_text (xml_node_struct *root)
Private Attributes
xml_node_struct * _root
Friends
class xml_node
Detailed Description
Definition at line 705 of file pugixml.hpp.
Member Typedef Documentation
unspecified_bool_type
typedef void(* pugi::xml_text::unspecified_bool_type) (xml_text ***) private
Definition at line 711 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_text() [1/2]
PUGI__FN pugi::xml_text::xml_text (xml_node_struct * root) explicit private
Definition at line 6345 of file pugixml.cpp.
xml_text() [2/2]
PUGI__FN pugi::xml_text::xml_text ()
Definition at line 6372 of file pugixml.cpp.
Member Function Documentation
_data()
PUGI__FN xml_node_struct * pugi::xml_text::_data () const private
Definition at line 6349 of file pugixml.cpp.
References _root, pugi::xml_node_struct::first_child, pugi::node_element, PUGI__NODETYPE, and pugi::xml_node_struct::value.
Referenced by _data_new(), as_bool(), as_double(), as_float(), as_int(), as_string(), as_uint(), data(), empty(), get(), operator unspecified_bool_type(), and operator!().
_data_new()
PUGI__FN xml_node_struct * pugi::xml_text::_data_new () private
Definition at line 6364 of file pugixml.cpp.
References _data(), _root, pugi::node_pcdata, and xml_node.
Referenced by set(), set(), set(), set(), set(), set(), set(), and set().
as_bool()
PUGI__FN bool pugi::xml_text::as_bool (bool def = false) const
Definition at line 6437 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
as_double()
PUGI__FN double pugi::xml_text::as_double (double def = 0) const
Definition at line 6423 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
as_float()
PUGI__FN float pugi::xml_text::as_float (float def = 0) const
Definition at line 6430 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
as_int()
PUGI__FN int pugi::xml_text::as_int (int def = 0) const
Definition at line 6409 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
as_string()
PUGI__FN const char_t * pugi::xml_text::as_string (const char_t * def = PUGIXML_TEXT("")) const
Definition at line 6402 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
as_uint()
PUGI__FN unsigned int pugi::xml_text::as_uint (unsigned int def = 0) const
Definition at line 6416 of file pugixml.cpp.
References _data(), and pugi::xml_node_struct::value.
data()
PUGI__FN xml_node pugi::xml_text::data () const
Definition at line 6594 of file pugixml.cpp.
References _data(), and xml_node.
empty()
PUGI__FN bool pugi::xml_text::empty () const
Definition at line 6390 of file pugixml.cpp.
References _data().
get()
PUGI__FN const char_t * pugi::xml_text::get () const
Definition at line 6395 of file pugixml.cpp.
References _data(), PUGIXML_TEXT, and pugi::xml_node_struct::value.
operator unspecified_bool_type()
PUGI__FN pugi::xml_text::operator xml_text::unspecified_bool_type () const
Definition at line 6380 of file pugixml.cpp.
References _data(), and pugi::unspecified_bool_xml_text().
operator!()
PUGI__FN bool pugi::xml_text::operator! () const
Definition at line 6385 of file pugixml.cpp.
References _data().
operator=() [1/8]
PUGI__FN xml_text & pugi::xml_text::operator= (bool rhs)
Definition at line 6574 of file pugixml.cpp.
References set().
operator=() [2/8]
PUGI__FN xml_text & pugi::xml_text::operator= (const char_t * rhs)
Definition at line 6532 of file pugixml.cpp.
References set().
operator=() [3/8]
PUGI__FN xml_text & pugi::xml_text::operator= (double rhs)
Definition at line 6562 of file pugixml.cpp.
References set().
operator=() [4/8]
PUGI__FN xml_text & pugi::xml_text::operator= (float rhs)
Definition at line 6568 of file pugixml.cpp.
References set().
operator=() [5/8]
PUGI__FN xml_text & pugi::xml_text::operator= (int rhs)
Definition at line 6538 of file pugixml.cpp.
References set().
operator=() [6/8]
PUGI__FN xml_text & pugi::xml_text::operator= (long rhs)
Definition at line 6550 of file pugixml.cpp.
References set().
operator=() [7/8]
PUGI__FN xml_text & pugi::xml_text::operator= (unsigned int rhs)
Definition at line 6544 of file pugixml.cpp.
References set().
operator=() [8/8]
PUGI__FN xml_text & pugi::xml_text::operator= (unsigned long rhs)
Definition at line 6556 of file pugixml.cpp.
References set().
set() [1/8]
PUGI__FN bool pugi::xml_text::set (bool rhs)
Definition at line 6509 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
set() [2/8]
PUGI__FN bool pugi::xml_text::set (const char_t * rhs)
Definition at line 6460 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
Referenced by operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator=().
set() [3/8]
PUGI__FN bool pugi::xml_text::set (double rhs)
Definition at line 6502 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
set() [4/8]
PUGI__FN bool pugi::xml_text::set (float rhs)
Definition at line 6495 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
set() [5/8]
PUGI__FN bool pugi::xml_text::set (int rhs)
Definition at line 6467 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
set() [6/8]
PUGI__FN bool pugi::xml_text::set (long rhs)
Definition at line 6481 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
set() [7/8]
PUGI__FN bool pugi::xml_text::set (unsigned int rhs)
Definition at line 6474 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
set() [8/8]
PUGI__FN bool pugi::xml_text::set (unsigned long rhs)
Definition at line 6488 of file pugixml.cpp.
References _data_new(), pugi::xml_node_struct::header, and pugi::xml_node_struct::value.
Friends And Related Symbol Documentation
xml_node
friend class xml_node friend
Definition at line 707 of file pugixml.hpp.
Referenced by _data_new(), and data().
Member Data Documentation
_root
xml_node_struct* pugi::xml_text::_root private
Definition at line 709 of file pugixml.hpp.
Referenced by _data(), and _data_new().
The documentation for this class was generated from the following files:
pugixml.hpp
pugixml.cpp