CARLA: CarlaRecorderStates Class Reference
CarlaRecorderStates Class Reference
#include <CarlaRecorderState.h>
Public Member Functions
void Add (const CarlaRecorderStateTrafficLight &State)
void Clear (void)
const std::vector< CarlaRecorderStateTrafficLight > & GetStates ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderStateTrafficLight > StatesTrafficLights
Detailed Description
Definition at line 28 of file CarlaRecorderState.h.
Member Function Documentation
Add()
void CarlaRecorderStates::Add (const CarlaRecorderStateTrafficLight & State)
Definition at line 34 of file CarlaRecorderState.cpp.
References State, and StatesTrafficLights.
Referenced by FFrameData::AddState(), ACarlaRecorder::AddState(), and Read().
Clear()
void CarlaRecorderStates::Clear (void)
Definition at line 29 of file CarlaRecorderState.cpp.
References StatesTrafficLights.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetStates()
const std::vector< CarlaRecorderStateTrafficLight > & CarlaRecorderStates::GetStates ()
Definition at line 72 of file CarlaRecorderState.cpp.
References StatesTrafficLights.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderStates::Read (std::istream & InFile)
Definition at line 58 of file CarlaRecorderState.cpp.
References Add(), and CarlaRecorderStateTrafficLight::Read().
Referenced by FFrameData::Read().
Write()
void CarlaRecorderStates::Write (std::ostream & OutFile)
Definition at line 39 of file CarlaRecorderState.cpp.
References State, and StatesTrafficLights.
Referenced by ACarlaRecorder::Write(), and FFrameData::Write().
Member Data Documentation
StatesTrafficLights
std::vector<CarlaRecorderStateTrafficLight> CarlaRecorderStates::StatesTrafficLights private
Definition at line 45 of file CarlaRecorderState.h.
Referenced by Add(), Clear(), GetStates(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderState.h
CarlaRecorderState.cpp