CARLA: AActorWithRandomEngine Class Reference
AActorWithRandomEngine Class Reference
Base class for actors containing a random engine with a fixed seed.
#include <ActorWithRandomEngine.h>
Public Member Functions
AActorWithRandomEngine (const FObjectInitializer &ObjectInitializer)
URandomEngine * GetRandomEngine ()
int32 GetSeed () const
void SetSeed (int32 InSeed)
Protected Member Functions
virtual void OnConstruction (const FTransform &Transform) override
Private Attributes
bool bGenerateRandomSeed = false
Set a random seed.
URandomEngine * RandomEngine
int32 Seed = 123456789
Seed of the pseudo-random engine.
Detailed Description
Base class for actors containing a random engine with a fixed seed.
Definition at line 17 of file ActorWithRandomEngine.h.
Constructor & Destructor Documentation
AActorWithRandomEngine()
AActorWithRandomEngine::AActorWithRandomEngine (const FObjectInitializer & ObjectInitializer)
Definition at line 12 of file ActorWithRandomEngine.cpp.
References RandomEngine.
Member Function Documentation
GetRandomEngine()
URandomEngine * AActorWithRandomEngine::GetRandomEngine () inline
Definition at line 36 of file ActorWithRandomEngine.h.
GetSeed()
int32 AActorWithRandomEngine::GetSeed () const inline
Definition at line 42 of file ActorWithRandomEngine.h.
References URandomEngine::Seed().
OnConstruction()
void AActorWithRandomEngine::OnConstruction (const FTransform & Transform) override protected virtual
Definition at line 18 of file ActorWithRandomEngine.cpp.
References RandomEngine, Seed, and URandomEngine::Seed().
SetSeed()
void AActorWithRandomEngine::SetSeed (int32 InSeed)
Definition at line 40 of file ActorWithRandomEngine.cpp.
References RandomEngine, Seed, and URandomEngine::Seed().
Member Data Documentation
bGenerateRandomSeed
bool AActorWithRandomEngine::bGenerateRandomSeed = false private
Set a random seed.
Definition at line 54 of file ActorWithRandomEngine.h.
RandomEngine
URandomEngine* AActorWithRandomEngine::RandomEngine private
Definition at line 61 of file ActorWithRandomEngine.h.
Referenced by AActorWithRandomEngine(), OnConstruction(), and SetSeed().
Seed
int32 AActorWithRandomEngine::Seed = 123456789 private
Seed of the pseudo-random engine.
Definition at line 58 of file ActorWithRandomEngine.h.
Referenced by OnConstruction(), and SetSeed().
The documentation for this class was generated from the following files:
ActorWithRandomEngine.h
ActorWithRandomEngine.cpp