CARLA: CarlaRecorderCollisions Class Reference
CarlaRecorderCollisions Class Reference
#include <CarlaRecorderCollision.h>
Public Member Functions
void Add (const CarlaRecorderCollision &Collision)
void Clear (void)
void Write (std::ostream &OutFile)
Private Attributes
std::unordered_set< CarlaRecorderCollision > Collisions
Detailed Description
Definition at line 45 of file CarlaRecorderCollision.h.
Member Function Documentation
Add()
void CarlaRecorderCollisions::Add (const CarlaRecorderCollision & Collision)
Definition at line 45 of file CarlaRecorderCollision.cpp.
References Collision, and Collisions.
Referenced by FFrameData::AddCollision(), and ACarlaRecorder::AddCollision().
Clear()
void CarlaRecorderCollisions::Clear (void)
Definition at line 40 of file CarlaRecorderCollision.cpp.
References Collisions.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
Write()
void CarlaRecorderCollisions::Write (std::ostream & OutFile)
Definition at line 50 of file CarlaRecorderCollision.cpp.
References Collision, and Collisions.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
Collisions
std::unordered_set<CarlaRecorderCollision> CarlaRecorderCollisions::Collisions private
Definition at line 53 of file CarlaRecorderCollision.h.
Referenced by Add(), Clear(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderCollision.h
CarlaRecorderCollision.cpp