CARLA: carla::sensor::data::SemanticLidarData Class Reference
carla::sensor::data::SemanticLidarData Class Reference
#include <SemanticLidarData.h>
Public Member Functions
uint32_t GetChannelCount () const
float GetHorizontalAngle () const
SemanticLidarData & operator= (SemanticLidarData &&)=default
virtual void ResetMemory (std::vector< uint32_t > points_per_channel)
SemanticLidarData (uint32_t ChannelCount=0u)
void SetHorizontalAngle (float angle)
virtual void WriteChannelCount (std::vector< uint32_t > points_per_channel)
virtual void WritePointSync (SemanticLidarDetection &detection)
virtual ~SemanticLidarData ()
Protected Types
enum Index : size_t { HorizontalAngle , ChannelCount , SIZE }
Protected Attributes
std::vector< uint32_t > _header
uint32_t _max_channel_points
Private Attributes
std::vector< SemanticLidarDetection > _ser_points
Friends
class carla::ros2::ROS2
class s11n::SemanticLidarHeaderView
class s11n::SemanticLidarSerializer
Detailed Description
Definition at line 86 of file SemanticLidarData.h.
Member Enumeration Documentation
Index
enum carla::sensor::data::SemanticLidarData::Index : size_t protected
Enumerator
HorizontalAngle
ChannelCount
SIZE
Definition at line 90 of file SemanticLidarData.h.
Constructor & Destructor Documentation
SemanticLidarData()
carla::sensor::data::SemanticLidarData::SemanticLidarData (uint32_t ChannelCount = 0u) inline explicit
Definition at line 97 of file SemanticLidarData.h.
References _header, and ChannelCount.
~SemanticLidarData()
virtual carla::sensor::data::SemanticLidarData::~SemanticLidarData () inline virtual
Definition at line 104 of file SemanticLidarData.h.
Member Function Documentation
GetChannelCount()
uint32_t carla::sensor::data::SemanticLidarData::GetChannelCount () const inline
Definition at line 114 of file SemanticLidarData.h.
References _header, and ChannelCount.
Referenced by carla::sensor::data::LidarData::ResetMemory(), ResetMemory(), and WriteChannelCount().
GetHorizontalAngle()
float carla::sensor::data::SemanticLidarData::GetHorizontalAngle () const inline
Definition at line 106 of file SemanticLidarData.h.
References _header, and HorizontalAngle.
Referenced by ARayCastSemanticLidar::SimulateLidar().
operator=()
SemanticLidarData & carla::sensor::data::SemanticLidarData::operator= (SemanticLidarData &&) default
ResetMemory()
virtual void carla::sensor::data::SemanticLidarData::ResetMemory (std::vector< uint32_t > points_per_channel) inline virtual
Reimplemented in carla::sensor::data::LidarData.
Definition at line 118 of file SemanticLidarData.h.
References _header, _ser_points, DEBUG_ASSERT, GetChannelCount(), and SIZE.
Referenced by ARayCastSemanticLidar::ComputeAndSaveDetections().
SetHorizontalAngle()
void carla::sensor::data::SemanticLidarData::SetHorizontalAngle (float angle) inline
Definition at line 110 of file SemanticLidarData.h.
References _header, and HorizontalAngle.
Referenced by ARayCastSemanticLidar::SimulateLidar().
WriteChannelCount()
virtual void carla::sensor::data::SemanticLidarData::WriteChannelCount (std::vector< uint32_t > points_per_channel) inline virtual
Definition at line 129 of file SemanticLidarData.h.
References _header, GetChannelCount(), and SIZE.
Referenced by ARayCastSemanticLidar::ComputeAndSaveDetections(), and ARayCastLidar::ComputeAndSaveDetections().
WritePointSync()
virtual void carla::sensor::data::SemanticLidarData::WritePointSync (SemanticLidarDetection & detection) inline virtual
Reimplemented in carla::sensor::data::LidarData.
Definition at line 134 of file SemanticLidarData.h.
References _ser_points.
Referenced by ARayCastSemanticLidar::ComputeAndSaveDetections().
Friends And Related Symbol Documentation
carla::ros2::ROS2
friend class carla::ros2::ROS2 friend
Definition at line 147 of file SemanticLidarData.h.
s11n::SemanticLidarHeaderView
friend class s11n::SemanticLidarHeaderView friend
Definition at line 145 of file SemanticLidarData.h.
s11n::SemanticLidarSerializer
friend class s11n::SemanticLidarSerializer friend
Definition at line 146 of file SemanticLidarData.h.
Member Data Documentation
_header
std::vector<uint32_t> carla::sensor::data::SemanticLidarData::_header protected
Definition at line 139 of file SemanticLidarData.h.
Referenced by GetChannelCount(), GetHorizontalAngle(), carla::sensor::data::LidarData::ResetMemory(), ResetMemory(), SemanticLidarData(), carla::sensor::s11n::LidarSerializer::Serialize(), carla::sensor::s11n::SemanticLidarSerializer::Serialize(), SetHorizontalAngle(), and WriteChannelCount().
_max_channel_points
uint32_t carla::sensor::data::SemanticLidarData::_max_channel_points protected
Definition at line 140 of file SemanticLidarData.h.
_ser_points
std::vector<SemanticLidarDetection> carla::sensor::data::SemanticLidarData::_ser_points private
Definition at line 143 of file SemanticLidarData.h.
Referenced by carla::ros2::ROS2::ProcessDataFromSemanticLidar(), ResetMemory(), carla::sensor::s11n::SemanticLidarSerializer::Serialize(), and WritePointSync().
The documentation for this class was generated from the following file:
SemanticLidarData.h