CARLA: carla::client::Landmark Class Reference
carla::client::Landmark Class Reference
Class containing a reference to RoadInfoSignal.
#include <Landmark.h>
Public Member Functions
std::string GetCountry () const
double GetDistance () const
double GetHeight () const
double GethOffset () const
std::string GetId () const
std::string GetName () const
road::SignalOrientation GetOrientation () const
double GetPitch () const
road::RoadId GetRoadId () const
double GetRoll () const
double GetS () const
std::string GetSubType () const
double GetT () const
std::string GetText () const
const geom::Transform & GetTransform () const
std::string GetType () const
std::string GetUnit () const
const auto & GetValidities () const
double GetValue () const
SharedPtr< Waypoint > GetWaypoint () const
double GetWidth () const
double GetZOffset () const
bool IsDynamic () const
Private Member Functions
Landmark (SharedPtr< Waypoint > waypoint, SharedPtr< const Map > parent, const road::element::RoadInfoSignal *signal, double distance_from_search=0)
Private Attributes
double _distance_from_search
SharedPtr< const Map > _parent
const road::element::RoadInfoSignal * _signal
SharedPtr< Waypoint > _waypoint
waypoint where the signal is affecting
friend Map
friend Waypoint
Detailed Description
Class containing a reference to RoadInfoSignal.
Definition at line 22 of file Landmark.h.
Constructor & Destructor Documentation
Landmark()
carla::client::Landmark::Landmark (SharedPtr< Waypoint > waypoint, SharedPtr< const Map > parent, const road::element::RoadInfoSignal * signal, double distance_from_search = 0) inline private
Definition at line 122 of file Landmark.h.
Member Function Documentation
GetCountry()
std::string carla::client::Landmark::GetCountry () const inline
Definition at line 69 of file Landmark.h.
References _signal, carla::road::Signal::GetCountry(), and carla::road::element::RoadInfoSignal::GetSignal().
GetDistance()
double carla::client::Landmark::GetDistance () const inline
Definition at line 37 of file Landmark.h.
References _distance_from_search.
GetHeight()
double carla::client::Landmark::GetHeight () const inline
Definition at line 89 of file Landmark.h.
References _signal, carla::road::Signal::GetHeight(), and carla::road::element::RoadInfoSignal::GetSignal().
GethOffset()
double carla::client::Landmark::GethOffset () const inline
Definition at line 101 of file Landmark.h.
References _signal, carla::road::Signal::GetHOffset(), and carla::road::element::RoadInfoSignal::GetSignal().
GetId()
std::string carla::client::Landmark::GetId () const inline
Definition at line 49 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetSignalId().
Referenced by carla::client::World::GetTrafficLight(), and carla::client::World::GetTrafficSign().
GetName()
std::string carla::client::Landmark::GetName () const inline
Definition at line 53 of file Landmark.h.
References _signal, carla::road::Signal::GetName(), and carla::road::element::RoadInfoSignal::GetSignal().
GetOrientation()
road::SignalOrientation carla::client::Landmark::GetOrientation () const inline
Definition at line 61 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetOrientation().
GetPitch()
double carla::client::Landmark::GetPitch () const inline
Definition at line 105 of file Landmark.h.
References _signal, carla::road::Signal::GetPitch(), and carla::road::element::RoadInfoSignal::GetSignal().
GetRoadId()
road::RoadId carla::client::Landmark::GetRoadId () const inline
Definition at line 33 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetRoadId().
GetRoll()
double carla::client::Landmark::GetRoll () const inline
Definition at line 109 of file Landmark.h.
References _signal, carla::road::Signal::GetRoll(), and carla::road::element::RoadInfoSignal::GetSignal().
GetS()
double carla::client::Landmark::GetS () const inline
Definition at line 41 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetS().
GetSubType()
std::string carla::client::Landmark::GetSubType () const inline
Definition at line 77 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetSubtype().
GetT()
double carla::client::Landmark::GetT () const inline
Definition at line 45 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetT().
GetText()
std::string carla::client::Landmark::GetText () const inline
Definition at line 97 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetText().
GetTransform()
const geom::Transform & carla::client::Landmark::GetTransform () const inline
Definition at line 29 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetTransform().
GetType()
std::string carla::client::Landmark::GetType () const inline
Definition at line 73 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetType().
GetUnit()
std::string carla::client::Landmark::GetUnit () const inline
Definition at line 85 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetUnit().
GetValidities()
const auto & carla::client::Landmark::GetValidities () const inline
Definition at line 113 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::GetValidities().
GetValue()
double carla::client::Landmark::GetValue () const inline
Definition at line 81 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetValue().
GetWaypoint()
SharedPtr< Waypoint > carla::client::Landmark::GetWaypoint () const inline
Definition at line 25 of file Landmark.h.
References _waypoint.
GetWidth()
double carla::client::Landmark::GetWidth () const inline
Definition at line 93 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetWidth().
GetZOffset()
double carla::client::Landmark::GetZOffset () const inline
Definition at line 65 of file Landmark.h.
References _signal, carla::road::element::RoadInfoSignal::GetSignal(), and carla::road::Signal::GetZOffset().
IsDynamic()
bool carla::client::Landmark::IsDynamic () const inline
Definition at line 57 of file Landmark.h.
References _signal, and carla::road::element::RoadInfoSignal::IsDynamic().
Member Data Documentation
_distance_from_search
double carla::client::Landmark::_distance_from_search private
Definition at line 139 of file Landmark.h.
Referenced by GetDistance().
_parent
SharedPtr<const Map> carla::client::Landmark::_parent private
Definition at line 135 of file Landmark.h.
_signal
const road::element::RoadInfoSignal* carla::client::Landmark::_signal private
Definition at line 137 of file Landmark.h.
Referenced by GetCountry(), GetHeight(), GethOffset(), GetId(), carla::client::Map::GetLandmarkGroup(), GetName(), GetOrientation(), GetPitch(), GetRoadId(), GetRoll(), GetS(), GetSubType(), GetT(), GetText(), GetTransform(), GetType(), GetUnit(), GetValidities(), GetValue(), GetWidth(), GetZOffset(), and IsDynamic().
_waypoint
SharedPtr<Waypoint> carla::client::Landmark::_waypoint private
waypoint where the signal is affecting
Definition at line 133 of file Landmark.h.
Referenced by GetWaypoint().
Map
friend carla::client::Landmark::Map private
Definition at line 120 of file Landmark.h.
Waypoint
friend carla::client::Landmark::Waypoint private
Definition at line 119 of file Landmark.h.
The documentation for this class was generated from the following file:
Landmark.h