CARLA: UActorBlueprintFunctionLibrary Class Reference
UActorBlueprintFunctionLibrary Class Reference
#include <ActorBlueprintFunctionLibrary.h>
Static Public Member Functions
static bool CheckActorDefinition (const FActorDefinition &ActorDefinitions)
Return whether the actor definition is valid. Prints all the errors found.
static bool CheckActorDefinitions (const TArray< FActorDefinition > &ActorDefinitions)
Return whether the list of actor definitions is valid.
static FActorDefinition MakeGenericDefinition (const FString &Category, const FString &Type, const FString &Id)
static FActorDefinition MakeGenericSensorDefinition (const FString &Type, const FString &Id)
static FActorDefinition MakeCameraDefinition (const FString &Id, bool bEnableModifyingPostProcessEffects=false)
static void MakeCameraDefinition (const FString &Id, bool bEnableModifyingPostProcessEffects, bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeNormalsCameraDefinition ()
static void MakeNormalsCameraDefinition (bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeLidarDefinition (const FString &Id)
static void MakeLidarDefinition (const FString &Id, bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeGnssDefinition ()
static void MakeGnssDefinition (bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeIMUDefinition ()
static void MakeIMUDefinition (bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeRadarDefinition ()
static void MakeRadarDefinition (bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeV2XDefinition ()
static void MakeV2XDefinition (bool &Success, FActorDefinition &Definition)
static FActorDefinition MakeCustomV2XDefinition ()
static void MakeCustomV2XDefinition (bool &Success, FActorDefinition &Definition)
static void MakeVehicleDefinition (const FVehicleParameters &Parameters, bool &Success, FActorDefinition &Definition)
static void MakeVehicleDefinitions (const TArray< FVehicleParameters > &ParameterArray, TArray< FActorDefinition > &Definitions)
static void MakePedestrianDefinition (const FPedestrianParameters &Parameters, bool &Success, FActorDefinition &Definition)
static void MakePedestrianDefinitions (const TArray< FPedestrianParameters > &ParameterArray, TArray< FActorDefinition > &Definitions)
static void MakeTriggerDefinitions (const TArray< FString > &ParameterArray, TArray< FActorDefinition > &Definitions)
static void MakeTriggerDefinition (const FString &Id, bool &Success, FActorDefinition &Definition)
static void MakePropDefinition (const FPropParameters &Parameters, bool &Success, FActorDefinition &Definition)
static void MakePropDefinitions (const TArray< FPropParameters > &ParameterArray, TArray< FActorDefinition > &Definitions)
static void MakeObstacleDetectorDefinitions (const FString &Type, const FString &Id, FActorDefinition &Definition)
static bool ActorAttributeToBool (const FActorAttribute &ActorAttribute, bool Default)
============================================================================
static int32 ActorAttributeToInt (const FActorAttribute &ActorAttribute, int32 Default)
static float ActorAttributeToFloat (const FActorAttribute &ActorAttribute, float Default)
static FString ActorAttributeToString (const FActorAttribute &ActorAttribute, const FString &Default)
static FColor ActorAttributeToColor (const FActorAttribute &ActorAttribute, const FColor &Default)
static bool RetrieveActorAttributeToBool (const FString &Id, const TMap< FString, FActorAttribute > &Attributes, bool Default)
static int32 RetrieveActorAttributeToInt (const FString &Id, const TMap< FString, FActorAttribute > &Attributes, int32 Default)
static float RetrieveActorAttributeToFloat (const FString &Id, const TMap< FString, FActorAttribute > &Attributes, float Default)
static FString RetrieveActorAttributeToString (const FString &Id, const TMap< FString, FActorAttribute > &Attributes, const FString &Default)
static FColor RetrieveActorAttributeToColor (const FString &Id, const TMap< FString, FActorAttribute > &Attributes, const FColor &Default)
static void SetCamera (const FActorDescription &Description, ASceneCaptureSensor *Camera)
static void SetCamera (const FActorDescription &Description, AShaderBasedSensor *Camera)
static void SetLidar (const FActorDescription &Description, FLidarDescription &Lidar)
static void SetGnss (const FActorDescription &Description, AGnssSensor *Gnss)
static void SetIMU (const FActorDescription &Description, AInertialMeasurementUnit *IMU)
static void SetRadar (const FActorDescription &Description, ARadar *Radar)
static void SetV2X (const FActorDescription &Description, AV2XSensor *V2X)
static void SetCustomV2X (const FActorDescription &Description, ACustomV2XSensor *V2X)
Detailed Description
Definition at line 31 of file ActorBlueprintFunctionLibrary.h.
Member Function Documentation
ActorAttributeToBool()
bool UActorBlueprintFunctionLibrary::ActorAttributeToBool (const FActorAttribute & ActorAttribute, bool Default) static
============================================================================
@}
@name Helpers to retrieve attribute values
– Helpers to retrieve attribute values ---------------------------------—
Definition at line 1724 of file ActorBlueprintFunctionLibrary.cpp.
References Bool, FActorAttribute::Id, FActorAttribute::Type, and FActorAttribute::Value.
Referenced by RetrieveActorAttributeToBool(), and SetCamera().
ActorAttributeToColor()
FColor UActorBlueprintFunctionLibrary::ActorAttributeToColor (const FActorAttribute & ActorAttribute, const FColor & Default) static
Definition at line 1772 of file ActorBlueprintFunctionLibrary.cpp.
References FActorAttribute::Id, RGBColor, FActorAttribute::Type, and FActorAttribute::Value.
Referenced by RetrieveActorAttributeToColor().
ActorAttributeToFloat()
float UActorBlueprintFunctionLibrary::ActorAttributeToFloat (const FActorAttribute & ActorAttribute, float Default) static
Definition at line 1748 of file ActorBlueprintFunctionLibrary.cpp.
References Float, FActorAttribute::Id, FActorAttribute::Type, and FActorAttribute::Value.
Referenced by RetrieveActorAttributeToFloat(), and ASensor::Set().
ActorAttributeToInt()
int32 UActorBlueprintFunctionLibrary::ActorAttributeToInt (const FActorAttribute & ActorAttribute, int32 Default) static
Definition at line 1736 of file ActorBlueprintFunctionLibrary.cpp.
References FActorAttribute::Id, Int, FActorAttribute::Type, and FActorAttribute::Value.
Referenced by RetrieveActorAttributeToInt().
ActorAttributeToString()
FString UActorBlueprintFunctionLibrary::ActorAttributeToString (const FActorAttribute & ActorAttribute, const FString & Default) static
Definition at line 1760 of file ActorBlueprintFunctionLibrary.cpp.
References FActorAttribute::Id, String, FActorAttribute::Type, and FActorAttribute::Value.
Referenced by RetrieveActorAttributeToString().
CheckActorDefinition()
bool UActorBlueprintFunctionLibrary::CheckActorDefinition (const FActorDefinition & ActorDefinition) static
Return whether the actor definition is valid. Prints all the errors found.
============================================================================
@}
@name Actor definition validators
– Actor definition validators ------------------------------------------—
Definition at line 178 of file ActorBlueprintFunctionLibrary.cpp.
References FActorDefinitionValidator::SingleIsValid().
Referenced by UActorDispatcher::Bind(), MakeCameraDefinition(), MakeCustomV2XDefinition(), MakeGnssDefinition(), MakeIMUDefinition(), MakeLidarDefinition(), MakeNormalsCameraDefinition(), MakePedestrianDefinition(), MakePropDefinition(), MakeRadarDefinition(), MakeTriggerDefinition(), MakeV2XDefinition(), and MakeVehicleDefinition().
CheckActorDefinitions()
bool UActorBlueprintFunctionLibrary::CheckActorDefinitions (const TArray< FActorDefinition > & ActorDefinitions) static
Return whether the list of actor definitions is valid.
Prints all the errors found.
Definition at line 184 of file ActorBlueprintFunctionLibrary.cpp.
References FActorDefinitionValidator::AreValid().
MakeCameraDefinition() [1/2]
void UActorBlueprintFunctionLibrary::MakeCameraDefinition (const FString & Id, bool bEnableModifyingPostProcessEffects, bool & Success, FActorDefinition & Definition) static
Definition at line 306 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForSensorRoleNames(), AddVariationsForSensor(), Bool, FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, String, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeCameraDefinition() [2/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeCameraDefinition (const FString & Id, bool bEnableModifyingPostProcessEffects = false) static
Definition at line 295 of file ActorBlueprintFunctionLibrary.cpp.
References MakeCameraDefinition(), and Success.
Referenced by ADepthCamera::GetSensorDefinition(), ADVSCamera::GetSensorDefinition(), AInstanceSegmentationCamera::GetSensorDefinition(), AOpticalFlowCamera::GetSensorDefinition(), ASceneCaptureCamera::GetSensorDefinition(), ASemanticSegmentationCamera::GetSensorDefinition(), and MakeCameraDefinition().
MakeCustomV2XDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeCustomV2XDefinition () static
Definition at line 1251 of file ActorBlueprintFunctionLibrary.cpp.
References MakeCustomV2XDefinition(), and Success.
Referenced by ACustomV2XSensor::GetSensorDefinition(), and MakeCustomV2XDefinition().
MakeCustomV2XDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeCustomV2XDefinition (bool & Success, FActorDefinition & Definition) static
Definition at line 1260 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForSensor(), Bool, FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, String, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeGenericDefinition()
FActorDefinition UActorBlueprintFunctionLibrary::MakeGenericDefinition (const FString & Category, const FString & Type, const FString & Id) static
@}
@name Helpers to create actor definitions
Definition at line 276 of file ActorBlueprintFunctionLibrary.cpp.
References FillIdAndTags().
Referenced by MakeGenericSensorDefinition().
MakeGenericSensorDefinition()
FActorDefinition UActorBlueprintFunctionLibrary::MakeGenericSensorDefinition (const FString & Type, const FString & Id) static
Definition at line 286 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForSensorRoleNames(), and MakeGenericDefinition().
Referenced by ACollisionSensor::GetSensorDefinition(), ALaneInvasionSensor::GetSensorDefinition(), ARssSensor::GetSensorDefinition(), and MakeObstacleDetectorDefinitions().
MakeGnssDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeGnssDefinition () static
Definition at line 1363 of file ActorBlueprintFunctionLibrary.cpp.
References MakeGnssDefinition(), and Success.
Referenced by AGnssSensor::GetSensorDefinition(), and MakeGnssDefinition().
MakeGnssDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeGnssDefinition (bool & Success, FActorDefinition & Definition) static
Definition at line 1372 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForSensor(), FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeIMUDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeIMUDefinition () static
Definition at line 745 of file ActorBlueprintFunctionLibrary.cpp.
References MakeIMUDefinition(), and Success.
Referenced by AInertialMeasurementUnit::GetSensorDefinition(), and MakeIMUDefinition().
MakeIMUDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeIMUDefinition (bool & Success, FActorDefinition & Definition) static
Definition at line 754 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForSensor(), FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeLidarDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeLidarDefinition (const FString & Id) static
Definition at line 900 of file ActorBlueprintFunctionLibrary.cpp.
References MakeLidarDefinition(), and Success.
Referenced by ARayCastLidar::GetSensorDefinition(), ARayCastSemanticLidar::GetSensorDefinition(), and MakeLidarDefinition().
MakeLidarDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeLidarDefinition (const FString & Id, bool & Success, FActorDefinition & Definition) static
Definition at line 910 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForSensorRoleNames(), AddVariationsForSensor(), FActorVariation::bRestrictToRecommended, CheckActorDefinition(), DEBUG_ASSERT, FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeNormalsCameraDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeNormalsCameraDefinition () static
Definition at line 659 of file ActorBlueprintFunctionLibrary.cpp.
References MakeNormalsCameraDefinition(), and Success.
Referenced by ANormalsCamera::GetSensorDefinition(), and MakeNormalsCameraDefinition().
MakeNormalsCameraDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeNormalsCameraDefinition (bool & Success, FActorDefinition & Definition) static
Definition at line 668 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForSensorRoleNames(), AddVariationsForSensor(), FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeObstacleDetectorDefinitions()
void UActorBlueprintFunctionLibrary::MakeObstacleDetectorDefinitions (const FString & Type, const FString & Id, FActorDefinition & Definition) static
Definition at line 1680 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForSensor(), Bool, FActorVariation::bRestrictToRecommended, Float, FActorVariation::Id, MakeGenericSensorDefinition(), FActorVariation::RecommendedValues, FActorVariation::Type, and FActorDefinition::Variations.
Referenced by AObstacleDetectionSensor::GetSensorDefinition().
MakePedestrianDefinition()
void UActorBlueprintFunctionLibrary::MakePedestrianDefinition (const FPedestrianParameters & Parameters, bool & Success, FActorDefinition & Definition) static
Todo
We need to validate here the params.
Definition at line 1552 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForActorRoleName(), FPedestrianParameters::Age, FActorDefinition::Attributes, Bool, FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FActorDefinition::Class, FPedestrianParameters::Class, FillIdAndTags(), Float, FPedestrianParameters::Gender, FPedestrianParameters::Generation, FActorVariation::Id, FPedestrianParameters::Id, Int, FActorVariation::RecommendedValues, FPedestrianParameters::Speed, String, Success, FActorVariation::Type, and FActorDefinition::Variations.
Referenced by MakePedestrianDefinitions().
MakePedestrianDefinitions()
void UActorBlueprintFunctionLibrary::MakePedestrianDefinitions (const TArray< FPedestrianParameters > & ParameterArray, TArray< FActorDefinition > & Definitions) static
Definition at line 1619 of file ActorBlueprintFunctionLibrary.cpp.
References FillActorDefinitionArray(), and MakePedestrianDefinition().
MakePropDefinition()
void UActorBlueprintFunctionLibrary::MakePropDefinition (const FPropParameters & Parameters, bool & Success, FActorDefinition & Definition) static
Todo
We need to validate here the params.
Definition at line 1644 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForActorRoleName(), FActorDefinition::Attributes, CheckActorDefinition(), FillIdAndTags(), FPropParameters::Name, FPropParameters::Size, String, and Success.
Referenced by MakePropDefinitions().
MakePropDefinitions()
void UActorBlueprintFunctionLibrary::MakePropDefinitions (const TArray< FPropParameters > & ParameterArray, TArray< FActorDefinition > & Definitions) static
Definition at line 1673 of file ActorBlueprintFunctionLibrary.cpp.
References FillActorDefinitionArray(), and MakePropDefinition().
MakeRadarDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeRadarDefinition () static
Definition at line 843 of file ActorBlueprintFunctionLibrary.cpp.
References MakeRadarDefinition(), and Success.
Referenced by ARadar::GetSensorDefinition(), and MakeRadarDefinition().
MakeRadarDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeRadarDefinition (bool & Success, FActorDefinition & Definition) static
Definition at line 852 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForSensor(), FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeTriggerDefinition()
void UActorBlueprintFunctionLibrary::MakeTriggerDefinition (const FString & Id, bool & Success, FActorDefinition & Definition) static
Definition at line 1633 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForTrigger(), CheckActorDefinition(), FillIdAndTags(), and Success.
Referenced by ATriggerFactory::GetDefinitions(), and MakeTriggerDefinitions().
MakeTriggerDefinitions()
void UActorBlueprintFunctionLibrary::MakeTriggerDefinitions (const TArray< FString > & ParameterArray, TArray< FActorDefinition > & Definitions) static
Definition at line 1626 of file ActorBlueprintFunctionLibrary.cpp.
References FillActorDefinitionArray(), and MakeTriggerDefinition().
MakeV2XDefinition() [1/2]
FActorDefinition UActorBlueprintFunctionLibrary::MakeV2XDefinition () static
Definition at line 1018 of file ActorBlueprintFunctionLibrary.cpp.
References MakeV2XDefinition(), and Success.
Referenced by AV2XSensor::GetSensorDefinition(), and MakeV2XDefinition().
MakeV2XDefinition() [2/2]
void UActorBlueprintFunctionLibrary::MakeV2XDefinition (bool & Success, FActorDefinition & Definition) static
Definition at line 1027 of file ActorBlueprintFunctionLibrary.cpp.
References AddVariationsForSensor(), Bool, FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FillIdAndTags(), Float, FActorVariation::Id, Int, FActorVariation::RecommendedValues, String, Success, FActorVariation::Type, and FActorDefinition::Variations.
MakeVehicleDefinition()
void UActorBlueprintFunctionLibrary::MakeVehicleDefinition (const FVehicleParameters & Parameters, bool & Success, FActorDefinition & Definition) static
Todo
We need to validate here the params.
Definition at line 1434 of file ActorBlueprintFunctionLibrary.cpp.
References AddRecommendedValuesForActorRoleName(), FActorDefinition::Attributes, FVehicleParameters::BaseType, Bool, FActorVariation::bRestrictToRecommended, CheckActorDefinition(), FActorDefinition::Class, FVehicleParameters::Class, ColorToFString(), FillIdAndTags(), FVehicleParameters::Generation, FVehicleParameters::HasDynamicDoors, FVehicleParameters::HasLights, FActorVariation::Id, Int, FVehicleParameters::Make, FVehicleParameters::Model, FVehicleParameters::NumberOfWheels, FVehicleParameters::ObjectType, FVehicleParameters::RecommendedColors, FActorVariation::RecommendedValues, RGBColor, FVehicleParameters::SpecialType, String, Success, FVehicleParameters::SupportedDrivers, FActorVariation::Type, and FActorDefinition::Variations.
Referenced by MakeVehicleDefinitions().
MakeVehicleDefinitions()
void UActorBlueprintFunctionLibrary::MakeVehicleDefinitions (const TArray< FVehicleParameters > & ParameterArray, TArray< FActorDefinition > & Definitions) static
Definition at line 1545 of file ActorBlueprintFunctionLibrary.cpp.
References FillActorDefinitionArray(), and MakeVehicleDefinition().
RetrieveActorAttributeToBool()
bool UActorBlueprintFunctionLibrary::RetrieveActorAttributeToBool (const FString & Id, const TMap< FString, FActorAttribute > & Attributes, bool Default) static
Definition at line 1814 of file ActorBlueprintFunctionLibrary.cpp.
References ActorAttributeToBool().
Referenced by ADVSCamera::Set(), AObstacleDetectionSensor::Set(), SetCustomV2X(), and SetV2X().
RetrieveActorAttributeToColor()
FColor UActorBlueprintFunctionLibrary::RetrieveActorAttributeToColor (const FString & Id, const TMap< FString, FActorAttribute > & Attributes, const FColor & Default) static
Definition at line 1854 of file ActorBlueprintFunctionLibrary.cpp.
References ActorAttributeToColor().
RetrieveActorAttributeToFloat()
float UActorBlueprintFunctionLibrary::RetrieveActorAttributeToFloat (const FString & Id, const TMap< FString, FActorAttribute > & Attributes, float Default) static
Definition at line 1834 of file ActorBlueprintFunctionLibrary.cpp.
References ActorAttributeToFloat().
Referenced by ADVSCamera::Set(), AObstacleDetectionSensor::Set(), SetCamera(), SetCamera(), SetCustomV2X(), SetGnss(), SetIMU(), SetLidar(), SetRadar(), SetV2X(), and ATriggerFactory::SpawnActor().
RetrieveActorAttributeToInt()
int32 UActorBlueprintFunctionLibrary::RetrieveActorAttributeToInt (const FString & Id, const TMap< FString, FActorAttribute > & Attributes, int32 Default) static
Definition at line 1824 of file ActorBlueprintFunctionLibrary.cpp.
References ActorAttributeToInt().
Referenced by ADVSCamera::Set(), SetCamera(), SetCustomV2X(), SetGnss(), SetIMU(), SetLidar(), SetRadar(), and SetV2X().
RetrieveActorAttributeToString()
FString UActorBlueprintFunctionLibrary::RetrieveActorAttributeToString (const FString & Id, const TMap< FString, FActorAttribute > & Attributes, const FString & Default) static
Definition at line 1844 of file ActorBlueprintFunctionLibrary.cpp.
References ActorAttributeToString().
Referenced by SetCamera(), SetCustomV2X(), and SetV2X().
SetCamera() [1/2]
void UActorBlueprintFunctionLibrary::SetCamera (const FActorDescription & Description, ASceneCaptureSensor * Camera) static
@}
@name Helpers to set Actors
Definition at line 1882 of file ActorBlueprintFunctionLibrary.cpp.
References ActorAttributeToBool(), CARLA_ABFL_CHECK_ACTOR, ASceneCaptureSensor::EnablePostProcessingEffects(), RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), RetrieveActorAttributeToString(), ASceneCaptureSensor::SetAperture(), ASceneCaptureSensor::SetBladeCount(), ASceneCaptureSensor::SetBloomIntensity(), ASceneCaptureSensor::SetChromAberrIntensity(), ASceneCaptureSensor::SetChromAberrOffset(), ASceneCaptureSensor::SetDepthBlurAmount(), ASceneCaptureSensor::SetDepthBlurRadius(), ASceneCaptureSensor::SetDepthOfFieldMinFstop(), ASceneCaptureSensor::SetExposureCalibrationConstant(), ASceneCaptureSensor::SetExposureCompensation(), ASceneCaptureSensor::SetExposureMaxBrightness(), ASceneCaptureSensor::SetExposureMethod(), ASceneCaptureSensor::SetExposureMinBrightness(), ASceneCaptureSensor::SetExposureSpeedDown(), ASceneCaptureSensor::SetExposureSpeedUp(), ASceneCaptureSensor::SetFilmBlackClip(), ASceneCaptureSensor::SetFilmShoulder(), ASceneCaptureSensor::SetFilmSlope(), ASceneCaptureSensor::SetFilmToe(), ASceneCaptureSensor::SetFilmWhiteClip(), ASceneCaptureSensor::SetFocalDistance(), ASceneCaptureSensor::SetFOVAngle(), ASceneCaptureSensor::SetImageSize(), ASceneCaptureSensor::SetISO(), ASceneCaptureSensor::SetLensFlareIntensity(), ASceneCaptureSensor::SetMotionBlurIntensity(), ASceneCaptureSensor::SetMotionBlurMaxDistortion(), ASceneCaptureSensor::SetMotionBlurMinObjectScreenSize(), ASceneCaptureSensor::SetShutterSpeed(), ASceneCaptureSensor::SetTargetGamma(), ASceneCaptureSensor::SetWhiteTemp(), ASceneCaptureSensor::SetWhiteTint(), and FActorDescription::Variations.
Referenced by ASceneCaptureSensor::Set(), and AShaderBasedSensor::Set().
SetCamera() [2/2]
void UActorBlueprintFunctionLibrary::SetCamera (const FActorDescription & Description, AShaderBasedSensor * Camera) static
Definition at line 1973 of file ActorBlueprintFunctionLibrary.cpp.
References CARLA_ABFL_CHECK_ACTOR, RetrieveActorAttributeToFloat(), AShaderBasedSensor::SetFloatShaderParameter(), and FActorDescription::Variations.
SetCustomV2X()
void UActorBlueprintFunctionLibrary::SetCustomV2X (const FActorDescription & Description, ACustomV2XSensor * V2X) static
Definition at line 2192 of file ActorBlueprintFunctionLibrary.cpp.
References CARLA_ABFL_CHECK_ACTOR, URandomEngine::GenerateRandomSeed(), Geometric, ASensor::GetRandomEngine(), Highway, RetrieveActorAttributeToBool(), RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), RetrieveActorAttributeToString(), Rural, ACustomV2XSensor::SetPathLossModel(), ACustomV2XSensor::SetPropagationParams(), ACustomV2XSensor::SetScenario(), ASensor::SetSeed(), Urban, FActorDescription::Variations, and Winner.
Referenced by ACustomV2XSensor::Set().
SetGnss()
void UActorBlueprintFunctionLibrary::SetGnss (const FActorDescription & Description, AGnssSensor * Gnss) static
Definition at line 2025 of file ActorBlueprintFunctionLibrary.cpp.
References CARLA_ABFL_CHECK_ACTOR, URandomEngine::GenerateRandomSeed(), ASensor::GetRandomEngine(), RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), AGnssSensor::SetAltitudeBias(), AGnssSensor::SetAltitudeDeviation(), AGnssSensor::SetLatitudeBias(), AGnssSensor::SetLatitudeDeviation(), AGnssSensor::SetLongitudeBias(), AGnssSensor::SetLongitudeDeviation(), ASensor::SetSeed(), and FActorDescription::Variations.
Referenced by AGnssSensor::Set().
SetIMU()
void UActorBlueprintFunctionLibrary::SetIMU (const FActorDescription & Description, AInertialMeasurementUnit * IMU) static
Definition at line 2054 of file ActorBlueprintFunctionLibrary.cpp.
References CARLA_ABFL_CHECK_ACTOR, URandomEngine::GenerateRandomSeed(), ASensor::GetRandomEngine(), RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), AInertialMeasurementUnit::SetAccelerationStandardDeviation(), AInertialMeasurementUnit::SetGyroscopeBias(), AInertialMeasurementUnit::SetGyroscopeStandardDeviation(), ASensor::SetSeed(), and FActorDescription::Variations.
Referenced by AInertialMeasurementUnit::Set().
SetLidar()
void UActorBlueprintFunctionLibrary::SetLidar (const FActorDescription & Description, FLidarDescription & Lidar) static
Definition at line 1992 of file ActorBlueprintFunctionLibrary.cpp.
References FLidarDescription::AtmospAttenRate, FLidarDescription::Channels, FLidarDescription::DropOffAtZeroIntensity, FLidarDescription::DropOffGenRate, FLidarDescription::DropOffIntensityLimit, FLidarDescription::HorizontalFov, FLidarDescription::LowerFovLimit, FLidarDescription::NoiseStdDev, FLidarDescription::PointsPerSecond, FLidarDescription::RandomSeed, FLidarDescription::Range, RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), FLidarDescription::RotationFrequency, FLidarDescription::UpperFovLimit, and FActorDescription::Variations.
Referenced by ARayCastLidar::Set(), and ARayCastSemanticLidar::Set().
SetRadar()
void UActorBlueprintFunctionLibrary::SetRadar (const FActorDescription & Description, ARadar * Radar) static
Definition at line 2085 of file ActorBlueprintFunctionLibrary.cpp.
References CARLA_ABFL_CHECK_ACTOR, RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), and FActorDescription::Variations.
Referenced by ARadar::Set().
SetV2X()
void UActorBlueprintFunctionLibrary::SetV2X (const FActorDescription & Description, AV2XSensor * V2X) static
Definition at line 2112 of file ActorBlueprintFunctionLibrary.cpp.
References CARLA_ABFL_CHECK_ACTOR, URandomEngine::GenerateRandomSeed(), Geometric, ASensor::GetRandomEngine(), Highway, RetrieveActorAttributeToBool(), RetrieveActorAttributeToFloat(), RetrieveActorAttributeToInt(), RetrieveActorAttributeToString(), Rural, AV2XSensor::SetAccelerationStandardDeviation(), AV2XSensor::SetCaServiceParams(), AV2XSensor::SetGNSSDeviation(), AV2XSensor::SetPathLossModel(), AV2XSensor::SetPropagationParams(), AV2XSensor::SetScenario(), ASensor::SetSeed(), AV2XSensor::SetVelDeviation(), AV2XSensor::SetYawrateDeviation(), Urban, FActorDescription::Variations, and Winner.
Referenced by AV2XSensor::Set().
The documentation for this class was generated from the following files:
ActorBlueprintFunctionLibrary.h
ActorBlueprintFunctionLibrary.cpp