CARLA: geometry_msgs::msg::Pose Class Reference
geometry_msgs::msg::Pose Class Reference
This class represents the structure Pose defined by the user in the IDL file.
#include <Pose.h>
Public Member Functions
eProsima_user_DllExport void deserialize (eprosima::fastcdr::Cdr &cdr)
This function deserializes an object using CDR serialization.
eProsima_user_DllExport bool operator!= (const Pose &x) const
Comparison operator.
eProsima_user_DllExport Pose & operator= (const Pose &x)
Copy assignment.
eProsima_user_DllExport Pose & operator= (Pose &&x) noexcept
Move assignment.
eProsima_user_DllExport bool operator== (const Pose &x) const
Comparison operator.
eProsima_user_DllExport geometry_msgs::msg::Quaternion & orientation ()
This function returns a reference to member orientation.
eProsima_user_DllExport const geometry_msgs::msg::Quaternion & orientation () const
This function returns a constant reference to member orientation.
eProsima_user_DllExport void orientation (const geometry_msgs::msg::Quaternion &_orientation)
This function copies the value in member orientation.
eProsima_user_DllExport void orientation (geometry_msgs::msg::Quaternion &&_orientation)
This function moves the value in member orientation.
eProsima_user_DllExport Pose ()
Default constructor.
eProsima_user_DllExport Pose (const Pose &x)
Copy constructor.
eProsima_user_DllExport Pose (Pose &&x) noexcept
Move constructor.
eProsima_user_DllExport geometry_msgs::msg::Point & position ()
This function returns a reference to member position.
eProsima_user_DllExport const geometry_msgs::msg::Point & position () const
This function returns a constant reference to member position.
eProsima_user_DllExport void position (const geometry_msgs::msg::Point &_position)
This function copies the value in member position.
eProsima_user_DllExport void position (geometry_msgs::msg::Point &&_position)
This function moves the value in member position.
eProsima_user_DllExport void serialize (eprosima::fastcdr::Cdr &cdr) const
This function serializes an object using CDR serialization.
eProsima_user_DllExport void serializeKey (eprosima::fastcdr::Cdr &cdr) const
This function serializes the key members of an object using CDR serialization.
eProsima_user_DllExport ~Pose ()
Default destructor.
Static Public Member Functions
static eProsima_user_DllExport size_t getCdrSerializedSize (const geometry_msgs::msg::Pose &data, size_t current_alignment=0)
This function returns the serialized size of a data depending on the buffer alignment.
static eProsima_user_DllExport size_t getKeyMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
static eProsima_user_DllExport size_t getMaxCdrSerializedSize (size_t current_alignment=0)
This function returns the maximum serialized size of an object depending on the buffer alignment.
static eProsima_user_DllExport bool isKeyDefined ()
This function tells you if the Key has been defined for this type.
Private Attributes
geometry_msgs::msg::Quaternion m_orientation
geometry_msgs::msg::Point m_position
Detailed Description
This class represents the structure Pose defined by the user in the IDL file.
Definition at line 73 of file Pose.h.
Constructor & Destructor Documentation
Pose() [1/3]
geometry_msgs::msg::Pose::Pose ()
Default constructor.
Definition at line 44 of file Pose.cpp.
~Pose()
geometry_msgs::msg::Pose::~Pose ()
Default destructor.
Definition at line 48 of file Pose.cpp.
Pose() [2/3]
geometry_msgs::msg::Pose::Pose (const Pose & x)
Copy constructor.
Parameters
x Reference to the object geometry_msgs::msg::Pose that will be copied.
Definition at line 52 of file Pose.cpp.
References m_orientation, and m_position.
Pose() [3/3]
geometry_msgs::msg::Pose::Pose (Pose && x) noexcept
Move constructor.
Parameters
x Reference to the object geometry_msgs::msg::Pose that will be copied.
Definition at line 59 of file Pose.cpp.
Member Function Documentation
deserialize()
void geometry_msgs::msg::Pose::deserialize (eprosima::fastcdr::Cdr & cdr)
This function deserializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 121 of file Pose.cpp.
Referenced by geometry_msgs::msg::PosePubSubType::deserialize().
getCdrSerializedSize()
size_t geometry_msgs::msg::Pose::getCdrSerializedSize (const geometry_msgs::msg::Pose & data, size_t current_alignment = 0) static
This function returns the serialized size of a data depending on the buffer alignment.
Parameters
data Data which is calculated its serialized size.
current_alignment Buffer alignment.
Returns
Serialized size.
Definition at line 103 of file Pose.cpp.
References geometry_msgs::msg::Point::getCdrSerializedSize(), geometry_msgs::msg::Quaternion::getCdrSerializedSize(), orientation(), and position().
Referenced by geometry_msgs::msg::PoseWithCovariance::getCdrSerializedSize(), and geometry_msgs::msg::PosePubSubType::getSerializedSizeProvider().
getKeyMaxCdrSerializedSize()
size_t geometry_msgs::msg::Pose::getKeyMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of the Key of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 205 of file Pose.cpp.
References geometry_msgs_msg_Pose_max_key_cdr_typesize.
Referenced by geometry_msgs::msg::PosePubSubType::getKey(), and geometry_msgs::msg::PosePubSubType::PosePubSubType().
getMaxCdrSerializedSize()
size_t geometry_msgs::msg::Pose::getMaxCdrSerializedSize (size_t current_alignment = 0) static
This function returns the maximum serialized size of an object depending on the buffer alignment.
Parameters
current_alignment Buffer alignment.
Returns
Maximum serialized size.
Definition at line 96 of file Pose.cpp.
References geometry_msgs_msg_Pose_max_cdr_typesize.
Referenced by geometry_msgs::msg::PosePubSubType::PosePubSubType().
isKeyDefined()
bool geometry_msgs::msg::Pose::isKeyDefined () static
This function tells you if the Key has been defined for this type.
Definition at line 212 of file Pose.cpp.
Referenced by geometry_msgs::msg::PosePubSubType::PosePubSubType().
operator!=()
bool geometry_msgs::msg::Pose::operator!= (const Pose & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Pose object to compare.
Definition at line 90 of file Pose.cpp.
operator=() [1/2]
geometry_msgs::msg::Pose & geometry_msgs::msg::Pose::operator= (const Pose & x)
Copy assignment.
Parameters
x Reference to the object geometry_msgs::msg::Pose that will be copied.
Definition at line 66 of file Pose.cpp.
References m_orientation, and m_position.
operator=() [2/2]
geometry_msgs::msg::Pose & geometry_msgs::msg::Pose::operator= (Pose && x) noexcept
Move assignment.
Parameters
x Reference to the object geometry_msgs::msg::Pose that will be copied.
Definition at line 75 of file Pose.cpp.
operator==()
bool geometry_msgs::msg::Pose::operator== (const Pose & x) const
Comparison operator.
Parameters
x geometry_msgs::msg::Pose object to compare.
Definition at line 84 of file Pose.cpp.
References m_orientation, and m_position.
orientation() [1/4]
geometry_msgs::msg::Quaternion & geometry_msgs::msg::Pose::orientation ()
This function returns a reference to member orientation.
Returns
Reference to member orientation
Definition at line 199 of file Pose.cpp.
orientation() [2/4]
const geometry_msgs::msg::Quaternion & geometry_msgs::msg::Pose::orientation () const
This function returns a constant reference to member orientation.
Returns
Constant reference to member orientation
Definition at line 190 of file Pose.cpp.
orientation() [3/4]
void geometry_msgs::msg::Pose::orientation (const geometry_msgs::msg::Quaternion & _orientation)
This function copies the value in member orientation.
Parameters
_orientation New value to be copied in member orientation
Definition at line 170 of file Pose.cpp.
Referenced by getCdrSerializedSize().
orientation() [4/4]
void geometry_msgs::msg::Pose::orientation (geometry_msgs::msg::Quaternion && _orientation)
This function moves the value in member orientation.
Parameters
_orientation New value to be moved in member orientation
Definition at line 180 of file Pose.cpp.
position() [1/4]
geometry_msgs::msg::Point & geometry_msgs::msg::Pose::position ()
This function returns a reference to member position.
Returns
Reference to member position
Definition at line 161 of file Pose.cpp.
position() [2/4]
const geometry_msgs::msg::Point & geometry_msgs::msg::Pose::position () const
This function returns a constant reference to member position.
Returns
Constant reference to member position
Definition at line 152 of file Pose.cpp.
position() [3/4]
void geometry_msgs::msg::Pose::position (const geometry_msgs::msg::Point & _position)
This function copies the value in member position.
Parameters
_position New value to be copied in member position
Definition at line 132 of file Pose.cpp.
Referenced by getCdrSerializedSize().
position() [4/4]
void geometry_msgs::msg::Pose::position (geometry_msgs::msg::Point && _position)
This function moves the value in member position.
Parameters
_position New value to be moved in member position
Definition at line 142 of file Pose.cpp.
serialize()
void geometry_msgs::msg::Pose::serialize (eprosima::fastcdr::Cdr & cdr) const
This function serializes an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 114 of file Pose.cpp.
Referenced by geometry_msgs::msg::PosePubSubType::serialize().
serializeKey()
void geometry_msgs::msg::Pose::serializeKey (eprosima::fastcdr::Cdr & cdr) const
This function serializes the key members of an object using CDR serialization.
Parameters
cdr CDR serialization object.
Definition at line 217 of file Pose.cpp.
Referenced by geometry_msgs::msg::PosePubSubType::getKey().
Member Data Documentation
m_orientation
geometry_msgs::msg::Quaternion geometry_msgs::msg::Pose::m_orientation private
Definition at line 236 of file Pose.h.
Referenced by operator=(), operator==(), and Pose().
m_position
geometry_msgs::msg::Point geometry_msgs::msg::Pose::m_position private
Definition at line 235 of file Pose.h.
Referenced by operator=(), operator==(), and Pose().
The documentation for this class was generated from the following files:
Pose.h
Pose.cpp