CARLA: CommonAttributes Namespace Reference
CommonAttributes Namespace Reference
Variables
static const FString DEFAULT = TEXT("/Carla/Config/Default")
static const FString DEFINITIONS = TEXT("props")
static const FString PATH = FPaths::ProjectContentDir()
Variable Documentation
DEFAULT
const FString CommonAttributes::DEFAULT = TEXT("/Carla/Config/Default") static
Definition at line 18 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), and UCarlaBlueprintRegistry::LoadPropDefinitions().
DEFINITIONS
const FString CommonAttributes::DEFINITIONS = TEXT("props") static
Definition at line 19 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), and UCarlaBlueprintRegistry::LoadPropDefinitions().
PATH
const FString CommonAttributes::PATH = FPaths::ProjectContentDir() static
Definition at line 17 of file CarlaBlueprintRegistry.cpp.
Referenced by UCarlaBlueprintRegistry::AddToCarlaBlueprintRegistry(), and UCarlaBlueprintRegistry::LoadPropDefinitions().