CARLA: carla::image::io::detail::io_resolver Struct Reference
carla::image::io::detail::io_resolver Struct Reference
#include <ImageIOConfig.h>
Static Public Member Functions
template<typename IO , typename Str >
static std::enable_if<!IO::is_supported, bool >::type match_extension (const Str &)
template<typename IO , typename Str >
static std::enable_if< IO::is_supported, bool >::type match_extension (const Str &str)
template<typename IO , typename... Args>
static std::enable_if<!IO::is_supported >::type read_image (Args &&...)
template<typename IO , typename Str , typename... Args>
static std::enable_if< IO::is_supported >::type read_image (const Str &path, Args &&... args)
template<typename IO , typename... Args>
static std::enable_if<!IO::is_supported >::type write_view (Args &&...)
template<typename IO , typename... Args>
static std::enable_if< IO::is_supported >::type write_view (std::string &path, Args &&... args)
Detailed Description
Definition at line 206 of file ImageIOConfig.h.
Member Function Documentation
match_extension() [1/2]
template<typename IO , typename Str > static std::enable_if<!IO::is_supported, bool >::type carla::image::io::detail::io_resolver::match_extension (const Str &) inline static
Definition at line 214 of file ImageIOConfig.h.
match_extension() [2/2]
template<typename IO , typename Str > static std::enable_if< IO::is_supported, bool >::type carla::image::io::detail::io_resolver::match_extension (const Str & str) inline static
Definition at line 209 of file ImageIOConfig.h.
read_image() [1/2]
template<typename IO , typename... Args> static std::enable_if<!IO::is_supported >::type carla::image::io::detail::io_resolver::read_image (Args && ...) inline static
Definition at line 225 of file ImageIOConfig.h.
References DEBUG_ASSERT.
read_image() [2/2]
template<typename IO , typename Str , typename... Args> static std::enable_if< IO::is_supported >::type carla::image::io::detail::io_resolver::read_image (const Str & path, Args &&... args) inline static
Definition at line 219 of file ImageIOConfig.h.
References carla::log_debug().
write_view() [1/2]
template<typename IO , typename... Args> static std::enable_if<!IO::is_supported >::type carla::image::io::detail::io_resolver::write_view (Args && ...) inline static
Definition at line 237 of file ImageIOConfig.h.
References DEBUG_ASSERT.
write_view() [2/2]
template<typename IO , typename... Args> static std::enable_if< IO::is_supported >::type carla::image::io::detail::io_resolver::write_view (std::string & path, Args &&... args) inline static
Definition at line 230 of file ImageIOConfig.h.
References carla::log_debug(), and carla::FileSystem::ValidateFilePath().
The documentation for this struct was generated from the following file:
ImageIOConfig.h