CARLA: carla::geom::Rotation Class Reference
carla::geom::Rotation Class Reference
#include <Rotation.h>
Public Member Functions
Vector3D GetForwardVector () const
Vector3D GetRightVector () const
Vector3D GetUpVector () const
void InverseRotateVector (Vector3D &in_point) const
MSGPACK_DEFINE_ARRAY (pitch, yaw, roll)
operator FRotator () const
bool operator!= (const Rotation &rhs) const
bool operator== (const Rotation &rhs) const
Vector3D RotateVector (const Vector3D &in_point) const
void RotateVector (Vector3D &in_point) const
Rotation ()=default
Rotation (const FRotator &rotator)
Rotation (float p, float y, float r)
Public Attributes
float pitch = 0.0f
float roll = 0.0f
float yaw = 0.0f
Detailed Description
Definition at line 22 of file Rotation.h.
Constructor & Destructor Documentation
Rotation() [1/3]
carla::geom::Rotation::Rotation () default
Rotation() [2/3]
carla::geom::Rotation::Rotation (float p, float y, float r) inline
Definition at line 43 of file Rotation.h.
Rotation() [3/3]
carla::geom::Rotation::Rotation (const FRotator & rotator) inline
Definition at line 145 of file Rotation.h.
Member Function Documentation
GetForwardVector()
Vector3D carla::geom::Rotation::GetForwardVector () const inline
Definition at line 52 of file Rotation.h.
References carla::geom::Math::GetForwardVector().
Referenced by carla::geom::Transform::GetForwardVector(), URoadMap::SetPixelAt(), TEST(), and AProceduralBuilding::UpdateTransformPositionToNextChunk().
GetRightVector()
Vector3D carla::geom::Rotation::GetRightVector () const inline
Definition at line 56 of file Rotation.h.
References carla::geom::Math::GetRightVector().
Referenced by carla::geom::Transform::GetRightVector(), and AProceduralBuilding::UpdateTransformPositionToNextSide().
GetUpVector()
Vector3D carla::geom::Rotation::GetUpVector () const inline
Definition at line 60 of file Rotation.h.
References carla::geom::Math::GetUpVector().
Referenced by ACarlaGameModeBase::DebugShowSignals(), and carla::geom::Transform::GetUpVector().
InverseRotateVector()
void carla::geom::Rotation::InverseRotateVector (Vector3D & in_point) const inline
Definition at line 98 of file Rotation.h.
References pitch, roll, carla::geom::Math::ToRadians(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, yaw, and carla::geom::Vector3D::z.
Referenced by carla::rss::RssCheck::GetSpeed(), and carla::geom::Transform::InverseTransformPoint().
MSGPACK_DEFINE_ARRAY()
carla::geom::Rotation::MSGPACK_DEFINE_ARRAY (pitch , yaw , roll)
operator FRotator()
carla::geom::Rotation::operator FRotator () const inline
Definition at line 148 of file Rotation.h.
References pitch, roll, and yaw.
operator!=()
bool carla::geom::Rotation::operator!= (const Rotation & rhs) const inline
Definition at line 135 of file Rotation.h.
operator==()
bool carla::geom::Rotation::operator== (const Rotation & rhs) const inline
Definition at line 131 of file Rotation.h.
References pitch, roll, and yaw.
RotateVector() [1/2]
Vector3D carla::geom::Rotation::RotateVector (const Vector3D & in_point) const inline
Definition at line 92 of file Rotation.h.
References RotateVector().
RotateVector() [2/2]
void carla::geom::Rotation::RotateVector (Vector3D & in_point) const inline
Definition at line 64 of file Rotation.h.
References pitch, roll, carla::geom::Math::ToRadians(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, yaw, and carla::geom::Vector3D::z.
Referenced by carla::geom::BoundingBox::GetLocalVertices(), RotateVector(), carla::geom::Transform::TransformPoint(), and carla::geom::Transform::TransformVector().
Member Data Documentation
pitch
float carla::geom::Rotation::pitch = 0.0f
Definition at line 29 of file Rotation.h.
Referenced by carla::road::Lane::ComputeTransform(), carla::geom::Math::GetForwardVector(), carla::geom::Transform::GetInverseMatrix(), carla::geom::Transform::GetMatrix(), carla::geom::Math::GetRightVector(), carla::geom::Math::GetUpVector(), InverseRotateVector(), operator FRotator(), operator==(), and RotateVector().
roll
float carla::geom::Rotation::roll = 0.0f
Definition at line 33 of file Rotation.h.
Referenced by carla::geom::Transform::GetInverseMatrix(), carla::geom::Transform::GetMatrix(), carla::geom::Math::GetRightVector(), carla::geom::Math::GetUpVector(), InverseRotateVector(), operator FRotator(), operator==(), and RotateVector().
yaw
float carla::geom::Rotation::yaw = 0.0f
Definition at line 31 of file Rotation.h.
Referenced by carla::nav::Navigation::AddOrUpdateVehicle(), carla::road::Lane::ComputeTransform(), carla::road::Map::GetAllCrosswalkZones(), carla::geom::Math::GetForwardVector(), carla::geom::Transform::GetInverseMatrix(), carla::geom::Transform::GetMatrix(), carla::geom::Math::GetRightVector(), carla::geom::Math::GetUpVector(), carla::nav::Navigation::GetWalkerTransform(), InverseRotateVector(), carla::client::LaneInvasionCallback::MakeBounds(), operator FRotator(), operator==(), and RotateVector().
The documentation for this class was generated from the following file:
Rotation.h