CARLA: carla::client::TrafficSign Class Reference
carla::client::TrafficSign Class Reference
#include <TrafficSign.h>
Public Member Functions
carla::road::SignId GetSignId () const
const geom::BoundingBox & GetTriggerVolume () const
TrafficSign (ActorInitializer init)
Public Member Functions inherited from carla::client::Actor
Actor (ActorInitializer init)
void AddAngularImpulse (const geom::Vector3D &vector)
Add angular impulse to the actor.
void AddForce (const geom::Vector3D &force)
Add force to the actor at its center of mass.
void AddForce (const geom::Vector3D &force, const geom::Vector3D &location)
Add force to the actor at certain location.
void AddImpulse (const geom::Vector3D &impulse, const geom::Vector3D &location)
Add impulse to the actor at certain location.
void AddImpulse (const geom::Vector3D &vector)
Add impulse to the actor at its center of mass.
void AddTorque (const geom::Vector3D &vector)
Add a torque to the actor.
virtual bool Destroy ()
Tell the simulator to destroy this Actor, and return whether the actor was successfully destroyed.
void DisableConstantVelocity ()
Disable the constant velocity mode.
void EnableConstantVelocity (const geom::Vector3D &vector)
Enable a constant velocity mode.
geom::Vector3D GetAcceleration () const
Return the current 3D acceleration of the actor.
rpc::ActorState GetActorState () const
geom::Vector3D GetAngularVelocity () const
Return the current 3D angular velocity of the actor.
std::vector< std::string > GetBoneNames () const
std::vector< geom::Transform > GetBoneRelativeTransforms () const
std::vector< geom::Transform > GetBoneWorldTransforms () const
std::vector< std::string > GetComponentNames () const
geom::Transform GetComponentRelativeTransform (const std::string componentName) const
geom::Transform GetComponentWorldTransform (const std::string componentName) const
geom::Location GetLocation () const
Return the current location of the actor.
std::vector< std::string > GetSocketNames () const
std::vector< geom::Transform > GetSocketRelativeTransforms () const
std::vector< geom::Transform > GetSocketWorldTransforms () const
geom::Transform GetTransform () const
Return the current transform of the actor.
geom::Vector3D GetVelocity () const
Return the current 3D velocity of the actor.
bool IsActive () const
bool IsAlive () const
bool IsDormant () const
const auto & Serialize () const
void SetActorDead ()
Set actor as dead and starts his life span.
void SetCollisions (bool enabled=true)
Enable or disable collisions on this actor.
void SetEnableGravity (bool enabled=true)
Enable or disable gravity on this actor.
void SetLocation (const geom::Location &location)
Teleport the actor to location.
void SetSimulatePhysics (bool enabled=true)
Enable or disable physics simulation on this actor.
void SetTargetAngularVelocity (const geom::Vector3D &vector)
Set the angular velocity of the actor before applying physics.
void SetTargetVelocity (const geom::Vector3D &vector)
Set the actor velocity before applying physics.
void SetTransform (const geom::Transform &transform)
Teleport and rotate the actor to transform.
virtual ~Actor ()=default
Public Member Functions inherited from carla::client::detail::ActorState
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Additional Inherited Members
Protected Member Functions inherited from carla::client::detail::ActorState
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Detailed Description
Definition at line 15 of file TrafficSign.h.
Constructor & Destructor Documentation
TrafficSign()
carla::client::TrafficSign::TrafficSign (ActorInitializer init) inline explicit
Definition at line 18 of file TrafficSign.h.
Member Function Documentation
GetSignId()
carla::road::SignId carla::client::TrafficSign::GetSignId () const
Definition at line 14 of file TrafficSign.cpp.
References carla::client::detail::ActorState::GetEpisode().
Referenced by carla::client::World::GetTrafficLight(), carla::client::World::GetTrafficLightFromOpenDRIVE(), and carla::client::World::GetTrafficSign().
GetTriggerVolume()
const geom::BoundingBox & carla::client::TrafficSign::GetTriggerVolume () const inline
Definition at line 20 of file TrafficSign.h.
Referenced by carla::client::TrafficLight::GetStopWaypoints().
The documentation for this class was generated from the following files:
TrafficSign.h
TrafficSign.cpp