CARLA: carla::road::element::GeometryPoly3 Class Reference
carla::road::element::GeometryPoly3 Class Reference final
#include <Geometry.h>
Classes
struct RtreeValue
Public Member Functions
std::pair< float, float > DistanceTo (const geom::Location &) const override
GeometryPoly3 (double start_offset, double length, double heading, const geom::Location &start_pos, double a, double b, double c, double d)
double Geta () const
double Getb () const
double Getc () const
double Getd () const
DirectedPoint PosFromDist (double dist) const override
Public Member Functions inherited from carla::road::element::Geometry
double GetHeading () const
double GetLength () const
double GetStartOffset () const
const geom::Location & GetStartPosition ()
GeometryType GetType () const
virtual ~Geometry ()=default
Private Types
using Rtree = geom::SegmentCloudRtree<RtreeValue, 1>
using TreeElement = Rtree::TreeElement
Private Member Functions
void PreComputeSpline ()
Private Attributes
double _a
double _b
double _c
double _d
geom::CubicPolynomial _poly
Rtree _rtree
Additional Inherited Members
Protected Member Functions inherited from carla::road::element::Geometry
Geometry (GeometryType type, double start_offset, double length, double heading, const geom::Location &start_pos)
Protected Attributes inherited from carla::road::element::Geometry
double _heading
double _length
geom::Location _start_position
double _start_position_offset
GeometryType _type
Detailed Description
Definition at line 196 of file Geometry.h.
Member Typedef Documentation
Rtree
using carla::road::element::GeometryPoly3::Rtree = geom::SegmentCloudRtree<RtreeValue, 1> private
Definition at line 249 of file Geometry.h.
TreeElement
using carla::road::element::GeometryPoly3::TreeElement = Rtree::TreeElement private
Definition at line 250 of file Geometry.h.
Constructor & Destructor Documentation
GeometryPoly3()
carla::road::element::GeometryPoly3::GeometryPoly3 (double start_offset, double length, double heading, const geom::Location & start_pos, double a, double b, double c, double d) inline
Definition at line 199 of file Geometry.h.
References _poly, PreComputeSpline(), and carla::geom::CubicPolynomial::Set().
Member Function Documentation
DistanceTo()
std::pair< float, float > carla::road::element::GeometryPoly3::DistanceTo (const geom::Location &) const override virtual
Implements carla::road::element::Geometry.
Definition at line 128 of file Geometry.cpp.
References carla::road::element::Geometry::_start_position, carla::geom::Vector3D::x, and carla::geom::Vector3D::y.
Geta()
double carla::road::element::GeometryPoly3::Geta () const inline
Definition at line 217 of file Geometry.h.
References _a.
Getb()
double carla::road::element::GeometryPoly3::Getb () const inline
Definition at line 220 of file Geometry.h.
References _b.
Getc()
double carla::road::element::GeometryPoly3::Getc () const inline
Definition at line 223 of file Geometry.h.
References _c.
Getd()
double carla::road::element::GeometryPoly3::Getd () const inline
Definition at line 226 of file Geometry.h.
References _d.
PosFromDist()
DirectedPoint carla::road::element::GeometryPoly3::PosFromDist (double dist) const override virtual
Implements carla::road::element::Geometry.
Definition at line 109 of file Geometry.cpp.
References carla::road::element::Geometry::_heading, _rtree, carla::road::element::Geometry::_start_position, carla::geom::SegmentCloudRtree< T, Dimension >::GetNearestNeighbours(), carla::road::element::DirectedPoint::location, carla::road::element::RotatebyAngle(), carla::geom::Vector2D::x, carla::geom::Vector3D::x, carla::geom::Vector2D::y, and carla::geom::Vector3D::y.
PreComputeSpline()
void carla::road::element::GeometryPoly3::PreComputeSpline () private
Definition at line 134 of file Geometry.cpp.
References carla::road::element::Geometry::_length, _poly, _rtree, carla::geom::CubicPolynomial::Evaluate(), carla::geom::SegmentCloudRtree< T, Dimension >::InsertElement(), and carla::geom::CubicPolynomial::Tangent().
Referenced by GeometryPoly3().
Member Data Documentation
_a
double carla::road::element::GeometryPoly3::_a private
Definition at line 238 of file Geometry.h.
Referenced by Geta().
_b
double carla::road::element::GeometryPoly3::_b private
Definition at line 239 of file Geometry.h.
Referenced by Getb().
_c
double carla::road::element::GeometryPoly3::_c private
Definition at line 240 of file Geometry.h.
Referenced by Getc().
_d
double carla::road::element::GeometryPoly3::_d private
Definition at line 241 of file Geometry.h.
Referenced by Getd().
_poly
geom::CubicPolynomial carla::road::element::GeometryPoly3::_poly private
Definition at line 236 of file Geometry.h.
Referenced by GeometryPoly3(), and PreComputeSpline().
_rtree
Rtree carla::road::element::GeometryPoly3::_rtree private
Definition at line 251 of file Geometry.h.
Referenced by PosFromDist(), and PreComputeSpline().
The documentation for this class was generated from the following files:
Geometry.h
Geometry.cpp