CARLA: carla::multigpu::Secondary Class Reference
carla::multigpu::Secondary Class Reference
#include <secondary.h>
Public Types
using endpoint = boost::asio::ip::tcp::endpoint
using protocol_type = endpoint::protocol_type
Public Member Functions
void AsyncRun (size_t worker_threads)
void Connect ()
SecondaryCommands & GetCommander ()
Secondary (boost::asio::ip::tcp::endpoint ep, SecondaryCommands::callback_type callback)
Secondary (std::string ip, uint16_t port, SecondaryCommands::callback_type callback)
void Stop ()
void Write (Buffer buffer)
void Write (std::shared_ptr< const carla::streaming::detail::tcp::Message > message)
void Write (std::string text)
~Secondary ()
Static Public Member Functions
template<typename... Buffers>
static auto MakeMessage (Buffers... buffers)
Private Member Functions
void ReadData ()
void Reconnect ()
Private Member Functions inherited from carla::profiler::LifetimeProfiled
LifetimeProfiled ()=default
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Private Attributes
std::shared_ptr< BufferPool > _buffer_pool
SecondaryCommands _commander
boost::asio::deadline_timer _connection_timer
std::atomic_bool _done {false}
boost::asio::ip::tcp::endpoint _endpoint
ThreadPool _pool
boost::asio::ip::tcp::socket _socket
boost::asio::io_context::strand _strand
Detailed Description
Definition at line 34 of file secondary.h.
Member Typedef Documentation
endpoint
using carla::multigpu::Secondary::endpoint = boost::asio::ip::tcp::endpoint
Definition at line 40 of file secondary.h.
protocol_type
using carla::multigpu::Secondary::protocol_type = endpoint::protocol_type
Definition at line 41 of file secondary.h.
Constructor & Destructor Documentation
Secondary() [1/2]
carla::multigpu::Secondary::Secondary (boost::asio::ip::tcp::endpoint ep, SecondaryCommands::callback_type callback)
Definition at line 27 of file secondary.cpp.
References _commander, and carla::multigpu::SecondaryCommands::set_callback().
Secondary() [2/2]
carla::multigpu::Secondary::Secondary (std::string ip, uint16_t port, SecondaryCommands::callback_type callback)
Definition at line 41 of file secondary.cpp.
References _commander, _endpoint, and carla::multigpu::SecondaryCommands::set_callback().
~Secondary()
carla::multigpu::Secondary::~Secondary ()
Definition at line 56 of file secondary.cpp.
References _pool, and carla::ThreadPool::Stop().
Member Function Documentation
AsyncRun()
void carla::multigpu::Secondary::AsyncRun (size_t worker_threads)
Definition at line 130 of file secondary.cpp.
Referenced by Connect().
Connect()
void carla::multigpu::Secondary::Connect ()
Definition at line 60 of file secondary.cpp.
References _commander, _strand, AsyncRun(), carla::log_info(), and carla::multigpu::SecondaryCommands::set_secondary().
GetCommander()
SecondaryCommands & carla::multigpu::Secondary::GetCommander () inline
Definition at line 57 of file secondary.h.
References _commander.
MakeMessage()
template<typename... Buffers> static auto carla::multigpu::Secondary::MakeMessage (Buffers... buffers) inline static
Definition at line 62 of file secondary.h.
ReadData()
void carla::multigpu::Secondary::ReadData () private
Definition at line 224 of file secondary.cpp.
References DEBUG_ASSERT_EQ, DEBUG_ASSERT_NE, DEBUG_ONLY, and carla::log_error().
Reconnect()
void carla::multigpu::Secondary::Reconnect () private
Definition at line 118 of file secondary.cpp.
References carla::time_duration::seconds().
Stop()
void carla::multigpu::Secondary::Stop ()
Definition at line 105 of file secondary.cpp.
Write() [1/3]
void carla::multigpu::Secondary::Write (Buffer buffer)
Definition at line 161 of file secondary.cpp.
References carla::BufferView::CreateFrom(), DEBUG_ASSERT, DEBUG_ONLY, and carla::log_error().
Write() [2/3]
void carla::multigpu::Secondary::Write (std::shared_ptr< const carla::streaming::detail::tcp::Message > message)
Definition at line 134 of file secondary.cpp.
References DEBUG_ASSERT, DEBUG_ONLY, and carla::log_error().
Write() [3/3]
void carla::multigpu::Secondary::Write (std::string text)
Definition at line 191 of file secondary.cpp.
References DEBUG_ONLY, and carla::log_error().
Member Data Documentation
_buffer_pool
std::shared_ptr<BufferPool> carla::multigpu::Secondary::_buffer_pool private
Definition at line 80 of file secondary.h.
_commander
SecondaryCommands carla::multigpu::Secondary::_commander private
Definition at line 82 of file secondary.h.
Referenced by Connect(), GetCommander(), Secondary(), and Secondary().
_connection_timer
boost::asio::deadline_timer carla::multigpu::Secondary::_connection_timer private
Definition at line 79 of file secondary.h.
_done
std::atomic_bool carla::multigpu::Secondary::_done {false} private
Definition at line 81 of file secondary.h.
_endpoint
boost::asio::ip::tcp::endpoint carla::multigpu::Secondary::_endpoint private
Definition at line 77 of file secondary.h.
Referenced by Secondary().
_pool
ThreadPool carla::multigpu::Secondary::_pool private
Definition at line 75 of file secondary.h.
Referenced by ~Secondary().
_socket
boost::asio::ip::tcp::socket carla::multigpu::Secondary::_socket private
Definition at line 76 of file secondary.h.
_strand
boost::asio::io_context::strand carla::multigpu::Secondary::_strand private
Definition at line 78 of file secondary.h.
Referenced by Connect().
The documentation for this class was generated from the following files:
secondary.h
secondary.cpp