CARLA: carla::client::detail::Client Class Reference
carla::client::detail::Client Class Reference
Provides communication with the rpc and streaming servers of a CARLA simulator.
#include <Client.h>
Classes
class Pimpl
Public Member Functions
void AddActorAngularImpulse (rpc::ActorId actor, const geom::Vector3D &vector)
void AddActorForce (rpc::ActorId actor, const geom::Vector3D &force)
void AddActorForce (rpc::ActorId actor, const geom::Vector3D &force, const geom::Vector3D &location)
void AddActorImpulse (rpc::ActorId actor, const geom::Vector3D &impulse)
void AddActorImpulse (rpc::ActorId actor, const geom::Vector3D &impulse, const geom::Vector3D &location)
void AddActorTorque (rpc::ActorId actor, const geom::Vector3D &vector)
bool AddTrafficManagerRunning (std::pair< std::string, uint16_t > trafficManagerInfo) const
Informs the server that a Traffic Manager is running on <IP, port>
void ApplyAckermannControllerSettings (rpc::ActorId vehicle, const rpc::AckermannControllerSettings &settings)
void ApplyAckermannControlToVehicle (rpc::ActorId vehicle, const rpc::VehicleAckermannControl &control)
void ApplyBatch (std::vector< rpc::Command > commands, bool do_tick_cue)
std::vector< rpc::CommandResponse > ApplyBatchSync (std::vector< rpc::Command > commands, bool do_tick_cue)
void ApplyColorTextureToObjects (const std::vector< std::string > &objects_name, const rpc::MaterialParameter &parameter, const rpc::TextureColor &Texture)
void ApplyColorTextureToObjects (const std::vector< std::string > &objects_name, const rpc::MaterialParameter &parameter, const rpc::TextureFloatColor &Texture)
void ApplyControlToVehicle (rpc::ActorId vehicle, const rpc::VehicleControl &control)
void ApplyControlToWalker (rpc::ActorId walker, const rpc::WalkerControl &control)
void ApplyPhysicsControlToVehicle (rpc::ActorId vehicle, const rpc::VehiclePhysicsControl &physics_control)
void BlendPose (rpc::ActorId walker, float blend)
std::vector< rpc::LabelledPoint > CastRay (geom::Location start_location, geom::Location end_location) const
Client (const std::string &host, uint16_t port, size_t worker_threads=0u)
void CloseVehicleDoor (rpc::ActorId vehicle, const rpc::VehicleDoor door_idx)
void CopyOpenDriveToServer (std::string opendrive, const rpc::OpendriveGenerationParameters &params)
bool DestroyActor (rpc::ActorId actor)
void DestroyTrafficManager (uint16_t port) const
void DisableActorConstantVelocity (rpc::ActorId actor)
void DisableForROS (const streaming::Token &token)
void DrawDebugShape (const rpc::DebugShape &shape)
void EnableActorConstantVelocity (rpc::ActorId actor, const geom::Vector3D &vector)
void EnableCarSim (rpc::ActorId vehicle, std::string simfile_path)
void EnableChronoPhysics (rpc::ActorId vehicle, uint64_t MaxSubsteps, float MaxSubstepDeltaTime, std::string VehicleJSON, std::string PowertrainJSON, std::string TireJSON, std::string BaseJSONPath)
void EnableEnvironmentObjects (std::vector< uint64_t > env_objects_ids, bool enable) const
void EnableForROS (const streaming::Token &token)
void FreezeAllTrafficLights (bool frozen)
void FreezeTrafficLight (rpc::ActorId traffic_light, bool freeze)
rpc::AckermannControllerSettings GetAckermannControllerSettings (rpc::ActorId vehicle) const
std::vector< std::string > GetActorBoneNames (rpc::ActorId actor)
std::vector< geom::Transform > GetActorBoneRelativeTransforms (rpc::ActorId actor)
std::vector< geom::Transform > GetActorBoneWorldTransforms (rpc::ActorId actor)
std::vector< std::string > GetActorComponentNames (rpc::ActorId actor)
geom::Transform GetActorComponentRelativeTransform (rpc::ActorId actor, const std::string componentName)
geom::Transform GetActorComponentWorldTransform (rpc::ActorId actor, const std::string componentName)
std::vector< rpc::ActorDefinition > GetActorDefinitions ()
std::vector< rpc::Actor > GetActorsById (const std::vector< ActorId > &ids)
std::vector< std::string > GetActorSocketNames (rpc::ActorId actor)
std::vector< geom::Transform > GetActorSocketRelativeTransforms (rpc::ActorId actor)
std::vector< geom::Transform > GetActorSocketWorldTransforms (rpc::ActorId actor)
std::vector< std::string > GetAvailableMaps ()
rpc::WalkerBoneControlOut GetBonesTransform (rpc::ActorId walker)
std::vector< uint8_t > GetCacheFile (const std::string &name, const bool request_otherwise=true) const
std::string GetClientVersion ()
const std::string GetEndpoint () const
std::vector< rpc::EnvironmentObject > GetEnvironmentObjects (uint8_t queried_tag) const
rpc::EpisodeInfo GetEpisodeInfo ()
rpc::EpisodeSettings GetEpisodeSettings ()
std::vector< ActorId > GetGroupTrafficLights (rpc::ActorId traffic_light)
float GetIMUISensorGravity () const
std::vector< geom::BoundingBox > GetLevelBBs (uint8_t queried_tag) const
Returns all the BBs of all the elements of the level.
std::vector< geom::BoundingBox > GetLightBoxes (rpc::ActorId traffic_light) const
std::string GetMapData () const
rpc::MapInfo GetMapInfo ()
std::vector< std::string > GetNamesOfAllObjects () const
std::vector< uint8_t > GetNavigationMesh () const
void GetPoseFromAnimation (rpc::ActorId walker)
std::vector< std::string > GetRequiredFiles (const std::string &folder="", const bool download=true) const
std::string GetServerVersion ()
rpc::Actor GetSpectator ()
time_duration GetTimeout () const
std::pair< std::string, uint16_t > GetTrafficManagerRunning (uint16_t port) const
Gets a pair filled with the <IP, port> of the Trafic Manager running on port.
rpc::VehicleLightState GetVehicleLightState (rpc::ActorId vehicle) const
rpc::VehiclePhysicsControl GetVehiclePhysicsControl (rpc::ActorId vehicle) const
rpc::VehicleLightStateList GetVehiclesLightStates ()
Returns a list of pairs where the firts element is the vehicle ID and the second one is the light state.
rpc::VehicleTelemetryData GetVehicleTelemetryData (rpc::ActorId vehicle) const
rpc::WeatherParameters GetWeatherParameters ()
float GetWheelSteerAngle (rpc::ActorId vehicle, rpc::VehicleWheelLocation wheel_location)
bool IsEnabledForROS (const streaming::Token &token)
bool IsTrafficManagerRunning (uint16_t port) const
Querry to know if a Traffic Manager is running on port.
void LoadEpisode (std::string map_name, bool reset_settings=true, rpc::MapLayer map_layer=rpc::MapLayer::All)
void LoadLevelLayer (rpc::MapLayer map_layer) const
void OpenVehicleDoor (rpc::ActorId vehicle, const rpc::VehicleDoor door_idx)
std::pair< bool, rpc::LabelledPoint > ProjectPoint (geom::Location location, geom::Vector3D direction, float search_distance) const
std::vector< rpc::LightState > QueryLightsStateToServer () const
std::string ReplayFile (std::string name, double start, double duration, uint32_t follow_id, bool replay_sensors)
void RequestFile (const std::string &name) const
void ResetAllTrafficLights ()
void ResetTrafficLightGroup (rpc::ActorId traffic_light)
void RestorePhysXPhysics (rpc::ActorId vehicle)
void Send (rpc::ActorId ActorId, std::string message)
uint64_t SendTickCue ()
void SetActorAutopilot (rpc::ActorId vehicle, bool enabled)
void SetActorCollisions (rpc::ActorId actor, bool enabled)
void SetActorDead (rpc::ActorId actor)
void SetActorEnableGravity (rpc::ActorId actor, bool enabled)
void SetActorLocation (rpc::ActorId actor, const geom::Location &location)
void SetActorSimulatePhysics (rpc::ActorId actor, bool enabled)
void SetActorTargetAngularVelocity (rpc::ActorId actor, const geom::Vector3D &vector)
void SetActorTargetVelocity (rpc::ActorId actor, const geom::Vector3D &vector)
void SetActorTransform (rpc::ActorId actor, const geom::Transform &transform)
void SetBonesTransform (rpc::ActorId walker, const rpc::WalkerBoneControlIn &bones)
uint64_t SetEpisodeSettings (const rpc::EpisodeSettings &settings)
bool SetFilesBaseFolder (const std::string &path)
void SetIMUISensorGravity (float NewIMUISensorGravity)
void SetLightStateToVehicle (rpc::ActorId vehicle, const rpc::VehicleLightState &light_state)
void SetReplayerIgnoreHero (bool ignore_hero)
void SetReplayerIgnoreSpectator (bool ignore_spectator)
void SetReplayerTimeFactor (double time_factor)
void SetTimeout (time_duration timeout)
void SetTrafficLightGreenTime (rpc::ActorId traffic_light, float green_time)
void SetTrafficLightRedTime (rpc::ActorId traffic_light, float red_time)
void SetTrafficLightState (rpc::ActorId traffic_light, const rpc::TrafficLightState trafficLightState)
void SetTrafficLightYellowTime (rpc::ActorId traffic_light, float yellow_time)
void SetWeatherParameters (const rpc::WeatherParameters &weather)
void SetWheelSteerDirection (rpc::ActorId vehicle, rpc::VehicleWheelLocation vehicle_wheel, float angle_in_deg)
std::string ShowRecorderActorsBlocked (std::string name, double min_time, double min_distance)
std::string ShowRecorderCollisions (std::string name, char type1, char type2)
std::string ShowRecorderFileInfo (std::string name, bool show_all)
void ShowVehicleDebugTelemetry (rpc::ActorId vehicle, bool enabled)
rpc::Actor SpawnActor (const rpc::ActorDescription &description, const geom::Transform &transform)
rpc::Actor SpawnActorWithParent (const rpc::ActorDescription &description, const geom::Transform &transform, rpc::ActorId parent, rpc::AttachmentType attachment_type, const std::string &socket_name="")
std::string StartRecorder (std::string name, bool additional_data)
void StopRecorder ()
void StopReplayer (bool keep_actors)
void SubscribeToGBuffer (rpc::ActorId ActorId, uint32_t GBufferId, std::function< void(Buffer)> callback)
void SubscribeToStream (const streaming::Token &token, std::function< void(Buffer)> callback)
void UnloadLevelLayer (rpc::MapLayer map_layer) const
void UnSubscribeFromGBuffer (rpc::ActorId ActorId, uint32_t GBufferId)
void UnSubscribeFromStream (const streaming::Token &token)
void UpdateDayNightCycle (const bool active) const
void UpdateServerLightsState (std::vector< rpc::LightState > &lights, bool discard_client=false) const
void UseCarSimRoad (rpc::ActorId vehicle, bool enabled)
~Client ()
Private Attributes
const std::unique_ptr< Pimpl > _pimpl
Additional Inherited Members
Private Member Functions inherited from carla::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable & operator= (const NonCopyable &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
Detailed Description
Provides communication with the rpc and streaming servers of a CARLA simulator.
Definition at line 70 of file client/detail/Client.h.
Constructor & Destructor Documentation
Client()
carla::client::detail::Client::Client (const std::string & host, uint16_t port, size_t worker_threads = 0u) explicit
Definition at line 103 of file client/detail/Client.cpp.
~Client()
carla::client::detail::Client::~Client () default
Member Function Documentation
AddActorAngularImpulse()
void carla::client::detail::Client::AddActorAngularImpulse (rpc::ActorId actor, const geom::Vector3D & vector)
Definition at line 413 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::AddActorAngularImpulse(), and carla::client::detail::Simulator::AddActorTorque().
AddActorForce() [1/2]
void carla::client::detail::Client::AddActorForce (rpc::ActorId actor, const geom::Vector3D & force)
Definition at line 405 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::AddActorForce(), and carla::client::detail::Simulator::AddActorForce().
AddActorForce() [2/2]
void carla::client::detail::Client::AddActorForce (rpc::ActorId actor, const geom::Vector3D & force, const geom::Vector3D & location)
Definition at line 409 of file client/detail/Client.cpp.
References _pimpl.
AddActorImpulse() [1/2]
void carla::client::detail::Client::AddActorImpulse (rpc::ActorId actor, const geom::Vector3D & impulse)
Definition at line 397 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::AddActorImpulse(), and carla::client::detail::Simulator::AddActorImpulse().
AddActorImpulse() [2/2]
void carla::client::detail::Client::AddActorImpulse (rpc::ActorId actor, const geom::Vector3D & impulse, const geom::Vector3D & location)
Definition at line 401 of file client/detail/Client.cpp.
References _pimpl.
AddActorTorque()
void carla::client::detail::Client::AddActorTorque (rpc::ActorId actor, const geom::Vector3D & vector)
Definition at line 417 of file client/detail/Client.cpp.
References _pimpl.
AddTrafficManagerRunning()
bool carla::client::detail::Client::AddTrafficManagerRunning (std::pair< std::string, uint16_t > trafficManagerInfo) const
Informs the server that a Traffic Manager is running on <IP, port>
Definition at line 117 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::AddTrafficManagerRunning().
ApplyAckermannControllerSettings()
void carla::client::detail::Client::ApplyAckermannControllerSettings (rpc::ActorId vehicle, const rpc::AckermannControllerSettings & settings)
Definition at line 506 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyAckermannControllerSettings().
ApplyAckermannControlToVehicle()
void carla::client::detail::Client::ApplyAckermannControlToVehicle (rpc::ActorId vehicle, const rpc::VehicleAckermannControl & control)
Definition at line 497 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyAckermannControlToVehicle().
ApplyBatch()
void carla::client::detail::Client::ApplyBatch (std::vector< rpc::Command > commands, bool do_tick_cue)
Definition at line 707 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyBatch().
ApplyBatchSync()
std::vector< rpc::CommandResponse > carla::client::detail::Client::ApplyBatchSync (std::vector< rpc::Command > commands, bool do_tick_cue)
Definition at line 711 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyBatchSync().
ApplyColorTextureToObjects() [1/2]
void carla::client::detail::Client::ApplyColorTextureToObjects (const std::vector< std::string > & objects_name, const rpc::MaterialParameter & parameter, const rpc::TextureColor & Texture)
Definition at line 167 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyColorTextureToObjects(), and carla::client::detail::Simulator::ApplyColorTextureToObjects().
ApplyColorTextureToObjects() [2/2]
void carla::client::detail::Client::ApplyColorTextureToObjects (const std::vector< std::string > & objects_name, const rpc::MaterialParameter & parameter, const rpc::TextureFloatColor & Texture)
Definition at line 174 of file client/detail/Client.cpp.
References _pimpl.
ApplyControlToVehicle()
void carla::client::detail::Client::ApplyControlToVehicle (rpc::ActorId vehicle, const rpc::VehicleControl & control)
Definition at line 493 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyControlToVehicle(), and carla::client::detail::Simulator::SetLightsToVehicle().
ApplyControlToWalker()
void carla::client::detail::Client::ApplyControlToWalker (rpc::ActorId walker, const rpc::WalkerControl & control)
Definition at line 540 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyControlToWalker().
ApplyPhysicsControlToVehicle()
void carla::client::detail::Client::ApplyPhysicsControlToVehicle (rpc::ActorId vehicle, const rpc::VehiclePhysicsControl & physics_control)
Definition at line 294 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ApplyPhysicsControlToVehicle().
BlendPose()
void carla::client::detail::Client::BlendPose (rpc::ActorId walker, float blend)
Definition at line 553 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::BlendPose().
CastRay()
std::vector< rpc::LabelledPoint > carla::client::detail::Client::CastRay (geom::Location start_location, geom::Location end_location) const
Definition at line 757 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::CastRay().
CloseVehicleDoor()
void carla::client::detail::Client::CloseVehicleDoor (rpc::ActorId vehicle, const rpc::VehicleDoor door_idx)
Definition at line 312 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::CloseVehicleDoor().
CopyOpenDriveToServer()
void carla::client::detail::Client::CopyOpenDriveToServer (std::string opendrive, const rpc::OpendriveGenerationParameters & params)
Definition at line 162 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::LoadOpenDriveEpisode().
DestroyActor()
bool carla::client::detail::Client::DestroyActor (rpc::ActorId actor)
Definition at line 364 of file client/detail/Client.cpp.
References _pimpl, and carla::log_error().
Referenced by carla::client::detail::Simulator::DestroyActor(), and carla::client::detail::Simulator::DestroyActor().
DestroyTrafficManager()
void carla::client::detail::Client::DestroyTrafficManager (uint16_t port) const
Definition at line 121 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::DestroyTrafficManager().
DisableActorConstantVelocity()
void carla::client::detail::Client::DisableActorConstantVelocity (rpc::ActorId actor)
Definition at line 393 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::DisableActorConstantVelocity().
DisableForROS()
void carla::client::detail::Client::DisableForROS (const streaming::Token & token)
Definition at line 668 of file client/detail/Client.cpp.
References _pimpl, and carla::streaming::detail::token_type::get_stream_id().
Referenced by carla::client::detail::Simulator::DisableForROS().
DrawDebugShape()
void carla::client::detail::Client::DrawDebugShape (const rpc::DebugShape & shape)
Definition at line 703 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::DrawDebugShape().
EnableActorConstantVelocity()
void carla::client::detail::Client::EnableActorConstantVelocity (rpc::ActorId actor, const geom::Vector3D & vector)
Definition at line 389 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::EnableActorConstantVelocity().
EnableCarSim()
void carla::client::detail::Client::EnableCarSim (rpc::ActorId vehicle, std::string simfile_path)
Definition at line 510 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::EnableCarSim().
EnableChronoPhysics()
void carla::client::detail::Client::EnableChronoPhysics (rpc::ActorId vehicle, uint64_t MaxSubsteps, float MaxSubstepDeltaTime, std::string VehicleJSON, std::string PowertrainJSON, std::string TireJSON, std::string BaseJSONPath)
Definition at line 518 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::EnableChronoPhysics().
EnableEnvironmentObjects()
void carla::client::detail::Client::EnableEnvironmentObjects (std::vector< uint64_t > env_objects_ids, bool enable) const
Definition at line 745 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::EnableEnvironmentObjects().
EnableForROS()
void carla::client::detail::Client::EnableForROS (const streaming::Token & token)
Definition at line 663 of file client/detail/Client.cpp.
References _pimpl, and carla::streaming::detail::token_type::get_stream_id().
Referenced by carla::client::detail::Simulator::EnableForROS().
FreezeAllTrafficLights()
void carla::client::detail::Client::FreezeAllTrafficLights (bool frozen)
Definition at line 591 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::FreezeAllTrafficLights().
FreezeTrafficLight()
void carla::client::detail::Client::FreezeTrafficLight (rpc::ActorId traffic_light, bool freeze)
Definition at line 579 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::FreezeTrafficLight().
GetAckermannControllerSettings()
rpc::AckermannControllerSettings carla::client::detail::Client::GetAckermannControllerSettings (rpc::ActorId vehicle) const
Definition at line 501 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetAckermannControllerSettings().
GetActorBoneNames()
std::vector< std::string > carla::client::detail::Client::GetActorBoneNames (rpc::ActorId actor)
Definition at line 444 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorBoneNames().
GetActorBoneRelativeTransforms()
std::vector< geom::Transform > carla::client::detail::Client::GetActorBoneRelativeTransforms (rpc::ActorId actor)
Definition at line 434 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorBoneRelativeTransforms().
GetActorBoneWorldTransforms()
std::vector< geom::Transform > carla::client::detail::Client::GetActorBoneWorldTransforms (rpc::ActorId actor)
Definition at line 429 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorBoneWorldTransforms().
GetActorComponentNames()
std::vector< std::string > carla::client::detail::Client::GetActorComponentNames (rpc::ActorId actor)
Definition at line 439 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorComponentNames().
GetActorComponentRelativeTransform()
geom::Transform carla::client::detail::Client::GetActorComponentRelativeTransform (rpc::ActorId actor, const std::string componentName)
Definition at line 425 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorComponentRelativeTransform().
GetActorComponentWorldTransform()
geom::Transform carla::client::detail::Client::GetActorComponentWorldTransform (rpc::ActorId actor, const std::string componentName)
Definition at line 421 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorComponentWorldTransform().
GetActorDefinitions()
std::vector< rpc::ActorDefinition > carla::client::detail::Client::GetActorDefinitions ()
Definition at line 246 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetBlueprintLibrary().
GetActorsById()
std::vector< rpc::Actor > carla::client::detail::Client::GetActorsById (const std::vector< ActorId > & ids)
Definition at line 278 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Episode::GetActorById().
GetActorSocketNames()
std::vector< std::string > carla::client::detail::Client::GetActorSocketNames (rpc::ActorId actor)
Definition at line 459 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorSocketNames().
GetActorSocketRelativeTransforms()
std::vector< geom::Transform > carla::client::detail::Client::GetActorSocketRelativeTransforms (rpc::ActorId actor)
Definition at line 454 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorSocketRelativeTransforms().
GetActorSocketWorldTransforms()
std::vector< geom::Transform > carla::client::detail::Client::GetActorSocketWorldTransforms (rpc::ActorId actor)
Definition at line 449 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetActorSocketWorldTransforms().
GetAvailableMaps()
std::vector< std::string > carla::client::detail::Client::GetAvailableMaps ()
Definition at line 242 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetAvailableMaps().
GetBonesTransform()
rpc::WalkerBoneControlOut carla::client::detail::Client::GetBonesTransform (rpc::ActorId walker)
Definition at line 544 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetBonesTransform().
GetCacheFile()
std::vector< uint8_t > carla::client::detail::Client::GetCacheFile (const std::string & name, const bool request_otherwise = true) const
Definition at line 230 of file client/detail/Client.cpp.
References carla::client::FileTransfer::ReadFile(), and RequestFile().
Referenced by carla::client::detail::Simulator::GetCacheFile().
GetClientVersion()
std::string carla::client::detail::Client::GetClientVersion ()
Definition at line 139 of file client/detail/Client.cpp.
Referenced by carla::client::detail::Simulator::GetClientVersion().
GetEndpoint()
const std::string carla::client::detail::Client::GetEndpoint () const
Definition at line 135 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetEndpoint(), carla::client::detail::Simulator::Tick(), and carla::client::detail::Simulator::WaitForTick().
GetEnvironmentObjects()
std::vector< rpc::EnvironmentObject > carla::client::detail::Client::GetEnvironmentObjects (uint8_t queried_tag) const
Definition at line 740 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetEnvironmentObjects().
GetEpisodeInfo()
rpc::EpisodeInfo carla::client::detail::Client::GetEpisodeInfo ()
Definition at line 185 of file client/detail/Client.cpp.
References _pimpl.
GetEpisodeSettings()
rpc::EpisodeSettings carla::client::detail::Client::GetEpisodeSettings ()
Definition at line 254 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetEpisodeSettings(), and carla::client::detail::Simulator::LoadEpisode().
GetGroupTrafficLights()
std::vector< ActorId > carla::client::detail::Client::GetGroupTrafficLights (rpc::ActorId traffic_light)
Definition at line 604 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetGroupTrafficLights().
GetIMUISensorGravity()
float carla::client::detail::Client::GetIMUISensorGravity () const
Definition at line 270 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetIMUISensorGravity().
GetLevelBBs()
std::vector< geom::BoundingBox > carla::client::detail::Client::GetLevelBBs (uint8_t queried_tag) const
Returns all the BBs of all the elements of the level.
Definition at line 735 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetLevelBBs().
GetLightBoxes()
std::vector< geom::BoundingBox > carla::client::detail::Client::GetLightBoxes (rpc::ActorId traffic_light) const
Definition at line 595 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetLightBoxes().
GetMapData()
std::string carla::client::detail::Client::GetMapData () const
Definition at line 193 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetCurrentMap().
GetMapInfo()
rpc::MapInfo carla::client::detail::Client::GetMapInfo ()
Definition at line 189 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetCurrentMap().
GetNamesOfAllObjects()
std::vector< std::string > carla::client::detail::Client::GetNamesOfAllObjects () const
Definition at line 181 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetNamesOfAllObjects().
GetNavigationMesh()
std::vector< uint8_t > carla::client::detail::Client::GetNavigationMesh () const
Definition at line 197 of file client/detail/Client.cpp.
References _pimpl.
GetPoseFromAnimation()
void carla::client::detail::Client::GetPoseFromAnimation (rpc::ActorId walker)
Definition at line 557 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetPoseFromAnimation().
GetRequiredFiles()
std::vector< std::string > carla::client::detail::Client::GetRequiredFiles (const std::string & folder = "", const bool download = true) const
Definition at line 205 of file client/detail/Client.cpp.
References _pimpl, carla::client::FileTransfer::FileExists(), carla::log_info(), and RequestFile().
Referenced by carla::client::detail::Simulator::GetCurrentMap(), and carla::client::detail::Simulator::GetRequiredFiles().
GetServerVersion()
std::string carla::client::detail::Client::GetServerVersion ()
Definition at line 143 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetServerVersion().
GetSpectator()
rpc::Actor carla::client::detail::Client::GetSpectator ()
Definition at line 250 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetSpectator().
GetTimeout()
time_duration carla::client::detail::Client::GetTimeout () const
Definition at line 131 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetNetworkingTimeout(), carla::client::detail::Simulator::GetReadyCurrentEpisode(), and carla::client::detail::Simulator::LoadEpisode().
GetTrafficManagerRunning()
std::pair< std::string, uint16_t > carla::client::detail::Client::GetTrafficManagerRunning (uint16_t port) const
Gets a pair filled with the <IP, port> of the Trafic Manager running on port.
If there is no Traffic Manager running the pair will be ("", 0)
Definition at line 113 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetTrafficManagerRunning().
GetVehicleLightState()
rpc::VehicleLightState carla::client::detail::Client::GetVehicleLightState (rpc::ActorId vehicle) const
Definition at line 289 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetVehicleLightState().
GetVehiclePhysicsControl()
rpc::VehiclePhysicsControl carla::client::detail::Client::GetVehiclePhysicsControl (rpc::ActorId vehicle) const
Definition at line 284 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetVehiclePhysicsControl().
GetVehiclesLightStates()
rpc::VehicleLightStateList carla::client::detail::Client::GetVehiclesLightStates ()
Returns a list of pairs where the firts element is the vehicle ID and the second one is the light state.
Definition at line 600 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetVehiclesLightStates().
GetVehicleTelemetryData()
rpc::VehicleTelemetryData carla::client::detail::Client::GetVehicleTelemetryData (rpc::ActorId vehicle) const
Definition at line 484 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetVehicleTelemetryData().
GetWeatherParameters()
rpc::WeatherParameters carla::client::detail::Client::GetWeatherParameters ()
Definition at line 262 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetWeatherParameters().
GetWheelSteerAngle()
float carla::client::detail::Client::GetWheelSteerAngle (rpc::ActorId vehicle, rpc::VehicleWheelLocation wheel_location)
Definition at line 325 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::GetWheelSteerAngle().
IsEnabledForROS()
bool carla::client::detail::Client::IsEnabledForROS (const streaming::Token & token)
Definition at line 673 of file client/detail/Client.cpp.
References _pimpl, and carla::streaming::detail::token_type::get_stream_id().
Referenced by carla::client::detail::Simulator::IsEnabledForROS().
IsTrafficManagerRunning()
bool carla::client::detail::Client::IsTrafficManagerRunning (uint16_t port) const
Querry to know if a Traffic Manager is running on port.
Definition at line 109 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::IsTrafficManagerRunning().
LoadEpisode()
void carla::client::detail::Client::LoadEpisode (std::string map_name, bool reset_settings = true, rpc::MapLayer map_layer = rpc::MapLayer::All)
Definition at line 147 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::LoadEpisode().
LoadLevelLayer()
void carla::client::detail::Client::LoadLevelLayer (rpc::MapLayer map_layer) const
Definition at line 152 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::LoadLevelLayer().
OpenVehicleDoor()
void carla::client::detail::Client::OpenVehicleDoor (rpc::ActorId vehicle, const rpc::VehicleDoor door_idx)
Definition at line 306 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::OpenVehicleDoor().
ProjectPoint()
std::pair< bool, rpc::LabelledPoint > carla::client::detail::Client::ProjectPoint (geom::Location location, geom::Vector3D direction, float search_distance) const
Definition at line 751 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ProjectPoint().
QueryLightsStateToServer()
std::vector< rpc::LightState > carla::client::detail::Client::QueryLightsStateToServer () const
Definition at line 722 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::QueryLightsStateToServer().
ReplayFile()
std::string carla::client::detail::Client::ReplayFile (std::string name, double start, double duration, uint32_t follow_id, bool replay_sensors)
Definition at line 629 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ReplayFile().
RequestFile()
void carla::client::detail::Client::RequestFile (const std::string & name) const
Definition at line 224 of file client/detail/Client.cpp.
References _pimpl, and carla::client::FileTransfer::WriteFile().
Referenced by GetCacheFile(), GetRequiredFiles(), and carla::client::detail::Simulator::RequestFile().
ResetAllTrafficLights()
void carla::client::detail::Client::ResetAllTrafficLights ()
Definition at line 587 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ResetAllTrafficLights().
ResetTrafficLightGroup()
void carla::client::detail::Client::ResetTrafficLightGroup (rpc::ActorId traffic_light)
Definition at line 583 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ResetTrafficLightGroup().
RestorePhysXPhysics()
void carla::client::detail::Client::RestorePhysXPhysics (rpc::ActorId vehicle)
Definition at line 536 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::RestorePhysXPhysics().
Send()
void carla::client::detail::Client::Send (rpc::ActorId ActorId, std::string message)
Definition at line 678 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::Send().
SendTickCue()
uint64_t carla::client::detail::Client::SendTickCue ()
Definition at line 718 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::LoadEpisode(), and carla::client::detail::Simulator::Tick().
SetActorAutopilot()
void carla::client::detail::Client::SetActorAutopilot (rpc::ActorId vehicle, bool enabled)
Definition at line 480 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetVehicleAutopilot().
SetActorCollisions()
void carla::client::detail::Client::SetActorCollisions (rpc::ActorId actor, bool enabled)
Definition at line 468 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorCollisions(), and carla::client::detail::Simulator::SetActorCollisions().
SetActorDead()
void carla::client::detail::Client::SetActorDead (rpc::ActorId actor)
Definition at line 472 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorDead(), and carla::client::detail::Simulator::SetActorDead().
SetActorEnableGravity()
void carla::client::detail::Client::SetActorEnableGravity (rpc::ActorId actor, bool enabled)
Definition at line 476 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorEnableGravity().
SetActorLocation()
void carla::client::detail::Client::SetActorLocation (rpc::ActorId actor, const geom::Location & location)
Definition at line 373 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorLocation().
SetActorSimulatePhysics()
void carla::client::detail::Client::SetActorSimulatePhysics (rpc::ActorId actor, bool enabled)
Definition at line 464 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorSimulatePhysics().
SetActorTargetAngularVelocity()
void carla::client::detail::Client::SetActorTargetAngularVelocity (rpc::ActorId actor, const geom::Vector3D & vector)
Definition at line 385 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorTargetAngularVelocity().
SetActorTargetVelocity()
void carla::client::detail::Client::SetActorTargetVelocity (rpc::ActorId actor, const geom::Vector3D & vector)
Definition at line 381 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorTargetVelocity().
SetActorTransform()
void carla::client::detail::Client::SetActorTransform (rpc::ActorId actor, const geom::Transform & transform)
Definition at line 377 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetActorTransform().
SetBonesTransform()
void carla::client::detail::Client::SetBonesTransform (rpc::ActorId walker, const rpc::WalkerBoneControlIn & bones)
Definition at line 549 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetBonesTransform().
SetEpisodeSettings()
uint64_t carla::client::detail::Client::SetEpisodeSettings (const rpc::EpisodeSettings & settings)
Definition at line 258 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetEpisodeSettings().
SetFilesBaseFolder()
bool carla::client::detail::Client::SetFilesBaseFolder (const std::string & path)
Definition at line 201 of file client/detail/Client.cpp.
References carla::client::FileTransfer::SetFilesBaseFolder().
Referenced by carla::client::detail::Simulator::SetFilesBaseFolder().
SetIMUISensorGravity()
void carla::client::detail::Client::SetIMUISensorGravity (float NewIMUISensorGravity)
Definition at line 274 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetIMUISensorGravity().
SetLightStateToVehicle()
void carla::client::detail::Client::SetLightStateToVehicle (rpc::ActorId vehicle, const rpc::VehicleLightState & light_state)
Definition at line 300 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetLightStateToVehicle().
SetReplayerIgnoreHero()
void carla::client::detail::Client::SetReplayerIgnoreHero (bool ignore_hero)
Definition at line 643 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetReplayerIgnoreHero().
SetReplayerIgnoreSpectator()
void carla::client::detail::Client::SetReplayerIgnoreSpectator (bool ignore_spectator)
Definition at line 647 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetReplayerIgnoreSpectator().
SetReplayerTimeFactor()
void carla::client::detail::Client::SetReplayerTimeFactor (double time_factor)
Definition at line 639 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetReplayerTimeFactor().
SetTimeout()
void carla::client::detail::Client::SetTimeout (time_duration timeout)
Definition at line 127 of file client/detail/Client.cpp.
References _pimpl, and carla::time_duration::milliseconds().
Referenced by carla::client::detail::Simulator::SetNetworkingTimeout().
SetTrafficLightGreenTime()
void carla::client::detail::Client::SetTrafficLightGreenTime (rpc::ActorId traffic_light, float green_time)
Definition at line 567 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetTrafficLightGreenTime().
SetTrafficLightRedTime()
void carla::client::detail::Client::SetTrafficLightRedTime (rpc::ActorId traffic_light, float red_time)
Definition at line 575 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetTrafficLightRedTime().
SetTrafficLightState()
void carla::client::detail::Client::SetTrafficLightState (rpc::ActorId traffic_light, const rpc::TrafficLightState trafficLightState)
Definition at line 561 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetTrafficLightState().
SetTrafficLightYellowTime()
void carla::client::detail::Client::SetTrafficLightYellowTime (rpc::ActorId traffic_light, float yellow_time)
Definition at line 571 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetTrafficLightYellowTime().
SetWeatherParameters()
void carla::client::detail::Client::SetWeatherParameters (const rpc::WeatherParameters & weather)
Definition at line 266 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetWeatherParameters().
SetWheelSteerDirection()
void carla::client::detail::Client::SetWheelSteerDirection (rpc::ActorId vehicle, rpc::VehicleWheelLocation vehicle_wheel, float angle_in_deg)
Definition at line 318 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SetWheelSteerDirection().
ShowRecorderActorsBlocked()
std::string carla::client::detail::Client::ShowRecorderActorsBlocked (std::string name, double min_time, double min_distance)
Definition at line 625 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ShowRecorderActorsBlocked().
ShowRecorderCollisions()
std::string carla::client::detail::Client::ShowRecorderCollisions (std::string name, char type1, char type2)
Definition at line 621 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ShowRecorderCollisions().
ShowRecorderFileInfo()
std::string carla::client::detail::Client::ShowRecorderFileInfo (std::string name, bool show_all)
Definition at line 617 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ShowRecorderFileInfo().
ShowVehicleDebugTelemetry()
void carla::client::detail::Client::ShowVehicleDebugTelemetry (rpc::ActorId vehicle, bool enabled)
Definition at line 489 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::ShowVehicleDebugTelemetry().
SpawnActor()
rpc::Actor carla::client::detail::Client::SpawnActor (const rpc::ActorDescription & description, const geom::Transform & transform)
Definition at line 331 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SpawnActor().
SpawnActorWithParent()
rpc::Actor carla::client::detail::Client::SpawnActorWithParent (const rpc::ActorDescription & description, const geom::Transform & transform, rpc::ActorId parent, rpc::AttachmentType attachment_type, const std::string & socket_name = "")
Definition at line 337 of file client/detail/Client.cpp.
References _pimpl, carla::geom::Math::Dot(), carla::geom::Transform::location, carla::geom::Vector3D::MakeSafeUnitVector(), carla::rpc::SpringArm, and carla::rpc::SpringArmGhost.
Referenced by carla::client::detail::Simulator::SpawnActor().
StartRecorder()
std::string carla::client::detail::Client::StartRecorder (std::string name, bool additional_data)
Definition at line 609 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::StartRecorder().
StopRecorder()
void carla::client::detail::Client::StopRecorder ()
Definition at line 613 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::StopRecorder().
StopReplayer()
void carla::client::detail::Client::StopReplayer (bool keep_actors)
Definition at line 635 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::StopReplayer().
SubscribeToGBuffer()
void carla::client::detail::Client::SubscribeToGBuffer (rpc::ActorId ActorId, uint32_t GBufferId, std::function< void(Buffer)> callback)
Definition at line 682 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::SubscribeToGBuffer().
SubscribeToStream()
void carla::client::detail::Client::SubscribeToStream (const streaming::Token & token, std::function< void(Buffer)> callback)
Definition at line 651 of file client/detail/Client.cpp.
References _pimpl, and carla::streaming::detail::token_type::get_stream_id().
Referenced by carla::client::detail::Episode::Listen(), and carla::client::detail::Simulator::SubscribeToSensor().
UnloadLevelLayer()
void carla::client::detail::Client::UnloadLevelLayer (rpc::MapLayer map_layer) const
Definition at line 157 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::UnloadLevelLayer().
UnSubscribeFromGBuffer()
void carla::client::detail::Client::UnSubscribeFromGBuffer (rpc::ActorId ActorId, uint32_t GBufferId)
Definition at line 693 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::UnSubscribeFromGBuffer().
UnSubscribeFromStream()
void carla::client::detail::Client::UnSubscribeFromStream (const streaming::Token & token)
Definition at line 659 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::UnSubscribeFromSensor(), and carla::client::detail::Episode::~Episode().
UpdateDayNightCycle()
void carla::client::detail::Client::UpdateDayNightCycle (const bool active) const
Definition at line 731 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::UpdateDayNightCycle().
UpdateServerLightsState()
void carla::client::detail::Client::UpdateServerLightsState (std::vector< rpc::LightState > & lights, bool discard_client = false) const
Definition at line 727 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::UpdateServerLightsState().
UseCarSimRoad()
void carla::client::detail::Client::UseCarSimRoad (rpc::ActorId vehicle, bool enabled)
Definition at line 514 of file client/detail/Client.cpp.
References _pimpl.
Referenced by carla::client::detail::Simulator::UseCarSimRoad().
Member Data Documentation
_pimpl
const std::unique_ptr<Pimpl> carla::client::detail::Client::_pimpl private
Definition at line 476 of file client/detail/Client.h.
Referenced by AddActorAngularImpulse(), AddActorForce(), AddActorForce(), AddActorImpulse(), AddActorImpulse(), AddActorTorque(), AddTrafficManagerRunning(), ApplyAckermannControllerSettings(), ApplyAckermannControlToVehicle(), ApplyBatch(), ApplyBatchSync(), ApplyColorTextureToObjects(), ApplyColorTextureToObjects(), ApplyControlToVehicle(), ApplyControlToWalker(), ApplyPhysicsControlToVehicle(), BlendPose(), CastRay(), CloseVehicleDoor(), CopyOpenDriveToServer(), DestroyActor(), DestroyTrafficManager(), DisableActorConstantVelocity(), DisableForROS(), DrawDebugShape(), EnableActorConstantVelocity(), EnableCarSim(), EnableChronoPhysics(), EnableEnvironmentObjects(), EnableForROS(), FreezeAllTrafficLights(), FreezeTrafficLight(), GetAckermannControllerSettings(), GetActorBoneNames(), GetActorBoneRelativeTransforms(), GetActorBoneWorldTransforms(), GetActorComponentNames(), GetActorComponentRelativeTransform(), GetActorComponentWorldTransform(), GetActorDefinitions(), GetActorsById(), GetActorSocketNames(), GetActorSocketRelativeTransforms(), GetActorSocketWorldTransforms(), GetAvailableMaps(), GetBonesTransform(), GetEndpoint(), GetEnvironmentObjects(), GetEpisodeInfo(), GetEpisodeSettings(), GetGroupTrafficLights(), GetIMUISensorGravity(), GetLevelBBs(), GetLightBoxes(), GetMapData(), GetMapInfo(), GetNamesOfAllObjects(), GetNavigationMesh(), GetPoseFromAnimation(), GetRequiredFiles(), GetServerVersion(), GetSpectator(), GetTimeout(), GetTrafficManagerRunning(), GetVehicleLightState(), GetVehiclePhysicsControl(), GetVehiclesLightStates(), GetVehicleTelemetryData(), GetWeatherParameters(), GetWheelSteerAngle(), IsEnabledForROS(), IsTrafficManagerRunning(), LoadEpisode(), LoadLevelLayer(), OpenVehicleDoor(), ProjectPoint(), QueryLightsStateToServer(), ReplayFile(), RequestFile(), ResetAllTrafficLights(), ResetTrafficLightGroup(), RestorePhysXPhysics(), Send(), SendTickCue(), SetActorAutopilot(), SetActorCollisions(), SetActorDead(), SetActorEnableGravity(), SetActorLocation(), SetActorSimulatePhysics(), SetActorTargetAngularVelocity(), SetActorTargetVelocity(), SetActorTransform(), SetBonesTransform(), SetEpisodeSettings(), SetIMUISensorGravity(), SetLightStateToVehicle(), SetReplayerIgnoreHero(), SetReplayerIgnoreSpectator(), SetReplayerTimeFactor(), SetTimeout(), SetTrafficLightGreenTime(), SetTrafficLightRedTime(), SetTrafficLightState(), SetTrafficLightYellowTime(), SetWeatherParameters(), SetWheelSteerDirection(), ShowRecorderActorsBlocked(), ShowRecorderCollisions(), ShowRecorderFileInfo(), ShowVehicleDebugTelemetry(), SpawnActor(), SpawnActorWithParent(), StartRecorder(), StopRecorder(), StopReplayer(), SubscribeToGBuffer(), SubscribeToStream(), UnloadLevelLayer(), UnSubscribeFromGBuffer(), UnSubscribeFromStream(), UpdateDayNightCycle(), UpdateServerLightsState(), and UseCarSimRoad().
The documentation for this class was generated from the following files:
client/detail/Client.h
client/detail/Client.cpp