CARLA: geometry_msgs::msg::TwistPubSubType Class Reference
geometry_msgs::msg::TwistPubSubType Class Reference
This class represents the TopicDataType of the type Twist defined by the user in the IDL file.
#include <TwistPubSubTypes.h>
Public Types
typedef Twist type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport TwistPubSubType ()
virtual eProsima_user_DllExport ~TwistPubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Static Private Member Functions
static constexpr bool is_plain_impl ()
Detailed Description
This class represents the TopicDataType of the type Twist defined by the user in the IDL file.
Definition at line 75 of file TwistPubSubTypes.h.
Member Typedef Documentation
type
typedef Twist geometry_msgs::msg::TwistPubSubType::type
Definition at line 79 of file TwistPubSubTypes.h.
Constructor & Destructor Documentation
TwistPubSubType()
geometry_msgs::msg::TwistPubSubType::TwistPubSubType ()
Definition at line 32 of file TwistPubSubTypes.cpp.
References geometry_msgs::msg::Twist::getKeyMaxCdrSerializedSize(), geometry_msgs::msg::Twist::getMaxCdrSerializedSize(), geometry_msgs::msg::Twist::isKeyDefined(), and m_keyBuffer.
~TwistPubSubType()
geometry_msgs::msg::TwistPubSubType::~TwistPubSubType () override virtual
Definition at line 45 of file TwistPubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * geometry_msgs::msg::TwistPubSubType::createData () override virtual
Definition at line 122 of file TwistPubSubTypes.cpp.
deleteData()
void geometry_msgs::msg::TwistPubSubType::deleteData (void * data) override virtual
Definition at line 127 of file TwistPubSubTypes.cpp.
deserialize()
bool geometry_msgs::msg::TwistPubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file TwistPubSubTypes.cpp.
References geometry_msgs::msg::Twist::deserialize().
getKey()
bool geometry_msgs::msg::TwistPubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file TwistPubSubTypes.cpp.
References geometry_msgs::msg::Twist::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and geometry_msgs::msg::Twist::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> geometry_msgs::msg::TwistPubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file TwistPubSubTypes.cpp.
References geometry_msgs::msg::Twist::getCdrSerializedSize().
is_plain_impl()
static constexpr bool geometry_msgs::msg::TwistPubSubType::is_plain_impl () inline static constexpr private
Definition at line 134 of file TwistPubSubTypes.h.
serialize()
bool geometry_msgs::msg::TwistPubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file TwistPubSubTypes.cpp.
References geometry_msgs::msg::Twist::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* geometry_msgs::msg::TwistPubSubType::m_keyBuffer
Definition at line 132 of file TwistPubSubTypes.h.
Referenced by getKey(), TwistPubSubType(), and ~TwistPubSubType().
m_md5
MD5 geometry_msgs::msg::TwistPubSubType::m_md5
Definition at line 131 of file TwistPubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
TwistPubSubTypes.h
TwistPubSubTypes.cpp