CARLA: carla::sensor::data::RadarData Class Reference
carla::sensor::data::RadarData Class Reference
#include <RadarData.h>
Public Member Functions
size_t GetDetectionCount () const
Returns the number of current detections.
RadarData & operator= (RadarData &&)=default
RadarData ()=default
void Reset ()
Deletes the current detections.
void SetResolution (uint32_t resolution)
Set a new resolution for the RadarData.
void WriteDetection (RadarDetection detection)
Adds a new detection.
Static Public Attributes
static constexpr auto detection_size = sizeof(RadarDetection)
Private Attributes
std::vector< RadarDetection > _detections
Friends
class carla::ros2::ROS2
class s11n::RadarSerializer
Detailed Description
Definition at line 34 of file RadarData.h.
Constructor & Destructor Documentation
RadarData()
carla::sensor::data::RadarData::RadarData () explicit default
Member Function Documentation
GetDetectionCount()
size_t carla::sensor::data::RadarData::GetDetectionCount () const inline
Returns the number of current detections.
Definition at line 58 of file RadarData.h.
References _detections.
Referenced by carla::ros2::ROS2::ProcessDataFromRadar().
operator=()
RadarData & carla::sensor::data::RadarData::operator= (RadarData &&) default
Reset()
void carla::sensor::data::RadarData::Reset () inline
Deletes the current detections.
It doesn't change the resolution nor the allocated memory.
Definition at line 64 of file RadarData.h.
References _detections.
Referenced by ARadar::PostPhysTick().
SetResolution()
void carla::sensor::data::RadarData::SetResolution (uint32_t resolution) inline
Set a new resolution for the RadarData.
Allocates / Deallocates space in memory if needed.
Warning
This is expensive, not to be called each tick!
Definition at line 49 of file RadarData.h.
References _detections.
Referenced by ARadar::SetPointsPerSecond().
WriteDetection()
void carla::sensor::data::RadarData::WriteDetection (RadarDetection detection) inline
Adds a new detection.
Definition at line 69 of file RadarData.h.
References _detections.
Referenced by ARadar::SendLineTraces().
Friends And Related Symbol Documentation
carla::ros2::ROS2
friend class carla::ros2::ROS2 friend
Definition at line 77 of file RadarData.h.
s11n::RadarSerializer
friend class s11n::RadarSerializer friend
Definition at line 76 of file RadarData.h.
Member Data Documentation
_detections
std::vector<RadarDetection> carla::sensor::data::RadarData::_detections private
Definition at line 74 of file RadarData.h.
Referenced by GetDetectionCount(), carla::ros2::ROS2::ProcessDataFromRadar(), Reset(), carla::sensor::s11n::RadarSerializer::Serialize(), SetResolution(), and WriteDetection().
detection_size
constexpr auto carla::sensor::data::RadarData::detection_size = sizeof(RadarDetection) static constexpr
Definition at line 41 of file RadarData.h.
The documentation for this class was generated from the following file:
RadarData.h