CARLA: CarlaRecorderFrames Class Reference
CarlaRecorderFrames Class Reference
#include <CarlaRecorderFrames.h>
Public Member Functions
CarlaRecorderFrames (void)
void Reset ()
void SetFrame (double DeltaSeconds)
void WriteEnd (std::ostream &OutFile)
void WriteStart (std::ostream &OutFile)
Private Attributes
CarlaRecorderFrame Frame
std::streampos OffsetPreviousFrame
Detailed Description
Definition at line 25 of file CarlaRecorderFrames.h.
Constructor & Destructor Documentation
CarlaRecorderFrames()
CarlaRecorderFrames::CarlaRecorderFrames (void)
Definition at line 23 of file CarlaRecorderFrames.cpp.
References Reset().
Member Function Documentation
Reset()
void CarlaRecorderFrames::Reset (void)
Definition at line 28 of file CarlaRecorderFrames.cpp.
References CarlaRecorderFrame::DurationThis, CarlaRecorderFrame::Elapsed, Frame, CarlaRecorderFrame::Id, and OffsetPreviousFrame.
Referenced by CarlaRecorderFrames(), and ACarlaRecorder::Start().
SetFrame()
void CarlaRecorderFrames::SetFrame (double DeltaSeconds)
Definition at line 36 of file CarlaRecorderFrames.cpp.
References CarlaRecorderFrame::DurationThis, CarlaRecorderFrame::Elapsed, Frame, and CarlaRecorderFrame::Id.
Referenced by ACarlaRecorder::Write().
WriteEnd()
void CarlaRecorderFrames::WriteEnd (std::ostream & OutFile)
Definition at line 83 of file CarlaRecorderFrames.cpp.
References FrameEnd.
Referenced by ACarlaRecorder::Write().
WriteStart()
void CarlaRecorderFrames::WriteStart (std::ostream & OutFile)
Definition at line 52 of file CarlaRecorderFrames.cpp.
References CarlaRecorderFrame::DurationThis, CarlaRecorderFrame::Elapsed, Frame, FrameStart, CarlaRecorderFrame::Id, and OffsetPreviousFrame.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
Frame
CarlaRecorderFrame CarlaRecorderFrames::Frame private
Definition at line 40 of file CarlaRecorderFrames.h.
Referenced by Reset(), SetFrame(), and WriteStart().
OffsetPreviousFrame
std::streampos CarlaRecorderFrames::OffsetPreviousFrame private
Definition at line 41 of file CarlaRecorderFrames.h.
Referenced by Reset(), and WriteStart().
The documentation for this class was generated from the following files:
CarlaRecorderFrames.h
CarlaRecorderFrames.cpp