CARLA: CarlaRecorderEventsParent Class Reference
CarlaRecorderEventsParent Class Reference
#include <CarlaRecorderEventParent.h>
Public Member Functions
void Add (const CarlaRecorderEventParent &Event)
void Clear (void)
const std::vector< CarlaRecorderEventParent > & GetEvents ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderEventParent > Events
Detailed Description
Definition at line 21 of file CarlaRecorderEventParent.h.
Member Function Documentation
Add()
void CarlaRecorderEventsParent::Add (const CarlaRecorderEventParent & Event)
Definition at line 34 of file CarlaRecorderEventParent.cpp.
References Events.
Referenced by FFrameData::AddEvent(), ACarlaRecorder::AddEvent(), and Read().
Clear()
void CarlaRecorderEventsParent::Clear (void)
Definition at line 29 of file CarlaRecorderEventParent.cpp.
References Events.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetEvents()
const std::vector< CarlaRecorderEventParent > & CarlaRecorderEventsParent::GetEvents ()
Definition at line 82 of file CarlaRecorderEventParent.cpp.
References Events.
Read()
void CarlaRecorderEventsParent::Read (std::istream & InFile)
Definition at line 67 of file CarlaRecorderEventParent.cpp.
References Add(), and EventParent.
Referenced by FFrameData::Read().
Write()
void CarlaRecorderEventsParent::Write (std::ostream & OutFile)
Definition at line 39 of file CarlaRecorderEventParent.cpp.
References EventParent, and Events.
Referenced by ACarlaRecorder::Write(), and FFrameData::Write().
Member Data Documentation
Events
std::vector<CarlaRecorderEventParent> CarlaRecorderEventsParent::Events private
Definition at line 32 of file CarlaRecorderEventParent.h.
Referenced by Add(), Clear(), GetEvents(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderEventParent.h
CarlaRecorderEventParent.cpp