CARLA: carla::RecurrentSharedFuture< T > Class Template Reference
carla::RecurrentSharedFuture< T > Class Template Reference
This class is meant to be used similar to a shared future, but the value can be set any number of times.
#include <RecurrentSharedFuture.h>
Classes
struct mapped_type
Public Types
using SharedException = detail::SharedException
Public Member Functions
template<typename ExceptionT >
void SetException (ExceptionT &&exception)
Set a exception, this exception will be thrown on all the threads waiting.
template<typename T2 >
void SetValue (const T2 &value)
Set the value and notify all waiting threads.
boost::optional< T > WaitFor (time_duration timeout)
Wait until the next value is set.
Private Attributes
std::condition_variable _cv
std::map< const char *, mapped_type > _map
std::mutex _mutex
Detailed Description
template<typename T>
class carla::RecurrentSharedFuture< T >
This class is meant to be used similar to a shared future, but the value can be set any number of times.
Definition at line 43 of file RecurrentSharedFuture.h.
Member Typedef Documentation
SharedException
template<typename T > using carla::RecurrentSharedFuture< T >::SharedException = detail::SharedException
Definition at line 46 of file RecurrentSharedFuture.h.
Member Function Documentation
SetException()
template<typename T > template<typename ExceptionT > void carla::RecurrentSharedFuture< T >::SetException (ExceptionT && exception)
Set a exception, this exception will be thrown on all the threads waiting.
Note
The exception will be stored on a SharedException and thrown as such.
Definition at line 139 of file RecurrentSharedFuture.h.
Referenced by TEST().
SetValue()
template<typename T > template<typename T2 > void carla::RecurrentSharedFuture< T >::SetValue (const T2 & value)
Set the value and notify all waiting threads.
Definition at line 128 of file RecurrentSharedFuture.h.
Referenced by TEST().
WaitFor()
template<typename T > boost::optional< T > carla::RecurrentSharedFuture< T >::WaitFor (time_duration timeout)
Wait until the next value is set.
Any number of threads can be waiting simultaneously.
Returns
empty optional if the timeout is met.
Definition at line 113 of file RecurrentSharedFuture.h.
References carla::detail::thread_tag, carla::throw_exception(), and carla::time_duration::to_chrono().
Referenced by TEST(), TEST(), and TEST().
Member Data Documentation
_cv
template<typename T > std::condition_variable carla::RecurrentSharedFuture< T >::_cv private
Definition at line 70 of file RecurrentSharedFuture.h.
_map
template<typename T > std::map<const char *, mapped_type> carla::RecurrentSharedFuture< T >::_map private
Definition at line 77 of file RecurrentSharedFuture.h.
_mutex
template<typename T > std::mutex carla::RecurrentSharedFuture< T >::_mutex private
Definition at line 68 of file RecurrentSharedFuture.h.
The documentation for this class was generated from the following file:
RecurrentSharedFuture.h