CARLA: carla::rpc::Client Class Reference
carla::rpc::Client Class Reference
#include <Client.h>
Public Member Functions
template<typename... Args>
void async_call (const std::string &function, Args &&... args)
template<typename... Args>
auto call (const std::string &function, Args &&... args)
template<typename... Args>
Client (Args &&... args)
auto get_timeout () const
void set_timeout (int64_t value)
Private Attributes
::rpc::client _client
Detailed Description
Definition at line 16 of file rpc/Client.h.
Constructor & Destructor Documentation
Client()
template<typename... Args> carla::rpc::Client::Client (Args &&... args) inline explicit
Definition at line 20 of file rpc/Client.h.
Member Function Documentation
async_call()
template<typename... Args> void carla::rpc::Client::async_call (const std::string & function, Args &&... args) inline
Definition at line 37 of file rpc/Client.h.
References _client, and carla::rpc::Metadata::MakeAsync().
Referenced by carla::client::detail::Client::Pimpl::AsyncCall().
call()
template<typename... Args> auto carla::rpc::Client::call (const std::string & function, Args &&... args) inline
Definition at line 32 of file rpc/Client.h.
References _client, and carla::rpc::Metadata::MakeSync().
Referenced by carla::client::detail::Client::Pimpl::RawCall().
get_timeout()
auto carla::rpc::Client::get_timeout () const inline
Definition at line 27 of file rpc/Client.h.
References _client.
Referenced by carla::client::detail::Client::Pimpl::GetTimeout().
set_timeout()
void carla::rpc::Client::set_timeout (int64_t value) inline
Definition at line 23 of file rpc/Client.h.
References _client.
Referenced by carla::client::detail::Client::Pimpl::Pimpl().
Member Data Documentation
_client
::rpc::client carla::rpc::Client::_client private
Definition at line 43 of file rpc/Client.h.
Referenced by async_call(), call(), get_timeout(), and set_timeout().
The documentation for this class was generated from the following file:
rpc/Client.h