CARLA: carla::client::World Class Reference
carla::client::World Class Reference
#include <World.h>
Public Member Functions
void ApplyColorTextureToObject (const std::string &actor_name, const rpc::MaterialParameter &parameter, const rpc::TextureColor &Texture)
void ApplyColorTextureToObjects (const std::vector< std::string > &objects_names, const rpc::MaterialParameter &parameter, const rpc::TextureColor &Texture)
void ApplyFloatColorTextureToObject (const std::string &actor_name, const rpc::MaterialParameter &parameter, const rpc::TextureFloatColor &Texture)
void ApplyFloatColorTextureToObjects (const std::vector< std::string > &objects_names, const rpc::MaterialParameter &parameter, const rpc::TextureFloatColor &Texture)
uint64_t ApplySettings (const rpc::EpisodeSettings &settings, time_duration timeout)
void ApplyTexturesToObject (const std::string &actor_name, const rpc::TextureColor &diffuse_texture, const rpc::TextureFloatColor &emissive_texture, const rpc::TextureFloatColor &normal_texture, const rpc::TextureFloatColor &ao_roughness_metallic_emissive_texture)
void ApplyTexturesToObjects (const std::vector< std::string > &objects_names, const rpc::TextureColor &diffuse_texture, const rpc::TextureFloatColor &emissive_texture, const rpc::TextureFloatColor &normal_texture, const rpc::TextureFloatColor &ao_roughness_metallic_emissive_texture)
std::vector< rpc::LabelledPoint > CastRay (geom::Location start_location, geom::Location end_location) const
void EnableEnvironmentObjects (std::vector< uint64_t > env_objects_ids, bool enable) const
void FreezeAllTrafficLights (bool frozen)
SharedPtr< Actor > GetActor (ActorId id) const
Find actor by id, return nullptr if not found.
SharedPtr< ActorList > GetActors () const
Return a list with all the actors currently present in the world.
SharedPtr< ActorList > GetActors (const std::vector< ActorId > &actor_ids) const
Return a list with the actors requested by ActorId.
SharedPtr< BlueprintLibrary > GetBlueprintLibrary () const
Return the list of blueprints available in this world.
std::vector< rpc::EnvironmentObject > GetEnvironmentObjects (uint8_t queried_tag) const
detail::EpisodeProxy GetEpisode () const
uint64_t GetId () const
Get the id of the episode associated with this world.
float GetIMUISensorGravity () const
Get Gravity value used for IMUI Sensor accelerometer calculation.
std::vector< geom::BoundingBox > GetLevelBBs (uint8_t queried_tag) const
Returns all the BBs of all the elements of the level.
SharedPtr< LightManager > GetLightManager () const
SharedPtr< Map > GetMap () const
Return the map that describes this world.
std::vector< std::string > GetNamesOfAllObjects () const
boost::optional< geom::Location > GetRandomLocationFromNavigation () const
Get a random location from the pedestrians navigation mesh.
rpc::EpisodeSettings GetSettings () const
WorldSnapshot GetSnapshot () const
Return a snapshot of the world at this moment.
SharedPtr< Actor > GetSpectator () const
Return the spectator actor.
SharedPtr< Actor > GetTrafficLight (const Landmark &landmark) const
SharedPtr< Actor > GetTrafficLightFromOpenDRIVE (const road::SignId &sign_id) const
std::vector< SharedPtr< Actor > > GetTrafficLightsFromWaypoint (const Waypoint &waypoint, double distance) const
std::vector< SharedPtr< Actor > > GetTrafficLightsInJunction (const road::JuncId junc_id) const
SharedPtr< Actor > GetTrafficSign (const Landmark &landmark) const
rpc::VehicleLightStateList GetVehiclesLightStates () const
Returns a list of pairs where the firts element is the vehicle ID and the second one is the light state.
rpc::WeatherParameters GetWeather () const
Retrieve the weather parameters currently active in the world.
boost::optional< rpc::LabelledPoint > GroundProjection (geom::Location location, float search_distance=10000.0) const
void LoadLevelLayer (rpc::MapLayer map_layers) const
DebugHelper MakeDebugHelper () const
size_t OnTick (std::function< void(WorldSnapshot)> callback)
Register a callback to be called every time a world tick is received.
World & operator= (const World &)=default
World & operator= (World &&)=default
boost::optional< rpc::LabelledPoint > ProjectPoint (geom::Location location, geom::Vector3D direction, float search_distance=10000.f) const
void RemoveOnTick (size_t callback_id)
Remove a callback registered with OnTick.
void ResetAllTrafficLights ()
void SetIMUISensorGravity (float NewIMUISensorGravity)
Set Gravity value used for IMUI Sensor accelerometer calculation.
void SetPedestriansCrossFactor (float percentage)
set the probability that an agent could cross the roads in its path following percentage of 0.0f means no pedestrian can cross roads percentage of 0.5f means 50% of all pedestrians can cross roads percentage of 1.0f means all pedestrians can cross roads if needed
void SetPedestriansSeed (unsigned int seed)
set the seed to use with random numbers in the pedestrians module
void SetWeather (const rpc::WeatherParameters &weather)
Change the weather in the simulation.
SharedPtr< Actor > SpawnActor (const ActorBlueprint &blueprint, const geom::Transform &transform, Actor *parent=nullptr, rpc::AttachmentType attachment_type=rpc::AttachmentType::Rigid, const std::string &socket_name="")
Spawn an actor into the world based on the blueprint provided at transform.
uint64_t Tick (time_duration timeout)
Signal the simulator to continue to next tick (only has effect on synchronous mode).
SharedPtr< Actor > TrySpawnActor (const ActorBlueprint &blueprint, const geom::Transform &transform, Actor *parent=nullptr, rpc::AttachmentType attachment_type=rpc::AttachmentType::Rigid, const std::string &socket_name="") noexcept
Same as SpawnActor but return nullptr on failure instead of throwing an exception.
void UnloadLevelLayer (rpc::MapLayer map_layers) const
WorldSnapshot WaitForTick (time_duration timeout) const
Block calling thread until a world tick is received.
World (const World &)=default
World (detail::EpisodeProxy episode)
World (World &&)=default
~World ()
Private Attributes
detail::EpisodeProxy _episode
Detailed Description
Definition at line 46 of file World.h.
Constructor & Destructor Documentation
World() [1/3]
carla::client::World::World (detail::EpisodeProxy episode) inline explicit
Definition at line 49 of file World.h.
~World()
carla::client::World::~World () inline
Definition at line 51 of file World.h.
World() [2/3]
carla::client::World::World (const World &) default
World() [3/3]
carla::client::World::World (World &&) default
Member Function Documentation
ApplyColorTextureToObject()
void carla::client::World::ApplyColorTextureToObject (const std::string & actor_name, const rpc::MaterialParameter & parameter, const rpc::TextureColor & Texture)
Definition at line 309 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by ApplyTexturesToObject().
ApplyColorTextureToObjects()
void carla::client::World::ApplyColorTextureToObjects (const std::vector< std::string > & objects_names, const rpc::MaterialParameter & parameter, const rpc::TextureColor & Texture)
Definition at line 316 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by ApplyTexturesToObjects().
ApplyFloatColorTextureToObject()
void carla::client::World::ApplyFloatColorTextureToObject (const std::string & actor_name, const rpc::MaterialParameter & parameter, const rpc::TextureFloatColor & Texture)
Definition at line 323 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by ApplyTexturesToObject().
ApplyFloatColorTextureToObjects()
void carla::client::World::ApplyFloatColorTextureToObjects (const std::vector< std::string > & objects_names, const rpc::MaterialParameter & parameter, const rpc::TextureFloatColor & Texture)
Definition at line 330 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by ApplyTexturesToObjects().
ApplySettings()
uint64_t carla::client::World::ApplySettings (const rpc::EpisodeSettings & settings, time_duration timeout)
Returns
The id of the frame when the settings were applied.
Definition at line 56 of file World.cpp.
References _episode, carla::rpc::EpisodeSettings::fixed_delta_seconds, GetSnapshot(), carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), carla::log_warning(), carla::time_duration::milliseconds(), and Tick().
ApplyTexturesToObject()
void carla::client::World::ApplyTexturesToObject (const std::string & actor_name, const rpc::TextureColor & diffuse_texture, const rpc::TextureFloatColor & emissive_texture, const rpc::TextureFloatColor & normal_texture, const rpc::TextureFloatColor & ao_roughness_metallic_emissive_texture)
Definition at line 341 of file World.cpp.
References ApplyColorTextureToObject(), ApplyFloatColorTextureToObject(), carla::rpc::Texture< T >::GetHeight(), carla::rpc::Texture< T >::GetWidth(), carla::rpc::Tex_Ao_Roughness_Metallic_Emissive, carla::rpc::Tex_Diffuse, carla::rpc::Tex_Emissive, and carla::rpc::Tex_Normal.
ApplyTexturesToObjects()
void carla::client::World::ApplyTexturesToObjects (const std::vector< std::string > & objects_names, const rpc::TextureColor & diffuse_texture, const rpc::TextureFloatColor & emissive_texture, const rpc::TextureFloatColor & normal_texture, const rpc::TextureFloatColor & ao_roughness_metallic_emissive_texture)
Definition at line 369 of file World.cpp.
References ApplyColorTextureToObjects(), ApplyFloatColorTextureToObjects(), carla::rpc::Texture< T >::GetHeight(), carla::rpc::Texture< T >::GetWidth(), carla::rpc::Tex_Ao_Roughness_Metallic_Emissive, carla::rpc::Tex_Diffuse, carla::rpc::Tex_Emissive, and carla::rpc::Tex_Normal.
CastRay()
std::vector< rpc::LabelledPoint > carla::client::World::CastRay (geom::Location start_location, geom::Location end_location) const
Definition at line 266 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
EnableEnvironmentObjects()
void carla::client::World::EnableEnvironmentObjects (std::vector< uint64_t > env_objects_ids, bool enable) const
Definition at line 245 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
FreezeAllTrafficLights()
void carla::client::World::FreezeAllTrafficLights (bool frozen)
Definition at line 233 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetActor()
SharedPtr< Actor > carla::client::World::GetActor (ActorId id) const
Find actor by id, return nullptr if not found.
Definition at line 107 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::nav::WalkerManager::GetAllTrafficLightWaypoints().
GetActors() [1/2]
SharedPtr< ActorList > carla::client::World::GetActors () const
Return a list with all the actors currently present in the world.
Definition at line 115 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::client::TrafficLight::GetGroupTrafficLights(), GetTrafficLight(), GetTrafficLightFromOpenDRIVE(), GetTrafficSign(), carla::client::RssSensor::TickRssSensor(), and carla::traffic_manager::ALSM::Update().
GetActors() [2/2]
SharedPtr< ActorList > carla::client::World::GetActors (const std::vector< ActorId > & actor_ids) const
Return a list with the actors requested by ActorId.
Definition at line 121 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetBlueprintLibrary()
SharedPtr< BlueprintLibrary > carla::client::World::GetBlueprintLibrary () const
Return the list of blueprints available in this world.
This blueprints can be used to spawning actor into the world.
Definition at line 36 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetEnvironmentObjects()
std::vector< rpc::EnvironmentObject > carla::client::World::GetEnvironmentObjects (uint8_t queried_tag) const
Definition at line 241 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetEpisode()
detail::EpisodeProxy carla::client::World::GetEpisode () const inline
Definition at line 174 of file World.h.
References _episode.
GetId()
uint64_t carla::client::World::GetId () const inline
Get the id of the episode associated with this world.
Definition at line 60 of file World.h.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::GetId().
GetIMUISensorGravity()
float carla::client::World::GetIMUISensorGravity () const
Get Gravity value used for IMUI Sensor accelerometer calculation.
Definition at line 94 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetLevelBBs()
std::vector< geom::BoundingBox > carla::client::World::GetLevelBBs (uint8_t queried_tag) const
Returns all the BBs of all the elements of the level.
Definition at line 237 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetLightManager()
SharedPtr< LightManager > carla::client::World::GetLightManager () const
Definition at line 229 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetMap()
SharedPtr< Map > carla::client::World::GetMap () const
Return the map that describes this world.
Definition at line 24 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by GetTrafficLightsInJunction(), carla::client::RssSensor::Listen(), carla::client::Client::LoadWorldIfDifferent(), and carla::traffic_manager::TrafficManagerLocal::SetupLocalMap().
GetNamesOfAllObjects()
std::vector< std::string > carla::client::World::GetNamesOfAllObjects () const
Definition at line 337 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetRandomLocationFromNavigation()
boost::optional< geom::Location > carla::client::World::GetRandomLocationFromNavigation () const
Get a random location from the pedestrians navigation mesh.
Definition at line 44 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetSettings()
rpc::EpisodeSettings carla::client::World::GetSettings () const
Definition at line 52 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::client::RssSensor::TickRssSensor().
GetSnapshot()
WorldSnapshot carla::client::World::GetSnapshot () const
Return a snapshot of the world at this moment.
Definition at line 103 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by ApplySettings(), carla::traffic_manager::ALSM::Reset(), carla::traffic_manager::TrafficManagerLocal::Run(), carla::traffic_manager::ALSM::Update(), carla::traffic_manager::MotionPlanStage::Update(), and carla::traffic_manager::TrafficLightStage::Update().
GetSpectator()
SharedPtr< Actor > carla::client::World::GetSpectator () const
Return the spectator actor.
The spectator controls the view in the simulator window.
Definition at line 48 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
GetTrafficLight()
SharedPtr< Actor > carla::client::World::GetTrafficLight (const Landmark & landmark) const
Definition at line 194 of file World.cpp.
References GetActors(), carla::client::Landmark::GetId(), carla::client::TrafficSign::GetSignId(), and carla::StringUtil::Match().
Referenced by GetTrafficLightsFromWaypoint().
GetTrafficLightFromOpenDRIVE()
SharedPtr< Actor > carla::client::World::GetTrafficLightFromOpenDRIVE (const road::SignId & sign_id) const
Definition at line 210 of file World.cpp.
References GetActors(), carla::client::TrafficSign::GetSignId(), and carla::StringUtil::Match().
Referenced by GetTrafficLightsInJunction().
GetTrafficLightsFromWaypoint()
std::vector< SharedPtr< Actor > > carla::client::World::GetTrafficLightsFromWaypoint (const Waypoint & waypoint, double distance) const
Definition at line 271 of file World.cpp.
References carla::client::Waypoint::GetAllLandmarksInDistance(), GetTrafficLight(), and carla::road::SignalType::IsTrafficLight().
GetTrafficLightsInJunction()
std::vector< SharedPtr< Actor > > carla::client::World::GetTrafficLightsInJunction (const road::JuncId junc_id) const
Definition at line 291 of file World.cpp.
References carla::road::Junction::GetControllers(), GetMap(), and GetTrafficLightFromOpenDRIVE().
GetTrafficSign()
SharedPtr< Actor > carla::client::World::GetTrafficSign (const Landmark & landmark) const
Definition at line 178 of file World.cpp.
References GetActors(), carla::client::Landmark::GetId(), carla::client::TrafficSign::GetSignId(), and carla::StringUtil::Match().
GetVehiclesLightStates()
rpc::VehicleLightStateList carla::client::World::GetVehiclesLightStates () const
Returns a list of pairs where the firts element is the vehicle ID and the second one is the light state.
Definition at line 40 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::traffic_manager::VehicleLightStage::UpdateWorldInfo().
GetWeather()
rpc::WeatherParameters carla::client::World::GetWeather () const
Retrieve the weather parameters currently active in the world.
Definition at line 86 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::traffic_manager::VehicleLightStage::UpdateWorldInfo().
GroundProjection()
boost::optional< rpc::LabelledPoint > carla::client::World::GroundProjection (geom::Location location, float search_distance = 10000.0) const
Definition at line 260 of file World.cpp.
References ProjectPoint().
LoadLevelLayer()
void carla::client::World::LoadLevelLayer (rpc::MapLayer map_layers) const
Definition at line 28 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
MakeDebugHelper()
DebugHelper carla::client::World::MakeDebugHelper () const inline
Definition at line 170 of file World.h.
References _episode.
OnTick()
size_t carla::client::World::OnTick (std::function< void(WorldSnapshot)> callback)
Register a callback to be called every time a world tick is received.
Returns
ID of the callback, use it to remove the callback.
Definition at line 156 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
operator=() [1/2]
World & carla::client::World::operator= (const World &) default
operator=() [2/2]
World & carla::client::World::operator= (World &&) default
ProjectPoint()
boost::optional< rpc::LabelledPoint > carla::client::World::ProjectPoint (geom::Location location, geom::Vector3D direction, float search_distance = 10000.f) const
Definition at line 251 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by GroundProjection().
RemoveOnTick()
void carla::client::World::RemoveOnTick (size_t callback_id)
Remove a callback registered with OnTick.
Definition at line 160 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
ResetAllTrafficLights()
void carla::client::World::ResetAllTrafficLights ()
Definition at line 225 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Referenced by carla::traffic_manager::TrafficManagerLocal::SetRandomDeviceSeed().
SetIMUISensorGravity()
void carla::client::World::SetIMUISensorGravity (float NewIMUISensorGravity)
Set Gravity value used for IMUI Sensor accelerometer calculation.
Definition at line 98 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
SetPedestriansCrossFactor()
void carla::client::World::SetPedestriansCrossFactor (float percentage)
set the probability that an agent could cross the roads in its path following percentage of 0.0f means no pedestrian can cross roads percentage of 0.5f means 50% of all pedestrians can cross roads percentage of 1.0f means all pedestrians can cross roads if needed
Definition at line 170 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
SetPedestriansSeed()
void carla::client::World::SetPedestriansSeed (unsigned int seed)
set the seed to use with random numbers in the pedestrians module
Definition at line 174 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
SetWeather()
void carla::client::World::SetWeather (const rpc::WeatherParameters & weather)
Change the weather in the simulation.
Definition at line 90 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
SpawnActor()
SharedPtr< Actor > carla::client::World::SpawnActor (const ActorBlueprint & blueprint, const geom::Transform & transform, Actor * parent = nullptr, rpc::AttachmentType attachment_type = rpc::AttachmentType::Rigid, const std::string & socket_name = "")
Spawn an actor into the world based on the blueprint provided at transform.
If a parent is provided, the actor is attached to parent.
Definition at line 127 of file World.cpp.
References _episode, carla::client::Inherit, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
Tick()
uint64_t carla::client::World::Tick (time_duration timeout)
Signal the simulator to continue to next tick (only has effect on synchronous mode).
Returns
The id of the frame that this call started.
Definition at line 164 of file World.cpp.
References _episode, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::time_duration::milliseconds().
Referenced by ApplySettings().
TrySpawnActor()
SharedPtr< Actor > carla::client::World::TrySpawnActor (const ActorBlueprint & blueprint, const geom::Transform & transform, Actor * parent = nullptr, rpc::AttachmentType attachment_type = rpc::AttachmentType::Rigid, const std::string & socket_name = "") noexcept
Same as SpawnActor but return nullptr on failure instead of throwing an exception.
Definition at line 136 of file World.cpp.
UnloadLevelLayer()
void carla::client::World::UnloadLevelLayer (rpc::MapLayer map_layers) const
Definition at line 32 of file World.cpp.
References _episode, and carla::client::detail::EpisodeProxyImpl< PointerT >::Lock().
WaitForTick()
WorldSnapshot carla::client::World::WaitForTick (time_duration timeout) const
Block calling thread until a world tick is received.
Definition at line 149 of file World.cpp.
References _episode, carla::client::detail::EpisodeProxyImpl< PointerT >::Lock(), and carla::time_duration::milliseconds().
Member Data Documentation
_episode
detail::EpisodeProxy carla::client::World::_episode private
Definition at line 244 of file World.h.
Referenced by ApplyColorTextureToObject(), ApplyColorTextureToObjects(), ApplyFloatColorTextureToObject(), ApplyFloatColorTextureToObjects(), ApplySettings(), CastRay(), EnableEnvironmentObjects(), FreezeAllTrafficLights(), GetActor(), GetActors(), GetActors(), GetBlueprintLibrary(), GetEnvironmentObjects(), GetEpisode(), GetId(), GetIMUISensorGravity(), GetLevelBBs(), GetLightManager(), GetMap(), GetNamesOfAllObjects(), GetRandomLocationFromNavigation(), GetSettings(), GetSnapshot(), GetSpectator(), GetVehiclesLightStates(), GetWeather(), LoadLevelLayer(), MakeDebugHelper(), OnTick(), ProjectPoint(), RemoveOnTick(), ResetAllTrafficLights(), SetIMUISensorGravity(), SetPedestriansCrossFactor(), SetPedestriansSeed(), SetWeather(), SpawnActor(), Tick(), UnloadLevelLayer(), and WaitForTick().
The documentation for this class was generated from the following files:
World.h
World.cpp