CARLA: CaService Class Reference
CaService Class Reference
#include <CaService.h>
Public Member Functions
CaService (URandomEngine *random_engine)
CAM_t GetCamMessage ()
void SetAccelerationStandardDeviation (const FVector &Vec)
void SetGNSSDeviation (const float noise_lat_stddev, const float noise_lon_stddev, const float noise_alt_stddev, const float noise_head_stddev, const float noise_lat_bias, const float noise_lon_bias, const float noise_alt_bias, const float noise_head_bias)
void SetOwner (UWorld *world, AActor *Owner)
void SetParams (const float GenCamMin, const float GenCamMax, const bool FixedRate)
void SetVelDeviation (const float noise_vel_stddev_x)
void SetYawrateDeviation (const float noise_yawrate_stddev, const float noise_yawrate_bias)
bool Trigger (float DeltaSeconds)
Private Member Functions
void AddBasicContainer (CAMContainer::BasicContainer_t &BasicContainer)
void AddBasicVehicleContainerHighFrequency (CAMContainer::HighFrequencyContainer_t &hfc, float DeltaTime)
void AddCooperativeAwarenessMessage (CAMContainer::CoopAwareness_t &CoopAwarenessMessage, float DeltaTime)
void AddLowFrequencyContainer (CAMContainer::LowFrequencyContainer_t &lfc)
void AddRSUContainerHighFrequency (CAMContainer::HighFrequencyContainer_t &hfc)
ITSContainer::SpeedValue_t BuildSpeedValue (const float vel)
bool CheckHeadingDelta (float DeltaSeconds)
bool CheckPositionDelta (float DeltaSeconds)
bool CheckSpeedDelta (float DeltaSeconds)
bool CheckTriggeringConditions (float DeltaSeconds)
carla::geom::Vector3D ComputeAccelerometer (const float DeltaTime)
const carla::geom::Vector3D ComputeAccelerometerNoise (const FVector &Accelerometer)
float ComputeSpeed ()
const float ComputeYawNoise (const FVector &Gyroscope)
float ComputeYawRate ()
CAM_t CreateCooperativeAwarenessMessage (float DeltaTime)
void CreateITSPduHeader (CAM_t &message)
void GenerateCamMessage (float DeltaTime)
double GetFVectorAngle (const FVector &a, const FVector &b)
float GetHeading ()
FVector GetReferencePosition ()
ITSContainer::StationType_t GetStationType ()
long GetVehicleRole ()
Private Attributes
float AltitudeBias
float AltitudeDeviation
carla::geom::GeoLocation CurrentGeoReference
float HeadingBias
float HeadingDeviation
float LatitudeBias
float LatitudeDeviation
float LongitudeBias
float LongitudeDeviation
AActor * mActorOwner
CAM_t mCAMMessage
FCarlaActor * mCarlaActor
UCarlaEpisode * mCarlaEpisode
bool mDccRestriction
double mElapsedTime
bool mFixedRate
float mGenCam
unsigned int mGenCamLowDynamicsCounter
unsigned int mGenCamLowDynamicsLimit
float mGenCamMax
float mGenCamMin
float mGenDeltaTimeMod
std::chrono::milliseconds mGenerationDelta0
float mGenerationInterval
FVector mLastCamHeading
FVector mLastCamPosition
float mLastCamSpeed
float mLastCamTimeStamp
float mLastLowCamTimeStamp
const long mMessageId = ITSContainer::messageID_cam
const long mProtocolVersion = 2
URandomEngine * mRandomEngine
long mStationId
long mStationType
ACarlaWheeledVehicle * mVehicle
UWorld * mWorld
float PrevDeltaTime
Used to compute the acceleration.
std::array< FVector, 2 > PrevLocation
Used to compute the acceleration.
FVector StdDevAccel
Standard deviation for acceleration settings.
FVector VehicleHeading
FVector VehiclePosition
float VehicleSpeed
float VelocityDeviation
float YawrateBias
float YawrateDeviation
Detailed Description
Definition at line 20 of file CaService.h.
Constructor & Destructor Documentation
CaService()
CaService::CaService (URandomEngine * random_engine)
Definition at line 33 of file CaService.cpp.
References mGenerationDelta0, and mRandomEngine.
Member Function Documentation
AddBasicContainer()
void CaService::AddBasicContainer (CAMContainer::BasicContainer_t & BasicContainer) private
Definition at line 418 of file CaService.cpp.
References ITSContainer::ReferencePosition::altitude, ITSContainer::Altitude::altitudeConfidence, ITSContainer::AltitudeConfidence_unavailable, ITSContainer::Altitude::altitudeValue, ITSContainer::AltitudeValue_oneCentimeter, GetReferencePosition(), ITSContainer::HeadingValue_unavailable, ITSContainer::ReferencePosition::latitude, ITSContainer::Latitude_oneMicroDegreeNorth, ITSContainer::ReferencePosition::longitude, ITSContainer::Longitude_oneMicroDegreeEast, mStationType, ITSContainer::ReferencePosition::positionConfidenceEllipse, CAMContainer::BasicContainer::referencePosition, ITSContainer::SemiAxisLength_unavailable, ITSContainer::PosConfidenceEllipse::semiMajorConfidence, ITSContainer::PosConfidenceEllipse::semiMajorOrientation, ITSContainer::PosConfidenceEllipse::semiMinorConfidence, and CAMContainer::BasicContainer::stationType.
Referenced by AddCooperativeAwarenessMessage().
AddBasicVehicleContainerHighFrequency()
void CaService::AddBasicVehicleContainerHighFrequency (CAMContainer::HighFrequencyContainer_t & hfc, float DeltaTime) private
Definition at line 468 of file CaService.cpp.
References ITSContainer::AccelerationConfidence_unavailable, CAMContainer::BasicVehicleContainerHighFrequency::accelerationControlAvailable, CAMContainer::HighFrequencyContainer::basicVehicleContainerHighFrequency, BuildSpeedValue(), CAMContainer::BasicVehicleContainerHighFrequency::cenDsrcTollingZoneAvailable, ComputeAccelerometer(), ComputeSpeed(), ComputeYawRate(), CAMContainer::BasicVehicleContainerHighFrequency::curvature, CAMContainer::BasicVehicleContainerHighFrequency::curvatureCalculationMode, ITSContainer::CurvatureCalculationMode_yarRateUsed, ITSContainer::Curvature::curvatureConfidence, ITSContainer::CurvatureConfidence_unavailable, ITSContainer::Curvature::curvatureValue, ITSContainer::CurvatureValue_unavailable, CAMContainer::BasicVehicleContainerHighFrequency::driveDirection, ITSContainer::DriveDirection_backward, ITSContainer::DriveDirection_forward, UBoundingBoxCalculator::GetActorBoundingBox(), GetHeading(), ACarlaWheeledVehicle::GetVehicleForwardSpeed(), CAMContainer::BasicVehicleContainerHighFrequency::heading, ITSContainer::Heading::headingConfidence, ITSContainer::HeadingConfidence_equalOrWithinOneDegree, ITSContainer::Heading::headingValue, CAMContainer::HighFrequencyContainer_PR_basicVehicleContainerHighFrequency, CAMContainer::BasicVehicleContainerHighFrequency::lanePositionAvailable, CAMContainer::BasicVehicleContainerHighFrequency::lateralAcceleration, CAMContainer::BasicVehicleContainerHighFrequency::lateralAccelerationAvailable, ITSContainer::LateralAcceleration::lateralAccelerationConfidence, ITSContainer::LateralAcceleration::lateralAccelerationValue, ITSContainer::LateralAccelerationValue_pointOneMeterPerSecSquaredToLeft, ITSContainer::LateralAccelerationValue_unavailable, CAMContainer::BasicVehicleContainerHighFrequency::longitudinalAcceleration, ITSContainer::LongitudinalAcceleration::longitudinalAccelerationConfidence, ITSContainer::LongitudinalAcceleration::longitudinalAccelerationValue, ITSContainer::LongitudinalAccelerationValue_pointOneMeterPerSecSquaredForward, ITSContainer::LongitudinalAccelerationValue_unavailable, mActorOwner, mVehicle, CAMContainer::BasicVehicleContainerHighFrequency::performanceClassAvailable, CAMContainer::HighFrequencyContainer::present, CAMContainer::BasicVehicleContainerHighFrequency::speed, ITSContainer::speed::speedConfidence, ITSContainer::SpeedConfidence_equalOrWithInOneCentimerterPerSec, ITSContainer::speed::speedValue, CAMContainer::BasicVehicleContainerHighFrequency::steeringWheelAngleAvailable, carla::geom::Math::ToDegrees(), CAMContainer::BasicVehicleContainerHighFrequency::vehicleLength, ITSContainer::VehicleLength::vehicleLengthConfidenceIndication, ITSContainer::VehicleLengthConfidenceIndication_unavailable, ITSContainer::VehicleLength::vehicleLengthValue, CAMContainer::BasicVehicleContainerHighFrequency::vehicleWidth, CAMContainer::BasicVehicleContainerHighFrequency::verticalAcceleration, CAMContainer::BasicVehicleContainerHighFrequency::verticalAccelerationAvailable, ITSContainer::VerticalAcceleration::verticalAccelerationConfidence, ITSContainer::VerticalAcceleration::verticalAccelerationValue, ITSContainer::VerticalAccelerationValue_pointOneMeterPerSecSquaredUp, ITSContainer::VerticalAccelerationValue_unavailable, carla::geom::Vector3D::x, carla::geom::Vector3D::y, CAMContainer::BasicVehicleContainerHighFrequency::yawRate, ITSContainer::YawRate::yawRateConfidence, ITSContainer::YawRateConfidence_unavailable, ITSContainer::YawRate::yawRateValue, ITSContainer::YawRateValue_degSec_000_01ToLeft, ITSContainer::YawRateValue_unavailable, and carla::geom::Vector3D::z.
Referenced by AddCooperativeAwarenessMessage().
AddCooperativeAwarenessMessage()
void CaService::AddCooperativeAwarenessMessage (CAMContainer::CoopAwareness_t & CoopAwarenessMessage, float DeltaTime) private
Definition at line 381 of file CaService.cpp.
References AddBasicContainer(), AddBasicVehicleContainerHighFrequency(), AddLowFrequencyContainer(), AddRSUContainerHighFrequency(), CAMContainer::CamParameters::basicContainer, CAMContainer::CoopAwareness::camParameters, CAMContainer::CoopAwareness::generationDeltaTime, CAMContainer::GenerationDeltaTime_oneMilliSec, UCarlaEpisode::GetElapsedGameTime(), CAMContainer::CamParameters::highFrequencyContainer, CAMContainer::CamParameters::lowFrequencyContainer, CAMContainer::LowFrequencyContainer_PR_NOTHING, mCarlaEpisode, mElapsedTime, mGenerationDelta0, mLastLowCamTimeStamp, CAMContainer::LowFrequencyContainer::present, scLowFrequencyContainerInterval, CAMContainer::BasicContainer::stationType, ITSContainer::StationType_pedestrian, and ITSContainer::StationType_roadSideUnit.
Referenced by CreateCooperativeAwarenessMessage().
AddLowFrequencyContainer()
void CaService::AddLowFrequencyContainer (CAMContainer::LowFrequencyContainer_t & lfc) private
Definition at line 693 of file CaService.cpp.
References CAMContainer::LowFrequencyContainer::basicVehicleContainerLowFrequency, CAMContainer::BasicVehicleContainerLowFrequency::exteriorLights, ITSContainer::ExteriorLights_fogLightOn, ITSContainer::ExteriorLights_highBeamHeadlightsOn, ITSContainer::ExteriorLights_leftTurnSignalOn, ITSContainer::ExteriorLights_lowBeamHeadlightsOn, ITSContainer::ExteriorLights_parkingLightsOn, ITSContainer::ExteriorLights_reverseLightOn, ITSContainer::ExteriorLights_rightTurnSignalOn, FVehicleLightState::Fog, ACarlaWheeledVehicle::GetVehicleLightState(), GetVehicleRole(), FVehicleLightState::HighBeam, FVehicleLightState::LeftBlinker, FVehicleLightState::LowBeam, CAMContainer::LowFrequencyContainer_PR_basicVehicleContainerLowFrequency, mVehicle, ITSContainer::PathHistory::NumberOfPathPoint, CAMContainer::BasicVehicleContainerLowFrequency::pathHistory, FVehicleLightState::Position, CAMContainer::LowFrequencyContainer::present, FVehicleLightState::Reverse, FVehicleLightState::RightBlinker, and CAMContainer::BasicVehicleContainerLowFrequency::vehicleRole.
Referenced by AddCooperativeAwarenessMessage().
AddRSUContainerHighFrequency()
void CaService::AddRSUContainerHighFrequency (CAMContainer::HighFrequencyContainer_t & hfc) private
Definition at line 671 of file CaService.cpp.
References ITSContainer::ProtectedCommunicationZone::expiryTimeAvailable, CAMContainer::HighFrequencyContainer_PR_rsuContainerHighFrequency, ITSContainer::ProtectedCommunicationZonesRSU::list, CAMContainer::HighFrequencyContainer::present, ITSContainer::ProtectedCommunicationZonesRSU::ProtectedCommunicationZoneCount, CAMContainer::RSUContainerHighFrequency::protectedCommunicationZonesRSU, ITSContainer::ProtectedCommunicationZone::protectedZoneIDAvailable, ITSContainer::ProtectedCommunicationZone::protectedZoneLatitude, ITSContainer::ProtectedCommunicationZone::protectedZoneLongitude, ITSContainer::ProtectedCommunicationZone::protectedZoneRadiusAvailable, ITSContainer::ProtectedCommunicationZone::protectedZoneType, ITSContainer::ProtectedZoneType_cenDsrcTolling, and CAMContainer::HighFrequencyContainer::rsuContainerHighFrequency.
Referenced by AddCooperativeAwarenessMessage().
BuildSpeedValue()
ITSContainer::SpeedValue_t CaService::BuildSpeedValue (const float vel) private
Definition at line 15 of file CaService.cpp.
References ITSContainer::SpeedValue_oneCentimeterPerSec, and ITSContainer::SpeedValue_unavailable.
Referenced by AddBasicVehicleContainerHighFrequency().
CheckHeadingDelta()
bool CaService::CheckHeadingDelta (float DeltaSeconds) private
Definition at line 735 of file CaService.cpp.
References GetFVectorAngle(), ACarlaWheeledVehicle::GetVehicleOrientation(), mLastCamHeading, mVehicle, carla::geom::Math::ToDegrees(), and VehicleHeading.
Referenced by CheckTriggeringConditions().
CheckPositionDelta()
bool CaService::CheckPositionDelta (float DeltaSeconds) private
Definition at line 174 of file CaService.cpp.
References mLastCamPosition, mVehicle, and VehiclePosition.
Referenced by CheckTriggeringConditions().
CheckSpeedDelta()
bool CaService::CheckSpeedDelta (float DeltaSeconds) private
Definition at line 186 of file CaService.cpp.
References ACarlaWheeledVehicle::GetVehicleForwardSpeed(), mLastCamSpeed, mVehicle, and VehicleSpeed.
Referenced by CheckTriggeringConditions().
CheckTriggeringConditions()
bool CaService::CheckTriggeringConditions (float DeltaSeconds) private
Definition at line 138 of file CaService.cpp.
References CheckHeadingDelta(), CheckPositionDelta(), CheckSpeedDelta(), GenerateCamMessage(), mDccRestriction, mElapsedTime, mFixedRate, mGenCam, mGenCamLowDynamicsCounter, mGenCamLowDynamicsLimit, mGenCamMax, mGenCamMin, and mLastCamTimeStamp.
Referenced by Trigger().
ComputeAccelerometer()
carla::geom::Vector3D CaService::ComputeAccelerometer (const float DeltaTime) private
Definition at line 564 of file CaService.cpp.
References ComputeAccelerometerNoise(), mActorOwner, mVehicle, PrevDeltaTime, and PrevLocation.
Referenced by AddBasicVehicleContainerHighFrequency().
ComputeAccelerometerNoise()
const carla::geom::Vector3D CaService::ComputeAccelerometerNoise (const FVector & Accelerometer) private
Definition at line 551 of file CaService.cpp.
References URandomEngine::GetNormalDistribution(), mRandomEngine, and StdDevAccel.
Referenced by ComputeAccelerometer().
ComputeSpeed()
float CaService::ComputeSpeed () private
Definition at line 608 of file CaService.cpp.
References URandomEngine::GetNormalDistribution(), ACarlaWheeledVehicle::GetVehicleForwardSpeed(), mRandomEngine, mVehicle, and VelocityDeviation.
Referenced by AddBasicVehicleContainerHighFrequency().
ComputeYawNoise()
const float CaService::ComputeYawNoise (const FVector & Gyroscope) private
Definition at line 641 of file CaService.cpp.
References URandomEngine::GetNormalDistribution(), mRandomEngine, YawrateBias, and YawrateDeviation.
Referenced by ComputeYawRate().
ComputeYawRate()
float CaService::ComputeYawRate () private
Definition at line 621 of file CaService.cpp.
References ComputeYawNoise(), FIMU_GetActorAngularVelocityInRadians(), and mActorOwner.
Referenced by AddBasicVehicleContainerHighFrequency().
CreateCooperativeAwarenessMessage()
CAM_t CaService::CreateCooperativeAwarenessMessage (float DeltaTime) private
Definition at line 363 of file CaService.cpp.
References AddCooperativeAwarenessMessage(), CAM::cam, and CreateITSPduHeader().
Referenced by GenerateCamMessage(), and Trigger().
CreateITSPduHeader()
void CaService::CreateITSPduHeader (CAM_t & message) private
Definition at line 373 of file CaService.cpp.
References CAM::header, ITSContainer::ItsPduHeader::messageID, mMessageId, mProtocolVersion, mStationId, ITSContainer::ItsPduHeader::protocolVersion, and ITSContainer::ItsPduHeader::stationID.
Referenced by CreateCooperativeAwarenessMessage().
GenerateCamMessage()
void CaService::GenerateCamMessage (float DeltaTime) private
Definition at line 206 of file CaService.cpp.
References CreateCooperativeAwarenessMessage(), mCAMMessage, mElapsedTime, mLastCamHeading, mLastCamPosition, mLastCamSpeed, mLastCamTimeStamp, VehicleHeading, VehiclePosition, and VehicleSpeed.
Referenced by CheckTriggeringConditions().
GetCamMessage()
CAM_t CaService::GetCamMessage ()
Definition at line 129 of file CaService.cpp.
References mCAMMessage.
Referenced by AV2XSensor::PrePhysTick().
GetFVectorAngle()
double CaService::GetFVectorAngle (const FVector & a, const FVector & b) private
Definition at line 200 of file CaService.cpp.
Referenced by CheckHeadingDelta().
GetHeading()
float CaService::GetHeading () private
Definition at line 312 of file CaService.cpp.
References URandomEngine::GetNormalDistribution(), HeadingBias, HeadingDeviation, mActorOwner, mRandomEngine, and carla::geom::Math::ToDegrees().
Referenced by AddBasicVehicleContainerHighFrequency().
GetReferencePosition()
FVector CaService::GetReferencePosition () private
Definition at line 284 of file CaService.cpp.
References carla::geom::GeoLocation::altitude, AltitudeBias, AltitudeDeviation, CurrentGeoReference, UCarlaStatics::GetLargeMapManager(), URandomEngine::GetNormalDistribution(), carla::geom::GeoLocation::latitude, LatitudeBias, LatitudeDeviation, ALargeMapManager::LocalToGlobalLocation(), carla::geom::GeoLocation::longitude, LongitudeBias, LongitudeDeviation, mActorOwner, mRandomEngine, mWorld, and carla::geom::GeoLocation::Transform().
Referenced by AddBasicContainer().
GetStationType()
ITSContainer::StationType_t CaService::GetStationType () private
Definition at line 216 of file CaService.cpp.
References FActorInfo::Description, UCarlaEpisode::FindCarlaActor(), FCarlaActor::GetActorInfo(), FCarlaActor::GetActorType(), UCarlaStatics::GetCurrentEpisode(), ATagger::GetTagOfTaggedComponent(), mActorOwner, mCarlaActor, mCarlaEpisode, mVehicle, mWorld, ITSContainer::StationType_bus, ITSContainer::StationType_cyclist, ITSContainer::StationType_lightTruck, ITSContainer::StationType_motorcycle, ITSContainer::StationType_passengerCar, ITSContainer::StationType_pedestrian, ITSContainer::StationType_roadSideUnit, ITSContainer::StationType_specialVehicles, ITSContainer::StationType_tram, ITSContainer::StationType_unknown, FActorDescription::Variations, and FCarlaActor::Vehicle.
Referenced by GetVehicleRole(), and SetOwner().
GetVehicleRole()
long CaService::GetVehicleRole () private
Definition at line 338 of file CaService.cpp.
References GetStationType(), ITSContainer::StationType_bus, ITSContainer::StationType_cyclist, ITSContainer::StationType_moped, ITSContainer::StationType_motorcycle, ITSContainer::StationType_specialVehicles, ITSContainer::StationType_tram, ITSContainer::VehicleRole_default, ITSContainer::VehicleRole_emergency, and ITSContainer::VehicleRole_publicTransport.
Referenced by AddLowFrequencyContainer().
SetAccelerationStandardDeviation()
void CaService::SetAccelerationStandardDeviation (const FVector & Vec)
Definition at line 433 of file CaService.cpp.
References StdDevAccel.
Referenced by AV2XSensor::SetAccelerationStandardDeviation().
SetGNSSDeviation()
void CaService::SetGNSSDeviation (const float noise_lat_stddev, const float noise_lon_stddev, const float noise_alt_stddev, const float noise_head_stddev, const float noise_lat_bias, const float noise_lon_bias, const float noise_alt_bias, const float noise_head_bias)
Definition at line 438 of file CaService.cpp.
References AltitudeBias, AltitudeDeviation, HeadingBias, HeadingDeviation, LatitudeBias, LatitudeDeviation, LongitudeBias, and LongitudeDeviation.
Referenced by AV2XSensor::SetGNSSDeviation().
SetOwner()
void CaService::SetOwner (UWorld * world, AActor * Owner)
Definition at line 44 of file CaService.cpp.
References CurrentGeoReference, UCarlaEpisode::FindCarlaActor(), FCarlaActor::GetActorId(), FCarlaActor::GetActorType(), UCarlaStatics::GetCurrentEpisode(), UCarlaEpisode::GetElapsedGameTime(), UCarlaEpisode::GetGeoReference(), GetStationType(), mActorOwner, mCarlaActor, mCarlaEpisode, mDccRestriction, mElapsedTime, mGenCamMax, mGenerationInterval, mLastCamHeading, mLastCamPosition, mLastCamSpeed, mLastCamTimeStamp, mLastLowCamTimeStamp, mStationId, mStationType, mVehicle, mWorld, scLowFrequencyContainerInterval, FCarlaActor::TrafficLight, FCarlaActor::TrafficSign, FCarlaActor::Vehicle, VehicleHeading, VehiclePosition, and VehicleSpeed.
Referenced by AV2XSensor::SetOwner().
SetParams()
void CaService::SetParams (const float GenCamMin, const float GenCamMax, const bool FixedRate)
Definition at line 90 of file CaService.cpp.
References mFixedRate, mGenCam, mGenCamMax, and mGenCamMin.
Referenced by AV2XSensor::SetCaServiceParams().
SetVelDeviation()
void CaService::SetVelDeviation (const float noise_vel_stddev_x)
Definition at line 457 of file CaService.cpp.
References VelocityDeviation.
Referenced by AV2XSensor::SetVelDeviation().
SetYawrateDeviation()
void CaService::SetYawrateDeviation (const float noise_yawrate_stddev, const float noise_yawrate_bias)
Definition at line 462 of file CaService.cpp.
References YawrateBias, and YawrateDeviation.
Referenced by AV2XSensor::SetYawrateDeviation().
Trigger()
bool CaService::Trigger (float DeltaSeconds)
Definition at line 105 of file CaService.cpp.
References CheckTriggeringConditions(), CreateCooperativeAwarenessMessage(), UCarlaEpisode::GetElapsedGameTime(), mCAMMessage, mCarlaEpisode, mElapsedTime, mGenerationInterval, mLastCamTimeStamp, mStationType, ITSContainer::StationType_roadSideUnit, and Trigger().
Referenced by AV2XSensor::PrePhysTick(), and Trigger().
Member Data Documentation
AltitudeBias
float CaService::AltitudeBias private
Definition at line 107 of file CaService.h.
Referenced by GetReferencePosition(), and SetGNSSDeviation().
AltitudeDeviation
float CaService::AltitudeDeviation private
Definition at line 102 of file CaService.h.
Referenced by GetReferencePosition(), and SetGNSSDeviation().
CurrentGeoReference
carla::geom::GeoLocation CaService::CurrentGeoReference private
Definition at line 99 of file CaService.h.
Referenced by GetReferencePosition(), and SetOwner().
HeadingBias
float CaService::HeadingBias private
Definition at line 108 of file CaService.h.
Referenced by GetHeading(), and SetGNSSDeviation().
HeadingDeviation
float CaService::HeadingDeviation private
Definition at line 103 of file CaService.h.
Referenced by GetHeading(), and SetGNSSDeviation().
LatitudeBias
float CaService::LatitudeBias private
Definition at line 105 of file CaService.h.
Referenced by GetReferencePosition(), and SetGNSSDeviation().
LatitudeDeviation
float CaService::LatitudeDeviation private
Definition at line 100 of file CaService.h.
Referenced by GetReferencePosition(), and SetGNSSDeviation().
LongitudeBias
float CaService::LongitudeBias private
Definition at line 106 of file CaService.h.
Referenced by GetReferencePosition(), and SetGNSSDeviation().
LongitudeDeviation
float CaService::LongitudeDeviation private
Definition at line 101 of file CaService.h.
Referenced by GetReferencePosition(), and SetGNSSDeviation().
mActorOwner
AActor* CaService::mActorOwner private
Definition at line 42 of file CaService.h.
Referenced by AddBasicVehicleContainerHighFrequency(), ComputeAccelerometer(), ComputeYawRate(), GetHeading(), GetReferencePosition(), GetStationType(), and SetOwner().
mCAMMessage
CAM_t CaService::mCAMMessage private
Definition at line 127 of file CaService.h.
Referenced by GenerateCamMessage(), GetCamMessage(), and Trigger().
mCarlaActor
FCarlaActor* CaService::mCarlaActor private
Definition at line 43 of file CaService.h.
Referenced by GetStationType(), and SetOwner().
mCarlaEpisode
UCarlaEpisode* CaService::mCarlaEpisode private
Definition at line 44 of file CaService.h.
Referenced by AddCooperativeAwarenessMessage(), GetStationType(), SetOwner(), and Trigger().
mDccRestriction
bool CaService::mDccRestriction private
Definition at line 54 of file CaService.h.
Referenced by CheckTriggeringConditions(), and SetOwner().
mElapsedTime
double CaService::mElapsedTime private
Definition at line 52 of file CaService.h.
Referenced by AddCooperativeAwarenessMessage(), CheckTriggeringConditions(), GenerateCamMessage(), SetOwner(), and Trigger().
mFixedRate
bool CaService::mFixedRate private
Definition at line 55 of file CaService.h.
Referenced by CheckTriggeringConditions(), and SetParams().
mGenCam
float CaService::mGenCam private
Definition at line 51 of file CaService.h.
Referenced by CheckTriggeringConditions(), and SetParams().
mGenCamLowDynamicsCounter
unsigned int CaService::mGenCamLowDynamicsCounter private
Definition at line 56 of file CaService.h.
Referenced by CheckTriggeringConditions().
mGenCamLowDynamicsLimit
unsigned int CaService::mGenCamLowDynamicsLimit private
Definition at line 57 of file CaService.h.
Referenced by CheckTriggeringConditions().
mGenCamMax
float CaService::mGenCamMax private
Definition at line 50 of file CaService.h.
Referenced by CheckTriggeringConditions(), SetOwner(), and SetParams().
mGenCamMin
float CaService::mGenCamMin private
Definition at line 49 of file CaService.h.
Referenced by CheckTriggeringConditions(), and SetParams().
mGenDeltaTimeMod
float CaService::mGenDeltaTimeMod private
Definition at line 53 of file CaService.h.
mGenerationDelta0
std::chrono::milliseconds CaService::mGenerationDelta0 private
Definition at line 67 of file CaService.h.
Referenced by AddCooperativeAwarenessMessage(), and CaService().
mGenerationInterval
float CaService::mGenerationInterval private
Definition at line 58 of file CaService.h.
Referenced by SetOwner(), and Trigger().
mLastCamHeading
FVector CaService::mLastCamHeading private
Definition at line 66 of file CaService.h.
Referenced by CheckHeadingDelta(), GenerateCamMessage(), and SetOwner().
mLastCamPosition
FVector CaService::mLastCamPosition private
Definition at line 64 of file CaService.h.
Referenced by CheckPositionDelta(), GenerateCamMessage(), and SetOwner().
mLastCamSpeed
float CaService::mLastCamSpeed private
Definition at line 65 of file CaService.h.
Referenced by CheckSpeedDelta(), GenerateCamMessage(), and SetOwner().
mLastCamTimeStamp
float CaService::mLastCamTimeStamp private
Definition at line 47 of file CaService.h.
Referenced by CheckTriggeringConditions(), GenerateCamMessage(), SetOwner(), and Trigger().
mLastLowCamTimeStamp
float CaService::mLastLowCamTimeStamp private
Definition at line 48 of file CaService.h.
Referenced by AddCooperativeAwarenessMessage(), and SetOwner().
mMessageId
const long CaService::mMessageId = ITSContainer::messageID_cam private
Definition at line 82 of file CaService.h.
Referenced by CreateITSPduHeader().
mProtocolVersion
const long CaService::mProtocolVersion = 2 private
Definition at line 81 of file CaService.h.
Referenced by CreateITSPduHeader().
mRandomEngine
URandomEngine* CaService::mRandomEngine private
Definition at line 130 of file CaService.h.
Referenced by CaService(), ComputeAccelerometerNoise(), ComputeSpeed(), ComputeYawNoise(), GetHeading(), and GetReferencePosition().
mStationId
long CaService::mStationId private
Definition at line 83 of file CaService.h.
Referenced by CreateITSPduHeader(), and SetOwner().
mStationType
long CaService::mStationType private
Definition at line 84 of file CaService.h.
Referenced by AddBasicContainer(), SetOwner(), and Trigger().
mVehicle
ACarlaWheeledVehicle* CaService::mVehicle private
Definition at line 46 of file CaService.h.
Referenced by AddBasicVehicleContainerHighFrequency(), AddLowFrequencyContainer(), CheckHeadingDelta(), CheckPositionDelta(), CheckSpeedDelta(), ComputeAccelerometer(), ComputeSpeed(), GetStationType(), and SetOwner().
mWorld
UWorld* CaService::mWorld private
Definition at line 45 of file CaService.h.
Referenced by GetReferencePosition(), GetStationType(), and SetOwner().
PrevDeltaTime
float CaService::PrevDeltaTime private
Used to compute the acceleration.
Definition at line 95 of file CaService.h.
Referenced by ComputeAccelerometer().
PrevLocation
std::array<FVector, 2> CaService::PrevLocation private
Used to compute the acceleration.
Definition at line 92 of file CaService.h.
Referenced by ComputeAccelerometer().
StdDevAccel
FVector CaService::StdDevAccel private
Standard deviation for acceleration settings.
Definition at line 89 of file CaService.h.
Referenced by ComputeAccelerometerNoise(), and SetAccelerationStandardDeviation().
VehicleHeading
FVector CaService::VehicleHeading private
Definition at line 62 of file CaService.h.
Referenced by CheckHeadingDelta(), GenerateCamMessage(), and SetOwner().
VehiclePosition
FVector CaService::VehiclePosition private
Definition at line 61 of file CaService.h.
Referenced by CheckPositionDelta(), GenerateCamMessage(), and SetOwner().
VehicleSpeed
float CaService::VehicleSpeed private
Definition at line 60 of file CaService.h.
Referenced by CheckSpeedDelta(), GenerateCamMessage(), and SetOwner().
VelocityDeviation
float CaService::VelocityDeviation private
Definition at line 112 of file CaService.h.
Referenced by ComputeSpeed(), and SetVelDeviation().
YawrateBias
float CaService::YawrateBias private
Definition at line 118 of file CaService.h.
Referenced by ComputeYawNoise(), and SetYawrateDeviation().
YawrateDeviation
float CaService::YawrateDeviation private
Definition at line 117 of file CaService.h.
Referenced by ComputeYawNoise(), and SetYawrateDeviation().
The documentation for this class was generated from the following files:
CaService.h
CaService.cpp