CARLA: carla::rpc::Texture< T > Class Template Reference
carla::rpc::Texture< T > Class Template Reference
#include <Texture.h>
Public Member Functions
T & At (uint32_t x, uint32_t y)
const T & At (uint32_t x, uint32_t y) const
const T * GetDataPtr () const
uint32_t GetHeight () const
uint32_t GetWidth () const
MSGPACK_DEFINE_ARRAY (_width, _height, _texture_data)
void SetDimensions (uint32_t width, uint32_t height)
Texture ()=default
Texture (uint32_t width, uint32_t height)
Private Attributes
uint32_t _height = 0
std::vector< T > _texture_data
uint32_t _width = 0
Detailed Description
template<typename T>
class carla::rpc::Texture< T >
Definition at line 19 of file Texture.h.
Constructor & Destructor Documentation
Texture() [1/2]
template<typename T > carla::rpc::Texture< T >::Texture () default
Texture() [2/2]
template<typename T > carla::rpc::Texture< T >::Texture (uint32_t width, uint32_t height) inline
Definition at line 24 of file Texture.h.
References carla::rpc::Texture< T >::_height, carla::rpc::Texture< T >::_texture_data, and carla::rpc::Texture< T >::_width.
Member Function Documentation
At() [1/2]
template<typename T > T & carla::rpc::Texture< T >::At (uint32_t x, uint32_t y) inline
Definition at line 43 of file Texture.h.
References carla::rpc::Texture< T >::_texture_data, and carla::rpc::Texture< T >::_width.
Referenced by ACarlaGameModeBase::CreateUETexture(), and ACarlaGameModeBase::CreateUETexture().
At() [2/2]
template<typename T > const T & carla::rpc::Texture< T >::At (uint32_t x, uint32_t y) const inline
Definition at line 47 of file Texture.h.
References carla::rpc::Texture< T >::_texture_data, and carla::rpc::Texture< T >::_width.
GetDataPtr()
template<typename T > const T * carla::rpc::Texture< T >::GetDataPtr () const inline
Definition at line 51 of file Texture.h.
References carla::rpc::Texture< T >::_texture_data.
GetHeight()
template<typename T > uint32_t carla::rpc::Texture< T >::GetHeight () const inline
Definition at line 33 of file Texture.h.
References carla::rpc::Texture< T >::_height.
Referenced by carla::client::World::ApplyTexturesToObject(), carla::client::World::ApplyTexturesToObjects(), ACarlaGameModeBase::CreateUETexture(), and ACarlaGameModeBase::CreateUETexture().
GetWidth()
template<typename T > uint32_t carla::rpc::Texture< T >::GetWidth () const inline
Definition at line 29 of file Texture.h.
References carla::rpc::Texture< T >::_width.
Referenced by carla::client::World::ApplyTexturesToObject(), carla::client::World::ApplyTexturesToObjects(), ACarlaGameModeBase::CreateUETexture(), and ACarlaGameModeBase::CreateUETexture().
MSGPACK_DEFINE_ARRAY()
template<typename T > carla::rpc::Texture< T >::MSGPACK_DEFINE_ARRAY (_width , _height , _texture_data)
SetDimensions()
template<typename T > void carla::rpc::Texture< T >::SetDimensions (uint32_t width, uint32_t height) inline
Definition at line 37 of file Texture.h.
References carla::rpc::Texture< T >::_height, carla::rpc::Texture< T >::_texture_data, and carla::rpc::Texture< T >::_width.
Member Data Documentation
_height
template<typename T > uint32_t carla::rpc::Texture< T >::_height = 0 private
Definition at line 58 of file Texture.h.
Referenced by carla::rpc::Texture< T >::GetHeight(), carla::rpc::Texture< T >::SetDimensions(), and carla::rpc::Texture< T >::Texture().
_texture_data
template<typename T > std::vector<T> carla::rpc::Texture< T >::_texture_data private
Definition at line 59 of file Texture.h.
Referenced by carla::rpc::Texture< T >::At(), carla::rpc::Texture< T >::At(), carla::rpc::Texture< T >::GetDataPtr(), carla::rpc::Texture< T >::SetDimensions(), and carla::rpc::Texture< T >::Texture().
_width
template<typename T > uint32_t carla::rpc::Texture< T >::_width = 0 private
Definition at line 57 of file Texture.h.
Referenced by carla::rpc::Texture< T >::At(), carla::rpc::Texture< T >::At(), carla::rpc::Texture< T >::GetWidth(), carla::rpc::Texture< T >::SetDimensions(), and carla::rpc::Texture< T >::Texture().
The documentation for this class was generated from the following file:
Texture.h