CARLA: carla::opendrive::parser::ProfilesParser Class Reference
carla::opendrive::parser::ProfilesParser Class Reference
#include <ProfilesParser.h>
Static Public Member Functions
static void Parse (const pugi::xml_document &xml, carla::road::MapBuilder &map_builder)
Detailed Description
Definition at line 22 of file ProfilesParser.h.
Member Function Documentation
Parse()
void carla::opendrive::parser::ProfilesParser::Parse (const pugi::xml_document & xml, carla::road::MapBuilder & map_builder) static
Todo
: RoadInfo classes must be created to fit this information
Definition at line 46 of file ProfilesParser.cpp.
References carla::opendrive::parser::ElevationProfile::a, carla::opendrive::parser::LateralProfile::a, carla::road::MapBuilder::AddRoadElevationProfile(), carla::opendrive::parser::ElevationProfile::b, carla::opendrive::parser::LateralProfile::b, carla::opendrive::parser::ElevationProfile::c, carla::opendrive::parser::LateralProfile::c, pugi::xml_node::child(), pugi::xml_node::children(), carla::opendrive::parser::LateralProfile::cross, carla::opendrive::parser::ElevationProfile::d, carla::opendrive::parser::LateralProfile::d, carla::road::MapBuilder::GetRoad(), carla::opendrive::parser::ElevationProfile::road, carla::opendrive::parser::LateralProfile::road, carla::opendrive::parser::ElevationProfile::s, carla::opendrive::parser::LateralProfile::s, carla::opendrive::parser::LateralProfile::shape, carla::opendrive::parser::LateralCrossfall::side, carla::opendrive::parser::LateralShape::t, and carla::opendrive::parser::LateralProfile::type.
Referenced by carla::opendrive::OpenDriveParser::Load().
The documentation for this class was generated from the following files:
ProfilesParser.h
ProfilesParser.cpp