CARLA: UTaggedComponent Class Reference
UTaggedComponent Class Reference
#include <TaggedComponent.h>
Public Member Functions
virtual FBoxSphereBounds CalcBounds (const FTransform &LocalToWorld) const
virtual FPrimitiveSceneProxy * CreateSceneProxy () override
FLinearColor GetColor ()
virtual void OnRegister () override
void SetColor (FLinearColor color)
virtual void TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction *ThisTickFunction) override
UTaggedComponent (const FObjectInitializer &ObjectInitializer)
Private Member Functions
FPrimitiveSceneProxy * CreateSceneProxy (UHierarchicalInstancedStaticMeshComponent *MeshComponent)
FPrimitiveSceneProxy * CreateSceneProxy (UInstancedStaticMeshComponent *MeshComponent)
FPrimitiveSceneProxy * CreateSceneProxy (USkeletalMeshComponent *SkeletalMeshComponent)
FPrimitiveSceneProxy * CreateSceneProxy (UStaticMeshComponent *StaticMeshComponent)
Private Attributes
bool bShouldWaitFrame = true
bool bSkeletalMesh = false
FLinearColor Color
int NumFramesToWait = 2
UMaterial * TaggedMaterial
UMaterialInstanceDynamic * TaggedMID
Detailed Description
Definition at line 11 of file TaggedComponent.h.
Constructor & Destructor Documentation
UTaggedComponent()
UTaggedComponent::UTaggedComponent (const FObjectInitializer & ObjectInitializer)
Definition at line 11 of file TaggedComponent.cpp.
References TaggedMaterial.
Member Function Documentation
CalcBounds()
FBoxSphereBounds UTaggedComponent::CalcBounds (const FTransform & LocalToWorld) const virtual
Definition at line 53 of file TaggedComponent.cpp.
CreateSceneProxy() [1/5]
FPrimitiveSceneProxy * UTaggedComponent::CreateSceneProxy () override virtual
Definition at line 63 of file TaggedComponent.cpp.
References bSkeletalMesh, CreateSceneProxy(), and IsValid().
Referenced by CreateSceneProxy().
CreateSceneProxy() [2/5]
FPrimitiveSceneProxy * UTaggedComponent::CreateSceneProxy (UHierarchicalInstancedStaticMeshComponent * MeshComponent) private
Definition at line 156 of file TaggedComponent.cpp.
References TaggedMID.
CreateSceneProxy() [3/5]
FPrimitiveSceneProxy * UTaggedComponent::CreateSceneProxy (UInstancedStaticMeshComponent * MeshComponent) private
Definition at line 177 of file TaggedComponent.cpp.
References TaggedMID.
CreateSceneProxy() [4/5]
FPrimitiveSceneProxy * UTaggedComponent::CreateSceneProxy (USkeletalMeshComponent * SkeletalMeshComponent) private
Definition at line 129 of file TaggedComponent.cpp.
References bShouldWaitFrame, and TaggedMID.
CreateSceneProxy() [5/5]
FPrimitiveSceneProxy * UTaggedComponent::CreateSceneProxy (UStaticMeshComponent * StaticMeshComponent) private
Definition at line 102 of file TaggedComponent.cpp.
References TaggedMID.
GetColor()
FLinearColor UTaggedComponent::GetColor ()
Definition at line 48 of file TaggedComponent.cpp.
References Color.
OnRegister()
void UTaggedComponent::OnRegister () override virtual
Definition at line 24 of file TaggedComponent.cpp.
References IsValid(), SetColor(), TaggedMaterial, and TaggedMID.
SetColor()
void UTaggedComponent::SetColor (FLinearColor color)
Definition at line 38 of file TaggedComponent.cpp.
References IsValid(), and TaggedMID.
Referenced by OnRegister(), and ATagger::TagActor().
TickComponent()
void UTaggedComponent::TickComponent (float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction * ThisTickFunction) override virtual
Definition at line 197 of file TaggedComponent.cpp.
References bShouldWaitFrame, bSkeletalMesh, and NumFramesToWait.
Member Data Documentation
bShouldWaitFrame
bool UTaggedComponent::bShouldWaitFrame = true private
Definition at line 44 of file TaggedComponent.h.
Referenced by CreateSceneProxy(), and TickComponent().
bSkeletalMesh
bool UTaggedComponent::bSkeletalMesh = false private
Definition at line 36 of file TaggedComponent.h.
Referenced by CreateSceneProxy(), and TickComponent().
Color
FLinearColor UTaggedComponent::Color private
Definition at line 28 of file TaggedComponent.h.
Referenced by GetColor().
NumFramesToWait
int UTaggedComponent::NumFramesToWait = 2 private
Definition at line 45 of file TaggedComponent.h.
Referenced by TickComponent().
TaggedMaterial
UMaterial* UTaggedComponent::TaggedMaterial private
Definition at line 31 of file TaggedComponent.h.
Referenced by OnRegister(), and UTaggedComponent().
TaggedMID
UMaterialInstanceDynamic* UTaggedComponent::TaggedMID private
Definition at line 34 of file TaggedComponent.h.
Referenced by CreateSceneProxy(), CreateSceneProxy(), CreateSceneProxy(), CreateSceneProxy(), OnRegister(), and SetColor().
The documentation for this class was generated from the following files:
TaggedComponent.h
TaggedComponent.cpp