CARLA: carla::sensor::s11n::SemanticLidarSerializer Class Reference
carla::sensor::s11n::SemanticLidarSerializer Class Reference
Serializes the data generated by Lidar sensors.
#include <SemanticLidarSerializer.h>
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static SemanticLidarHeaderView DeserializeHeader (const RawData &data)
static size_t GetHeaderOffset (const RawData &data)
template<typename Sensor >
static Buffer Serialize (const Sensor &sensor, const data::SemanticLidarData &measurement, Buffer &&output)
Detailed Description
Serializes the data generated by Lidar sensors.
Definition at line 59 of file SemanticLidarSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::SemanticLidarSerializer::Deserialize (RawData && data) static
Definition at line 14 of file SemanticLidarSerializer.cpp.
DeserializeHeader()
static SemanticLidarHeaderView carla::sensor::s11n::SemanticLidarSerializer::DeserializeHeader (const RawData & data) inline static
Definition at line 62 of file SemanticLidarSerializer.h.
References carla::sensor::RawData::begin().
Referenced by carla::sensor::data::SemanticLidarMeasurement::GetHeader(), and GetHeaderOffset().
GetHeaderOffset()
static size_t carla::sensor::s11n::SemanticLidarSerializer::GetHeaderOffset (const RawData & data) inline static
Definition at line 66 of file SemanticLidarSerializer.h.
References DeserializeHeader(), and carla::sensor::data::SemanticLidarData::SIZE.
Referenced by carla::sensor::data::SemanticLidarMeasurement::SemanticLidarMeasurement().
Serialize()
template<typename Sensor > Buffer carla::sensor::s11n::SemanticLidarSerializer::Serialize (const Sensor & sensor, const data::SemanticLidarData & measurement, Buffer && output) inline static
Definition at line 85 of file SemanticLidarSerializer.h.
References carla::sensor::data::SemanticLidarData::_header, carla::sensor::data::SemanticLidarData::_ser_points, and carla::Buffer::copy_from().
The documentation for this class was generated from the following files:
SemanticLidarSerializer.h
SemanticLidarSerializer.cpp