CARLA: sensor_msgs::msg::ImagePubSubType Class Reference
sensor_msgs::msg::ImagePubSubType Class Reference
This class represents the TopicDataType of the type Image defined by the user in the IDL file.
#include <ImagePubSubTypes.h>
Public Types
typedef Image type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
eProsima_user_DllExport ImagePubSubType ()
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
virtual eProsima_user_DllExport ~ImagePubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type Image defined by the user in the IDL file.
Definition at line 43 of file ImagePubSubTypes.h.
Member Typedef Documentation
type
typedef Image sensor_msgs::msg::ImagePubSubType::type
Definition at line 47 of file ImagePubSubTypes.h.
Constructor & Destructor Documentation
ImagePubSubType()
sensor_msgs::msg::ImagePubSubType::ImagePubSubType ()
Definition at line 32 of file ImagePubSubTypes.cpp.
References sensor_msgs::msg::Image::getKeyMaxCdrSerializedSize(), sensor_msgs::msg::Image::getMaxCdrSerializedSize(), sensor_msgs::msg::Image::isKeyDefined(), and m_keyBuffer.
~ImagePubSubType()
sensor_msgs::msg::ImagePubSubType::~ImagePubSubType () override virtual
Definition at line 45 of file ImagePubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * sensor_msgs::msg::ImagePubSubType::createData () override virtual
Definition at line 104 of file ImagePubSubTypes.cpp.
deleteData()
void sensor_msgs::msg::ImagePubSubType::deleteData (void * data) override virtual
Definition at line 109 of file ImagePubSubTypes.cpp.
deserialize()
bool sensor_msgs::msg::ImagePubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 72 of file ImagePubSubTypes.cpp.
References sensor_msgs::msg::Image::deserialize().
getKey()
bool sensor_msgs::msg::ImagePubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 115 of file ImagePubSubTypes.cpp.
References sensor_msgs::msg::Image::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and sensor_msgs::msg::Image::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> sensor_msgs::msg::ImagePubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 94 of file ImagePubSubTypes.cpp.
References sensor_msgs::msg::Image::getCdrSerializedSize().
serialize()
bool sensor_msgs::msg::ImagePubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file ImagePubSubTypes.cpp.
References sensor_msgs::msg::Image::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* sensor_msgs::msg::ImagePubSubType::m_keyBuffer
Definition at line 100 of file ImagePubSubTypes.h.
Referenced by getKey(), ImagePubSubType(), and ~ImagePubSubType().
m_md5
MD5 sensor_msgs::msg::ImagePubSubType::m_md5
Definition at line 99 of file ImagePubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
ImagePubSubTypes.h
ImagePubSubTypes.cpp