CARLA: CarlaRecorderActorTriggerVolumes Class Reference
CarlaRecorderActorTriggerVolumes Class Reference
#include <CarlaRecorderBoundingBox.h>
Public Member Functions
void Add (const CarlaRecorderActorBoundingBox &InObj)
void Clear (void)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderActorBoundingBox > Boxes
Detailed Description
Definition at line 51 of file CarlaRecorderBoundingBox.h.
Member Function Documentation
Add()
void CarlaRecorderActorTriggerVolumes::Add (const CarlaRecorderActorBoundingBox & InObj)
Definition at line 73 of file CarlaRecorderBoundingBox.cpp.
References Boxes.
Referenced by FFrameData::AddTriggerVolume(), and ACarlaRecorder::AddTriggerVolume().
Clear()
void CarlaRecorderActorTriggerVolumes::Clear (void)
Definition at line 68 of file CarlaRecorderBoundingBox.cpp.
References Boxes.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
Write()
void CarlaRecorderActorTriggerVolumes::Write (std::ostream & OutFile)
Definition at line 78 of file CarlaRecorderBoundingBox.cpp.
References Boxes, and TriggerVolume.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
Boxes
std::vector<CarlaRecorderActorBoundingBox> CarlaRecorderActorTriggerVolumes::Boxes private
Definition at line 63 of file CarlaRecorderBoundingBox.h.
Referenced by Add(), Clear(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderBoundingBox.h
CarlaRecorderBoundingBox.cpp