CARLA: xpath_query_impl Struct Reference
xpath_query_impl Struct Reference
Public Member Functions
xpath_query_impl ()
Static Public Member Functions
static xpath_query_impl * create ()
static void destroy (xpath_query_impl *impl)
Public Attributes
xpath_allocator alloc
xpath_memory_block block
bool oom
xpath_ast_node * root
Detailed Description
Definition at line 11883 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_query_impl()
xpath_query_impl::xpath_query_impl () inline
Definition at line 11902 of file pugixml.cpp.
References block, xpath_memory_block::capacity, xpath_memory_block::data, and xpath_memory_block::next.
Referenced by create().
Member Function Documentation
create()
static xpath_query_impl * xpath_query_impl::create () inline static
Definition at line 11885 of file pugixml.cpp.
References xml_memory_management_function_storage< T >::allocate, and xpath_query_impl().
destroy()
static void xpath_query_impl::destroy (xpath_query_impl * impl) inline static
Definition at line 11893 of file pugixml.cpp.
References alloc, xml_memory_management_function_storage< T >::deallocate, and xpath_allocator::release().
Member Data Documentation
alloc
xpath_allocator xpath_query_impl::alloc
Definition at line 11909 of file pugixml.cpp.
Referenced by destroy().
block
xpath_memory_block xpath_query_impl::block
Definition at line 11910 of file pugixml.cpp.
Referenced by xpath_query_impl().
oom
bool xpath_query_impl::oom
Definition at line 11911 of file pugixml.cpp.
root
xpath_ast_node* xpath_query_impl::root
Definition at line 11908 of file pugixml.cpp.
Referenced by evaluate_node_set_prepare().
The documentation for this struct was generated from the following file:
pugixml.cpp