CARLA: CarlaRecorderLightScenes Struct Reference
CarlaRecorderLightScenes Struct Reference
#include <CarlaRecorderLightScene.h>
Public Member Functions
void Add (const CarlaRecorderLightScene &InObj)
void Clear (void)
const std::vector< CarlaRecorderLightScene > & GetLights ()
void Read (std::istream &InFile)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderLightScene > Lights
Detailed Description
Definition at line 29 of file CarlaRecorderLightScene.h.
Member Function Documentation
Add()
void CarlaRecorderLightScenes::Add (const CarlaRecorderLightScene & InObj)
Definition at line 36 of file CarlaRecorderLightScene.cpp.
References Lights, and Vehicle.
Referenced by FFrameData::AddEventLightSceneChanged(), ACarlaRecorder::AddEventLightSceneChanged(), and Read().
Clear()
void CarlaRecorderLightScenes::Clear (void)
Definition at line 31 of file CarlaRecorderLightScene.cpp.
References Lights.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
GetLights()
const std::vector< CarlaRecorderLightScene > & CarlaRecorderLightScenes::GetLights ()
Definition at line 81 of file CarlaRecorderLightScene.cpp.
References Lights.
Referenced by FFrameData::PlayFrameData().
Read()
void CarlaRecorderLightScenes::Read (std::istream & InFile)
Definition at line 67 of file CarlaRecorderLightScene.cpp.
References Add(), and CarlaRecorderLightScene::Read().
Referenced by FFrameData::Read().
Write()
void CarlaRecorderLightScenes::Write (std::ostream & OutFile)
Definition at line 41 of file CarlaRecorderLightScene.cpp.
References Lights, and SceneLight.
Referenced by ACarlaRecorder::Write(), and FFrameData::Write().
Member Data Documentation
Lights
std::vector<CarlaRecorderLightScene> CarlaRecorderLightScenes::Lights private
Definition at line 45 of file CarlaRecorderLightScene.h.
Referenced by Add(), Clear(), GetLights(), and Write().
The documentation for this struct was generated from the following files:
CarlaRecorderLightScene.h
CarlaRecorderLightScene.cpp