CARLA: carla::AtomicSharedPtr< T > Class Template Reference
carla::AtomicSharedPtr< T > Class Template Reference
A very simple atomic shared ptr with release-acquire memory order.
#include <AtomicSharedPtr.h>
Public Member Functions
template<typename... Args>
AtomicSharedPtr (Args &&... args)
AtomicSharedPtr (AtomicSharedPtr &&)=delete
AtomicSharedPtr (const AtomicSharedPtr &rhs)
bool compare_exchange (std::shared_ptr< T > *expected, std::shared_ptr< T > desired) noexcept
std::shared_ptr< T > load () const noexcept
AtomicSharedPtr & operator= (AtomicSharedPtr &&)=delete
AtomicSharedPtr & operator= (const AtomicSharedPtr &rhs) noexcept
AtomicSharedPtr & operator= (std::shared_ptr< T > ptr) noexcept
void reset (std::shared_ptr< T > ptr=nullptr) noexcept
void store (std::shared_ptr< T > ptr) noexcept
Private Attributes
std::shared_ptr< T > _ptr
Detailed Description
template<typename T>
class carla::AtomicSharedPtr< T >
A very simple atomic shared ptr with release-acquire memory order.
Definition at line 15 of file AtomicSharedPtr.h.
Constructor & Destructor Documentation
AtomicSharedPtr() [1/3]
template<typename T > template<typename... Args> carla::AtomicSharedPtr< T >::AtomicSharedPtr (Args &&... args) inline explicit
Definition at line 19 of file AtomicSharedPtr.h.
AtomicSharedPtr() [2/3]
template<typename T > carla::AtomicSharedPtr< T >::AtomicSharedPtr (const AtomicSharedPtr< T > & rhs) inline
Definition at line 22 of file AtomicSharedPtr.h.
AtomicSharedPtr() [3/3]
template<typename T > carla::AtomicSharedPtr< T >::AtomicSharedPtr (AtomicSharedPtr< T > &&) delete
Member Function Documentation
compare_exchange()
template<typename T > bool carla::AtomicSharedPtr< T >::compare_exchange (std::shared_ptr< T > * expected, std::shared_ptr< T > desired) inline noexcept
Definition at line 39 of file AtomicSharedPtr.h.
References carla::AtomicSharedPtr< T >::_ptr.
load()
template<typename T > std::shared_ptr< T > carla::AtomicSharedPtr< T >::load () const inline noexcept
Definition at line 35 of file AtomicSharedPtr.h.
References carla::AtomicSharedPtr< T >::_ptr.
Referenced by carla::client::detail::AtomicList< T >::Load(), and carla::client::detail::Load().
operator=() [1/3]
template<typename T > AtomicSharedPtr & carla::AtomicSharedPtr< T >::operator= (AtomicSharedPtr< T > &&) delete
operator=() [2/3]
template<typename T > AtomicSharedPtr & carla::AtomicSharedPtr< T >::operator= (const AtomicSharedPtr< T > & rhs) inline noexcept
Definition at line 53 of file AtomicSharedPtr.h.
References carla::AtomicSharedPtr< T >::store().
operator=() [3/3]
template<typename T > AtomicSharedPtr & carla::AtomicSharedPtr< T >::operator= (std::shared_ptr< T > ptr) inline noexcept
Definition at line 48 of file AtomicSharedPtr.h.
References carla::AtomicSharedPtr< T >::store().
reset()
template<typename T > void carla::AtomicSharedPtr< T >::reset (std::shared_ptr< T > ptr = nullptr) inline noexcept
Definition at line 31 of file AtomicSharedPtr.h.
References carla::AtomicSharedPtr< T >::store().
store()
template<typename T > void carla::AtomicSharedPtr< T >::store (std::shared_ptr< T > ptr) inline noexcept
Definition at line 27 of file AtomicSharedPtr.h.
References carla::AtomicSharedPtr< T >::_ptr.
Referenced by carla::AtomicSharedPtr< T >::operator=(), carla::AtomicSharedPtr< T >::operator=(), and carla::AtomicSharedPtr< T >::reset().
Member Data Documentation
_ptr
template<typename T > std::shared_ptr<T> carla::AtomicSharedPtr< T >::_ptr private
Definition at line 62 of file AtomicSharedPtr.h.
Referenced by carla::AtomicSharedPtr< T >::compare_exchange(), carla::AtomicSharedPtr< T >::load(), and carla::AtomicSharedPtr< T >::store().
The documentation for this class was generated from the following file:
AtomicSharedPtr.h