CARLA: carla::geom::SegmentCloudRtree< T, Dimension > Class Template Reference
carla::geom::SegmentCloudRtree< T, Dimension > Class Template Reference
Rtree class working with 3D segment clouds.
#include <Rtree.h>
Public Types
typedef boost::geometry::model::point< float, Dimension, boost::geometry::cs::cartesian > BPoint
typedef boost::geometry::model::segment< BPoint > BSegment
typedef std::pair< BSegment, std::pair< T, T > > TreeElement
Public Member Functions
template<typename Geometry >
std::vector< TreeElement > GetIntersections (const Geometry &geometry) const
Returns segments that intersec the specified geometry Warning: intersection between 3D segments is not implemented by boost.
template<typename Geometry >
std::vector< TreeElement > GetNearestNeighbours (const Geometry &geometry, size_t number_neighbours=1) const
template<typename Geometry , typename Filter >
std::vector< TreeElement > GetNearestNeighboursWithFilter (const Geometry &geometry, Filter filter, size_t number_neighbours=1) const
Return nearest neighbors with a user defined filter.
size_t GetTreeSize () const
void InsertElement (const BSegment &segment, const T &element_start, const T &element_end)
void InsertElement (const TreeElement &element)
void InsertElements (const std::vector< TreeElement > &elements)
Private Attributes
boost::geometry::index::rtree< TreeElement, boost::geometry::index::linear< 16 > > _rtree
Detailed Description
template<typename T, size_t Dimension = 3>
class carla::geom::SegmentCloudRtree< T, Dimension >
Rtree class working with 3D segment clouds.
Stores a pair of T elements (one for each end of the segment) Useful to perform fast k-NN searches.
Definition at line 86 of file Rtree.h.
Member Typedef Documentation
BPoint
template<typename T , size_t Dimension = 3> typedef boost::geometry::model::point<float, Dimension, boost::geometry::cs::cartesian> carla::geom::SegmentCloudRtree< T, Dimension >::BPoint
Definition at line 89 of file Rtree.h.
BSegment
template<typename T , size_t Dimension = 3> typedef boost::geometry::model::segment<BPoint> carla::geom::SegmentCloudRtree< T, Dimension >::BSegment
Definition at line 90 of file Rtree.h.
TreeElement
template<typename T , size_t Dimension = 3> typedef std::pair<BSegment, std::pair<T, T> > carla::geom::SegmentCloudRtree< T, Dimension >::TreeElement
Definition at line 91 of file Rtree.h.
Member Function Documentation
GetIntersections()
template<typename T , size_t Dimension = 3> template<typename Geometry > std::vector< TreeElement > carla::geom::SegmentCloudRtree< T, Dimension >::GetIntersections (const Geometry & geometry) const inline
Returns segments that intersec the specified geometry Warning: intersection between 3D segments is not implemented by boost.
Definition at line 135 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
Referenced by carla::road::Map::ComputeJunctionConflicts().
GetNearestNeighbours()
template<typename T , size_t Dimension = 3> template<typename Geometry > std::vector< TreeElement > carla::geom::SegmentCloudRtree< T, Dimension >::GetNearestNeighbours (const Geometry & geometry, size_t number_neighbours = 1) const inline
Definition at line 124 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
Referenced by carla::road::element::GeometryPoly3::PosFromDist(), and carla::road::element::GeometryParamPoly3::PosFromDist().
GetNearestNeighboursWithFilter()
template<typename T , size_t Dimension = 3> template<typename Geometry , typename Filter > std::vector< TreeElement > carla::geom::SegmentCloudRtree< T, Dimension >::GetNearestNeighboursWithFilter (const Geometry & geometry, Filter filter, size_t number_neighbours = 1) const inline
Return nearest neighbors with a user defined filter.
The filter reveices as an argument a TreeElement value and needs to return a bool to accept or reject the value [&](Rtree::TreeElement const &element){if (IsOk(element)) return true; else return false;}
Definition at line 111 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
Referenced by carla::road::Map::GetClosestWaypointOnRoad().
GetTreeSize()
template<typename T , size_t Dimension = 3> size_t carla::geom::SegmentCloudRtree< T, Dimension >::GetTreeSize () const inline
Definition at line 143 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
InsertElement() [1/2]
template<typename T , size_t Dimension = 3> void carla::geom::SegmentCloudRtree< T, Dimension >::InsertElement (const BSegment & segment, const T & element_start, const T & element_end) inline
Definition at line 93 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
Referenced by carla::road::element::GeometryPoly3::PreComputeSpline(), and carla::road::element::GeometryParamPoly3::PreComputeSpline().
InsertElement() [2/2]
template<typename T , size_t Dimension = 3> void carla::geom::SegmentCloudRtree< T, Dimension >::InsertElement (const TreeElement & element) inline
Definition at line 97 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
InsertElements()
template<typename T , size_t Dimension = 3> void carla::geom::SegmentCloudRtree< T, Dimension >::InsertElements (const std::vector< TreeElement > & elements) inline
Definition at line 101 of file Rtree.h.
References carla::geom::SegmentCloudRtree< T, Dimension >::_rtree.
Referenced by carla::road::Map::CreateRtree().
Member Data Documentation
_rtree
template<typename T , size_t Dimension = 3> boost::geometry::index::rtree<TreeElement, boost::geometry::index::linear<16> > carla::geom::SegmentCloudRtree< T, Dimension >::_rtree private
Definition at line 149 of file Rtree.h.
Referenced by carla::geom::SegmentCloudRtree< T, Dimension >::GetIntersections(), carla::geom::SegmentCloudRtree< T, Dimension >::GetNearestNeighbours(), carla::geom::SegmentCloudRtree< T, Dimension >::GetNearestNeighboursWithFilter(), carla::geom::SegmentCloudRtree< T, Dimension >::GetTreeSize(), carla::geom::SegmentCloudRtree< T, Dimension >::InsertElement(), carla::geom::SegmentCloudRtree< T, Dimension >::InsertElement(), and carla::geom::SegmentCloudRtree< T, Dimension >::InsertElements().
The documentation for this class was generated from the following file:
Rtree.h