CARLA: pugi::xml_tree_walker Class Reference
pugi::xml_tree_walker Class Reference abstract
#include <pugixml.hpp>
Public Member Functions
virtual bool begin (xml_node &node)
virtual bool end (xml_node &node)
virtual bool for_each (xml_node &node)=0
xml_tree_walker ()
virtual ~xml_tree_walker ()
Protected Member Functions
int depth () const
Private Attributes
int _depth
Friends
class xml_node
Detailed Description
Definition at line 921 of file pugixml.hpp.
Constructor & Destructor Documentation
xml_tree_walker()
PUGI__FN pugi::xml_tree_walker::xml_tree_walker ()
Definition at line 5078 of file pugixml.cpp.
~xml_tree_walker()
PUGI__FN pugi::xml_tree_walker::~xml_tree_walker () virtual
Definition at line 5082 of file pugixml.cpp.
Member Function Documentation
begin()
PUGI__FN bool pugi::xml_tree_walker::begin (xml_node & node) virtual
Definition at line 5091 of file pugixml.cpp.
Referenced by pugi::xml_node::traverse().
depth()
PUGI__FN int pugi::xml_tree_walker::depth () const protected
Definition at line 5086 of file pugixml.cpp.
References _depth.
end()
PUGI__FN bool pugi::xml_tree_walker::end (xml_node & node) virtual
Definition at line 5096 of file pugixml.cpp.
Referenced by pugi::xml_node::traverse().
for_each()
virtual bool pugi::xml_tree_walker::for_each (xml_node & node) pure virtual
Referenced by pugi::xml_node::traverse().
Friends And Related Symbol Documentation
xml_node
friend class xml_node friend
Definition at line 923 of file pugixml.hpp.
Member Data Documentation
_depth
int pugi::xml_tree_walker::_depth private
Definition at line 926 of file pugixml.hpp.
Referenced by depth(), and pugi::xml_node::traverse().
The documentation for this class was generated from the following files:
pugixml.hpp
pugixml.cpp