CARLA: tf2_msgs::msg::TFMessagePubSubType Class Reference
tf2_msgs::msg::TFMessagePubSubType Class Reference
This class represents the TopicDataType of the type TFMessage defined by the user in the IDL file.
#include <TFMessagePubSubTypes.h>
Public Types
typedef TFMessage type
Public Member Functions
virtual eProsima_user_DllExport void * createData () override
virtual eProsima_user_DllExport void deleteData (void *data) override
virtual eProsima_user_DllExport bool deserialize (eprosima::fastrtps::rtps::SerializedPayload_t *payload, void *data) override
virtual eProsima_user_DllExport bool getKey (void *data, eprosima::fastrtps::rtps::InstanceHandle_t *ihandle, bool force_md5=false) override
virtual eProsima_user_DllExport std::function< uint32_t()> getSerializedSizeProvider (void *data) override
virtual eProsima_user_DllExport bool serialize (void *data, eprosima::fastrtps::rtps::SerializedPayload_t *payload) override
eProsima_user_DllExport TFMessagePubSubType ()
virtual eProsima_user_DllExport ~TFMessagePubSubType () override
Public Attributes
unsigned char * m_keyBuffer
MD5 m_md5
Detailed Description
This class represents the TopicDataType of the type TFMessage defined by the user in the IDL file.
Definition at line 46 of file TFMessagePubSubTypes.h.
Member Typedef Documentation
type
typedef TFMessage tf2_msgs::msg::TFMessagePubSubType::type
Definition at line 50 of file TFMessagePubSubTypes.h.
Constructor & Destructor Documentation
TFMessagePubSubType()
tf2_msgs::msg::TFMessagePubSubType::TFMessagePubSubType ()
Definition at line 32 of file TFMessagePubSubTypes.cpp.
References tf2_msgs::msg::TFMessage::getKeyMaxCdrSerializedSize(), tf2_msgs::msg::TFMessage::getMaxCdrSerializedSize(), tf2_msgs::msg::TFMessage::isKeyDefined(), and m_keyBuffer.
~TFMessagePubSubType()
tf2_msgs::msg::TFMessagePubSubType::~TFMessagePubSubType () override virtual
Definition at line 45 of file TFMessagePubSubTypes.cpp.
References m_keyBuffer.
Member Function Documentation
createData()
void * tf2_msgs::msg::TFMessagePubSubType::createData () override virtual
Definition at line 122 of file TFMessagePubSubTypes.cpp.
deleteData()
void tf2_msgs::msg::TFMessagePubSubType::deleteData (void * data) override virtual
Definition at line 127 of file TFMessagePubSubTypes.cpp.
deserialize()
bool tf2_msgs::msg::TFMessagePubSubType::deserialize (eprosima::fastrtps::rtps::SerializedPayload_t * payload, void * data) override virtual
Definition at line 82 of file TFMessagePubSubTypes.cpp.
References tf2_msgs::msg::TFMessage::deserialize().
getKey()
bool tf2_msgs::msg::TFMessagePubSubType::getKey (void * data, eprosima::fastrtps::rtps::InstanceHandle_t * ihandle, bool force_md5 = false) override virtual
Definition at line 133 of file TFMessagePubSubTypes.cpp.
References tf2_msgs::msg::TFMessage::getKeyMaxCdrSerializedSize(), m_keyBuffer, m_md5, and tf2_msgs::msg::TFMessage::serializeKey().
getSerializedSizeProvider()
std::function< uint32_t()> tf2_msgs::msg::TFMessagePubSubType::getSerializedSizeProvider (void * data) override virtual
Definition at line 112 of file TFMessagePubSubTypes.cpp.
References tf2_msgs::msg::TFMessage::getCdrSerializedSize().
serialize()
bool tf2_msgs::msg::TFMessagePubSubType::serialize (void * data, eprosima::fastrtps::rtps::SerializedPayload_t * payload) override virtual
Definition at line 53 of file TFMessagePubSubTypes.cpp.
References tf2_msgs::msg::TFMessage::serialize().
Member Data Documentation
m_keyBuffer
unsigned char* tf2_msgs::msg::TFMessagePubSubType::m_keyBuffer
Definition at line 103 of file TFMessagePubSubTypes.h.
Referenced by getKey(), TFMessagePubSubType(), and ~TFMessagePubSubType().
m_md5
MD5 tf2_msgs::msg::TFMessagePubSubType::m_md5
Definition at line 102 of file TFMessagePubSubTypes.h.
Referenced by getKey().
The documentation for this class was generated from the following files:
TFMessagePubSubTypes.h
TFMessagePubSubTypes.cpp