CARLA: carla::sensor::s11n::GnssSerializer Class Reference
carla::sensor::s11n::GnssSerializer Class Reference
#include <GnssSerializer.h>
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static geom::GeoLocation DeserializeRawData (const RawData &message)
template<typename SensorT >
static Buffer Serialize (const SensorT &, const geom::GeoLocation &geo_location)
Detailed Description
Definition at line 24 of file GnssSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::GnssSerializer::Deserialize (RawData && data) static
Definition at line 15 of file GnssSerializer.cpp.
DeserializeRawData()
static geom::GeoLocation carla::sensor::s11n::GnssSerializer::DeserializeRawData (const RawData & message) inline static
Definition at line 27 of file GnssSerializer.h.
References carla::sensor::RawData::begin(), and carla::sensor::RawData::size().
Referenced by carla::sensor::data::GnssMeasurement::GnssMeasurement().
Serialize()
template<typename SensorT > static Buffer carla::sensor::s11n::GnssSerializer::Serialize (const SensorT & , const geom::GeoLocation & geo_location) inline static
Definition at line 32 of file GnssSerializer.h.
References carla::MsgPack::Pack().
The documentation for this class was generated from the following files:
GnssSerializer.h
GnssSerializer.cpp