CARLA: carla::sensor::s11n::ImageSerializer Class Reference
carla::sensor::s11n::ImageSerializer Class Reference
Serializes image buffers generated by camera sensors.
#include <ImageSerializer.h>
Classes
struct ImageHeader
Static Public Member Functions
static SharedPtr< SensorData > Deserialize (RawData &&data)
static const ImageHeader & DeserializeHeader (const RawData &data)
template<typename Sensor >
static Buffer Serialize (const Sensor &sensor, Buffer &&bitmap)
Static Public Attributes
static constexpr auto header_offset = sizeof(ImageHeader)
Detailed Description
Serializes image buffers generated by camera sensors.
Definition at line 23 of file ImageSerializer.h.
Member Function Documentation
Deserialize()
SharedPtr< SensorData > carla::sensor::s11n::ImageSerializer::Deserialize (RawData && data) static
Definition at line 15 of file ImageSerializer.cpp.
DeserializeHeader()
static const ImageHeader & carla::sensor::s11n::ImageSerializer::DeserializeHeader (const RawData & data) inline static
Definition at line 36 of file ImageSerializer.h.
References carla::sensor::RawData::begin().
Referenced by carla::sensor::data::ImageTmpl< PixelT >::GetHeader().
Serialize()
template<typename Sensor > Buffer carla::sensor::s11n::ImageSerializer::Serialize (const Sensor & sensor, Buffer && bitmap) inline static
Definition at line 47 of file ImageSerializer.h.
References DEBUG_ASSERT.
Member Data Documentation
header_offset
constexpr auto carla::sensor::s11n::ImageSerializer::header_offset = sizeof(ImageHeader) static constexpr
Definition at line 34 of file ImageSerializer.h.
Referenced by carla::ros2::ROS2::ProcessDataFromCamera(), and carla::ros2::ROS2::ProcessDataFromDVS().
The documentation for this class was generated from the following files:
ImageSerializer.h
ImageSerializer.cpp