CARLA: CarlaRecorderActorsKinematics Class Reference
CarlaRecorderActorsKinematics Class Reference
#include <CarlaRecorderKinematics.h>
Public Member Functions
void Add (const CarlaRecorderKinematics &InObj)
void Clear (void)
void Write (std::ostream &OutFile)
Private Attributes
std::vector< CarlaRecorderKinematics > Kinematics
Detailed Description
Definition at line 25 of file CarlaRecorderKinematics.h.
Member Function Documentation
Add()
void CarlaRecorderActorsKinematics::Add (const CarlaRecorderKinematics & InObj)
Definition at line 32 of file CarlaRecorderKinematics.cpp.
References Kinematics.
Referenced by FFrameData::AddKinematics(), and ACarlaRecorder::AddKinematics().
Clear()
void CarlaRecorderActorsKinematics::Clear (void)
Definition at line 27 of file CarlaRecorderKinematics.cpp.
References Kinematics.
Referenced by FFrameData::Clear(), and ACarlaRecorder::Clear().
Write()
void CarlaRecorderActorsKinematics::Write (std::ostream & OutFile)
Definition at line 37 of file CarlaRecorderKinematics.cpp.
References Kinematics, and Kinematics.
Referenced by ACarlaRecorder::Write().
Member Data Documentation
Kinematics
std::vector<CarlaRecorderKinematics> CarlaRecorderActorsKinematics::Kinematics private
Definition at line 37 of file CarlaRecorderKinematics.h.
Referenced by Add(), Clear(), and Write().
The documentation for this class was generated from the following files:
CarlaRecorderKinematics.h
CarlaRecorderKinematics.cpp