CARLA: WheeledVehicleAIController.cpp File Reference
WheeledVehicleAIController.cpp File Reference
#include "Carla.h"
#include "WheeledVehicleAIController.h"
#include "MapGen/RoadMap.h"
#include "Traffic/RoutePlanner.h"
#include "Vehicle/CarlaWheeledVehicle.h"
#include "Carla/CityMapGenerator.h"
#include "Carla/Util/RandomEngine.h"
#include "EngineUtils.h"
#include "GameFramework/Pawn.h"
#include "WheeledVehicleMovementComponent.h"
Functions
template<typename T >
static void ClearQueue (std::queue< T > &Queue)
static bool IsThereAnObstacleAhead (const ACarlaWheeledVehicle &Vehicle, const float Speed, const FVector &Direction)
static bool RayCast (const AActor &Actor, const FVector &Start, const FVector &End)
Function Documentation
ClearQueue()
template<typename T > static void ClearQueue (std::queue< T > & Queue) static
Definition at line 75 of file WheeledVehicleAIController.cpp.
Referenced by AWheeledVehicleAIController::ConfigureAutopilot(), and AWheeledVehicleAIController::SetFixedRoute().
IsThereAnObstacleAhead()
static bool IsThereAnObstacleAhead (const ACarlaWheeledVehicle & Vehicle, const float Speed, const FVector & Direction) static
Definition at line 44 of file WheeledVehicleAIController.cpp.
References RayCast(), and Vehicle.
RayCast()
static bool RayCast (const AActor & Actor, const FVector & Start, const FVector & End) static
Definition at line 24 of file WheeledVehicleAIController.cpp.
References Success.
Referenced by IsThereAnObstacleAhead().