CARLA: carla::client::detail::ActorState Class Reference
carla::client::detail::ActorState Class Reference
Internal state of an Actor.
#include <ActorState.h>
Public Member Functions
const std::vector< ActorAttributeValue > & GetAttributes () const
const std::string & GetDisplayId () const
ActorId GetId () const
SharedPtr< Actor > GetParent () const
ActorId GetParentId () const
const std::vector< uint8_t > & GetSemanticTags () const
const std::string & GetTypeId () const
World GetWorld () const
Protected Member Functions
ActorState (rpc::Actor description, EpisodeProxy episode)
const rpc::Actor & GetActorDescription () const
const geom::BoundingBox & GetBoundingBox () const
EpisodeProxy & GetEpisode ()
const EpisodeProxy & GetEpisode () const
Private Attributes
std::vector< ActorAttributeValue > _attributes
rpc::Actor _description
std::string _display_id
EpisodeProxy _episode
Friends
class Simulator
Additional Inherited Members
Private Member Functions inherited from carla::MovableNonCopyable
MovableNonCopyable ()=default
MovableNonCopyable (const MovableNonCopyable &)=delete
MovableNonCopyable (MovableNonCopyable &&)=default
MovableNonCopyable & operator= (const MovableNonCopyable &)=delete
MovableNonCopyable & operator= (MovableNonCopyable &&)=default
Detailed Description
Internal state of an Actor.
Definition at line 22 of file client/detail/ActorState.h.
Constructor & Destructor Documentation
ActorState()
carla::client::detail::ActorState::ActorState (rpc::Actor description, EpisodeProxy episode) explicit protected
Member Function Documentation
GetActorDescription()
const rpc::Actor & carla::client::detail::ActorState::GetActorDescription () const inline protected
Definition at line 64 of file client/detail/ActorState.h.
References _description.
Referenced by carla::client::detail::Simulator::DisableForROS(), carla::client::detail::Simulator::EnableForROS(), carla::client::detail::Simulator::IsEnabledForROS(), carla::client::ServerSideSensor::ListenToGBuffer(), carla::client::ServerSideSensor::Send(), carla::client::Actor::Serialize(), carla::client::ServerSideSensor::StopGBuffer(), carla::client::detail::Simulator::SubscribeToSensor(), and carla::client::detail::Simulator::UnSubscribeFromSensor().
GetAttributes()
const std::vector< ActorAttributeValue > & carla::client::detail::ActorState::GetAttributes () const inline
Definition at line 51 of file client/detail/ActorState.h.
References _attributes.
GetBoundingBox()
const geom::BoundingBox & carla::client::detail::ActorState::GetBoundingBox () const inline protected
Definition at line 60 of file client/detail/ActorState.h.
References _description, and carla::rpc::Actor::bounding_box.
GetDisplayId()
const std::string & carla::client::detail::ActorState::GetDisplayId () const inline
Definition at line 33 of file client/detail/ActorState.h.
References _display_id.
Referenced by carla::client::RssSensor::AppendRoutingTarget(), carla::client::Actor::Destroy(), carla::client::ServerSideSensor::Destroy(), carla::client::detail::Simulator::DestroyActor(), carla::client::RssSensor::GetEgoVehicleDynamics(), carla::client::RssSensor::GetOtherVehicleDynamics(), carla::client::RssSensor::GetPedestrianDynamics(), carla::client::RssSensor::GetRoadBoundariesMode(), carla::client::RssSensor::GetRoutingTargets(), carla::client::LaneInvasionSensor::Listen(), carla::client::ServerSideSensor::Listen(), carla::client::RssSensor::Listen(), carla::client::ServerSideSensor::ListenToGBuffer(), carla::client::RssSensor::RegisterActorConstellationCallback(), carla::client::detail::Simulator::RegisterAIController(), carla::client::RssSensor::ResetRoutingTargets(), carla::client::ServerSideSensor::Send(), carla::client::RssSensor::SetEgoVehicleDynamics(), carla::client::RssSensor::SetLogLevel(), carla::client::RssSensor::SetMapLogLevel(), carla::client::RssSensor::SetOtherVehicleDynamics(), carla::client::RssSensor::SetPedestrianDynamics(), carla::client::RssSensor::SetRoadBoundariesMode(), carla::client::ServerSideSensor::Stop(), carla::client::RssSensor::Stop(), carla::client::ServerSideSensor::StopGBuffer(), carla::client::detail::Simulator::UnregisterAIController(), and carla::client::ServerSideSensor::~ServerSideSensor().
GetEpisode() [1/2]
EpisodeProxy & carla::client::detail::ActorState::GetEpisode () inline protected
Definition at line 68 of file client/detail/ActorState.h.
References _episode.
Referenced by carla::client::Actor::AddAngularImpulse(), carla::client::Actor::AddForce(), carla::client::Actor::AddForce(), carla::client::Actor::AddImpulse(), carla::client::Actor::AddImpulse(), carla::client::Actor::AddTorque(), carla::client::Vehicle::ApplyAckermannControl(), carla::client::Vehicle::ApplyAckermannControllerSettings(), carla::client::Vehicle::ApplyControl(), carla::client::Walker::ApplyControl(), carla::client::Vehicle::ApplyPhysicsControl(), carla::client::Walker::BlendPose(), carla::client::Vehicle::CloseDoor(), carla::client::Actor::Destroy(), carla::client::detail::Simulator::DestroyActor(), carla::client::Actor::DisableConstantVelocity(), carla::client::ServerSideSensor::DisableForROS(), carla::client::Vehicle::EnableCarSim(), carla::client::Vehicle::EnableChronoPhysics(), carla::client::Actor::EnableConstantVelocity(), carla::client::ServerSideSensor::EnableForROS(), carla::client::TrafficLight::Freeze(), carla::client::Actor::GetAcceleration(), carla::client::Vehicle::GetAckermannControllerSettings(), carla::client::Actor::GetActorState(), carla::client::TrafficLight::GetAffectedLaneWaypoints(), carla::client::Actor::GetAngularVelocity(), carla::client::Actor::GetBoneNames(), carla::client::Actor::GetBoneRelativeTransforms(), carla::client::Walker::GetBonesTransform(), carla::client::Actor::GetBoneWorldTransforms(), carla::client::Actor::GetComponentNames(), carla::client::Actor::GetComponentRelativeTransform(), carla::client::Actor::GetComponentWorldTransform(), carla::client::Vehicle::GetControl(), carla::client::TrafficLight::GetElapsedTime(), carla::client::Vehicle::GetFailureState(), carla::client::TrafficLight::GetGreenTime(), carla::client::TrafficLight::GetGroupTrafficLights(), carla::client::TrafficLight::GetLightBoxes(), carla::client::Vehicle::GetLightState(), carla::client::Actor::GetLocation(), carla::client::TrafficLight::GetOpenDRIVEID(), carla::client::Vehicle::GetPhysicsControl(), carla::client::TrafficLight::GetPoleIndex(), carla::client::Walker::GetPoseFromAnimation(), carla::client::WalkerAIController::GetRandomLocation(), carla::client::TrafficLight::GetRedTime(), carla::client::TrafficSign::GetSignId(), carla::client::Actor::GetSocketNames(), carla::client::Actor::GetSocketRelativeTransforms(), carla::client::Actor::GetSocketWorldTransforms(), carla::client::Vehicle::GetSpeedLimit(), carla::client::TrafficLight::GetState(), carla::client::TrafficLight::GetStopWaypoints(), carla::client::Vehicle::GetTelemetryData(), carla::client::Vehicle::GetTrafficLight(), carla::client::Vehicle::GetTrafficLightState(), carla::client::Actor::GetTransform(), carla::client::Actor::GetVelocity(), carla::client::Walker::GetWalkerControl(), carla::client::Vehicle::GetWheelSteerAngle(), carla::client::TrafficLight::GetYellowTime(), carla::client::WalkerAIController::GoToLocation(), carla::client::Actor::IsActive(), carla::client::Actor::IsAlive(), carla::client::Vehicle::IsAtTrafficLight(), carla::client::Actor::IsDormant(), carla::client::ServerSideSensor::IsEnabledForROS(), carla::client::TrafficLight::IsFrozen(), carla::client::LaneInvasionSensor::Listen(), carla::client::ServerSideSensor::Listen(), carla::client::RssSensor::Listen(), carla::client::ServerSideSensor::ListenToGBuffer(), carla::client::Vehicle::OpenDoor(), carla::client::TrafficLight::ResetGroup(), carla::client::Vehicle::RestorePhysXPhysics(), carla::client::ServerSideSensor::Send(), carla::client::Actor::SetActorDead(), carla::client::Vehicle::SetAutopilot(), carla::client::Walker::SetBonesTransform(), carla::client::Actor::SetCollisions(), carla::client::Actor::SetEnableGravity(), carla::client::TrafficLight::SetGreenTime(), carla::client::Vehicle::SetLightState(), carla::client::Actor::SetLocation(), carla::client::WalkerAIController::SetMaxSpeed(), carla::client::TrafficLight::SetRedTime(), carla::client::Actor::SetSimulatePhysics(), carla::client::TrafficLight::SetState(), carla::client::Actor::SetTargetAngularVelocity(), carla::client::Actor::SetTargetVelocity(), carla::client::Actor::SetTransform(), carla::client::Vehicle::SetWheelSteerDirection(), carla::client::TrafficLight::SetYellowTime(), carla::client::Vehicle::ShowDebugTelemetry(), carla::client::WalkerAIController::Start(), carla::client::WalkerAIController::Stop(), carla::client::LaneInvasionSensor::Stop(), carla::client::ServerSideSensor::Stop(), carla::client::RssSensor::Stop(), carla::client::ServerSideSensor::StopGBuffer(), carla::client::Vehicle::UseCarSimRoad(), and carla::client::ServerSideSensor::~ServerSideSensor().
GetEpisode() [2/2]
const EpisodeProxy & carla::client::detail::ActorState::GetEpisode () const inline protected
Definition at line 72 of file client/detail/ActorState.h.
References _episode.
GetId()
ActorId carla::client::detail::ActorState::GetId () const inline
Definition at line 25 of file client/detail/ActorState.h.
References _description, and carla::rpc::Actor::id.
Referenced by carla::client::detail::Simulator::AddActorAngularImpulse(), carla::client::detail::Simulator::AddActorForce(), carla::client::detail::Simulator::AddActorForce(), carla::client::detail::Simulator::AddActorImpulse(), carla::client::detail::Simulator::AddActorImpulse(), carla::client::detail::Simulator::AddActorTorque(), carla::client::detail::Simulator::ApplyAckermannControllerSettings(), carla::client::detail::Simulator::ApplyAckermannControlToVehicle(), carla::client::detail::Simulator::ApplyControlToVehicle(), carla::client::detail::Simulator::ApplyControlToWalker(), carla::client::detail::Simulator::ApplyPhysicsControlToVehicle(), carla::client::detail::Simulator::BlendPose(), carla::client::detail::Simulator::CloseVehicleDoor(), carla::rss::RssCheck::CreateWorldModel(), carla::client::detail::Simulator::DestroyActor(), carla::client::detail::Simulator::DisableActorConstantVelocity(), carla::client::detail::Simulator::EnableActorConstantVelocity(), carla::client::detail::Simulator::EnableCarSim(), carla::client::detail::Simulator::EnableChronoPhysics(), carla::client::detail::Simulator::FreezeTrafficLight(), carla::client::detail::Simulator::GetAckermannControllerSettings(), carla::client::detail::Simulator::GetActorBoneNames(), carla::client::detail::Simulator::GetActorBoneRelativeTransforms(), carla::client::detail::Simulator::GetActorBoneWorldTransforms(), carla::client::detail::Simulator::GetActorComponentNames(), carla::client::detail::Simulator::GetActorComponentRelativeTransform(), carla::client::detail::Simulator::GetActorComponentWorldTransform(), carla::client::detail::Simulator::GetActorSnapshot(), carla::client::detail::Simulator::GetActorSocketNames(), carla::client::detail::Simulator::GetActorSocketRelativeTransforms(), carla::client::detail::Simulator::GetActorSocketWorldTransforms(), carla::client::detail::Simulator::GetBonesTransform(), carla::client::detail::Simulator::GetGroupTrafficLights(), carla::client::detail::Simulator::GetLightBoxes(), carla::client::detail::Simulator::GetPoseFromAnimation(), carla::client::detail::Simulator::GetVehicleLightState(), carla::client::detail::Simulator::GetVehiclePhysicsControl(), carla::client::detail::Simulator::GetVehicleTelemetryData(), carla::client::detail::Simulator::GetWheelSteerAngle(), carla::client::detail::Simulator::OpenVehicleDoor(), carla::client::detail::Simulator::RegisterAIController(), carla::client::detail::Simulator::ResetTrafficLightGroup(), carla::client::detail::Simulator::RestorePhysXPhysics(), carla::client::detail::Simulator::Send(), carla::client::detail::Simulator::SetActorCollisions(), carla::client::detail::Simulator::SetActorDead(), carla::client::detail::Simulator::SetActorEnableGravity(), carla::client::detail::Simulator::SetActorLocation(), carla::client::detail::Simulator::SetActorSimulatePhysics(), carla::client::detail::Simulator::SetActorTargetAngularVelocity(), carla::client::detail::Simulator::SetActorTargetVelocity(), carla::client::detail::Simulator::SetActorTransform(), carla::client::detail::Simulator::SetBonesTransform(), carla::client::detail::Simulator::SetLightStateToVehicle(), carla::client::detail::Simulator::SetLightsToVehicle(), carla::client::detail::Simulator::SetTrafficLightGreenTime(), carla::client::detail::Simulator::SetTrafficLightRedTime(), carla::client::detail::Simulator::SetTrafficLightState(), carla::client::detail::Simulator::SetTrafficLightYellowTime(), carla::client::detail::Simulator::SetVehicleAutopilot(), carla::client::detail::Simulator::SetWheelSteerDirection(), carla::client::detail::Simulator::ShowVehicleDebugTelemetry(), carla::client::detail::Simulator::SpawnActor(), carla::client::detail::Simulator::SubscribeToGBuffer(), carla::client::detail::Simulator::UnregisterAIController(), carla::client::detail::Simulator::UnSubscribeFromGBuffer(), and carla::client::detail::Simulator::UseCarSimRoad().
GetParent()
SharedPtr< Actor > carla::client::detail::ActorState::GetParent () const
Definition at line 31 of file ActorState.cpp.
Referenced by carla::client::WalkerAIController::GoToLocation(), carla::client::LaneInvasionSensor::Listen(), carla::client::RssSensor::Listen(), carla::client::detail::Simulator::RegisterAIController(), carla::client::WalkerAIController::SetMaxSpeed(), carla::client::WalkerAIController::Start(), carla::client::WalkerAIController::Stop(), carla::client::RssSensor::TickRssSensorThreadLocked(), and carla::client::detail::Simulator::UnregisterAIController().
GetParentId()
ActorId carla::client::detail::ActorState::GetParentId () const inline
Definition at line 37 of file client/detail/ActorState.h.
References _description, and carla::rpc::Actor::parent_id.
GetSemanticTags()
const std::vector< uint8_t > & carla::client::detail::ActorState::GetSemanticTags () const inline
Definition at line 41 of file client/detail/ActorState.h.
References _description, and carla::rpc::Actor::semantic_tags.
GetTypeId()
const std::string & carla::client::detail::ActorState::GetTypeId () const inline
Definition at line 29 of file client/detail/ActorState.h.
References _description, carla::rpc::Actor::description, and carla::rpc::ActorDescription::id.
GetWorld()
World carla::client::detail::ActorState::GetWorld () const inline
Definition at line 47 of file client/detail/ActorState.h.
References _episode.
Referenced by carla::client::TrafficLight::GetGroupTrafficLights(), carla::client::Vehicle::GetTrafficLight(), carla::client::RssSensor::Listen(), and carla::client::RssSensor::TickRssSensor().
Friends And Related Symbol Documentation
Simulator
friend class Simulator friend
Definition at line 78 of file client/detail/ActorState.h.
Member Data Documentation
_attributes
std::vector<ActorAttributeValue> carla::client::detail::ActorState::_attributes private
Definition at line 86 of file client/detail/ActorState.h.
Referenced by GetAttributes().
_description
rpc::Actor carla::client::detail::ActorState::_description private
Definition at line 80 of file client/detail/ActorState.h.
Referenced by GetActorDescription(), GetBoundingBox(), GetId(), GetParentId(), GetSemanticTags(), and GetTypeId().
_display_id
std::string carla::client::detail::ActorState::_display_id private
Definition at line 84 of file client/detail/ActorState.h.
Referenced by GetDisplayId().
_episode
EpisodeProxy carla::client::detail::ActorState::_episode private
Definition at line 82 of file client/detail/ActorState.h.
Referenced by GetEpisode(), GetEpisode(), and GetWorld().
The documentation for this class was generated from the following files:
client/detail/ActorState.h
ActorState.cpp