CARLA: FDataStreamTmpl< T > Class Template Reference
FDataStreamTmpl< T > Class Template Reference
A streaming channel for sending sensor data to clients.
#include <DataStream.h>
Public Types
using StreamType = T
Public Member Functions
bool AreClientsListening ()
FDataStreamTmpl ()=default
FDataStreamTmpl (StreamType InStream)
uint64_t GetSensorType ()
auto GetToken () const
Return the token that allows subscribing to this stream.
bool IsStreamReady ()
template<typename SensorT >
FAsyncDataStreamTmpl< T > MakeAsyncDataStream (const SensorT &Sensor, double Timestamp)
Create a FAsyncDataStream object.
Private Attributes
boost::optional< StreamType > Stream
Detailed Description
template<typename T>
class FDataStreamTmpl< T >
A streaming channel for sending sensor data to clients.
Each sensor has its own FDataStream. Note however that this class does not provide a send function. In order to send data, a FAsyncDataStream needs to be created using "MakeAsyncDataStream" function. FAsyncDataStream allows sending data from any thread.
Definition at line 26 of file DataStream.h.
Member Typedef Documentation
StreamType
template<typename T > using FDataStreamTmpl< T >::StreamType = T
Definition at line 30 of file DataStream.h.
Constructor & Destructor Documentation
FDataStreamTmpl() [1/2]
template<typename T > FDataStreamTmpl< T >::FDataStreamTmpl () default
FDataStreamTmpl() [2/2]
template<typename T > FDataStreamTmpl< T >::FDataStreamTmpl (StreamType InStream) inline
Definition at line 34 of file DataStream.h.
Member Function Documentation
AreClientsListening()
template<typename T > bool FDataStreamTmpl< T >::AreClientsListening () inline
Definition at line 64 of file DataStream.h.
References FDataStreamTmpl< T >::Stream.
Referenced by ASensor::Tick().
GetSensorType()
template<typename T > uint64_t FDataStreamTmpl< T >::GetSensorType () inline
Definition at line 58 of file DataStream.h.
References FDataStreamTmpl< T >::Stream.
Referenced by AGnssSensor::PostPhysTick(), ADVSCamera::PostPhysTick(), and AInertialMeasurementUnit::PostPhysTick().
GetToken()
template<typename T > auto FDataStreamTmpl< T >::GetToken () const inline
Return the token that allows subscribing to this stream.
Definition at line 52 of file DataStream.h.
References FDataStreamTmpl< T >::Stream.
Referenced by ASensor::EndPlay(), FCameraGBufferUint8::GetToken(), FCameraGBufferFloat::GetToken(), and FWorldObserver::GetToken().
IsStreamReady()
template<typename T > bool FDataStreamTmpl< T >::IsStreamReady () inline
Definition at line 46 of file DataStream.h.
References FDataStreamTmpl< T >::Stream.
Referenced by FWorldObserver::BroadcastTick().
MakeAsyncDataStream()
template<typename T > template<typename SensorT > FAsyncDataStreamTmpl< T > FDataStreamTmpl< T >::MakeAsyncDataStream (const SensorT & Sensor, double Timestamp) inline
Create a FAsyncDataStream object.
Precondition
This functions needs to be called in the game-thread.
Definition at line 40 of file DataStream.h.
References FDataStreamTmpl< T >::Stream.
Referenced by FWorldObserver::BroadcastTick(), FCameraGBufferUint8::GetDataStream(), and FCameraGBufferFloat::GetDataStream().
Member Data Documentation
Stream
template<typename T > boost::optional<StreamType> FDataStreamTmpl< T >::Stream private
Definition at line 72 of file DataStream.h.
Referenced by FDataStreamTmpl< T >::AreClientsListening(), FDataStreamTmpl< T >::GetSensorType(), FDataStreamTmpl< T >::GetToken(), FDataStreamTmpl< T >::IsStreamReady(), FDataStreamTmpl< T >::MakeAsyncDataStream(), FAsyncDataStreamTmpl< T >::Send(), and FAsyncDataStreamTmpl< T >::SerializeAndSend().
The documentation for this class was generated from the following files:
AsyncDataStream.h
DataStream.h