CARLA: carla::traffic_manager::AtomicActorSet Class Reference
carla::traffic_manager::AtomicActorSet Class Reference
#include <AtomicActorSet.h>
Public Member Functions
AtomicActorSet ()
void Clear ()
bool Contains (ActorId id)
void Destroy (ActorId actor_id)
std::vector< ActorId > GetIDList ()
std::vector< ActorPtr > GetList ()
int GetState ()
void Insert (std::vector< ActorPtr > actor_list)
void Remove (std::vector< ActorId > actor_id_list)
size_t Size ()
Private Attributes
std::map< ActorId, ActorPtr > actor_set
std::mutex modification_mutex
int state_counter
Detailed Description
Definition at line 23 of file AtomicActorSet.h.
Constructor & Destructor Documentation
AtomicActorSet()
carla::traffic_manager::AtomicActorSet::AtomicActorSet () inline
Definition at line 33 of file AtomicActorSet.h.
Member Function Documentation
Clear()
void carla::traffic_manager::AtomicActorSet::Clear () inline
Definition at line 104 of file AtomicActorSet.h.
References actor_set, and modification_mutex.
Referenced by carla::traffic_manager::TrafficManagerLocal::Stop().
Contains()
bool carla::traffic_manager::AtomicActorSet::Contains (ActorId id) inline
Definition at line 92 of file AtomicActorSet.h.
References actor_set, and modification_mutex.
Referenced by carla::traffic_manager::ALSM::IdentifyDestroyedActors(), and carla::traffic_manager::ALSM::IdentifyNewActors().
Destroy()
void carla::traffic_manager::AtomicActorSet::Destroy (ActorId actor_id) inline
Definition at line 75 of file AtomicActorSet.h.
References actor_set, modification_mutex, and state_counter.
Referenced by carla::traffic_manager::ALSM::Update().
GetIDList()
std::vector< ActorId > carla::traffic_manager::AtomicActorSet::GetIDList () inline
Definition at line 45 of file AtomicActorSet.h.
References actor_set, and modification_mutex.
Referenced by carla::traffic_manager::TrafficManagerLocal::GetRegisteredVehiclesIDs(), carla::traffic_manager::ALSM::IdentifyDestroyedActors(), and carla::traffic_manager::TrafficManagerLocal::Run().
GetList()
std::vector< ActorPtr > carla::traffic_manager::AtomicActorSet::GetList () inline
Definition at line 35 of file AtomicActorSet.h.
References actor_set, and modification_mutex.
Referenced by carla::traffic_manager::ALSM::UpdateRegisteredActorsData().
GetState()
int carla::traffic_manager::AtomicActorSet::GetState () inline
Definition at line 86 of file AtomicActorSet.h.
References modification_mutex, and state_counter.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run().
Insert()
void carla::traffic_manager::AtomicActorSet::Insert (std::vector< ActorPtr > actor_list) inline
Definition at line 55 of file AtomicActorSet.h.
References actor_set, modification_mutex, and state_counter.
Referenced by carla::traffic_manager::TrafficManagerLocal::RegisterVehicles().
Remove()
void carla::traffic_manager::AtomicActorSet::Remove (std::vector< ActorId > actor_id_list) inline
Definition at line 64 of file AtomicActorSet.h.
References actor_set, modification_mutex, and state_counter.
Referenced by carla::traffic_manager::ALSM::RemoveActor().
Size()
size_t carla::traffic_manager::AtomicActorSet::Size () inline
Definition at line 98 of file AtomicActorSet.h.
References actor_set, and modification_mutex.
Referenced by carla::traffic_manager::TrafficManagerLocal::Run().
Member Data Documentation
actor_set
std::map<ActorId, ActorPtr> carla::traffic_manager::AtomicActorSet::actor_set private
Definition at line 28 of file AtomicActorSet.h.
Referenced by Clear(), Contains(), Destroy(), GetIDList(), GetList(), Insert(), Remove(), and Size().
modification_mutex
std::mutex carla::traffic_manager::AtomicActorSet::modification_mutex private
Definition at line 27 of file AtomicActorSet.h.
Referenced by Clear(), Contains(), Destroy(), GetIDList(), GetList(), GetState(), Insert(), Remove(), and Size().
state_counter
int carla::traffic_manager::AtomicActorSet::state_counter private
Definition at line 29 of file AtomicActorSet.h.
Referenced by Destroy(), GetState(), Insert(), and Remove().
The documentation for this class was generated from the following file:
AtomicActorSet.h