CARLA: carla::multigpu::SecondaryCommands Class Reference
carla::multigpu::SecondaryCommands Class Reference
#include <secondaryCommands.h>
Public Types
using callback_type = std::function<void(MultiGPUCommand, carla::Buffer)>
Public Member Functions
void process_command (Buffer buffer)
void set_callback (callback_type callback)
void set_secondary (std::shared_ptr< Secondary > secondary)
Private Attributes
callback_type _callback
std::shared_ptr< Secondary > _secondary
Detailed Description
Definition at line 19 of file secondaryCommands.h.
Member Typedef Documentation
callback_type
using carla::multigpu::SecondaryCommands::callback_type = std::function<void(MultiGPUCommand, carla::Buffer)>
Definition at line 22 of file secondaryCommands.h.
Member Function Documentation
process_command()
void carla::multigpu::SecondaryCommands::process_command (Buffer buffer)
Definition at line 22 of file secondaryCommands.cpp.
References _callback, carla::Buffer::data(), carla::multigpu::CommandHeader::id, and carla::multigpu::CommandHeader::size.
set_callback()
void carla::multigpu::SecondaryCommands::set_callback (callback_type callback)
Definition at line 18 of file secondaryCommands.cpp.
References _callback.
Referenced by carla::multigpu::Secondary::Secondary(), and carla::multigpu::Secondary::Secondary().
set_secondary()
void carla::multigpu::SecondaryCommands::set_secondary (std::shared_ptr< Secondary > secondary)
Definition at line 14 of file secondaryCommands.cpp.
References _secondary.
Referenced by carla::multigpu::Secondary::Connect().
Member Data Documentation
_callback
callback_type carla::multigpu::SecondaryCommands::_callback private
Definition at line 30 of file secondaryCommands.h.
Referenced by process_command(), and set_callback().
_secondary
std::shared_ptr<Secondary> carla::multigpu::SecondaryCommands::_secondary private
Definition at line 29 of file secondaryCommands.h.
Referenced by set_secondary().
The documentation for this class was generated from the following files:
secondaryCommands.h
secondaryCommands.cpp