CARLA: test_geom.cpp File Reference
test_geom.cpp File Reference
#include "test.h"
#include <carla/geom/Vector3D.h>
#include <carla/geom/Math.h>
#include <carla/geom/BoundingBox.h>
#include <carla/geom/Transform.h>
#include <limits>
Namespaces
namespace carla
This file contains definitions of common data structures used in traffic manager.
namespace carla::geom
Functions
std::ostream & carla::geom::operator<< (std::ostream &out, const Vector3D &vector3D)
TEST (geom, bbox_get_local_vertices_get_world_vertices_coherence)
TEST (geom, distance)
TEST (geom, forward_vector)
TEST (geom, nearest_point_arc)
TEST (geom, nearest_point_segment)
TEST (geom, single_point_no_transform)
TEST (geom, single_point_rotation)
TEST (geom, single_point_transform_inverse_transform_coherence)
TEST (geom, single_point_translation)
TEST (geom, single_point_translation_and_rotation)
Function Documentation
TEST() [1/10]
TEST (geom , bbox_get_local_vertices_get_world_vertices_coherence)
Definition at line 82 of file test_geom.cpp.
References carla::geom::BoundingBox::GetLocalVertices(), carla::geom::BoundingBox::GetWorldVertices(), and carla::geom::Transform::TransformPoint().
TEST() [2/10]
TEST (geom , distance)
Definition at line 138 of file test_geom.cpp.
References carla::geom::Math::Distance().
TEST() [3/10]
TEST (geom , forward_vector)
Definition at line 199 of file test_geom.cpp.
References carla::geom::Rotation::GetForwardVector().
TEST() [4/10]
TEST (geom , nearest_point_arc)
Definition at line 220 of file test_geom.cpp.
References carla::geom::Math::DistanceArcToPoint().
TEST() [5/10]
TEST (geom , nearest_point_segment)
Definition at line 151 of file test_geom.cpp.
References carla::geom::Math::DistanceSegmentToPoint().
TEST() [6/10]
TEST (geom , single_point_no_transform)
Definition at line 28 of file test_geom.cpp.
References carla::geom::Transform::TransformPoint(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
TEST() [7/10]
TEST (geom , single_point_rotation)
Definition at line 108 of file test_geom.cpp.
References carla::geom::Transform::TransformPoint(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
TEST() [8/10]
TEST (geom , single_point_transform_inverse_transform_coherence)
Definition at line 62 of file test_geom.cpp.
References carla::geom::Transform::InverseTransformPoint(), carla::geom::Transform::TransformPoint(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
TEST() [9/10]
TEST (geom , single_point_translation)
Definition at line 45 of file test_geom.cpp.
References carla::geom::Transform::TransformPoint(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.
TEST() [10/10]
TEST (geom , single_point_translation_and_rotation)
Definition at line 123 of file test_geom.cpp.
References carla::geom::Transform::TransformPoint(), carla::geom::Vector3D::x, carla::geom::Vector3D::y, and carla::geom::Vector3D::z.