CARLA: carla::sensor::data::CustomV2XDataS Class Reference
carla::sensor::data::CustomV2XDataS Class Reference
#include <V2XData.h>
Public Member Functions
CustomV2XDataS ()=default
size_t GetMessageCount () const
CustomV2XDataS & operator= (CustomV2XDataS &&)=default
void Reset ()
void WriteMessage (CustomV2XData message)
Private Attributes
std::vector< CustomV2XData > MessageList
Friends
class s11n::CustomV2XDataSerializer
Detailed Description
Definition at line 72 of file V2XData.h.
Constructor & Destructor Documentation
CustomV2XDataS()
carla::sensor::data::CustomV2XDataS::CustomV2XDataS () explicit default
Member Function Documentation
GetMessageCount()
size_t carla::sensor::data::CustomV2XDataS::GetMessageCount () const inline
Definition at line 81 of file V2XData.h.
References MessageList.
Referenced by ACustomV2XSensor::PostPhysTick().
operator=()
CustomV2XDataS & carla::sensor::data::CustomV2XDataS::operator= (CustomV2XDataS &&) default
Reset()
void carla::sensor::data::CustomV2XDataS::Reset () inline
Definition at line 87 of file V2XData.h.
References MessageList.
Referenced by ACustomV2XSensor::PostPhysTick().
WriteMessage()
void carla::sensor::data::CustomV2XDataS::WriteMessage (CustomV2XData message) inline
Definition at line 93 of file V2XData.h.
References MessageList.
Referenced by ACustomV2XSensor::WriteMessageToV2XData().
Friends And Related Symbol Documentation
s11n::CustomV2XDataSerializer
friend class s11n::CustomV2XDataSerializer friend
Definition at line 101 of file V2XData.h.
Member Data Documentation
MessageList
std::vector<CustomV2XData> carla::sensor::data::CustomV2XDataS::MessageList private
Definition at line 99 of file V2XData.h.
Referenced by GetMessageCount(), Reset(), carla::sensor::s11n::CustomV2XDataSerializer::Serialize(), and WriteMessage().
The documentation for this class was generated from the following file:
V2XData.h