CARLA: carla::ros2::CarlaTransformPublisher Class Reference
carla::ros2::CarlaTransformPublisher Class Reference
#include <CarlaTransformPublisher.h>
Public Member Functions
CarlaTransformPublisher (CarlaTransformPublisher &&)
CarlaTransformPublisher (const CarlaTransformPublisher &)
CarlaTransformPublisher (const char *ros_name="", const char *parent="")
bool Init ()
CarlaTransformPublisher & operator= (CarlaTransformPublisher &&)
CarlaTransformPublisher & operator= (const CarlaTransformPublisher &)
bool Publish ()
void SetData (int32_t seconds, uint32_t nanoseconds, const float *translation, const float *rotation)
const char * type () const override
~CarlaTransformPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Attributes
std::shared_ptr< CarlaTransformPublisherImpl > _impl
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 18 of file CarlaTransformPublisher.h.
Constructor & Destructor Documentation
CarlaTransformPublisher() [1/3]
carla::ros2::CarlaTransformPublisher::CarlaTransformPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 204 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaTransformPublisher()
carla::ros2::CarlaTransformPublisher::~CarlaTransformPublisher ()
Definition at line 210 of file CarlaTransformPublisher.cpp.
References _impl.
CarlaTransformPublisher() [2/3]
carla::ros2::CarlaTransformPublisher::CarlaTransformPublisher (const CarlaTransformPublisher & other)
Definition at line 227 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaTransformPublisher() [3/3]
carla::ros2::CarlaTransformPublisher::CarlaTransformPublisher (CarlaTransformPublisher && other)
Definition at line 243 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
Init()
bool carla::ros2::CarlaTransformPublisher::Init ()
Definition at line 47 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, and carla::ros2::CarlaPublisher::_name.
operator=() [1/2]
CarlaTransformPublisher & carla::ros2::CarlaTransformPublisher::operator= (CarlaTransformPublisher && other)
Definition at line 250 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaTransformPublisher & carla::ros2::CarlaTransformPublisher::operator= (const CarlaTransformPublisher & other)
Definition at line 234 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaTransformPublisher::Publish ()
Definition at line 90 of file CarlaTransformPublisher.cpp.
References _impl.
SetData()
void carla::ros2::CarlaTransformPublisher::SetData (int32_t seconds, uint32_t nanoseconds, const float * translation, const float * rotation)
Definition at line 152 of file CarlaTransformPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_parent, geometry_msgs::msg::TransformStamped::child_frame_id(), std_msgs::msg::Header::frame_id(), geometry_msgs::msg::TransformStamped::header(), builtin_interfaces::msg::Time::nanosec(), geometry_msgs::msg::Transform::rotation(), builtin_interfaces::msg::Time::sec(), std_msgs::msg::Header::stamp(), geometry_msgs::msg::TransformStamped::transform(), and geometry_msgs::msg::Transform::translation().
type()
const char * carla::ros2::CarlaTransformPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 30 of file CarlaTransformPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaTransformPublisherImpl> carla::ros2::CarlaTransformPublisher::_impl private
Definition at line 33 of file CarlaTransformPublisher.h.
Referenced by CarlaTransformPublisher(), CarlaTransformPublisher(), Init(), operator=(), operator=(), Publish(), SetData(), and ~CarlaTransformPublisher().
The documentation for this class was generated from the following files:
CarlaTransformPublisher.h
CarlaTransformPublisher.cpp