CARLA: FTrafficLightData Class Reference
FTrafficLightData Class Reference
#include <ActorData.h>
Public Member Functions
virtual void RecordActorData (FCarlaActor *CarlaActor, UCarlaEpisode *CarlaEpisode) override
virtual AActor * RespawnActor (UCarlaEpisode *CarlaEpisode, const FActorInfo &Info) override
virtual void RestoreActorData (FCarlaActor *CarlaActor, UCarlaEpisode *CarlaEpisode) override
Public Member Functions inherited from FActorData
FTransform GetLocalTransform (UCarlaEpisode *CarlaEpisode) const
virtual ~FActorData ()
Public Attributes
UTrafficLightController * Controller
ETrafficLightState LightState
TSubclassOf< AActor > Model
int PoleIndex
FString SignId
Public Attributes inherited from FActorData
FVector AngularVelocity = FVector(0,0,0)
bool bSimulatePhysics = false
FDVector Location
FQuat Rotation
FVector Scale
FVector Velocity
Detailed Description
Definition at line 109 of file ActorData.h.
Member Function Documentation
RecordActorData()
void FTrafficLightData::RecordActorData (FCarlaActor * CarlaActor, UCarlaEpisode * CarlaEpisode) override virtual
Reimplemented from FActorData.
Definition at line 222 of file ActorData.cpp.
References UTrafficLightController::AddCarlaActorTrafficLight(), Controller, FCarlaActor::GetActor(), LightState, Model, PoleIndex, FActorData::RecordActorData(), UTrafficLightController::RemoveTrafficLight(), SignId, and TrafficLight.
RespawnActor()
AActor * FTrafficLightData::RespawnActor (UCarlaEpisode * CarlaEpisode, const FActorInfo & Info) override virtual
Reimplemented from FActorData.
Definition at line 210 of file ActorData.cpp.
References FActorData::GetLocalTransform(), Model, and UCarlaEpisode::SpawnActor().
RestoreActorData()
void FTrafficLightData::RestoreActorData (FCarlaActor * CarlaActor, UCarlaEpisode * CarlaEpisode) override virtual
Reimplemented from FActorData.
Definition at line 237 of file ActorData.cpp.
References UTrafficLightController::AddTrafficLight(), Controller, FCarlaActor::GetActor(), UTrafficLightController::GetCurrentState(), UCarlaStatics::GetGameMode(), ACarlaGameModeBase::GetMap(), LightState, PoleIndex, UTrafficLightController::RemoveCarlaActorTrafficLight(), SignId, FTrafficLightStage::State, and TrafficLight.
Member Data Documentation
Controller
UTrafficLightController* FTrafficLightData::Controller
Definition at line 113 of file ActorData.h.
Referenced by FWorldObserver_GetDormantActorState(), RecordActorData(), and RestoreActorData().
LightState
ETrafficLightState FTrafficLightData::LightState
Definition at line 115 of file ActorData.h.
Referenced by RecordActorData(), and RestoreActorData().
Model
TSubclassOf<AActor> FTrafficLightData::Model
Definition at line 119 of file ActorData.h.
Referenced by RecordActorData(), and RespawnActor().
PoleIndex
int FTrafficLightData::PoleIndex
Definition at line 121 of file ActorData.h.
Referenced by FWorldObserver_GetDormantActorState(), RecordActorData(), and RestoreActorData().
SignId
FString FTrafficLightData::SignId
Definition at line 117 of file ActorData.h.
Referenced by FWorldObserver_GetDormantActorState(), RecordActorData(), and RestoreActorData().
The documentation for this class was generated from the following files:
ActorData.h
ActorData.cpp