CARLA: carla::opendrive::parser::GeometryParser Class Reference
carla::opendrive::parser::GeometryParser Class Reference
#include <GeometryParser.h>
Static Public Member Functions
static void Parse (const pugi::xml_document &xml, carla::road::MapBuilder &map_builder)
Detailed Description
Definition at line 22 of file GeometryParser.h.
Member Function Documentation
Parse()
void carla::opendrive::parser::GeometryParser::Parse (const pugi::xml_document & xml, carla::road::MapBuilder & map_builder) static
Definition at line 61 of file GeometryParser.cpp.
References carla::opendrive::parser::GeometryPoly3::a, carla::road::MapBuilder::AddRoadGeometryArc(), carla::road::MapBuilder::AddRoadGeometryLine(), carla::road::MapBuilder::AddRoadGeometryParamPoly3(), carla::road::MapBuilder::AddRoadGeometryPoly3(), carla::road::MapBuilder::AddRoadGeometrySpiral(), carla::opendrive::parser::Geometry::arc, pugi::xml_attribute::as_double(), pugi::xml_node::attribute(), carla::opendrive::parser::GeometryParamPoly3::aU, carla::opendrive::parser::GeometryParamPoly3::aV, carla::opendrive::parser::GeometryPoly3::b, carla::opendrive::parser::GeometryParamPoly3::bU, carla::opendrive::parser::GeometryParamPoly3::bV, carla::opendrive::parser::GeometryPoly3::c, pugi::xml_node::child(), pugi::xml_node::children(), carla::opendrive::parser::GeometryParamPoly3::cU, carla::opendrive::parser::GeometryArc::curvature, carla::opendrive::parser::GeometrySpiral::curvEnd, carla::opendrive::parser::GeometrySpiral::curvStart, carla::opendrive::parser::GeometryParamPoly3::cV, carla::opendrive::parser::GeometryPoly3::d, carla::opendrive::parser::GeometryParamPoly3::dU, carla::opendrive::parser::GeometryParamPoly3::dV, pugi::xml_node::first_child(), carla::road::MapBuilder::GetRoad(), carla::opendrive::parser::Geometry::hdg, carla::opendrive::parser::Geometry::length, pugi::xml_node::name(), carla::opendrive::parser::GeometryParamPoly3::p_range, carla::opendrive::parser::Geometry::param_poly3, carla::opendrive::parser::Geometry::poly3, carla::opendrive::parser::Geometry::road_id, carla::opendrive::parser::Geometry::s, carla::opendrive::parser::Geometry::spiral, carla::opendrive::parser::Geometry::type, pugi::xml_attribute::value(), carla::opendrive::parser::Geometry::x, and carla::opendrive::parser::Geometry::y.
Referenced by carla::opendrive::OpenDriveParser::Load().
The documentation for this class was generated from the following files:
GeometryParser.h
GeometryParser.cpp