CARLA: carla::ros2::CarlaRGBCameraPublisher Class Reference
carla::ros2::CarlaRGBCameraPublisher Class Reference
#include <CarlaRGBCameraPublisher.h>
Public Member Functions
CarlaRGBCameraPublisher (CarlaRGBCameraPublisher &&)
CarlaRGBCameraPublisher (const CarlaRGBCameraPublisher &)
CarlaRGBCameraPublisher (const char *ros_name="", const char *parent="")
bool HasBeenInitialized () const
bool Init ()
void InitInfoData (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify)
CarlaRGBCameraPublisher & operator= (CarlaRGBCameraPublisher &&)
CarlaRGBCameraPublisher & operator= (const CarlaRGBCameraPublisher &)
bool Publish ()
void SetCameraInfoData (int32_t seconds, uint32_t nanoseconds)
void SetImageData (int32_t seconds, uint32_t nanoseconds, uint32_t height, uint32_t width, const uint8_t *data)
const char * type () const override
~CarlaRGBCameraPublisher ()
Public Member Functions inherited from carla::ros2::CarlaPublisher
CarlaPublisher ()=default
const std::string & frame_id () const
void frame_id (std::string &&frame_id)
const std::string & name () const
void name (std::string &&name)
const std::string & parent () const
void parent (std::string &&parent)
virtual ~CarlaPublisher ()=default
Private Member Functions
bool InitImage ()
bool InitInfo ()
bool PublishImage ()
bool PublishInfo ()
void SetImageData (int32_t seconds, uint32_t nanoseconds, uint32_t height, uint32_t width, std::vector< uint8_t > &&data)
void SetInfoRegionOfInterest (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify)
Private Attributes
std::shared_ptr< CarlaRGBCameraPublisherImpl > _impl
std::shared_ptr< CarlaCameraInfoPublisherImpl > _impl_info
Additional Inherited Members
Protected Attributes inherited from carla::ros2::CarlaPublisher
std::string _frame_id = ""
std::string _name = ""
std::string _parent = ""
Detailed Description
Definition at line 19 of file CarlaRGBCameraPublisher.h.
Constructor & Destructor Documentation
CarlaRGBCameraPublisher() [1/3]
carla::ros2::CarlaRGBCameraPublisher::CarlaRGBCameraPublisher (const char * ros_name = "", const char * parent = "")
Definition at line 342 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_name, carla::ros2::CarlaPublisher::_parent, and carla::ros2::CarlaPublisher::parent().
~CarlaRGBCameraPublisher()
carla::ros2::CarlaRGBCameraPublisher::~CarlaRGBCameraPublisher ()
Definition at line 349 of file CarlaRGBCameraPublisher.cpp.
References _impl, and _impl_info.
CarlaRGBCameraPublisher() [2/3]
carla::ros2::CarlaRGBCameraPublisher::CarlaRGBCameraPublisher (const CarlaRGBCameraPublisher & other)
Definition at line 381 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
CarlaRGBCameraPublisher() [3/3]
carla::ros2::CarlaRGBCameraPublisher::CarlaRGBCameraPublisher (CarlaRGBCameraPublisher && other)
Definition at line 399 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Member Function Documentation
HasBeenInitialized()
bool carla::ros2::CarlaRGBCameraPublisher::HasBeenInitialized () const
Definition at line 55 of file CarlaRGBCameraPublisher.cpp.
References _impl_info.
Init()
bool carla::ros2::CarlaRGBCameraPublisher::Init ()
Definition at line 65 of file CarlaRGBCameraPublisher.cpp.
References InitImage(), and InitInfo().
InitImage()
bool carla::ros2::CarlaRGBCameraPublisher::InitImage () private
Definition at line 69 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Referenced by Init().
InitInfo()
bool carla::ros2::CarlaRGBCameraPublisher::InitInfo () private
Definition at line 118 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Referenced by Init().
InitInfoData()
void carla::ros2::CarlaRGBCameraPublisher::InitInfoData (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify)
Definition at line 59 of file CarlaRGBCameraPublisher.cpp.
References _impl_info, and SetInfoRegionOfInterest().
operator=() [1/2]
CarlaRGBCameraPublisher & carla::ros2::CarlaRGBCameraPublisher::operator= (CarlaRGBCameraPublisher && other)
Definition at line 407 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
operator=() [2/2]
CarlaRGBCameraPublisher & carla::ros2::CarlaRGBCameraPublisher::operator= (const CarlaRGBCameraPublisher & other)
Definition at line 389 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, _impl_info, carla::ros2::CarlaPublisher::_name, and carla::ros2::CarlaPublisher::_parent.
Publish()
bool carla::ros2::CarlaRGBCameraPublisher::Publish ()
Definition at line 166 of file CarlaRGBCameraPublisher.cpp.
References PublishImage(), and PublishInfo().
PublishImage()
bool carla::ros2::CarlaRGBCameraPublisher::PublishImage () private
Definition at line 170 of file CarlaRGBCameraPublisher.cpp.
References _impl.
Referenced by Publish().
PublishInfo()
bool carla::ros2::CarlaRGBCameraPublisher::PublishInfo () private
Definition at line 232 of file CarlaRGBCameraPublisher.cpp.
References _impl_info.
Referenced by Publish().
SetCameraInfoData()
void carla::ros2::CarlaRGBCameraPublisher::SetCameraInfoData (int32_t seconds, uint32_t nanoseconds)
Definition at line 321 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl_info, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
SetImageData() [1/2]
void carla::ros2::CarlaRGBCameraPublisher::SetImageData (int32_t seconds, uint32_t nanoseconds, uint32_t height, uint32_t width, const uint8_t * data)
Definition at line 294 of file CarlaRGBCameraPublisher.cpp.
References SetImageData().
Referenced by SetImageData().
SetImageData() [2/2]
void carla::ros2::CarlaRGBCameraPublisher::SetImageData (int32_t seconds, uint32_t nanoseconds, uint32_t height, uint32_t width, std::vector< uint8_t > && data) private
Definition at line 302 of file CarlaRGBCameraPublisher.cpp.
References carla::ros2::CarlaPublisher::_frame_id, _impl, std_msgs::msg::Header::frame_id(), builtin_interfaces::msg::Time::nanosec(), builtin_interfaces::msg::Time::sec(), and std_msgs::msg::Header::stamp().
SetInfoRegionOfInterest()
void carla::ros2::CarlaRGBCameraPublisher::SetInfoRegionOfInterest (uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify) private
Definition at line 332 of file CarlaRGBCameraPublisher.cpp.
References _impl_info, sensor_msgs::msg::RegionOfInterest::do_rectify(), sensor_msgs::msg::RegionOfInterest::height(), sensor_msgs::msg::RegionOfInterest::width(), sensor_msgs::msg::RegionOfInterest::x_offset(), and sensor_msgs::msg::RegionOfInterest::y_offset().
Referenced by InitInfoData().
type()
const char * carla::ros2::CarlaRGBCameraPublisher::type () const inline override virtual
Implements carla::ros2::CarlaPublisher.
Definition at line 35 of file CarlaRGBCameraPublisher.h.
Member Data Documentation
_impl
std::shared_ptr<CarlaRGBCameraPublisherImpl> carla::ros2::CarlaRGBCameraPublisher::_impl private
Definition at line 47 of file CarlaRGBCameraPublisher.h.
Referenced by CarlaRGBCameraPublisher(), CarlaRGBCameraPublisher(), InitImage(), operator=(), operator=(), PublishImage(), SetImageData(), and ~CarlaRGBCameraPublisher().
_impl_info
std::shared_ptr<CarlaCameraInfoPublisherImpl> carla::ros2::CarlaRGBCameraPublisher::_impl_info private
Definition at line 48 of file CarlaRGBCameraPublisher.h.
Referenced by CarlaRGBCameraPublisher(), CarlaRGBCameraPublisher(), HasBeenInitialized(), InitInfo(), InitInfoData(), operator=(), operator=(), PublishInfo(), SetCameraInfoData(), SetInfoRegionOfInterest(), and ~CarlaRGBCameraPublisher().
The documentation for this class was generated from the following files:
CarlaRGBCameraPublisher.h
CarlaRGBCameraPublisher.cpp