CARLA: pugi Namespace Reference
pugi Namespace Reference
Classes
class xml_attribute
class xml_attribute_iterator
struct xml_attribute_struct
class xml_document
class xml_named_node_iterator
class xml_node
class xml_node_iterator
struct xml_node_struct
class xml_object_range
struct xml_parse_result
class xml_text
class xml_tree_walker
class xml_writer
class xml_writer_file
class xml_writer_stream
class xpath_exception
class xpath_node
class xpath_node_set
struct xpath_parse_result
class xpath_query
class xpath_variable
class xpath_variable_set
Typedefs
typedef void *(* allocation_function) (size_t size)
typedef PUGIXML_CHAR char_t
typedef void(* deallocation_function) (void *ptr)
typedef std::basic_string< PUGIXML_CHAR, std::char_traits< PUGIXML_CHAR >, std::allocator< PUGIXML_CHAR > > string_t
Enumerations
enum xml_encoding {
encoding_auto , encoding_utf8 , encoding_utf16_le , encoding_utf16_be ,
encoding_utf16 , encoding_utf32_le , encoding_utf32_be , encoding_utf32 ,
encoding_wchar , encoding_latin1
}
enum xml_node_type {
node_null , node_document , node_element , node_pcdata ,
node_cdata , node_comment , node_pi , node_declaration ,
node_doctype
}
enum xml_parse_status {
status_ok = 0 , status_file_not_found , status_io_error , status_out_of_memory ,
status_internal_error , status_unrecognized_tag , status_bad_pi , status_bad_comment ,
status_bad_cdata , status_bad_doctype , status_bad_pcdata , status_bad_start_element ,
status_bad_attribute , status_bad_end_element , status_end_element_mismatch , status_append_invalid_root ,
status_no_document_element
}
enum xpath_value_type {
xpath_type_none , xpath_type_node_set , xpath_type_number , xpath_type_string ,
xpath_type_boolean
}
Functions
PUGI__FN std::string PUGIXML_FUNCTION as_utf8 (const std::basic_string< wchar_t > &str)
std::basic_string< char, std::char_traits< char >, std::allocator< char > > PUGIXML_FUNCTION as_utf8 (const std::basic_string< wchar_t, std::char_traits< wchar_t >, std::allocator< wchar_t > > &str)
PUGI__FN std::string PUGIXML_FUNCTION as_utf8 (const wchar_t *str)
PUGI__FN std::basic_string< wchar_t > PUGIXML_FUNCTION as_wide (const char *str)
std::basic_string< wchar_t, std::char_traits< wchar_t >, std::allocator< wchar_t > > PUGIXML_FUNCTION as_wide (const std::basic_string< char, std::char_traits< char >, std::allocator< char > > &str)
PUGI__FN std::basic_string< wchar_t > PUGIXML_FUNCTION as_wide (const std::string &str)
PUGI__FN allocation_function PUGIXML_FUNCTION get_memory_allocation_function ()
PUGI__FN deallocation_function PUGIXML_FUNCTION get_memory_deallocation_function ()
PUGI__FN void PUGIXML_FUNCTION set_memory_management_functions (allocation_function allocate, deallocation_function deallocate)
static PUGI__FN void unspecified_bool_xml_attribute (xml_attribute ***)
static PUGI__FN void unspecified_bool_xml_node (xml_node ***)
static PUGI__FN void unspecified_bool_xml_text (xml_text ***)
static PUGI__FN void unspecified_bool_xpath_node (xpath_node ***)
static PUGI__FN void unspecified_bool_xpath_query (xpath_query ***)
Variables
const unsigned int format_default = format_indent
const unsigned int format_indent = 0x01
const unsigned int format_indent_attributes = 0x40
const unsigned int format_no_declaration = 0x08
const unsigned int format_no_empty_element_tags = 0x80
const unsigned int format_no_escapes = 0x10
const unsigned int format_raw = 0x04
const unsigned int format_save_file_text = 0x20
const unsigned int format_write_bom = 0x02
const unsigned int parse_cdata = 0x0004
const unsigned int parse_comments = 0x0002
const unsigned int parse_declaration = 0x0100
const unsigned int parse_default = parse_cdata | parse_escapes | parse_wconv_attribute | parse_eol
const unsigned int parse_doctype = 0x0200
const unsigned int parse_embed_pcdata = 0x2000
const unsigned int parse_eol = 0x0020
const unsigned int parse_escapes = 0x0010
const unsigned int parse_fragment = 0x1000
const unsigned int parse_full = parse_default | parse_pi | parse_comments | parse_declaration | parse_doctype
const unsigned int parse_minimal = 0x0000
const unsigned int parse_pi = 0x0001
const unsigned int parse_trim_pcdata = 0x0800
const unsigned int parse_wconv_attribute = 0x0040
const unsigned int parse_wnorm_attribute = 0x0080
const unsigned int parse_ws_pcdata = 0x0008
const unsigned int parse_ws_pcdata_single = 0x0400
Typedef Documentation
allocation_function
typedef void *(* pugi::allocation_function) (size_t size)
Definition at line 1399 of file pugixml.hpp.
char_t
typedef PUGIXML_CHAR pugi::char_t
Definition at line 128 of file pugixml.hpp.
deallocation_function
typedef void(* pugi::deallocation_function) (void *ptr)
Definition at line 1402 of file pugixml.hpp.
string_t
typedef std::basic_string<PUGIXML_CHAR, std::char_traits<PUGIXML_CHAR>, std::allocator<PUGIXML_CHAR> > pugi::string_t
Definition at line 132 of file pugixml.hpp.
Enumeration Type Documentation
xml_encoding
enum pugi::xml_encoding
Enumerator
encoding_auto
encoding_utf8
encoding_utf16_le
encoding_utf16_be
encoding_utf16
encoding_utf32_le
encoding_utf32_be
encoding_utf32
encoding_wchar
encoding_latin1
Definition at line 218 of file pugixml.hpp.
xml_node_type
enum pugi::xml_node_type
Enumerator
node_null
node_document
node_element
node_pcdata
node_cdata
node_comment
node_pi
node_declaration
node_doctype
Definition at line 140 of file pugixml.hpp.
xml_parse_status
enum pugi::xml_parse_status
Enumerator
status_ok
status_file_not_found
status_io_error
status_out_of_memory
status_internal_error
status_unrecognized_tag
status_bad_pi
status_bad_comment
status_bad_cdata
status_bad_doctype
status_bad_pcdata
status_bad_start_element
status_bad_attribute
status_bad_end_element
status_end_element_mismatch
status_append_invalid_root
status_no_document_element
Definition at line 947 of file pugixml.hpp.
xpath_value_type
enum pugi::xpath_value_type
Enumerator
xpath_type_none
xpath_type_node_set
xpath_type_number
xpath_type_string
xpath_type_boolean
Definition at line 1076 of file pugixml.hpp.
Function Documentation
as_utf8() [1/3]
PUGI__FN std::string PUGIXML_FUNCTION pugi::as_utf8 (const std::basic_string< wchar_t > & str)
Definition at line 7228 of file pugixml.cpp.
as_utf8() [2/3]
std::basic_string< char, std::char_traits< char >, std::allocator< char > > PUGIXML_FUNCTION pugi::as_utf8 (const std::basic_string< wchar_t, std::char_traits< wchar_t >, std::allocator< wchar_t > > & str)
References as_utf8(), and as_wide().
as_utf8() [3/3]
std::basic_string< char, std::char_traits< char >, std::allocator< char > > PUGIXML_FUNCTION pugi::as_utf8 (const wchar_t * str)
Definition at line 7221 of file pugixml.cpp.
Referenced by as_utf8().
as_wide() [1/3]
std::basic_string< wchar_t, std::char_traits< wchar_t >, std::allocator< wchar_t > > PUGIXML_FUNCTION pugi::as_wide (const char * str)
Definition at line 7233 of file pugixml.cpp.
Referenced by as_utf8(), and as_wide().
as_wide() [2/3]
std::basic_string< wchar_t, std::char_traits< wchar_t >, std::allocator< wchar_t > > PUGIXML_FUNCTION pugi::as_wide (const std::basic_string< char, std::char_traits< char >, std::allocator< char > > & str)
References as_wide().
as_wide() [3/3]
PUGI__FN std::basic_string< wchar_t > PUGIXML_FUNCTION pugi::as_wide (const std::string & str)
Definition at line 7240 of file pugixml.cpp.
get_memory_allocation_function()
allocation_function PUGIXML_FUNCTION pugi::get_memory_allocation_function ()
Definition at line 7252 of file pugixml.cpp.
get_memory_deallocation_function()
deallocation_function PUGIXML_FUNCTION pugi::get_memory_deallocation_function ()
Definition at line 7257 of file pugixml.cpp.
set_memory_management_functions()
void PUGIXML_FUNCTION pugi::set_memory_management_functions (allocation_function allocate, deallocation_function deallocate)
Definition at line 7246 of file pugixml.cpp.
unspecified_bool_xml_attribute()
static PUGI__FN void pugi::unspecified_bool_xml_attribute (xml_attribute ***) static
Definition at line 5109 of file pugixml.cpp.
Referenced by pugi::xml_attribute::operator unspecified_bool_type().
unspecified_bool_xml_node()
static PUGI__FN void pugi::unspecified_bool_xml_node (xml_node ***) static
Definition at line 5391 of file pugixml.cpp.
Referenced by pugi::xml_node::operator unspecified_bool_type().
unspecified_bool_xml_text()
static PUGI__FN void pugi::unspecified_bool_xml_text (xml_text ***) static
Definition at line 6376 of file pugixml.cpp.
Referenced by pugi::xml_text::operator unspecified_bool_type().
unspecified_bool_xpath_node()
static PUGI__FN void pugi::unspecified_bool_xpath_node (xpath_node ***) static
Definition at line 11980 of file pugixml.cpp.
Referenced by pugi::xpath_node::operator unspecified_bool_type().
unspecified_bool_xpath_query()
static PUGI__FN void pugi::unspecified_bool_xpath_query (xpath_query ***) static
Definition at line 12682 of file pugixml.cpp.
Referenced by pugi::xpath_query::operator unspecified_bool_type().
Variable Documentation
format_default
const unsigned int pugi::format_default = format_indent
Definition at line 260 of file pugixml.hpp.
format_indent
const unsigned int pugi::format_indent = 0x01
Definition at line 235 of file pugixml.hpp.
format_indent_attributes
const unsigned int pugi::format_indent_attributes = 0x40
Definition at line 253 of file pugixml.hpp.
format_no_declaration
const unsigned int pugi::format_no_declaration = 0x08
Definition at line 244 of file pugixml.hpp.
Referenced by pugi::xml_document::save().
format_no_empty_element_tags
const unsigned int pugi::format_no_empty_element_tags = 0x80
Definition at line 256 of file pugixml.hpp.
format_no_escapes
const unsigned int pugi::format_no_escapes = 0x10
Definition at line 247 of file pugixml.hpp.
format_raw
const unsigned int pugi::format_raw = 0x04
Definition at line 241 of file pugixml.hpp.
Referenced by pugi::xml_document::save().
format_save_file_text
const unsigned int pugi::format_save_file_text = 0x20
Definition at line 250 of file pugixml.hpp.
Referenced by pugi::xml_document::save_file(), and pugi::xml_document::save_file().
format_write_bom
const unsigned int pugi::format_write_bom = 0x02
Definition at line 238 of file pugixml.hpp.
Referenced by pugi::xml_document::save().
parse_cdata
const unsigned int pugi::parse_cdata = 0x0004
Definition at line 166 of file pugixml.hpp.
parse_comments
const unsigned int pugi::parse_comments = 0x0002
Definition at line 163 of file pugixml.hpp.
parse_declaration
const unsigned int pugi::parse_declaration = 0x0100
Definition at line 185 of file pugixml.hpp.
parse_default
const unsigned int pugi::parse_default = parse_cdata | parse_escapes | parse_wconv_attribute | parse_eol
Definition at line 210 of file pugixml.hpp.
parse_doctype
const unsigned int pugi::parse_doctype = 0x0200
Definition at line 188 of file pugixml.hpp.
parse_embed_pcdata
const unsigned int pugi::parse_embed_pcdata = 0x2000
Definition at line 205 of file pugixml.hpp.
parse_eol
const unsigned int pugi::parse_eol = 0x0020
Definition at line 176 of file pugixml.hpp.
parse_escapes
const unsigned int pugi::parse_escapes = 0x0010
Definition at line 173 of file pugixml.hpp.
parse_fragment
const unsigned int pugi::parse_fragment = 0x1000
Definition at line 200 of file pugixml.hpp.
parse_full
const unsigned int pugi::parse_full = parse_default | parse_pi | parse_comments | parse_declaration | parse_doctype
Definition at line 215 of file pugixml.hpp.
parse_minimal
const unsigned int pugi::parse_minimal = 0x0000
Definition at line 157 of file pugixml.hpp.
parse_pi
const unsigned int pugi::parse_pi = 0x0001
Definition at line 160 of file pugixml.hpp.
parse_trim_pcdata
const unsigned int pugi::parse_trim_pcdata = 0x0800
Definition at line 196 of file pugixml.hpp.
parse_wconv_attribute
const unsigned int pugi::parse_wconv_attribute = 0x0040
Definition at line 179 of file pugixml.hpp.
parse_wnorm_attribute
const unsigned int pugi::parse_wnorm_attribute = 0x0080
Definition at line 182 of file pugixml.hpp.
parse_ws_pcdata
const unsigned int pugi::parse_ws_pcdata = 0x0008
Definition at line 170 of file pugixml.hpp.
parse_ws_pcdata_single
const unsigned int pugi::parse_ws_pcdata_single = 0x0400
Definition at line 193 of file pugixml.hpp.