CARLA: UCarlaEpisode Class Reference
UCarlaEpisode Class Reference
A simulation episode.
#include <CarlaEpisode.h>
Public Member Functions
void ApplySettings (const FEpisodeSettings &Settings)
void AttachActors (AActor *Child, AActor *Parent, EAttachmentType InAttachmentType=EAttachmentType::Rigid, const FString &SocketName="")
Attach Child to Parent.
bool DestroyActor (AActor *Actor)
bool DestroyActor (carla::rpc::ActorId ActorId)
FCarlaActor * FindCarlaActor (AActor *Actor) const
Find the actor view of Actor.
FCarlaActor * FindCarlaActor (FCarlaActor::IdType ActorId)
Find a Carla actor by id.
const TArray< FActorDefinition > & GetActorDefinitions () const
Return the list of actor definitions that are available to be spawned this episode.
FString GetActorDescriptionFromStream (carla::streaming::detail::stream_id_type StreamId)
Get the description of the Carla actor (sensor) using specific stream id.
FActorRegistry & GetActorRegistry ()
const FActorRegistry & GetActorRegistry () const
FIntVector GetCurrentMapOrigin () const
double GetElapsedGameTime () const
Game seconds since the start of this episode.
FFrameData & GetFrameData ()
const carla::geom::GeoLocation & GetGeoReference () const
Return the GeoLocation point of the map loaded.
auto GetId () const
Return the unique id of this episode.
const FString & GetMapName () const
Return the name of the map loaded in this episode.
TArray< FTransform > GetRecommendedSpawnPoints () const
Return the list of recommended spawn points for vehicles.
ACarlaRecorder * GetRecorder () const
CarlaReplayer * GetReplayer () const
FSensorManager & GetSensorManager ()
const FEpisodeSettings & GetSettings () const
APawn * GetSpectatorPawn () const
double GetVisualGameTime () const
Visual game seconds.
AWeather * GetWeather () const
bool LoadNewEpisode (const FString &MapString, bool ResetSettings=true)
Load a new map and start a new episode.
bool LoadNewOpendriveEpisode (const FString &OpenDriveString, const carla::rpc::OpendriveGenerationParameters &Params)
Load a new map generating the mesh from OpenDRIVE data and start a new episode.
void PutActorToSleep (carla::rpc::ActorId ActorId)
AActor * ReSpawnActorWithInfo (const FTransform &Transform, FActorDescription thisActorDescription)
Spawns an actor based on ActorDescription at Transform.
carla::rpc::Actor SerializeActor (AActor *Actor) const
Create a serializable object describing the actor.
carla::rpc::Actor SerializeActor (FCarlaActor *CarlaActor) const
Create a serializable object describing the actor.
void SetCurrentMapOrigin (const FIntVector &NewOrigin)
void SetRecorder (ACarlaRecorder *Rec)
void SetVisualGameTime (double Time)
AActor * SpawnActor (const FTransform &Transform, FActorDescription ActorDescription)
Spawns an actor based on ActorDescription at Transform.
TPair< EActorSpawnResultStatus, FCarlaActor * > SpawnActorWithInfo (const FTransform &Transform, FActorDescription thisActorDescription, FCarlaActor::IdType DesiredId=0)
Spawns an actor based on ActorDescription at Transform.
std::string StartRecorder (std::string name, bool AdditionalData)
UCarlaEpisode (const FObjectInitializer &ObjectInitializer)
void WakeActorUp (carla::rpc::ActorId ActorId)
Public Attributes
bool bIsPrimaryServer = true
Private Member Functions
void EndPlay ()
void InitializeAtBeginPlay ()
void RegisterActorFactory (ACarlaActorFactory &ActorFactory)
bool SetActorCollisions (FCarlaActor &CarlaActor, bool bEnabled)
bool SetActorDead (FCarlaActor &CarlaActor)
bool SetActorSimulatePhysics (FCarlaActor &CarlaActor, bool bEnabled)
void TickTimers (float DeltaSeconds)
std::pair< int, FCarlaActor & > TryToCreateReplayerActor (FVector &Location, FVector &Rotation, FActorDescription &ActorDesc, unsigned int desiredId)
Private Attributes
UActorDispatcher * ActorDispatcher = nullptr
FIntVector CurrentMapOrigin
double ElapsedGameTime = 0.0
FEpisodeSettings EpisodeSettings
FFrameData FrameData
const uint64 Id = 0u
carla::geom::GeoLocation MapGeoReference
FString MapName
UMaterialParameterCollectionInstance * MaterialParameters = nullptr
ACarlaRecorder * Recorder = nullptr
FSensorManager SensorManager
APawn * Spectator = nullptr
double VisualGameTime = 0.0
AWeather * Weather = nullptr
Friends
class ACarlaGameModeBase
class FCarlaEngine
Detailed Description
A simulation episode.
Each time the level is restarted a new episode is created.
Definition at line 38 of file CarlaEpisode.h.
Constructor & Destructor Documentation
UCarlaEpisode()
UCarlaEpisode::UCarlaEpisode (const FObjectInitializer & ObjectInitializer)
Definition at line 56 of file CarlaEpisode.cpp.
References ActorDispatcher, FrameData, and FFrameData::SetEpisode().
Member Function Documentation
ApplySettings()
void UCarlaEpisode::ApplySettings (const FEpisodeSettings & Settings)
Definition at line 230 of file CarlaEpisode.cpp.
References FEpisodeSettings::ActorActiveDistance, EpisodeSettings, FCarlaStaticDelegates::OnEpisodeSettingsChange, and FEpisodeSettings::TileStreamingDistance.
Referenced by FCarlaServer::FPimpl::BindActions(), LoadNewEpisode(), FCarlaEngine::NotifyBeginEpisode(), and FCarlaEngine::OnPreTick().
AttachActors()
void UCarlaEpisode::AttachActors (AActor * Child, AActor * Parent, EAttachmentType InAttachmentType = EAttachmentType::Rigid, const FString & SocketName = "")
Attach Child to Parent.
Precondition
Actors cannot be null.
Definition at line 294 of file CarlaEpisode.cpp.
References FFrameData::AddEvent(), ACarlaRecorder::AddEvent(), UActorAttacher::AttachActors(), bIsPrimaryServer, CurrentMapOrigin, FindCarlaActor(), FCarlaActor::GetActorId(), GetFrameData(), ACarlaRecorder::IsEnabled(), and Recorder.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerEventParent(), and FActorRegistry::WakeActorUp().
DestroyActor() [1/2]
bool UCarlaEpisode::DestroyActor (AActor * Actor) inline
Definition at line 253 of file CarlaEpisode.h.
References FCarlaActor::GetActorId().
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::ProcessReplayerEventDel(), and CarlaReplayerHelper::ProcessReplayerEventDel().
DestroyActor() [2/2]
bool UCarlaEpisode::DestroyActor (carla::rpc::ActorId ActorId) inline
Definition at line 264 of file CarlaEpisode.h.
EndPlay()
void UCarlaEpisode::EndPlay (void) private
Definition at line 406 of file CarlaEpisode.cpp.
References ACarlaRecorder::GetReplayer(), CarlaReplayer::IsEnabled(), Recorder, CarlaReplayer::Stop(), and ACarlaRecorder::Stop().
Referenced by ACarlaGameModeBase::EndPlay().
FindCarlaActor() [1/2]
FCarlaActor * UCarlaEpisode::FindCarlaActor (AActor * Actor) const inline
Find the actor view of Actor.
If the actor is not found or is pending kill, the returned view is invalid.
Definition at line 182 of file CarlaEpisode.h.
FindCarlaActor() [2/2]
FCarlaActor * UCarlaEpisode::FindCarlaActor (FCarlaActor::IdType ActorId) inline
Find a Carla actor by id.
If the actor is not found or is pending kill, the returned view is invalid.
Definition at line 173 of file CarlaEpisode.h.
Referenced by AttachActors(), FCarlaServer::FPimpl::BindActions(), ALargeMapManager::CheckActiveActors(), ALargeMapManager::CheckDormantActors(), ALargeMapManager::ConvertDormantToActiveActors(), FFrameData::CreateOrReuseActor(), ACarlaRecorder::CreateRecorderEventAdd(), FFrameData::CreateRecorderEventAdd(), CaService::GetStationType(), ALargeMapManager::OnActorDestroyed(), FFrameData::ProcessReplayerAnimBiker(), CarlaReplayerHelper::ProcessReplayerAnimBiker(), FFrameData::ProcessReplayerAnimVehicle(), CarlaReplayerHelper::ProcessReplayerAnimVehicle(), FFrameData::ProcessReplayerAnimVehicleWheels(), CarlaReplayerHelper::ProcessReplayerAnimVehicleWheels(), CarlaReplayerHelper::ProcessReplayerDoorVehicle(), FFrameData::ProcessReplayerEventDel(), CarlaReplayerHelper::ProcessReplayerEventDel(), FFrameData::ProcessReplayerEventParent(), CarlaReplayerHelper::ProcessReplayerEventParent(), FFrameData::ProcessReplayerLightVehicle(), CarlaReplayerHelper::ProcessReplayerLightVehicle(), FFrameData::ProcessReplayerPosition(), CarlaReplayerHelper::ProcessReplayerPosition(), FFrameData::ProcessReplayerStateTrafficLight(), CarlaReplayerHelper::ProcessReplayerStateTrafficLight(), CarlaReplayerHelper::ProcessReplayerWalkerBones(), SerializeActor(), FFrameData::SetCameraPosition(), CarlaReplayerHelper::SetCameraPosition(), ACustomV2XSensor::SetOwner(), CaService::SetOwner(), FFrameData::SetWalkerSpeed(), CarlaReplayerHelper::SetWalkerSpeed(), and CarlaReplayerHelper::TryToCreateReplayerActor().
GetActorDefinitions()
const TArray< FActorDefinition > & UCarlaEpisode::GetActorDefinitions () const inline
Return the list of actor definitions that are available to be spawned this episode.
Definition at line 124 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and InitializeAtBeginPlay().
GetActorDescriptionFromStream()
FString UCarlaEpisode::GetActorDescriptionFromStream (carla::streaming::detail::stream_id_type StreamId) inline
Get the description of the Carla actor (sensor) using specific stream id.
If the actor is not found returns an empty string
Definition at line 190 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions().
GetActorRegistry() [1/2]
FActorRegistry & UCarlaEpisode::GetActorRegistry () inline
Definition at line 160 of file CarlaEpisode.h.
GetActorRegistry() [2/2]
const FActorRegistry & UCarlaEpisode::GetActorRegistry () const inline
Definition at line 155 of file CarlaEpisode.h.
Referenced by ACarlaRecorder::AddCollision(), FFrameData::AddExistingActors(), ACarlaRecorder::AddExistingActors(), FFrameData::AddPhysicsControl(), ACarlaRecorder::AddPhysicsControl(), FFrameData::AddTrafficLightTime(), ACarlaRecorder::AddTrafficLightTime(), FFrameData::AddTriggerVolume(), ACarlaRecorder::AddTriggerVolume(), ACarlaRecorder::AddVehicleDoor(), FCarlaServer::FPimpl::BindActions(), ARayCastSemanticLidar::ComputeRawDetection(), FFrameData::CreateOrReuseActor(), FFrameData::FindTrafficLightAt(), CarlaReplayerHelper::FindTrafficLightAt(), FWorldObserver_Serialize(), FFrameData::GetFrameData(), PathLossModel::GetLocationIfVehicle(), PathLossModel::IsVehicle(), ALargeMapManager::OnActorSpawned(), ACustomV2XSensor::PostPhysTick(), AV2XSensor::PostPhysTick(), FFrameData::ProcessReplayerFinish(), CarlaReplayerHelper::ProcessReplayerFinish(), ALargeMapManager::RegisterInitialObjects(), PathLossModel::Simulate(), ACarlaRecorder::Ticking(), and CarlaReplayerHelper::TryToCreateReplayerActor().
GetCurrentMapOrigin()
FIntVector UCarlaEpisode::GetCurrentMapOrigin () const inline
Definition at line 323 of file CarlaEpisode.h.
Referenced by FWorldObserver_Serialize(), FActorData::GetLocalTransform(), and FActorData::RecordActorData().
GetElapsedGameTime()
double UCarlaEpisode::GetElapsedGameTime () const inline
Game seconds since the start of this episode.
Definition at line 99 of file CarlaEpisode.h.
Referenced by CaService::AddCooperativeAwarenessMessage(), FWorldObserver::BroadcastTick(), CaService::SetOwner(), and CaService::Trigger().
GetFrameData()
FFrameData & UCarlaEpisode::GetFrameData () inline
Definition at line 327 of file CarlaEpisode.h.
Referenced by AttachActors(), FCarlaEngine::NotifyInitGame(), FCarlaEngine::OnPostTick(), and SpawnActorWithInfo().
GetGeoReference()
const carla::geom::GeoLocation & UCarlaEpisode::GetGeoReference () const inline
Return the GeoLocation point of the map loaded.
Definition at line 134 of file CarlaEpisode.h.
Referenced by AGnssSensor::BeginPlay(), and CaService::SetOwner().
GetId()
auto UCarlaEpisode::GetId () const inline
Return the unique id of this episode.
Definition at line 86 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and FWorldObserver_Serialize().
GetMapName()
const FString & UCarlaEpisode::GetMapName () const inline
Return the name of the map loaded in this episode.
Definition at line 93 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions(), LoadNewEpisode(), FCarlaServer::NotifyBeginEpisode(), and CarlaReplayer::ReplayFile().
GetRecommendedSpawnPoints()
TArray< FTransform > UCarlaEpisode::GetRecommendedSpawnPoints () const
Return the list of recommended spawn points for vehicles.
Definition at line 241 of file CarlaEpisode.cpp.
References UCarlaStatics::GetGameMode(), and ACarlaGameModeBase::GetSpawnPointsTransforms().
Referenced by FCarlaServer::FPimpl::BindActions().
GetRecorder()
ACarlaRecorder * UCarlaEpisode::GetRecorder () const inline
Definition at line 306 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions(), and FCarlaEngine::OnPostTick().
GetReplayer()
CarlaReplayer * UCarlaEpisode::GetReplayer () const inline
Definition at line 316 of file CarlaEpisode.h.
Referenced by ACarlaRecorder::Ticking().
GetSensorManager()
FSensorManager & UCarlaEpisode::GetSensorManager () inline
Definition at line 329 of file CarlaEpisode.h.
Referenced by ASensor::BeginPlay(), ASensor::EndPlay(), and FCarlaEngine::OnPostTick().
GetSettings()
const FEpisodeSettings & UCarlaEpisode::GetSettings () const inline
Definition at line 73 of file CarlaEpisode.h.
Referenced by ACarlaGameModeBase::BeginPlay(), and FCarlaServer::FPimpl::BindActions().
GetSpectatorPawn()
APawn * UCarlaEpisode::GetSpectatorPawn () const inline
Definition at line 144 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::SetCameraPosition(), and CarlaReplayerHelper::SetCameraPosition().
GetVisualGameTime()
double UCarlaEpisode::GetVisualGameTime () const inline
Visual game seconds.
Definition at line 105 of file CarlaEpisode.h.
Referenced by ACarlaRecorder::Ticking().
GetWeather()
AWeather * UCarlaEpisode::GetWeather () const inline
Definition at line 150 of file CarlaEpisode.h.
Referenced by ASceneCaptureSensor::BeginPlay(), and FCarlaServer::FPimpl::BindActions().
InitializeAtBeginPlay()
void UCarlaEpisode::InitializeAtBeginPlay () private
Definition at line 323 of file CarlaEpisode.cpp.
References ActorDispatcher, FActorDescription::Class, Float, GetActorDefinitions(), FActorDescription::Id, MaterialParameters, UActorDispatcher::RegisterActor(), Spectator, String, UCarlaEpisode_GetTrafficSignId(), FActorDescription::UId, and FActorDescription::Variations.
Referenced by ACarlaGameModeBase::BeginPlay().
LoadNewEpisode()
bool UCarlaEpisode::LoadNewEpisode (const FString & MapString, bool ResetSettings = true)
Load a new map and start a new episode.
If MapString is empty, the current map is reloaded.
Definition at line 64 of file CarlaEpisode.cpp.
References ApplySettings(), bIsPrimaryServer, UCarlaGameInstance::GetCarlaEngine(), UCarlaStatics::GetGameInstance(), GetMapName(), FCarlaEngine::GetSecondaryServer(), and LoadNewEpisode().
Referenced by FCarlaServer::FPimpl::BindActions(), LoadNewEpisode(), and CarlaReplayer::ReplayFile().
LoadNewOpendriveEpisode()
bool UCarlaEpisode::LoadNewOpendriveEpisode (const FString & OpenDriveString, const carla::rpc::OpendriveGenerationParameters & Params)
Load a new map generating the mesh from OpenDRIVE data and start a new episode.
If MapString is empty, it fails.
Todo
this can take too long to finish, clients need a method to know if the navigation is available or not.
Definition at line 147 of file CarlaEpisode.cpp.
References BuildRecastBuilderFile(), carla::rpc::OpendriveGenerationParameters::enable_pedestrian_navigation, UCarlaStatics::GetGameInstance(), carla::opendrive::OpenDriveParser::Load(), carla::log_warning(), UCarlaGameInstance::SetOpendriveGenerationParameters(), and carla::rpc::OpendriveGenerationParameters::vertex_distance.
Referenced by FCarlaServer::FPimpl::BindActions().
PutActorToSleep()
void UCarlaEpisode::PutActorToSleep (carla::rpc::ActorId ActorId) inline
Definition at line 281 of file CarlaEpisode.h.
Referenced by FCarlaServer::FPimpl::BindActions(), ALargeMapManager::ConvertActiveToDormantActors(), FFrameData::ProcessReplayerEventParent(), and CarlaReplayerHelper::ProcessReplayerEventParent().
RegisterActorFactory()
void UCarlaEpisode::RegisterActorFactory (ACarlaActorFactory & ActorFactory) inline private
Definition at line 342 of file CarlaEpisode.h.
Referenced by ACarlaGameModeBase::SpawnActorFactories().
ReSpawnActorWithInfo()
AActor * UCarlaEpisode::ReSpawnActorWithInfo (const FTransform & Transform, FActorDescription thisActorDescription) inline
Spawns an actor based on ActorDescription at Transform.
Returns
the actor to be spawned
Definition at line 213 of file CarlaEpisode.h.
Referenced by FActorData::RespawnActor().
SerializeActor() [1/2]
carla::rpc::Actor UCarlaEpisode::SerializeActor (AActor * Actor) const
Create a serializable object describing the actor.
Can be used to serialized actors that are not in the registry
Definition at line 267 of file CarlaEpisode.cpp.
References carla::rpc::Actor::bounding_box, CarlaGetRelevantTagAsString(), carla::rpc::Actor::description, FindCarlaActor(), UBoundingBoxCalculator::GetActorBoundingBox(), ATagger::GetTagsOfTaggedActor(), carla::rpc::Actor::id, FActorDescription::Id, carla::rpc::Actor::semantic_tags, and SerializeActor().
SerializeActor() [2/2]
carla::rpc::Actor UCarlaEpisode::SerializeActor (FCarlaActor * CarlaActor) const
Create a serializable object describing the actor.
Definition at line 248 of file CarlaEpisode.cpp.
References FCarlaActor::GetActorInfo(), FCarlaActor::GetParent(), and FActorInfo::SerializedData.
Referenced by FCarlaServer::FPimpl::BindActions(), AObstacleDetectionSensor::OnObstacleDetectionEvent(), and SerializeActor().
SetActorCollisions()
bool UCarlaEpisode::SetActorCollisions (FCarlaActor & CarlaActor, bool bEnabled) private
SetActorDead()
bool UCarlaEpisode::SetActorDead (FCarlaActor & CarlaActor) private
SetActorSimulatePhysics()
bool UCarlaEpisode::SetActorSimulatePhysics (FCarlaActor & CarlaActor, bool bEnabled) private
SetCurrentMapOrigin()
void UCarlaEpisode::SetCurrentMapOrigin (const FIntVector & NewOrigin) inline
Definition at line 325 of file CarlaEpisode.h.
Referenced by ALargeMapManager::PostWorldOriginOffset().
SetRecorder()
void UCarlaEpisode::SetRecorder (ACarlaRecorder * Rec) inline
Definition at line 311 of file CarlaEpisode.h.
Referenced by ACarlaGameModeBase::InitGame(), and FCarlaEngine::NotifyBeginEpisode().
SetVisualGameTime()
void UCarlaEpisode::SetVisualGameTime (double Time) inline
Definition at line 110 of file CarlaEpisode.h.
Referenced by CarlaReplayer::ProcessVisualTime().
SpawnActor()
AActor * UCarlaEpisode::SpawnActor (const FTransform & Transform, FActorDescription ActorDescription) inline
Spawns an actor based on ActorDescription at Transform.
To properly despawn an actor created with this function call DestroyActor.
Returns
nullptr on failure.
Note
Special overload for blueprints.
Definition at line 234 of file CarlaEpisode.h.
Referenced by FTrafficSignData::RespawnActor(), and FTrafficLightData::RespawnActor().
SpawnActorWithInfo()
TPair< EActorSpawnResultStatus, FCarlaActor * > UCarlaEpisode::SpawnActorWithInfo (const FTransform & Transform, FActorDescription thisActorDescription, FCarlaActor::IdType DesiredId = 0)
Spawns an actor based on ActorDescription at Transform.
To properly despawn an actor created with this function call DestroyActor.
Returns
A pair containing the result of the spawn function and a view over the actor and its properties. If the status is different of Success the view is invalid.
Definition at line 435 of file CarlaEpisode.cpp.
References ActorDispatcher, bIsPrimaryServer, ACarlaRecorder::CreateRecorderEventAdd(), FFrameData::CreateRecorderEventAdd(), GetFrameData(), UCarlaStatics::GetLargeMapManager(), ALargeMapManager::GlobalToLocalTransform(), ACarlaRecorder::IsEnabled(), Recorder, and UActorDispatcher::SpawnActor().
Referenced by FCarlaServer::FPimpl::BindActions(), FFrameData::CreateOrReuseActor(), and CarlaReplayerHelper::TryToCreateReplayerActor().
StartRecorder()
std::string UCarlaEpisode::StartRecorder (std::string name, bool AdditionalData)
Definition at line 419 of file CarlaEpisode.cpp.
References MapName, Recorder, and ACarlaRecorder::Start().
Referenced by FCarlaServer::FPimpl::BindActions().
TickTimers()
void UCarlaEpisode::TickTimers (float DeltaSeconds) inline private
Definition at line 359 of file CarlaEpisode.h.
References carla::ros2::ROS2::GetInstance().
Referenced by FCarlaEngine::OnPreTick().
TryToCreateReplayerActor()
std::pair< int, FCarlaActor & > UCarlaEpisode::TryToCreateReplayerActor (FVector & Location, FVector & Rotation, FActorDescription & ActorDesc, unsigned int desiredId) private
WakeActorUp()
void UCarlaEpisode::WakeActorUp (carla::rpc::ActorId ActorId) inline
Definition at line 286 of file CarlaEpisode.h.
Referenced by ALargeMapManager::ConvertDormantToActiveActors().
Friends And Related Symbol Documentation
ACarlaGameModeBase
friend class ACarlaGameModeBase friend
Definition at line 335 of file CarlaEpisode.h.
FCarlaEngine
friend class FCarlaEngine friend
Definition at line 336 of file CarlaEpisode.h.
Member Data Documentation
ActorDispatcher
UActorDispatcher* UCarlaEpisode::ActorDispatcher = nullptr private
Definition at line 386 of file CarlaEpisode.h.
Referenced by InitializeAtBeginPlay(), SpawnActorWithInfo(), and UCarlaEpisode().
bIsPrimaryServer
bool UCarlaEpisode::bIsPrimaryServer = true
Definition at line 331 of file CarlaEpisode.h.
Referenced by AttachActors(), LoadNewEpisode(), FCarlaEngine::NotifyBeginEpisode(), and SpawnActorWithInfo().
CurrentMapOrigin
FIntVector UCarlaEpisode::CurrentMapOrigin private
Definition at line 401 of file CarlaEpisode.h.
Referenced by AttachActors().
ElapsedGameTime
double UCarlaEpisode::ElapsedGameTime = 0.0 private
Definition at line 374 of file CarlaEpisode.h.
EpisodeSettings
FEpisodeSettings UCarlaEpisode::EpisodeSettings private
Definition at line 383 of file CarlaEpisode.h.
Referenced by ApplySettings(), and FCarlaEngine::NotifyBeginEpisode().
FrameData
FFrameData UCarlaEpisode::FrameData private
Definition at line 403 of file CarlaEpisode.h.
Referenced by UCarlaEpisode().
Id
const uint64 UCarlaEpisode::Id = 0u private
Definition at line 371 of file CarlaEpisode.h.
MapGeoReference
carla::geom::GeoLocation UCarlaEpisode::MapGeoReference private
Definition at line 399 of file CarlaEpisode.h.
Referenced by ACarlaGameModeBase::ParseOpenDrive().
MapName
FString UCarlaEpisode::MapName private
Definition at line 380 of file CarlaEpisode.h.
Referenced by ACarlaGameModeBase::InitGame(), and StartRecorder().
MaterialParameters
UMaterialParameterCollectionInstance* UCarlaEpisode::MaterialParameters = nullptr private
Definition at line 395 of file CarlaEpisode.h.
Referenced by InitializeAtBeginPlay().
Recorder
ACarlaRecorder* UCarlaEpisode::Recorder = nullptr private
Definition at line 397 of file CarlaEpisode.h.
Referenced by AttachActors(), EndPlay(), SpawnActorWithInfo(), and StartRecorder().
SensorManager
FSensorManager UCarlaEpisode::SensorManager private
Definition at line 405 of file CarlaEpisode.h.
Spectator
APawn* UCarlaEpisode::Spectator = nullptr private
Definition at line 389 of file CarlaEpisode.h.
Referenced by InitializeAtBeginPlay().
VisualGameTime
double UCarlaEpisode::VisualGameTime = 0.0 private
Definition at line 377 of file CarlaEpisode.h.
Weather
AWeather* UCarlaEpisode::Weather = nullptr private
Definition at line 392 of file CarlaEpisode.h.
Referenced by ACarlaGameModeBase::BeginPlay(), and ACarlaGameModeBase::InitGame().
The documentation for this class was generated from the following files:
CarlaEpisode.h
CarlaEpisode.cpp